import {Component,ElementRef,ViewChild,HostListener} from '@angular/core';import {FormsModule} from '@angular/forms';import {DecimalPipe} from '@angular/common';import {RouterLink} from '@angular/router';import {Activity,Schedule,Scheduled,calculateSchedule} from './schedule';import {downloadBlob,exportSvg,exportWorkbook,exportTablePdf} from '../../core/export-utils';
@Component({standalone:true,imports:[FormsModule,DecimalPipe,RouterLink],templateUrl:'./pert.component.html',styleUrl:'../diagram/diagram.component.css',styles:[`.input-table{overflow:auto;max-height:450px}table{border-collapse:collapse;width:100%;font-size:.875rem}th,td{text-align:left;padding:.6rem;border-bottom:1px solid var(--line)}th{background:#113452}td input{background:#071a30;color:white;border:1px solid #315370;border-radius:6px;padding:.6rem;min-width:80px;width:100%}.metrics{display:flex;flex-wrap:wrap;gap:1rem;margin:1rem 0}.metrics>article{padding:1rem;border:1px solid var(--line);border-radius:12px}.metrics strong{font-size:1.7rem;color:var(--accent);display:block}.network{overflow:auto;background:white;border-radius:12px;margin:1rem 0}.network svg{max-width:none;display:block}.critical{color:#ff8b8b}.assumptions{font-size:.9rem;line-height:1.7;color:var(--muted)}.result-table{overflow:auto}`]})
export class PertComponent{
 @ViewChild('network') network?:ElementRef<SVGSVGElement>;
 name='Project Schedule';mode='cpm';units='days';rows:Activity[]=this.example();result?:Schedule;error='';message='';dirty=false;
 constructor(){this.calculate()}
 example():Activity[]{return [{id:'A',name:'Define scope',predecessors:'',duration:3,optimistic:2,likely:3,pessimistic:4},{id:'B',name:'Design solution',predecessors:'A',duration:4,optimistic:3,likely:4,pessimistic:5},{id:'C',name:'Prepare training',predecessors:'A',duration:2,optimistic:1,likely:2,pessimistic:3},{id:'D',name:'Pilot and launch',predecessors:'B,C',duration:3,optimistic:2,likely:3,pessimistic:4}]}
 changed(){this.dirty=true;this.calculate()}
 calculate(){try{this.result=calculateSchedule(this.rows,this.mode==='pert');this.error=''}catch(e){this.result=undefined;this.error=(e as Error).message}}
 add(){this.rows.push({id:'',name:'',predecessors:'',duration:1,optimistic:1,likely:1,pessimistic:1});this.changed()}
 remove(i:number){this.rows.splice(i,1);this.changed()}
 reset(){if(this.dirty&&!confirm('Replace current schedule with example data?'))return;this.rows=this.example();this.changed()}
 get width(){return Math.max(700,...(this.result?.activities.map(a=>a.x+210)||[]))}get height(){return Math.max(300,...(this.result?.activities.map(a=>a.y+130)||[]))}
 predecessor(id:string){return this.result!.activities.find(a=>a.id===id)!}
 edge(a:Scheduled,p:string){const n=this.predecessor(p);return `M ${n.x+180} ${n.y+45} L ${a.x} ${a.y+45}`}
 criticalEdge(a:Scheduled,p:string){const n=this.predecessor(p);return n.critical&&a.critical&&Math.abs(n.ef-a.es)<1e-8}
 save(){try{localStorage.setItem('pmport-schedule',JSON.stringify({name:this.name,mode:this.mode,units:this.units,rows:this.rows}));this.dirty=false;this.message='Saved on this device.'}catch{this.message='Browser storage is unavailable. Download an editable file.'}}
 validate(d:any){if(!d||typeof d.name!=='string'||!['cpm','pert'].includes(d.mode)||typeof d.units!=='string'||!Array.isArray(d.rows)||d.rows.length>100)throw Error();d.rows.forEach((a:any)=>{if(typeof a.id!=='string'||typeof a.name!=='string'||typeof a.predecessors!=='string')throw Error()});calculateSchedule(d.rows,d.mode==='pert');return d}
 load(){try{const text=localStorage.getItem('pmport-schedule');if(!text){this.message='No saved schedule found.';return}const d=this.validate(JSON.parse(text));if(this.dirty&&!confirm('Replace current changes with the saved schedule?'))return;this.apply(d);this.dirty=false;this.message='Saved schedule opened.'}catch{this.message='Could not open saved schedule.'}}
 apply(d:any){this.name=d.name;this.mode=d.mode;this.units=d.units;this.rows=d.rows;this.calculate()}
 download(){downloadBlob(new Blob([JSON.stringify({name:this.name,mode:this.mode,units:this.units,rows:this.rows},null,2)],{type:'application/json'}),'pmport-schedule.json')}
 async importFile(e:Event){const f=(e.target as HTMLInputElement).files?.[0];if(!f)return;try{if(f.size>2e6)throw Error();const d=this.validate(JSON.parse(await f.text()));if(this.dirty&&!confirm('Replace current changes with this schedule?'))return;this.apply(d);this.dirty=true;this.message='Schedule imported.'}catch{this.message='Choose a valid schedule file with non-circular dependencies.'}finally{(e.target as HTMLInputElement).value=''}}
 async export(format:'png'|'jpg'|'pdf'){if(!this.result)return;try{await exportSvg(this.network!.nativeElement,'pmport-network',format);this.message='Network exported.'}catch{this.message='Network export failed.'}}
 async exportTable(pdf=false){if(!this.result)return;const headers=['ID','Activity','Predecessors','Duration ('+this.units+')','PERT variance','ES','EF','LS','LF','Total float','Critical'];const rows=this.result.activities.map(a=>[a.id,a.name,a.pred.join(','),a.expected,a.variance,a.es,a.ef,a.ls,a.lf,a.float,a.critical?'Yes':'No']);const title=this.name+' — '+this.mode.toUpperCase()+' — Project duration '+this.result.duration+' '+this.units;try{if(pdf)await exportTablePdf(title,headers,rows,'pmport-schedule');else await exportWorkbook(title,headers,rows,'pmport-schedule');this.message='Calculation table exported.'}catch{this.message='Table export failed.'}}
 @HostListener('window:beforeunload',['$event']) unload(e:BeforeUnloadEvent){if(this.dirty)e.preventDefault()}
}
