import {ExamQuestion} from '../exam-types';

const D='Business Environment' as const;

export const BUSINESS_ENVIRONMENT_QUESTIONS:ExamQuestion[]=[
  // Task 1 — Define and establish project governance (5)
  {id:'E01',domain:D,task:1,approach:'Hybrid',type:'single',
   stem:'A new hybrid program has no clear rules for who can approve scope changes, budget changes or release decisions. What should the project manager do first?',
   options:['Make all decisions personally to avoid delays','Work with the sponsor to define governance: decision rights, escalation paths and thresholds, and the roles of the steering committee, product owners and change control board','Let each team decide independently','Wait for the PMO to issue a policy'],answer:[1],
   explanation:'Governance defines how decisions are made, by whom and within which limits. Establishing it early prevents delays and conflicts later.',
   ref:'Performance domain: Governance · Focus area: Initiating'},
  {id:'E02',domain:D,task:1,approach:'Agile',type:'single',
   stem:'An organization’s stage-gate governance requires detailed requirements sign-off before any development, which conflicts with the agile team’s approach. What should the project manager do?',
   options:['Ignore the gate requirements','Work with the governance body to tailor the gates—for example, approve a vision, roadmap and minimum viable product scope with regular reviews of working increments','Switch the project to a predictive approach','Ask the team to write full requirements anyway'],answer:[1],
   explanation:'Governance can be tailored to adaptive delivery while preserving oversight—shifting from document sign-offs to evidence from working increments.',
   ref:'Principle: Adopt a holistic view · Performance domain: Governance'},
  {id:'E03',domain:D,task:1,approach:'Predictive',type:'single',
   stem:'What is the primary role of a project management office (PMO) that focuses on value creation?',
   options:['Enforcing templates regardless of project needs','Providing governance, standards, support and portfolio insights that help projects deliver value, tailored to their context','Managing every project directly','Approving every task'],answer:[1],
   explanation:'Modern PMOs shift from compliance policing toward enabling value delivery through support, standards and insight.',
   ref:'Performance domain: Governance · Principle: Focus on value'},
  {id:'E04',domain:D,task:1,approach:'Hybrid',type:'multi',
   stem:'Which TWO elements should be defined in a project’s governance framework?',
   options:['Escalation paths and decision thresholds','The team’s preferred coding style','Success metrics and how performance will be reviewed','Individual lunch schedules','The colour scheme of status reports'],answer:[0,2],
   explanation:'Governance covers decision rights, escalation and how success and performance are measured and reviewed.',
   ref:'Performance domain: Governance · Focus area: Planning'},
  {id:'E05',domain:D,task:1,approach:'Predictive',type:'single',
   stem:'A sponsor asks the project manager to approve a vendor contract worth more than the project manager’s authority limit “just this once” to save time. What should the project manager do?',
   options:['Approve it because the sponsor asked','Explain the authority limit and route the contract for approval through the defined governance path, helping to expedite it','Ask the vendor to split the invoice','Approve it and inform governance afterwards'],answer:[1],
   explanation:'Accountable leaders respect governance limits even under pressure, while helping the organization act quickly within the rules.',
   ref:'Principle: Be an accountable leader · Ethics · Performance domain: Governance'},

  // Task 2 — Plan and manage compliance (3)
  {id:'E06',domain:D,task:2,approach:'Predictive',type:'single',
   stem:'A project must comply with accessibility standards for public websites. When should compliance requirements be identified?',
   options:['During user acceptance testing','During planning, so that they are built into requirements, design, testing and acceptance criteria','After launch, if complaints are received','Only if the regulator requests it'],answer:[1],
   explanation:'Compliance requirements identified early can be designed in at lower cost and risk than retrofitting them later.',
   ref:'Performance domain: Governance · Principle: Embed quality · Focus area: Planning'},
  {id:'E07',domain:D,task:2,approach:'Agile',type:'single',
   stem:'How can an agile team ensure ongoing compliance with data-protection requirements?',
   options:['Run a compliance review only before the final release','Include compliance criteria in the definition of done and in relevant acceptance criteria, and involve compliance experts in reviews','Assign compliance to a separate team after development','Rely on the vendor’s certification'],answer:[1],
   explanation:'Embedding compliance into the definition of done ensures that every increment meets the requirements.',
   ref:'Principle: Embed quality · Performance domain: Governance'},
  {id:'E08',domain:D,task:2,approach:'Hybrid',type:'single',
   stem:'An internal audit finds that the project has not kept required records of environmental permits. What should the project manager do first?',
   options:['Dispute the audit finding','Assess the gap with the compliance owner, take corrective action to restore the required records and controls, and update the compliance plan to prevent recurrence','Ask the team to back-date documents','Wait for the regulator to raise the issue'],answer:[1],
   explanation:'Compliance gaps must be corrected promptly and honestly, with process improvements to prevent recurrence. Falsifying records is unethical and illegal.',
   ref:'Principle: Integrate sustainability · Performance domain: Governance'},

  // Task 3 — Manage and control changes (7)
  {id:'E09',domain:D,task:3,approach:'Predictive',type:'single',
   stem:'A change request has been approved by the change control board. What should the project manager do next?',
   options:['Close the change request','Update the affected baselines and plans, implement the change, and communicate it to the affected stakeholders','Ask the requester to implement it','Wait for the next phase'],answer:[1],
   explanation:'After approval, the project manager updates the plans and baselines, manages implementation and informs stakeholders.',
   ref:'Performance domain: Governance · Focus area: Monitoring and Controlling'},
  {id:'E10',domain:D,task:3,approach:'Agile',type:'single',
   stem:'A stakeholder requests a new feature in the middle of a sprint. What should happen?',
   options:['The team adds it to the current sprint immediately','The request goes to the product owner, who adds it to the product backlog and prioritizes it for a future sprint, unless it is critical enough to justify renegotiating the sprint','The Scrum Master rejects the request','The sprint is cancelled'],answer:[1],
   explanation:'In Scrum, changes are managed through the product backlog. The sprint goal is protected, and the product owner decides on priority.',
   ref:'Performance domain: Scope · Focus area: Executing'},
  {id:'E11',domain:D,task:3,approach:'Predictive',type:'single',
   stem:'The sponsor verbally tells a team member to change a deliverable’s design. The team member starts the work. What should the project manager do?',
   options:['Allow the change because the sponsor requested it','Stop the unapproved work, document the request as a change request, analyze its impact and process it through change control','Ask the sponsor to stop interfering','Implement the change and update the plan later'],answer:[1],
   explanation:'Even sponsor requests must follow change control to protect baselines and ensure impacts are understood.',
   ref:'Performance domain: Governance · Principle: Be an accountable leader'},
  {id:'E12',domain:D,task:3,approach:'Hybrid',type:'single',
   stem:'In a hybrid project, which changes should normally go to the formal change control board?',
   options:['Every reordering of the product backlog','Changes that affect the approved baselines, contractual commitments or regulatory milestones','Daily task assignments','Changes to sprint retrospective formats'],answer:[1],
   explanation:'Tailored change control reserves formal review for changes that affect baselines, contracts or compliance, while the backlog absorbs routine adaptive change.',
   ref:'Principle: Adopt a holistic view · Performance domain: Governance'},
  {id:'E13',domain:D,task:3,approach:'Predictive',type:'multi',
   stem:'Which TWO items should a change request’s impact analysis include?',
   options:['Effects on scope, schedule, cost, quality and risk','The requester’s job title only','Alternatives considered and a recommendation','The project manager’s personal opinion of the requester','The number of previous change requests'],answer:[0,2],
   explanation:'A good impact analysis assesses effects across the constraints and presents alternatives with a recommendation for the decision-makers.',
   ref:'Performance domain: Governance · Focus area: Monitoring and Controlling'},
  {id:'E14',domain:D,task:3,approach:'Agile',type:'single',
   stem:'An agile team receives frequent requests from executives that bypass the product owner. What should the project manager do?',
   options:['Accept all requests to keep executives satisfied','Coach executives on how changes flow through the product owner and backlog, and make the impact of bypassing it visible','Ask the team to hide work from executives','Escalate to HR'],answer:[1],
   explanation:'Coaching stakeholders on the change process protects value-based prioritization and team focus.',
   ref:'Performance domains: Governance, Stakeholders'},
  {id:'E15',domain:D,task:3,approach:'Hybrid',type:'single',
   stem:'A change was rejected by the change control board. What should the project manager do?',
   options:['Implement it anyway if the team agrees','Record the decision in the change log, communicate it to the requester and stakeholders, and close the request','Resubmit it immediately','Delete the change request'],answer:[1],
   explanation:'Rejected changes are documented and communicated so that the decision is transparent and traceable.',
   ref:'Performance domain: Governance · Focus area: Monitoring and Controlling'},

  // Task 4 — Remove impediments and manage issues (5)
  {id:'E16',domain:D,task:4,approach:'Agile',type:'single',
   stem:'During the daily scrum, a developer says they have been blocked for two days waiting for test-environment access. What should the project manager or Scrum Master do?',
   options:['Note it for the retrospective','Take ownership of removing the impediment right after the daily scrum—contact the environment owner and escalate if needed','Ask the developer to find a workaround','Reassign the work to another developer'],answer:[1],
   explanation:'Removing impediments quickly is a core servant-leadership responsibility. Waiting for the retrospective prolongs the delay.',
   ref:'Principle: Build an empowered culture · Focus area: Executing'},
  {id:'E17',domain:D,task:4,approach:'Predictive',type:'single',
   stem:'A risk that was in the risk register has now occurred. Where should it be tracked?',
   options:['It stays only in the risk register','In the issue log, with an owner and actions, and the risk register updated accordingly','In the change log','In the lessons-learned register only'],answer:[1],
   explanation:'Once a risk occurs, it becomes an issue managed in the issue log, while the risk register is updated to reflect what happened.',
   ref:'Performance domain: Risk · Focus area: Executing'},
  {id:'E18',domain:D,task:4,approach:'Hybrid',type:'single',
   stem:'An issue is beyond the project manager’s authority to resolve and is threatening a key milestone. What should the project manager do?',
   options:['Keep trying to solve it alone','Escalate it according to the governance escalation path, with the facts, the impact and recommended options','Wait for the milestone to pass','Inform only the team'],answer:[1],
   explanation:'Timely escalation with clear information enables decision-makers to act. It follows exhausting what is within the project manager’s authority.',
   ref:'Performance domain: Governance · Principle: Be an accountable leader'},
  {id:'E19',domain:D,task:4,approach:'Agile',type:'single',
   stem:'The same impediment—late design approvals—appears in three consecutive retrospectives. What should the project manager do?',
   options:['Keep recording it','Analyze the root cause with the team and the design approvers, and agree on a systemic fix such as a design review cadence or delegated authority','Remove design approval from the process','Tell the team to work around it'],answer:[1],
   explanation:'Recurring impediments indicate a systemic problem. Root-cause analysis and collaboration with those involved address it permanently.',
   ref:'Principle: Embed quality · Focus area: Monitoring and Controlling'},
  {id:'E20',domain:D,task:4,approach:'Predictive',type:'multi',
   stem:'Which TWO details should be recorded for each item in an issue log?',
   options:['An owner responsible for resolution','The project manager’s salary','A target resolution date and the current status','The weather on the day the issue occurred','The colour of the project logo'],answer:[0,2],
   explanation:'An issue log needs an owner, a due date and the status so that issues are actively driven to resolution.',
   ref:'Focus area: Monitoring and Controlling'},

  // Task 5 — Plan and manage risk (6)
  {id:'E21',domain:D,task:5,approach:'Predictive',type:'dropdown',
   stem:'A risk has a 30% probability of causing a $50,000 loss. An opportunity has a 20% probability of saving $40,000. What is the combined expected monetary value (EMV)?',
   options:['–$15,000','–$7,000','+$8,000','–$23,000'],answer:[1],
   explanation:'Threat EMV = 0.30 × –$50,000 = –$15,000. Opportunity EMV = 0.20 × +$40,000 = +$8,000. Combined = –$7,000.',
   ref:'Performance domain: Risk · Focus area: Planning'},
  {id:'E22',domain:D,task:5,approach:'Predictive',type:'matching',
   stem:'Match each risk response to the strategy it represents.',
   pairs:[{left:'Buying insurance against equipment damage',right:0},{left:'Changing the design to remove a technology that might fail',right:1},{left:'Adding extra testing to reduce the probability of defects',right:2},{left:'Setting aside contingency time for a possible permit delay, with no other action',right:3}],
   choices:['Transfer','Avoid','Mitigate','Accept (active)'],
   explanation:'Insurance transfers financial impact; removing the cause avoids the threat; extra testing reduces probability (mitigation); a contingency reserve without other action is active acceptance.',
   ref:'Performance domain: Risk · Focus area: Planning'},
  {id:'E23',domain:D,task:5,approach:'Agile',type:'single',
   stem:'How do agile teams typically manage risk?',
   options:['With a detailed risk register reviewed only at phase gates','Continuously, through short iterations, frequent feedback, risk-based backlog prioritization and visible risk discussions in events such as planning and retrospectives','By avoiding all uncertain work','By transferring all risks to the product owner'],answer:[1],
   explanation:'Short feedback loops and prioritizing high-risk items early reduce uncertainty continuously.',
   ref:'Performance domain: Risk · Focus area: Executing'},
  {id:'E24',domain:D,task:5,approach:'Hybrid',type:'single',
   stem:'A risk owner has not updated their assigned high-impact risk in six weeks. What should the project manager do?',
   options:['Remove the risk from the register','Follow up with the risk owner to review the risk’s status, triggers and response, and reinforce ownership expectations','Take over the risk personally without discussion','Wait for the next audit'],answer:[1],
   explanation:'Risk management is continuous. The project manager ensures that owners actively monitor and respond to their risks.',
   ref:'Performance domain: Risk · Focus area: Monitoring and Controlling'},
  {id:'E25',domain:D,task:5,approach:'Predictive',type:'single',
   stem:'After a risk response is implemented, a new risk arises as a direct result of that response. What is this new risk called?',
   options:['Residual risk','Secondary risk','Emergent risk','Overall project risk'],answer:[1],
   explanation:'A secondary risk arises directly from implementing a risk response. A residual risk is what remains after the response.',
   ref:'Performance domain: Risk · Focus area: Monitoring and Controlling'},
  {id:'E26',domain:D,task:5,approach:'Hybrid',type:'single',
   stem:'A project depends on a supplier in a region affected by climate-related flooding. Which response best integrates sustainability and resilience?',
   options:['Ignore the risk because it is outside the project’s control','Assess the supply-chain climate risk, identify alternative or more resilient suppliers, and plan responses such as buffer stock or dual sourcing','Cancel the project','Transfer all risk to the supplier through the contract'],answer:[1],
   explanation:'Environmental and supply-chain risks should be identified and managed proactively. Resilient sourcing supports both sustainability and delivery.',
   ref:'Principle: Integrate sustainability · Performance domain: Risk'},

  // Task 6 — Continuous improvement (5)
  {id:'E27',domain:D,task:6,approach:'Agile',type:'single',
   stem:'What is the primary purpose of a sprint retrospective?',
   options:['To demonstrate the increment to stakeholders','For the team to inspect its way of working and agree on improvements to apply in the next sprint','To plan the next sprint’s backlog','To evaluate individual performance'],answer:[1],
   explanation:'The retrospective focuses on improving how the team works—people, processes, tools and the definition of done.',
   ref:'Principle: Embed quality · Focus area: Monitoring and Controlling'},
  {id:'E28',domain:D,task:6,approach:'Predictive',type:'single',
   stem:'The team repeatedly misses the same quality target. Which technique is most appropriate to find the underlying cause?',
   options:['Brainstorming new features','Root-cause analysis, such as the “5 Whys” or a fishbone (Ishikawa) diagram','A stakeholder register','A bidder conference'],answer:[1],
   explanation:'Root-cause techniques identify why a problem occurs, so that improvements address causes rather than symptoms.',
   ref:'Principle: Embed quality · Focus area: Monitoring and Controlling'},
  {id:'E29',domain:D,task:6,approach:'Hybrid',type:'single',
   stem:'Improvement actions agreed in retrospectives are rarely implemented. What should the project manager do?',
   options:['Stop holding retrospectives','Limit improvements to one or two per iteration, give each an owner, add them to the backlog and review progress at the next retrospective','Assign all improvements to the Scrum Master','Document the actions in a report for management'],answer:[1],
   explanation:'Improvements need ownership, capacity and follow-up. Treating them as planned work makes them happen.',
   ref:'Principle: Build an empowered culture · Focus area: Executing'},
  {id:'E30',domain:D,task:6,approach:'Predictive',type:'multi',
   stem:'Which TWO practices support continuous improvement on a predictive project?',
   options:['Capturing and applying lessons learned at phase reviews','Waiting until project closure to discuss any problems','Using quality audits to identify process improvements','Rejecting all process changes once the plan is approved','Avoiding metrics to save time'],answer:[0,2],
   explanation:'Phase-end lessons and quality audits feed improvements back into the project while it is still running.',
   ref:'Principle: Embed quality · Focus areas: Executing, Monitoring and Controlling'},
  {id:'E31',domain:D,task:6,approach:'Agile',type:'single',
   stem:'A team wants to experiment with a new code-review approach. How should they introduce it?',
   options:['Mandate it for all teams immediately','Run a small, time-boxed experiment with a clear hypothesis and measures, then inspect the results and decide whether to adopt it','Implement it without measuring','Ask management to approve every detail'],answer:[1],
   explanation:'Empirical, small experiments let teams test improvements safely and adopt what works.',
   ref:'Principle: Build an empowered culture · Focus area: Executing'},

  // Task 7 — Support organizational change (4)
  {id:'E32',domain:D,task:7,approach:'Predictive',type:'single',
   stem:'A new ERP system is technically ready, but users are resisting the new processes. What is the most effective response?',
   options:['Mandate use of the system and turn off the old one','Apply change-management practices: understand the causes of resistance, engage change champions, and provide training, support and reinforcement','Delay go-live indefinitely','Blame the users in the steering report'],answer:[1],
   explanation:'Adoption depends on people. Structured change management addresses awareness, desire, knowledge, ability and reinforcement.',
   ref:'Principle: Focus on value · Performance domain: Stakeholders'},
  {id:'E33',domain:D,task:7,approach:'Hybrid',type:'single',
   stem:'When should organizational change management activities begin on a project that will change how people work?',
   options:['After go-live','During initiation and planning, integrated with the project plan','Only when resistance appears','During closure'],answer:[1],
   explanation:'Change management is most effective when it is planned from the start and integrated with delivery.',
   ref:'Principle: Adopt a holistic view · Focus area: Planning'},
  {id:'E34',domain:D,task:7,approach:'Agile',type:'single',
   stem:'An organization is moving its teams from predictive to agile ways of working. A department manager feels they are losing control. What should the project manager do?',
   options:['Tell the manager that agile does not need managers','Work with the manager to clarify how their role will evolve—such as developing people, removing systemic impediments and supporting teams—and involve them in the transition','Exclude the manager from the transition','Ask HR to replace the manager'],answer:[1],
   explanation:'Supporting change means helping people see their new role and value. Managers are key to sustaining agile adoption.',
   ref:'Principle: Build an empowered culture · Performance domain: Stakeholders'},
  {id:'E35',domain:D,task:7,approach:'Hybrid',type:'multi',
   stem:'Which TWO indicators best show that an organizational change is being adopted?',
   options:['Actual usage of the new process or system and reduced workarounds','The number of training slides produced','Achievement of agreed outcome measures, such as cycle time or error rates','The size of the project team','The number of emails sent about the change'],answer:[0,2],
   explanation:'Adoption is shown by real behaviour change and outcomes, not by the volume of activities.',
   ref:'Principle: Focus on value · Focus area: Monitoring and Controlling'},

  // Task 8 — Evaluate external business environment changes (3)
  {id:'E36',domain:D,task:8,approach:'Agile',type:'single',
   stem:'A competitor launches a similar product with a feature customers love. What should the product owner and team do?',
   options:['Copy the feature immediately in the current sprint','Assess the market impact with stakeholders and data, then reprioritize the backlog if the new information changes the value of planned work','Ignore the competitor','Stop development until the strategy is updated'],answer:[1],
   explanation:'External changes should inform value-based prioritization after a proper assessment, not trigger impulsive changes.',
   ref:'Principle: Focus on value · Performance domain: Scope'},
  {id:'E37',domain:D,task:8,approach:'Predictive',type:'single',
   stem:'Currency exchange rates have moved significantly, increasing the cost of imported equipment by 12%. What should the project manager do?',
   options:['Absorb the cost silently','Assess the impact on the budget and risk exposure, consider responses such as hedging advice or alternative suppliers, and process any baseline change through governance','Cancel the equipment order','Wait for exchange rates to recover'],answer:[1],
   explanation:'External economic changes require impact analysis and an appropriate response through governance.',
   ref:'Performance domains: Finance, Risk · Principle: Adopt a holistic view'},
  {id:'E38',domain:D,task:8,approach:'Hybrid',type:'single',
   stem:'New government guidelines on the responsible use of AI are published. The project includes an AI-based decision tool. What should the project manager do?',
   options:['Assume the guidelines do not apply','Review the guidelines with legal, compliance and data experts, assess their impact on the tool’s design and approvals, and update the risk register and plan','Remove all AI features without analysis','Wait until the guidelines become law'],answer:[1],
   explanation:'Changes in the regulatory environment—especially around AI—must be assessed promptly for their effect on scope, compliance and risk.',
   ref:'Performance domains: Governance, Risk · AI in project management'}
];
