import {ExamQuestion} from '../exam-types';

const D='Process' as const;

export const PROCESS_QUESTIONS:ExamQuestion[]=[
  // Task 1 — Integrated plan and plan delivery (7)
  {id:'R01',domain:D,task:1,approach:'Hybrid',type:'single',
   stem:'A project has stable regulatory requirements for its infrastructure work and uncertain user requirements for its customer app. Which delivery approach is most appropriate?',
   options:['Predictive for the whole project','Agile for the whole project','A hybrid approach: predictive for the infrastructure and adaptive for the app, with integrated milestones','Whichever approach the team prefers'],answer:[2],
   explanation:'Tailoring the delivery approach to each component’s uncertainty and constraints is the essence of a hybrid approach. The parts must still be integrated through shared milestones and governance.',
   ref:'Principle: Adopt a holistic view · Focus area: Planning'},
  {id:'R02',domain:D,task:1,approach:'Predictive',type:'single',
   stem:'The project manager has developed the subsidiary plans for scope, schedule, cost and quality. What should happen next?',
   options:['Begin execution immediately','Integrate the subsidiary plans and baselines into the project management plan and obtain approval as defined by governance','Send each plan to the relevant manager for separate approval','Start procurement'],answer:[1],
   explanation:'Integration ensures that the plans are consistent with each other. The integrated plan is then approved according to the project’s governance.',
   ref:'Performance domain: Governance · Focus area: Planning'},
  {id:'R03',domain:D,task:1,approach:'Agile',type:'single',
   stem:'In an agile project, what replaces a detailed up-front plan for the whole project?',
   options:['No planning at all','Progressive, multi-level planning—a vision and roadmap, release planning and iteration planning—refined as more is learned','A detailed Gantt chart updated weekly','The product owner’s personal task list'],answer:[1],
   explanation:'Agile planning is continuous and layered, with more detail for near-term work and less for later work (rolling-wave elaboration).',
   ref:'Performance domains: Scope, Schedule · Focus area: Planning'},
  {id:'R04',domain:D,task:1,approach:'Hybrid',type:'multi',
   stem:'When tailoring the project approach, which TWO factors should the project manager consider most?',
   options:['The degree of requirements uncertainty and the rate of change','The project manager’s favourite methodology','Organizational culture, governance constraints and team experience','The approach used on the last project, regardless of context','The number of templates available'],answer:[0,2],
   explanation:'Tailoring is driven by the characteristics of the product, the project and the organization—not by habit or preference.',
   ref:'Principle: Adopt a holistic view · Performance domain: Governance'},
  {id:'R05',domain:D,task:1,approach:'Predictive',type:'single',
   stem:'Which document should be updated when a new sustainability reporting requirement must be tracked across the project?',
   options:['The project management plan, including communication and quality components, so that the requirement is integrated across the work','Only the risk register','A separate sustainability spreadsheet outside the plan','The project charter'],answer:[0],
   explanation:'Requirements that cut across the project should be integrated into the relevant components of the plan so they are delivered, measured and reported consistently.',
   ref:'Principle: Integrate sustainability · Focus area: Planning'},
  {id:'R06',domain:D,task:1,approach:'Agile',type:'single',
   stem:'The sponsor asks for a single document showing how three agile teams and one vendor team will coordinate their work toward a release. What should the project manager prepare?',
   options:['Separate sprint backlogs for each team','A release plan or program roadmap showing dependencies, milestones and integration points across the teams','A detailed WBS for each team','A RACI chart only'],answer:[1],
   explanation:'Coordinating several teams needs a shared release-level view of dependencies and integration points.',
   ref:'Performance domains: Schedule, Governance · Focus area: Planning'},
  {id:'R07',domain:D,task:1,approach:'Hybrid',type:'single',
   stem:'An organization plans to use an AI scheduling tool to generate the project schedule. What is the project manager’s most important responsibility?',
   options:['Accept the tool’s output because it is data-driven','Validate the tool’s assumptions, durations and logic with the team and experts, and remain accountable for the approved schedule','Let the PMO approve the schedule','Use the tool only for status reporting'],answer:[1],
   explanation:'AI can accelerate planning, but the project manager remains accountable for the quality and realism of the plan.',
   ref:'Principle: Be an accountable leader · AI in project management · Focus area: Planning'},

  // Task 2 — Develop and manage scope (8)
  {id:'R08',domain:D,task:2,approach:'Predictive',type:'single',
   stem:'What is the lowest level of a work breakdown structure called?',
   options:['Activity','Work package','Control account','Deliverable'],answer:[1],
   explanation:'The work package is the lowest level of the WBS, where cost and duration can be estimated and managed. Activities are defined later, during schedule planning.',
   ref:'Performance domain: Scope · Focus area: Planning'},
  {id:'R09',domain:D,task:2,approach:'Predictive',type:'single',
   stem:'A team member adds a feature that the customer did not request because they think the customer will like it. What is this called?',
   options:['Scope creep','Gold plating','Progressive elaboration','Value engineering'],answer:[1],
   explanation:'Gold plating is adding unrequested features. It adds cost and risk without approved value, so it should be avoided.',
   ref:'Performance domain: Scope · Principle: Focus on value'},
  {id:'R10',domain:D,task:2,approach:'Agile',type:'single',
   stem:'In an agile project, how is scope primarily managed?',
   options:['Through a signed-off scope statement and formal change requests','Through a prioritized product backlog that the product owner continually refines based on value and feedback','By the developers deciding what to build','By freezing scope after the first sprint'],answer:[1],
   explanation:'Adaptive scope is managed through the product backlog, which the product owner orders and refines as learning occurs.',
   ref:'Performance domain: Scope · Focus area: Planning'},
  {id:'R11',domain:D,task:2,approach:'Predictive',type:'single',
   stem:'What is the difference between validating scope and controlling quality?',
   options:['They are the same process','Controlling quality checks deliverables for correctness against requirements; validating scope is the customer’s formal acceptance of completed deliverables','Validating scope happens before quality control and is done by the team','Controlling quality is done by the customer'],answer:[1],
   explanation:'Quality control (usually internal) verifies correctness. Scope validation is the customer or sponsor formally accepting the verified deliverables.',
   ref:'Performance domain: Scope · Principle: Embed quality'},
  {id:'R12',domain:D,task:2,approach:'Agile',type:'matching',
   stem:'Match each agile scope term to its description.',
   pairs:[{left:'Epic',right:0},{left:'User story',right:1},{left:'Acceptance criteria',right:2},{left:'Definition of done',right:3}],
   choices:['A large body of work that will be split into smaller items','A small piece of functionality expressed from the user’s perspective','The conditions a specific item must satisfy to be accepted','The shared quality checklist that applies to every increment'],
   explanation:'Epics are decomposed into stories; acceptance criteria are item-specific; the definition of done applies to all work.',
   ref:'Performance domain: Scope · Principle: Embed quality'},
  {id:'R13',domain:D,task:2,approach:'Hybrid',type:'single',graphic:'burnup',
   stem:'Based on the release burnup chart, what is the most accurate interpretation?',
   options:['The team’s velocity dropped sharply after sprint 5','Total scope increased at sprint 5, so the completion forecast moved later even though velocity stayed stable','The release is ahead of schedule','The team stopped delivering after sprint 5'],answer:[1],
   explanation:'A burnup chart shows completed work and total scope as separate lines. The scope line rose from 200 to 260 points while completed work kept a steady slope, so the forecast moved out because of scope growth, not lower productivity.',
   ref:'Performance domains: Scope, Schedule · Focus area: Monitoring and Controlling'},
  {id:'R14',domain:D,task:2,approach:'Predictive',type:'single',
   stem:'A stakeholder asks the team to “just add one more report” during execution. The scope baseline does not include it. What should the project manager do?',
   options:['Add the report because it is small','Ask the stakeholder to submit a change request, and analyze its impact before a decision is made','Refuse the request','Add it and adjust the baseline afterwards'],answer:[1],
   explanation:'Changes to the baseline go through integrated change control, however small, to prevent scope creep.',
   ref:'Performance domains: Scope, Governance · Focus area: Monitoring and Controlling'},
  {id:'R15',domain:D,task:2,approach:'Hybrid',type:'multi',
   stem:'Which TWO items belong in a project scope statement?',
   options:['Product scope description and project deliverables','The team’s vacation schedule','Acceptance criteria, exclusions, constraints and assumptions','The detailed sprint backlog','Individual performance ratings'],answer:[0,2],
   explanation:'The scope statement describes the product, deliverables, acceptance criteria, exclusions, constraints and assumptions.',
   ref:'Performance domain: Scope · Focus area: Planning'},

  // Task 3 — Help ensure value-based delivery (7)
  {id:'R16',domain:D,task:3,approach:'Agile',type:'single',
   stem:'The product owner must choose which of four features to build next. Which approach best maximizes value?',
   options:['Build the feature requested by the most senior stakeholder','Prioritize using value, cost of delay, risk reduction and effort—for example with weighted shortest job first','Build the easiest feature first','Build features in the order they were requested'],answer:[1],
   explanation:'Value-based prioritization considers economic value, urgency, risk and size. Weighted shortest job first is one common technique.',
   ref:'Principle: Focus on value · Performance domain: Scope'},
  {id:'R17',domain:D,task:3,approach:'Agile',type:'single',
   stem:'What is the main purpose of a minimum viable product (MVP)?',
   options:['To deliver the cheapest possible product','To test key assumptions and learn from real users with the least effort','To meet the contract’s minimum requirements','To replace user testing'],answer:[1],
   explanation:'An MVP is a learning tool. It validates assumptions about value early, before significant investment.',
   ref:'Principle: Focus on value · Performance domain: Risk'},
  {id:'R18',domain:D,task:3,approach:'Predictive',type:'single',
   stem:'Halfway through a project, market conditions change and the expected benefits fall below the investment cost. What should the project manager do?',
   options:['Continue because the project is half done','Inform the sponsor and governance body with an updated business case analysis so that they can decide whether to continue, change or stop the project','Cut quality to reduce cost','Hide the analysis until the next phase gate'],answer:[1],
   explanation:'Sunk costs should not drive decisions. Governance must reassess viability when expected value changes significantly.',
   ref:'Principle: Focus on value · Performance domain: Governance'},
  {id:'R19',domain:D,task:3,approach:'Hybrid',type:'single',
   stem:'Which measure best indicates that a project is delivering value, rather than just output?',
   options:['Number of features delivered','Percentage of the budget spent','Achievement of agreed outcome measures, such as adoption, cost savings or customer satisfaction','Number of hours worked'],answer:[2],
   explanation:'Value is measured by outcomes and benefits, not by activity or output volume.',
   ref:'Principle: Focus on value · Focus area: Monitoring and Controlling'},
  {id:'R20',domain:D,task:3,approach:'Agile',type:'single',
   stem:'User feedback from a recent increment shows that customers rarely use a feature that consumed a quarter of the team’s effort. What should happen?',
   options:['Continue enhancing the feature to increase its use','Share the data with the product owner to reassess the backlog and redirect investment toward higher-value items','Remove the feature immediately without discussion','Ignore the data because the feature was approved'],answer:[1],
   explanation:'Empirical feedback should guide future investment. The product owner uses it to reprioritize toward value.',
   ref:'Principle: Focus on value · Performance domain: Scope'},
  {id:'R21',domain:D,task:3,approach:'Predictive',type:'single',
   stem:'Who is primarily responsible for tracking and reporting whether benefits are realized after the project closes?',
   options:['The project team','The benefits owner identified in the benefits management plan, usually in the business or operations','The vendor','The PMO, only if requested'],answer:[1],
   explanation:'Benefits are often realized after closure, so a named benefits owner in the business is accountable for tracking them.',
   ref:'Principle: Focus on value · Focus area: Closing'},
  {id:'R22',domain:D,task:3,approach:'Hybrid',type:'multi',
   stem:'Which TWO practices help ensure value is delivered early and often?',
   options:['Delivering in small, usable increments and gathering feedback','Holding all deliverables until the final release','Prioritizing work by value and risk','Measuring progress only by the percentage of the schedule elapsed','Adding all requested features before release'],answer:[0,2],
   explanation:'Incremental delivery and value-based prioritization deliver benefits earlier and reduce risk.',
   ref:'Principle: Focus on value · Performance domain: Scope'},

  // Task 4 — Plan and manage resources (6)
  {id:'R23',domain:D,task:4,approach:'Predictive',type:'single',
   stem:'Which tool shows who is Responsible, Accountable, Consulted and Informed for each deliverable?',
   options:['Resource histogram','RACI chart','Organizational breakdown structure','Resource calendar'],answer:[1],
   explanation:'A RACI chart is a responsibility assignment matrix that clarifies roles for each activity or deliverable. There should be only one “Accountable” per item.',
   ref:'Performance domain: Resources · Focus area: Planning'},
  {id:'R24',domain:D,task:4,approach:'Predictive',type:'single',
   stem:'What is the main difference between resource leveling and resource smoothing?',
   options:['They are the same technique','Leveling can change the critical path and end date; smoothing adjusts activities only within their float, so the end date does not change','Smoothing always extends the project','Leveling is used only in agile projects'],answer:[1],
   explanation:'Leveling resolves over-allocation even if the schedule is extended. Smoothing works within available float.',
   ref:'Performance domains: Resources, Schedule · Focus area: Planning'},
  {id:'R25',domain:D,task:4,approach:'Agile',type:'single',
   stem:'An agile team’s capacity will drop next sprint because two members are on vacation. How should this be handled in sprint planning?',
   options:['Plan the same amount of work and ask others to cover','Plan the sprint based on the reduced capacity and let the team select a realistic amount of work','Cancel the sprint','Add contractors for one sprint'],answer:[1],
   explanation:'Sprint planning should reflect actual team capacity so that commitments are realistic and the pace is sustainable.',
   ref:'Performance domain: Resources · Focus area: Planning'},
  {id:'R26',domain:D,task:4,approach:'Hybrid',type:'single',
   stem:'A project needs a rare cloud-security specialist for six weeks in four months’ time. What should the project manager do now?',
   options:['Wait until the work starts and then search','Identify the requirement in the resource plan, and start negotiations or procurement early given the lead time','Train an existing team member in six weeks','Remove the work from scope'],answer:[1],
   explanation:'Scarce resources need early planning and acquisition to avoid schedule risk.',
   ref:'Performance domain: Resources · Focus area: Planning'},
  {id:'R27',domain:D,task:4,approach:'Agile',type:'single',
   stem:'What team composition is ideal for an agile team?',
   options:['Specialists who work only in their own area','Cross-functional, stable team members—ideally with “T-shaped” skills—who together have everything needed to deliver increments','A team that changes every sprint','Only senior developers'],answer:[1],
   explanation:'Cross-functional, stable teams with broad skills reduce handoffs and dependencies and improve flow.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'R28',domain:D,task:4,approach:'Predictive',type:'single',
   stem:'Physical materials for a construction project are arriving earlier than needed and being damaged in storage. What should the project manager do?',
   options:['Accept the damage as a normal cost','Adjust delivery schedules with suppliers to just-in-time arrival, and improve storage and handling','Order extra materials to cover the losses','Stop all deliveries'],answer:[1],
   explanation:'Physical resource management includes logistics and timing. Just-in-time delivery reduces storage risk and waste.',
   ref:'Performance domain: Resources · Principle: Integrate sustainability'},

  // Task 5 — Plan and manage procurement (6)
  {id:'R29',domain:D,task:5,approach:'Predictive',type:'single',
   stem:'Which contract type places the most cost risk on the seller?',
   options:['Cost plus fixed fee','Time and materials','Firm fixed price','Cost plus award fee'],answer:[2],
   explanation:'Under a firm fixed price contract, the seller must deliver for the agreed price, so the seller bears most of the cost risk.',
   ref:'Performance domains: Finance, Resources (procurement) · Focus area: Planning'},
  {id:'R30',domain:D,task:5,approach:'Predictive',type:'dropdown',
   stem:'A fixed-price-incentive-fee contract has a target cost of $100,000, a target fee of $10,000, a ceiling price of $120,000 and a 70/30 buyer/seller share ratio. The seller’s actual cost is $90,000. What is the final price to the buyer?',
   options:['$97,000','$103,000','$110,000','$120,000'],answer:[1],
   explanation:'The underrun is $10,000. The seller earns 30% of it: $3,000. Fee = $10,000 + $3,000 = $13,000. Price = $90,000 + $13,000 = $103,000, which is below the ceiling.',
   ref:'Performance domain: Finance · Focus area: Executing'},
  {id:'R31',domain:D,task:5,approach:'Agile',type:'single',
   stem:'A buyer wants to procure software development services using an agile approach where scope will evolve. Which contracting approach fits best?',
   options:['A single firm fixed price contract for a fully specified scope','A contract structured around time-boxed increments, such as a fixed price per sprint or capped time and materials, with the ability to reprioritize scope','A cost-plus-percentage-of-cost contract','A purchase order for a fixed number of features'],answer:[1],
   explanation:'Agile-friendly contracts fix time and cost per increment while allowing scope to change, aligning commercial terms with adaptive delivery.',
   ref:'Performance domains: Resources, Finance · Focus area: Planning'},
  {id:'R32',domain:D,task:5,approach:'Predictive',type:'single',
   stem:'During a bidder conference, one bidder asks a question privately after the session. What should the project manager do?',
   options:['Answer only that bidder','Answer the question and share the question and answer with all bidders','Refuse to answer','Disqualify the bidder'],answer:[1],
   explanation:'Fairness and transparency require that all bidders receive the same information.',
   ref:'Principle: Be an accountable leader · Ethics · Focus area: Executing'},
  {id:'R33',domain:D,task:5,approach:'Hybrid',type:'multi',
   stem:'When selecting a vendor for a critical AI-enabled analytics platform, which TWO criteria are most important to include in the evaluation?',
   options:['Data privacy, security and responsible-AI practices','Only the lowest price','The vendor’s technical capability and support model, with references','The vendor’s office location near the project manager','The number of marketing awards the vendor has won'],answer:[0,2],
   explanation:'Source selection should balance capability, risk and compliance—especially for AI and data platforms—rather than price alone.',
   ref:'Performance domains: Risk, Resources · AI in project management'},
  {id:'R34',domain:D,task:5,approach:'Predictive',type:'single',
   stem:'The seller has delivered all items, but the contract requires a formal acceptance letter and final payment. The project is closing. What should the project manager confirm?',
   options:['That the seller has been paid—nothing else is needed','That deliverables are formally accepted, open claims are resolved, final payment is made and procurement records are archived','That the seller is invited to the closing party','That the contract is extended for future work'],answer:[1],
   explanation:'Closing procurements involves formal acceptance, resolving claims, completing payment and archiving records.',
   ref:'Focus area: Closing · Performance domain: Governance'},

  // Task 6 — Plan and manage finance (6)
  {id:'R35',domain:D,task:6,approach:'Predictive',type:'dropdown',
   stem:'BAC = $500,000, EV = $200,000, AC = $250,000. What is the to-complete performance index (TCPI) needed to finish within the original budget?',
   options:['0.80','1.00','1.20','1.25'],answer:[2],
   explanation:'TCPI = (BAC – EV) ÷ (BAC – AC) = (500 – 200) ÷ (500 – 250) = 300 ÷ 250 = 1.20. The remaining work must be done 20% more efficiently than planned.',
   ref:'Performance domain: Finance · Focus area: Monitoring and Controlling'},
  {id:'R36',domain:D,task:6,approach:'Predictive',type:'single',
   stem:'What is included in the cost baseline?',
   options:['Project cost estimates plus management reserve','Project cost estimates plus contingency reserves','Only direct costs','The total funding requirement including management reserve'],answer:[1],
   explanation:'The cost baseline is the approved budget including contingency reserves. Adding management reserves gives the total project budget.',
   ref:'Performance domain: Finance · Focus area: Planning'},
  {id:'R37',domain:D,task:6,approach:'Agile',type:'single',
   stem:'An agile team of eight people costs $96,000 per two-week sprint. The release is forecast to need six sprints. What is the most appropriate way to present the release budget?',
   options:['A fixed budget for a fixed set of features','About $576,000 for six sprints, with scope prioritized to fit, and the forecast updated as velocity and priorities evolve','$96,000 because only one sprint is planned','No budget, because agile projects are funded continuously'],answer:[1],
   explanation:'Agile budgets are often based on team cost multiplied by the number of iterations (6 × $96,000 = $576,000). Scope is managed to fit, and forecasts are revisited.',
   ref:'Performance domain: Finance · Focus area: Planning'},
  {id:'R38',domain:D,task:6,approach:'Hybrid',type:'single',
   stem:'The project’s CPI is 0.92 and trending down. What should the project manager do?',
   options:['Wait until the CPI drops below 0.80','Analyze the causes of the cost variance, forecast the EAC, and propose corrective actions or a baseline change through governance','Ask the finance team to fix the numbers','Remove contingency reserves to cover the variance'],answer:[1],
   explanation:'A deteriorating trend calls for analysis, forecasting and timely corrective action according to agreed variance thresholds.',
   ref:'Performance domain: Finance · Focus area: Monitoring and Controlling'},
  {id:'R39',domain:D,task:6,approach:'Predictive',type:'dropdown',
   stem:'A project has BAC = $800,000 and CPI = 0.80 at 50% complete. Using the typical-variance formula, what is the variance at completion (VAC)?',
   options:['–$100,000','–$160,000','–$200,000','+$200,000'],answer:[2],
   explanation:'EAC = BAC ÷ CPI = 800,000 ÷ 0.80 = $1,000,000. VAC = BAC – EAC = 800,000 – 1,000,000 = –$200,000.',
   ref:'Performance domain: Finance · Focus area: Monitoring and Controlling'},
  {id:'R40',domain:D,task:6,approach:'Hybrid',type:'single',
   stem:'Finance requires quarterly funding requests, but the project’s spending is uneven, with large vendor payments in some months. What should the project manager do?',
   options:['Request the full budget in the first quarter','Prepare a time-phased funding requirement based on the planned spend, including reserve timing, and reconcile it with funding limits','Delay vendor payments to smooth spending','Ignore the funding cycle'],answer:[1],
   explanation:'Funding requirements are derived from the time-phased cost baseline and must be reconciled with the organization’s funding constraints.',
   ref:'Performance domain: Finance · Focus area: Planning'},

  // Task 7 — Plan and optimize quality (5)
  {id:'R41',domain:D,task:7,approach:'Predictive',type:'single',
   stem:'Which cost of quality category includes training and process documentation?',
   options:['Internal failure costs','External failure costs','Prevention costs','Appraisal costs'],answer:[2],
   explanation:'Prevention costs (training, documented processes, the right equipment) are a cost of conformance. They reduce the much higher costs of failure.',
   ref:'Principle: Embed quality · Performance domain: Finance'},
  {id:'R42',domain:D,task:7,approach:'Predictive',type:'single',
   stem:'A Pareto chart of defects shows that two causes account for 78% of all defects. What should the team do?',
   options:['Address all causes equally','Focus improvement efforts on the two major causes first','Ignore the chart because the sample is small','Increase final inspections'],answer:[1],
   explanation:'The Pareto principle (80/20) helps the team focus on the vital few causes that produce most of the problems.',
   ref:'Principle: Embed quality · Focus area: Monitoring and Controlling'},
  {id:'R43',domain:D,task:7,approach:'Agile',type:'single',
   stem:'How do agile teams primarily ensure quality?',
   options:['A separate testing phase at the end of the project','Building quality in through a definition of done, continuous integration, automated testing and frequent feedback','Customer inspection of the final product','Quality audits once a year'],answer:[1],
   explanation:'Agile teams embed quality into every increment rather than relying on late inspection.',
   ref:'Principle: Embed quality · Performance domain: Scope'},
  {id:'R44',domain:D,task:7,approach:'Hybrid',type:'multi',
   stem:'Which TWO practices reflect “embedding quality into processes and deliverables”?',
   options:['Defining quality requirements and acceptance criteria early with stakeholders','Relying on final inspection to catch defects','Using root-cause analysis and continuous improvement on recurring defects','Accepting defects to protect the schedule','Testing only if time permits'],answer:[0,2],
   explanation:'Quality is planned in from the start and improved continuously, not inspected in at the end.',
   ref:'Principle: Embed quality · Focus areas: Planning, Monitoring and Controlling'},
  {id:'R45',domain:D,task:7,approach:'Predictive',type:'single',
   stem:'What is the difference between quality and grade?',
   options:['They mean the same thing','Quality is the degree to which characteristics meet requirements; grade is a category for products with the same use but different technical characteristics','Grade is always more important than quality','Low grade always means low quality'],answer:[1],
   explanation:'Low grade can be acceptable, but low quality (failing to meet requirements) is always a problem.',
   ref:'Principle: Embed quality · Performance domain: Scope'},

  // Task 8 — Plan and manage schedule (7)
  {id:'R46',domain:D,task:8,approach:'Predictive',type:'dropdown',graphic:'network',
   stem:'Using the network diagram (durations in days), what is the total project duration?',
   options:['12 days','14 days','15 days','23 days'],answer:[2],
   explanation:'The paths are A-B-D-F = 3+4+5+3 = 15, A-B-E-F = 12 and A-C-E-F = 14. The longest path (critical path) is A-B-D-F, so the duration is 15 days.',
   ref:'Performance domain: Schedule · Focus area: Planning'},
  {id:'R47',domain:D,task:8,approach:'Predictive',type:'hotspot',graphic:'network',
   stem:'Using the network diagram, click the activity on the critical path that has the longest duration.',
   options:['A','B','C','D','E','F'],answer:[3],
   explanation:'The critical path is A-B-D-F (3 + 4 + 5 + 3 = 15 days). Of these activities, D has the longest duration (5 days). C (6 days) is longer, but it is on path A-C-E-F (14 days) and has 1 day of float, so it is not critical.',
   ref:'Performance domain: Schedule · Focus area: Planning'},
  {id:'R48',domain:D,task:8,approach:'Predictive',type:'dropdown',
   stem:'An activity has an optimistic estimate of 4 days, a most likely estimate of 7 days and a pessimistic estimate of 16 days. What is the PERT (beta) expected duration?',
   options:['7 days','8 days','9 days','12 days'],answer:[1],
   explanation:'PERT = (O + 4M + P) ÷ 6 = (4 + 28 + 16) ÷ 6 = 48 ÷ 6 = 8 days.',
   ref:'Performance domain: Schedule · Focus area: Planning'},
  {id:'R49',domain:D,task:8,approach:'Predictive',type:'single',
   stem:'The project is two weeks behind. The sponsor will not accept a later date, and additional budget is available. Which schedule compression technique should the project manager consider first?',
   options:['Fast tracking critical-path activities that cannot overlap','Crashing critical-path activities where adding resources gives the greatest time saving for the lowest cost','Crashing non-critical activities','Reducing scope without approval'],answer:[1],
   explanation:'Crashing adds resources to critical-path activities. With budget available, it is chosen for the best cost-to-time trade-off. Compressing non-critical work does not shorten the project.',
   ref:'Performance domains: Schedule, Finance · Focus area: Monitoring and Controlling'},
  {id:'R50',domain:D,task:8,approach:'Agile',type:'single',
   stem:'What is the purpose of a time-box in agile delivery?',
   options:['To extend work until it is complete','To fix the duration of an activity or iteration so that scope adapts, creating a predictable cadence and forcing prioritization','To track individual hours','To replace the product backlog'],answer:[1],
   explanation:'Time-boxes fix time and let scope vary, which creates a rhythm and keeps the focus on the most valuable work.',
   ref:'Performance domain: Schedule · Focus area: Executing'},
  {id:'R51',domain:D,task:8,approach:'Hybrid',type:'single',
   stem:'A hybrid project has a fixed regulatory milestone that depends on outputs from an agile team. How should the project manager manage this dependency?',
   options:['Ask the agile team to stop sprinting and follow the Gantt chart','Make the milestone and its required outputs visible in the agile team’s release plan and backlog priorities, and track them in the integrated schedule','Ignore the dependency until the milestone is near','Create a separate project for the agile work'],answer:[1],
   explanation:'Dependencies between adaptive and predictive parts must be visible and prioritized in both planning views.',
   ref:'Principle: Adopt a holistic view · Performance domain: Schedule'},
  {id:'R52',domain:D,task:8,approach:'Agile',type:'single',
   stem:'An agile team’s velocity has varied between 22 and 38 points over the last six sprints. How should the team forecast the release?',
   options:['Use the highest velocity','Use a range based on low, average and high velocity, and communicate the forecast as a range','Use the most recent sprint only','Refuse to forecast'],answer:[1],
   explanation:'Range-based forecasting reflects real variability and supports honest conversations about scope and dates.',
   ref:'Performance domain: Schedule · Focus area: Planning'},

  // Task 9 — Evaluate project status (5)
  {id:'R53',domain:D,task:9,approach:'Agile',type:'single',graphic:'cfd',
   stem:'The cumulative flow diagram shows the team’s work over 10 days. What does it most likely indicate?',
   options:['The team is working at a steady, healthy flow','Work is accumulating in Testing, so testing is a bottleneck and work-in-progress should be limited','The backlog is empty','The team is finishing work faster than it starts'],answer:[1],
   explanation:'The Testing band is widening while the Done band grows slowly. Work is piling up in testing. Limiting WIP and swarming on testing would improve flow.',
   ref:'Performance domain: Schedule · Focus area: Monitoring and Controlling'},
  {id:'R54',domain:D,task:9,approach:'Predictive',type:'single',
   stem:'SPI = 1.05 and CPI = 0.85. What does this mean?',
   options:['Ahead of schedule and under budget','Ahead of schedule and over budget','Behind schedule and over budget','Behind schedule and under budget'],answer:[1],
   explanation:'An SPI above 1.0 means more work was completed than planned (ahead of schedule). A CPI below 1.0 means the completed work cost more than budgeted (over budget).',
   ref:'Performance domains: Schedule, Finance · Focus area: Monitoring and Controlling'},
  {id:'R55',domain:D,task:9,approach:'Hybrid',type:'single',
   stem:'A project dashboard shows all indicators as green, but team members privately say the project is struggling. What should the project manager do?',
   options:['Trust the dashboard','Investigate by reviewing actual progress data, speaking with the team and verifying how indicators are calculated','Ask the team to stop complaining','Change all indicators to red'],answer:[1],
   explanation:'Status reporting must reflect reality. Discrepancies should be investigated to avoid “watermelon” reporting (green outside, red inside).',
   ref:'Principle: Be an accountable leader · Focus area: Monitoring and Controlling'},
  {id:'R56',domain:D,task:9,approach:'Agile',type:'multi',
   stem:'Which TWO metrics best help an agile team evaluate its delivery performance?',
   options:['Velocity trend and cycle time','Number of hours each member works','Escaped defects and customer feedback on increments','Lines of code written','Number of meetings attended'],answer:[0,2],
   explanation:'Flow and predictability metrics, combined with quality and customer value signals, give a balanced view of performance.',
   ref:'Principle: Embed quality · Focus area: Monitoring and Controlling'},
  {id:'R57',domain:D,task:9,approach:'Predictive',type:'single',
   stem:'An AI analytics tool predicts a 70% probability that the project will miss its final milestone. What should the project manager do?',
   options:['Ignore the prediction because it is only a model','Treat the prediction as an early warning: validate the drivers behind it, discuss them with the team and update the risk and schedule analysis','Report the project as failed','Replace the schedule with the tool’s forecast'],answer:[1],
   explanation:'Predictive analytics provide useful signals, but they must be interpreted and validated by people before decisions are made.',
   ref:'Principle: Be an accountable leader · AI in project management · Performance domain: Risk'},

  // Task 10 — Manage project closure (5)
  {id:'R58',domain:D,task:10,approach:'Predictive',type:'single',
   stem:'The sponsor decides to cancel a project midway because of a strategy change. What should the project manager do?',
   options:['Stop all work and release the team immediately','Follow the closure process: document the work completed, transfer usable deliverables, close contracts, capture lessons learned and release resources','Continue work until the end of the phase','Ask the sponsor to reconsider'],answer:[1],
   explanation:'Even cancelled projects need an orderly closure to preserve value, meet contractual obligations and capture lessons learned.',
   ref:'Focus area: Closing · Principle: Be an accountable leader'},
  {id:'R59',domain:D,task:10,approach:'Agile',type:'single',
   stem:'An agile product has reached its last planned release. What indicates the project work can be closed?',
   options:['The product backlog is empty','The product owner and stakeholders confirm that the release goals and acceptance criteria are met and the product is transitioned to its owners','The team’s velocity drops to zero','The budget is fully spent'],answer:[1],
   explanation:'Closure is based on meeting objectives and transitioning the product, not on an empty backlog or a spent budget.',
   ref:'Focus area: Closing · Principle: Focus on value'},
  {id:'R60',domain:D,task:10,approach:'Predictive',type:'multi',
   stem:'Which TWO activities are part of administrative project closure?',
   options:['Obtaining formal acceptance of deliverables','Starting the next phase’s procurement','Archiving project records and updating organizational process assets','Hiring new team members','Rebaselining the schedule'],answer:[0,2],
   explanation:'Closure includes formal acceptance, archiving records and updating organizational assets with lessons learned.',
   ref:'Focus area: Closing · Performance domain: Governance'},
  {id:'R61',domain:D,task:10,approach:'Hybrid',type:'single',
   stem:'The customer has accepted all deliverables, but a few minor punch-list items remain open. The sponsor wants the team released. What is the best approach?',
   options:['Close the project and ignore the punch list','Agree on a plan and owner for the remaining items—for example in the warranty or operations backlog—document it, and then complete closure','Keep the whole team until every item is closed','Ask the customer to fix the items'],answer:[1],
   explanation:'Remaining items need clear ownership and documentation before closure, without holding the entire team unnecessarily.',
   ref:'Focus area: Closing · Performance domain: Resources'},
  {id:'R62',domain:D,task:10,approach:'Predictive',type:'single',
   stem:'Why should the project manager release team members formally at closure?',
   options:['It is optional','To ensure that people return to their functional areas with performance input provided, and that resource calendars are updated for other projects','To reduce payroll costs only','To reward the team'],answer:[1],
   explanation:'Formal release supports people’s careers and the organization’s resource planning.',
   ref:'Focus area: Closing · Performance domain: Resources'}
];
