export interface WorkItem{title:string;description?:string;repositoryUrl?:string;priority:number}
export interface PortfolioArea{id:string;number:string;category:string;description:string;tools:string[];workItems:WorkItem[];image:string;imageAlt:string;priority:number}
export interface MediaVideo{id:string;title:string;description:string;youtubeVideoId:string;priority:number;published:boolean}
export interface EventItem{title:string;date:string;description:string;image:string;imageAlt:string;repositoryUrl?:string;priority:number}
export interface ResourceItem{type:'Book'|'Article';title:string;description:string;repositoryUrl?:string;priority:number}
export interface Course{courseCode:string|null;courseName:string;academicStage?:string;term?:string;creditHours:number;grade:string|number|null;status:string;importantCoursework:string[]}
export interface Degree{id:string;shortName:string;degree:string;major:string;institution:string;studyPeriod:string;status:string;cgpa:number;cgpaScale:number|string;totalCredits?:number;completedCredits?:number;canadianEquivalency?:string;courses:Course[]}
export interface EducationData{profile:{name:string;lastUpdated:string;privacyNote:string};degrees:Degree[];sourceNotes:string[]}
export interface TrainingVideo{title:string;youtubeVideoId:string;duration?:string;priority:number}
export interface TrainingModule{id:string;title:string;summary:string;level:string;priority:number;videos:TrainingVideo[];quiz:{question:string;options:string[];answer:number};calculation:{question:string;answer:number;unit:string};steps:string[]}
