import {ExamQuestion} from '../../exam-types';

const D='Business Environment' as const;

export const BUSINESS_ENVIRONMENT_QUESTIONS:ExamQuestion[]=[
  // Task 1 — Governance (5)
  {id:'S3-B01',domain:D,task:1,approach:'Agile',type:'single',
   stem:'An organization runs 12 agile teams on one product. Executives want oversight without slowing teams down. Which governance approach fits best?',
   options:['Weekly approval of every team’s sprint backlog','Lightweight, cadence-based governance: regular portfolio or program reviews of outcomes, guardrails for budgets and risk, and decentralized decisions within those guardrails','No governance at all','A single manager approving every change'],answer:[1],
   explanation:'Adaptive governance sets guardrails and reviews outcomes at a regular cadence, letting teams decide within agreed limits.',
   ref:'Performance domain: Governance · Principle: Build an empowered culture'},
  {id:'S3-B02',domain:D,task:1,approach:'Predictive',type:'single',
   stem:'At project initiation, which governance element should define how the project’s success will be judged?',
   options:['The team’s vacation calendar','Success criteria and key performance measures agreed with the sponsor and documented in the charter or governance plan','The final lessons-learned report','The vendor’s marketing materials'],answer:[1],
   explanation:'Defining success criteria early gives governance a clear basis for decisions and evaluation.',
   ref:'Performance domain: Governance · Focus area: Initiating'},
  {id:'S3-B03',domain:D,task:1,approach:'Hybrid',type:'single',
   stem:'The board wants environmental, social and governance (ESG) commitments reflected in all major projects. How should the project manager respond?',
   options:['Treat ESG as a communications exercise','Incorporate the relevant ESG commitments into the project’s objectives, decision criteria, reporting and supplier requirements','Leave ESG to the sustainability department','Add ESG only to the closing report'],answer:[1],
   explanation:'Integrating ESG into objectives, decisions and reporting makes sustainability part of governance, not an afterthought.',
   ref:'Principle: Integrate sustainability · Performance domain: Governance'},
  {id:'S3-B04',domain:D,task:1,approach:'Predictive',type:'single',
   stem:'Several managers claim authority to approve project purchases, which causes confusion. What should be established?',
   options:['A first-come, first-served rule','An authority matrix (delegation of authority) defining who can approve which decisions and spending levels','Approval by the team','No approvals for small purchases'],answer:[1],
   explanation:'An authority matrix clarifies decision rights and prevents confusion and control gaps.',
   ref:'Performance domain: Governance · Focus area: Planning'},
  {id:'S3-B05',domain:D,task:1,approach:'Hybrid',type:'multi',
   stem:'The PMO’s standard governance process does not fit a fast-moving innovation project. Which TWO actions should the project manager take?',
   options:['Propose a tailored governance approach to the PMO, explaining the rationale and the controls it keeps','Ignore the PMO’s requirements','Agree with the PMO and sponsor on the minimum governance checkpoints and reporting','Use the full standard process without question','Run the project without a sponsor'],answer:[0,2],
   explanation:'Tailoring governance with the PMO maintains oversight while fitting the project’s context.',
   ref:'Principle: Adopt a holistic view · Performance domain: Governance'},

  // Task 2 — Compliance (5)
  {id:'S3-B06',domain:D,task:2,approach:'Agile',type:'single',
   stem:'A developer wants to use an open-source library in a commercial product. What should be checked first?',
   options:['Only whether the library is popular','The library’s licence terms and the organization’s open-source policy, to confirm that its use is permitted and obligations can be met','Whether the library is free of charge','Nothing; open source is always allowed'],answer:[1],
   explanation:'Open-source licences carry obligations that can affect commercial products. Compliance must be checked before use.',
   ref:'Performance domain: Governance · Principle: Embed quality'},
  {id:'S3-B07',domain:D,task:2,approach:'Predictive',type:'single',
   stem:'A foreign government official suggests that a “facilitation payment” will speed up a permit for an international project. What should the project manager do?',
   options:['Pay it, because it is common locally','Refuse, report it according to the organization’s anti-corruption policy, and seek guidance from the legal and compliance team','Ask the local agent to pay it','Pay it and record it as a consulting fee'],answer:[1],
   explanation:'Such payments may breach anti-corruption laws and policies. The ethical response is to refuse and report.',
   ref:'Principle: Be an accountable leader · Ethics'},
  {id:'S3-B08',domain:D,task:2,approach:'Hybrid',type:'single',
   stem:'A project will use AI to score loan applications, which involves personal information. What compliance step should come before development?',
   options:['None','A privacy impact assessment and an algorithmic or AI impact assessment, to identify legal, privacy and fairness risks and the required safeguards','A marketing review','A load test'],answer:[1],
   explanation:'Impact assessments identify risks to individuals and the safeguards required before high-impact AI systems are built.',
   ref:'Performance domain: Governance · AI in project management'},
  {id:'S3-B09',domain:D,task:2,approach:'Predictive',type:'single',
   stem:'The organization must keep project financial records for seven years. Who is responsible for making sure project records meet this requirement at closure?',
   options:['No one','The project manager, who must archive records according to the organization’s retention policy','The newest team member','The vendor'],answer:[1],
   explanation:'The project manager makes sure records are archived in line with retention requirements as part of closure.',
   ref:'Focus area: Closing · Performance domain: Governance'},
  {id:'S3-B10',domain:D,task:2,approach:'Hybrid',type:'multi',
   stem:'Which TWO practices help a project stay compliant with environmental permit conditions?',
   options:['Recording permit conditions as requirements with owners and monitoring activities','Reviewing permits only if inspectors arrive','Including permit obligations in contractor agreements and site inductions','Assuming contractors know the permits','Keeping permits in the sponsor’s office only'],answer:[0,2],
   explanation:'Compliance requires explicit ownership, monitoring and communication of obligations to everyone doing the work.',
   ref:'Principle: Integrate sustainability · Performance domain: Governance'},

  // Task 3 — Changes (6)
  {id:'S3-B11',domain:D,task:3,approach:'Predictive',type:'single',
   stem:'What is a configuration item?',
   options:['Any team meeting','A component—such as a document, software module or design drawing—that is identified and placed under configuration control','A type of risk','A cost account'],answer:[1],
   explanation:'Configuration items are controlled so that changes to them are tracked and versions are known.',
   ref:'Performance domain: Governance · Focus area: Monitoring and Controlling'},
  {id:'S3-B12',domain:D,task:3,approach:'Predictive',type:'single',
   stem:'A regulator requires a design change that must be implemented. Does it still need to go through change control?',
   options:['No, because it is mandatory','Yes: the change is documented and its impacts on scope, schedule and cost are analyzed so that plans and baselines are updated, even though approval is effectively required','Only if the cost is high','Only if the sponsor asks'],answer:[1],
   explanation:'Mandatory changes still need impact analysis, documentation and plan updates through change control.',
   ref:'Performance domain: Governance · Focus area: Monitoring and Controlling'},
  {id:'S3-B13',domain:D,task:3,approach:'Hybrid',type:'single',
   stem:'Two weeks before go-live, the organization declares a change freeze. A stakeholder requests a “small” change. What should happen?',
   options:['Make the change because it is small','Follow the freeze rules: defer the change unless it qualifies as critical under the defined exception process','Make the change after hours','Ask the team to vote'],answer:[1],
   explanation:'Change freezes reduce risk before go-live. Exceptions follow a defined process.',
   ref:'Performance domain: Governance · Principle: Embed quality'},
  {id:'S3-B14',domain:D,task:3,approach:'Agile',type:'single',
   stem:'A fixed-price agile contract specifies a set of features. The client now wants different features of similar size. What is the best approach?',
   options:['Refuse all changes','Use the contract’s change mechanism to swap features of equivalent size, documenting the change and keeping price and timeline stable','Deliver both sets for the same price','Terminate the contract'],answer:[1],
   explanation:'Agile-friendly contracts allow scope swaps within agreed rules, keeping commercial terms intact.',
   ref:'Performance domains: Resources (procurement), Scope'},
  {id:'S3-B15',domain:D,task:3,approach:'Predictive',type:'single',
   stem:'After a change to the design is approved, the project manager updates the scope baseline. Which other documents may also need updating?',
   options:['None','The schedule and cost baselines, requirements and traceability, risk register and communications, as affected','Only the lessons learned','Only the charter'],answer:[1],
   explanation:'Changes ripple through integrated plans. All affected documents and baselines must be updated.',
   ref:'Performance domain: Governance · Principle: Adopt a holistic view'},
  {id:'S3-B16',domain:D,task:3,approach:'Hybrid',type:'multi',
   stem:'Which TWO signs suggest a project’s change control is not working?',
   options:['Work is being done that cannot be traced to approved requirements or changes','Change requests are logged and decided promptly','Baselines no longer reflect what the team is actually delivering','Stakeholders know how to request changes','The change log is current'],answer:[0,2],
   explanation:'Untraceable work and outdated baselines indicate uncontrolled change.',
   ref:'Performance domains: Governance, Scope · Focus area: Monitoring and Controlling'},

  // Task 4 — Impediments and issues (5)
  {id:'S3-B17',domain:D,task:4,approach:'Predictive',type:'single',
   stem:'The issue log has 40 open issues, and the team does not know which to work on. What should the project manager do?',
   options:['Work on the oldest issues first','Prioritize issues by impact and urgency, confirm owners and due dates, and review the top issues regularly','Close all issues older than a month','Ask each team member to choose'],answer:[1],
   explanation:'Prioritization and ownership focus effort on the issues that matter most.',
   ref:'Focus area: Monitoring and Controlling · Performance domain: Governance'},
  {id:'S3-B18',domain:D,task:4,approach:'Hybrid',type:'single',
   stem:'What is the difference between a workaround and a permanent fix for an issue?',
   options:['There is no difference','A workaround is an unplanned response to keep work moving in the short term; a permanent fix addresses the root cause so that the issue does not recur','A permanent fix is always faster','A workaround is planned in advance'],answer:[1],
   explanation:'Workarounds handle immediate impact; permanent fixes remove the cause. Both may be needed.',
   ref:'Performance domain: Risk · Focus area: Executing'},
  {id:'S3-B19',domain:D,task:4,approach:'Agile',type:'single',
   stem:'The team’s build pipeline is slow and unreliable, wasting hours each day. The team says it has no time to fix it. What should the project manager do?',
   options:['Accept the delay','Make the cost of the problem visible to the product owner, and agree to dedicate capacity to fixing the pipeline as a priority','Ask the team to work longer hours','Remove automated tests to speed up builds'],answer:[1],
   explanation:'Removing systemic impediments often requires investing capacity, which the product owner can prioritize once the cost is clear.',
   ref:'Principle: Embed quality · Focus area: Executing'},
  {id:'S3-B20',domain:D,task:4,approach:'Predictive',type:'single',
   stem:'A supplier issue has been escalated twice with no response from the supplier’s project manager. What should the project manager do next?',
   options:['Wait longer','Follow the contract’s escalation path—for example, to the supplier’s account executive—through procurement, with documented impacts','Stop paying the supplier','Complain publicly'],answer:[1],
   explanation:'Contracts define escalation paths. Using them formally, with documented impacts, protects the project.',
   ref:'Performance domains: Resources (procurement), Governance'},
  {id:'S3-B21',domain:D,task:4,approach:'Hybrid',type:'multi',
   stem:'Which TWO practices help prevent recurring issues?',
   options:['Root-cause analysis of significant issues','Closing issues as soon as a workaround is found, without further action','Updating processes, checklists or risk registers based on the causes found','Blaming individuals','Recording issues only verbally'],answer:[0,2],
   explanation:'Understanding causes and changing processes prevents the same issues from returning.',
   ref:'Principle: Embed quality · Focus area: Monitoring and Controlling'},

  // Task 5 — Risk (5)
  {id:'S3-B22',domain:D,task:5,approach:'Predictive',type:'single',
   stem:'What is a risk breakdown structure (RBS)?',
   options:['A list of team members','A hierarchical representation of risk categories that helps identify and organize risks','A schedule of risk meetings','A budget for risks'],answer:[1],
   explanation:'An RBS groups potential sources of risk—technical, external, organizational and so on—to support systematic identification.',
   ref:'Performance domain: Risk · Focus area: Planning'},
  {id:'S3-B23',domain:D,task:5,approach:'Predictive',type:'single',
   stem:'What is the difference between qualitative and quantitative risk analysis?',
   options:['They are the same','Qualitative analysis prioritizes risks using probability and impact ratings; quantitative analysis numerically estimates their combined effect on project objectives, for example with simulation','Quantitative analysis is always done first','Qualitative analysis uses Monte Carlo simulation'],answer:[1],
   explanation:'Qualitative analysis is quick prioritization; quantitative analysis models overall effects for high-priority risks or the whole project.',
   ref:'Performance domain: Risk · Focus area: Planning'},
  {id:'S3-B24',domain:D,task:5,approach:'Hybrid',type:'single',
   stem:'What is a contingency plan, and how is it different from a fallback plan?',
   options:['They are the same','A contingency plan is carried out when a trigger shows the risk is occurring; a fallback plan is used if the primary response proves ineffective','A fallback plan is used first','A contingency plan is used only for opportunities'],answer:[1],
   explanation:'Contingency plans are triggered responses; fallback plans are the backup if the contingency plan fails.',
   ref:'Performance domain: Risk · Focus area: Planning'},
  {id:'S3-B25',domain:D,task:5,approach:'Agile',type:'single',
   stem:'How can an agile team use the product backlog to manage risk?',
   options:['By keeping risks out of the backlog','By prioritizing high-risk items and risk-reduction work—such as spikes—early, when there is still time to change course','By leaving risky items for the last sprint','By assigning risks to the Scrum Master only'],answer:[1],
   explanation:'A risk-adjusted backlog addresses major uncertainty early, reducing exposure.',
   ref:'Performance domain: Risk · Performance domain: Scope'},
  {id:'S3-B26',domain:D,task:5,approach:'Predictive',type:'multi',
   stem:'Which TWO elements should be recorded for each significant risk in the risk register?',
   options:['A risk owner responsible for monitoring and response','The team’s lunch preferences','Triggers or warning signs, and the planned response','The project manager’s salary','The colour of the project logo'],answer:[0,2],
   explanation:'Owners, triggers and responses make risks actionable.',
   ref:'Performance domain: Risk · Focus area: Planning'},

  // Task 6 — Continuous improvement (4)
  {id:'S3-B27',domain:D,task:6,approach:'Predictive',type:'single',
   stem:'Which sequence describes the Six Sigma DMAIC improvement method?',
   options:['Design, Make, Inspect, Approve, Close','Define, Measure, Analyze, Improve, Control','Discover, Model, Implement, Assess, Communicate','Decide, Monitor, Act, Inform, Change'],answer:[1],
   explanation:'DMAIC is a data-driven cycle for improving existing processes.',
   ref:'Principle: Embed quality · Focus area: Monitoring and Controlling'},
  {id:'S3-B28',domain:D,task:6,approach:'Agile',type:'single',
   stem:'A team has many improvement ideas from retrospectives but never acts on them. What practice helps?',
   options:['Ignoring the ideas','Keeping an improvement backlog, choosing the highest-value improvement for each sprint and tracking it like other work','Holding retrospectives less often','Implementing all ideas at once'],answer:[1],
   explanation:'Treating improvements as prioritized backlog items ensures that they are actually implemented.',
   ref:'Principle: Build an empowered culture · Focus area: Executing'},
  {id:'S3-B29',domain:D,task:6,approach:'Hybrid',type:'single',
   stem:'An organization holds a short, focused workshop in which a cross-functional team analyzes and improves one process within a few days. What is this called?',
   options:['A kaizen event','A bidder conference','A phase gate','A steering meeting'],answer:[0],
   explanation:'Kaizen events are short, intensive improvement efforts focused on a specific process.',
   ref:'Principle: Embed quality · Focus area: Executing'},
  {id:'S3-B30',domain:D,task:6,approach:'Predictive',type:'multi',
   stem:'Which TWO actions show that an organization is learning from its projects?',
   options:['Updating standards and templates when lessons reveal better practices','Repeating the same issues on each project','Tracking whether improvements actually reduce recurring problems','Keeping lessons confidential','Discarding project records'],answer:[0,2],
   explanation:'Organizational learning is shown by changed practices and measured improvement.',
   ref:'Principle: Embed quality · Focus area: Closing'},

  // Task 7 — Organizational change (4)
  {id:'S3-B31',domain:D,task:7,approach:'Predictive',type:'single',
   stem:'Before designing training for a new system, what should the project manager do?',
   options:['Use the vendor’s generic training','Conduct a training needs analysis to understand how roles will change and what each group needs to learn','Train everyone the same way','Skip training'],answer:[1],
   explanation:'Training needs analysis targets training to the real changes each group will experience.',
   ref:'Performance domain: Stakeholders · Focus area: Planning'},
  {id:'S3-B32',domain:D,task:7,approach:'Hybrid',type:'single',
   stem:'Staff trust their colleagues more than head office. How can the project make use of this during a system rollout?',
   options:['Rely only on head-office announcements','Develop super-users or change champions in each team who are trained early, help colleagues and give feedback to the project','Avoid local involvement','Hire external trainers only'],answer:[1],
   explanation:'Peer champions increase adoption and provide a feedback channel from the front line.',
   ref:'Performance domain: Stakeholders · Principle: Build an empowered culture'},
  {id:'S3-B33',domain:D,task:7,approach:'Agile',type:'single',
   stem:'The executive sponsor has been absent from all change communications, and staff believe leadership is not committed. What should the project manager do?',
   options:['Continue without the sponsor','Ask the sponsor to take a visible role—such as explaining why the change matters and attending key events—and prepare them to do so','Ask a junior manager to speak instead','Stop communicating'],answer:[1],
   explanation:'Visible, active sponsorship is one of the strongest factors in successful organizational change.',
   ref:'Performance domain: Stakeholders · Principle: Be an accountable leader'},
  {id:'S3-B34',domain:D,task:7,approach:'Hybrid',type:'multi',
   stem:'Which TWO actions help people adapt when a project changes their roles?',
   options:['Explaining clearly how roles will change and what support is available','Announcing changes on the go-live day','Providing training, coaching and time to practise before go-live','Removing old tools before people are ready','Discouraging questions'],answer:[0,2],
   explanation:'Clarity and preparation help people move through change with confidence.',
   ref:'Performance domain: Stakeholders · Focus area: Executing'},

  // Task 8 — External environment (4)
  {id:'S3-B35',domain:D,task:8,approach:'Predictive',type:'single',
   stem:'A national rail strike will delay deliveries of materials for several weeks. What should the project manager do?',
   options:['Wait for the strike to end','Assess the impact on the schedule, explore alternatives such as road transport or re-sequencing work, update the risk and issue logs, and inform stakeholders','Cancel all orders','Ask the team to work overtime'],answer:[1],
   explanation:'External events require impact analysis and practical responses, with transparent communication.',
   ref:'Principle: Adopt a holistic view · Performance domain: Risk'},
  {id:'S3-B36',domain:D,task:8,approach:'Agile',type:'single',
   stem:'An AI service the product depends on announces a large price increase next quarter. What should the product owner and team do?',
   options:['Ignore it until the bill arrives','Assess the cost impact and alternatives—such as other providers or design changes—and reprioritize the backlog if needed','Remove the feature immediately','Pass the full cost to customers without analysis'],answer:[1],
   explanation:'Changes in the external market, including supplier pricing, should be assessed and reflected in priorities and plans.',
   ref:'Performance domains: Finance, Scope · AI in project management'},
  {id:'S3-B37',domain:D,task:8,approach:'Hybrid',type:'single',
   stem:'Wildfire smoke has forced repeated site closures over the past two summers. How should the project respond for its next construction season?',
   options:['Hope for a better summer','Treat climate-related disruption as a known risk: plan schedule buffers, flexible work sequencing and health-and-safety procedures for poor air quality','Cancel the project','Ignore health and safety guidance'],answer:[1],
   explanation:'Recurring external conditions should be incorporated into risk planning to build resilience.',
   ref:'Principle: Integrate sustainability · Performance domain: Risk'},
  {id:'S3-B38',domain:D,task:8,approach:'Predictive',type:'multi',
   stem:'Which TWO sources help a project manager stay aware of changes in the external business environment?',
   options:['Regulatory updates and industry associations','Only the original business case','Market and economic reports, and supplier communications','Rumours in the hallway','Last year’s status reports'],answer:[0,2],
   explanation:'Monitoring credible external sources lets the project anticipate and respond to change.',
   ref:'Principle: Adopt a holistic view · Performance domain: Risk'}
];
