import {CaseStudy,ExamQuestion} from '../../exam-types';

export const CASE_STUDIES:CaseStudy[]=[
  {id:'G',title:'Case G · Prairie Grain Co-op: Digital Operations Platform (hybrid)',graphic:'tornado',context:[
    'Prairie Grain Co-op, owned by 3,000 farm members, is investing in a digital platform. It includes a new ERP for grain accounting (delivered predictively by an integrator) and a member mobile app with IoT grain-bin sensors (built by an internal agile team).',
    'The business case shows a base net present value (NPV) of $600,000. Many members farm in areas with limited internet access. Staff at the co-op’s grain elevators will use the new sensors and tablets daily.',
    'The finance team prepared a sensitivity analysis (tornado diagram) showing how much the NPV could change, in thousands of dollars, if each key variable moved to its low or high estimate.'
  ]},
  {id:'H',title:'Case H · Provincial Digital Licensing Service (agile, Scrum)',graphic:'burndown-2',context:[
    'A provincial ministry is replacing paper fishing and hunting licences with an online service. A Scrum team of eight—four ministry employees and four consultants—works in two-week sprints. The ministry must launch before the next licence season, set by regulation.',
    'The consultants’ contract ends at launch, after which the ministry team will run and improve the service. Ministry officials are new to agile, and some contact developers directly with requests.',
    'You are the project manager working with the team’s Scrum Master and product owner. The chart shows the burndown for the current sprint at the end of day 7.'
  ]},
  {id:'I',title:'Case I · City of Riverbend: Bridge Rehabilitation (predictive)',graphic:'risk-2',context:[
    'The City of Riverbend is rehabilitating a 60-year-old four-lane bridge used by 25,000 vehicles a day. The $9 million project includes deck replacement, steel repairs and repainting, with two lanes kept open during construction.',
    'An engineering consultant designed the work and inspects it. A general contractor builds it under a unit-price contract. City council must approve any change over $250,000.',
    'The risk team has plotted six risks on a probability-and-impact matrix (shown). The contractor’s plan also shows how many electricians are needed each week for lighting and signal work.'
  ]}
];

export const CASE_QUESTIONS:ExamQuestion[]=[
  // ---------- Case G ----------
  {id:'S3-G01',caseId:'G',domain:'Business Environment',task:5,approach:'Hybrid',type:'single',graphic:'tornado',
   stem:'Based on the tornado diagram, which variable should receive the most attention in risk management?',
   options:['Interest rate','Implementation cost','Commodity price','Maintenance cost'],answer:[2],
   explanation:'Commodity price has the widest bar (–420 to +380), so it has the greatest effect on NPV. Sensitivity analysis focuses risk effort on the variables that matter most.',
   ref:'Performance domains: Risk, Finance · Focus area: Planning'},
  {id:'S3-G02',caseId:'G',domain:'Process',task:6,approach:'Hybrid',type:'dropdown',graphic:'tornado',
   stem:'If the commodity price turns out at its low estimate and all other variables stay at base values, what will the NPV be?',
   options:['–$420,000','$180,000','$220,000','$980,000'],answer:[1],
   explanation:'Base NPV $600,000 + (–$420,000) = $180,000. The project still has a positive NPV, but its margin is much smaller.',
   ref:'Performance domain: Finance · Principle: Focus on value'},
  {id:'S3-G03',caseId:'G',domain:'Process',task:1,approach:'Hybrid',type:'single',
   stem:'The ERP integrator follows a phased predictive method, while the app team works in sprints. The app needs grain-contract data from the ERP. How should the project manager plan delivery?',
   options:['Make the app team wait until the ERP is finished','Create an integrated plan with interface milestones, an agreed data contract between the teams and joint integration testing points','Ask the integrator to work in sprints','Plan the two parts separately'],answer:[1],
   explanation:'Hybrid plans integrate different approaches through shared milestones, interface agreements and integration points.',
   ref:'Principle: Adopt a holistic view · Focus area: Planning'},
  {id:'S3-G04',caseId:'G',domain:'People',task:1,approach:'Hybrid',type:'single',
   stem:'Elevator staff and members see the project as “just an IT system.” What should the project manager do to build a common vision?',
   options:['Send a technical overview to all members','Work with the board and member representatives to describe the vision in terms of member and staff outcomes—faster payments, less spoilage and simpler work—and share it through stories from early users','Let the integrator explain the ERP','Wait until go-live to explain the benefits'],answer:[1],
   explanation:'A vision expressed in terms of outcomes that people care about builds understanding and support.',
   ref:'Principle: Focus on value · Performance domain: Stakeholders'},
  {id:'S3-G05',caseId:'G',domain:'Business Environment',task:7,approach:'Hybrid',type:'single',
   stem:'Elevator staff worry that the new sensors and tablets will be used to monitor their performance. Some are refusing to use them. What should the project manager do?',
   options:['Make sensor use mandatory','Meet with staff and their supervisors to explain the purpose and data use, involve staff in designing the workflows, and address any monitoring concerns in policy','Remove the sensors','Ask HR to discipline staff who refuse'],answer:[1],
   explanation:'Resistance often comes from fear. Transparency about purpose, involvement in design and clear policies build acceptance.',
   ref:'Performance domain: Stakeholders · Principle: Build an empowered culture'},
  {id:'S3-G06',caseId:'G',domain:'Business Environment',task:2,approach:'Hybrid',type:'single',
   stem:'The app will collect bin-sensor data from members’ farms. Who owns the data and how it can be used has not been defined. What should the project manager do?',
   options:['Assume the co-op owns all data','Work with legal and privacy advisors and member representatives to define data ownership, consent and use in member agreements before collecting data','Collect the data now and decide later','Let the IoT vendor decide'],answer:[1],
   explanation:'Data ownership, consent and use are legal and ethical requirements that must be agreed before data collection begins.',
   ref:'Performance domain: Governance · Principle: Integrate sustainability'},
  {id:'S3-G07',caseId:'G',domain:'Process',task:5,approach:'Hybrid',type:'single',
   stem:'No supplier has deployed bin sensors at this scale in prairie winters. How should the co-op procure the sensors?',
   options:['Sign a five-year contract for all sensors now','Start with a fixed-price pilot at a few sites, with options to scale up if agreed performance criteria are met','Buy the cheapest sensors available','Build the sensors in-house'],answer:[1],
   explanation:'A pilot with clear performance criteria and expansion options reduces risk when technology is unproven.',
   ref:'Performance domains: Resources (procurement), Risk'},
  {id:'S3-G08',caseId:'G',domain:'People',task:8,approach:'Hybrid',type:'multi',
   stem:'Many members have limited internet access. Which TWO communication approaches are most appropriate?',
   options:['Information sessions at elevators and member meetings','Communication only through the new app','Printed newsletters and local radio, alongside digital channels','Email only','Social media only'],answer:[0,2],
   explanation:'Communication channels must suit the audience. In-person and traditional channels reach members with limited connectivity.',
   ref:'Performance domain: Stakeholders · Focus area: Planning'},
  {id:'S3-G09',caseId:'G',domain:'Process',task:2,approach:'Hybrid',type:'single',
   stem:'The member council asks the app team to add a weather-forecast feature that was not in the original plan. How should this be handled?',
   options:['Add it to the current sprint','The product owner evaluates the request with the council against the product goal and value, and prioritizes it in the backlog if it fits','Submit it to the ERP integrator','Reject it because it was not in the original plan'],answer:[1],
   explanation:'For adaptive scope, the product owner evaluates and prioritizes new requests against the product goal.',
   ref:'Performance domain: Scope · Principle: Focus on value'},
  {id:'S3-G10',caseId:'G',domain:'Business Environment',task:8,approach:'Hybrid',type:'single',
   stem:'A severe drought is forecast to cut grain volumes, and the co-op’s revenue, by 30% next year. What should the project manager do?',
   options:['Continue as planned','Work with finance to update the business case and cash-flow forecast, and present options to the board—such as rephasing or reducing scope—while protecting the highest-value features','Cancel the project immediately','Speed up spending'],answer:[1],
   explanation:'External shocks affect the business case. Governance needs updated analysis and options to make informed decisions.',
   ref:'Principle: Focus on value · Performance domains: Finance, Governance'},

  // ---------- Case H ----------
  {id:'S3-H01',caseId:'H',domain:'Process',task:9,approach:'Agile',type:'single',graphic:'burndown-2',
   stem:'What does the sprint burndown indicate?',
   options:['The team is ahead of schedule','Work was added to the sprint after it started (remaining work rose from 60 to 65 points in the first days), and the team is now catching up','The team stopped working on days 2 and 3','The ideal line is wrong'],answer:[1],
   explanation:'An upward movement in a burndown means work was added. Since day 3, the team has been burning down quickly, but scope changes during a sprint should be discussed with the product owner.',
   ref:'Performance domains: Scope, Schedule · Focus area: Monitoring and Controlling'},
  {id:'S3-H02',caseId:'H',domain:'People',task:6,approach:'Agile',type:'single',
   stem:'A senior ministry official emails developers directly to add “urgent” items to the current sprint. What should the project manager do?',
   options:['Tell developers to add the items','Meet with the official, explain how requests flow through the product owner and backlog, and invite them to sprint reviews where they can influence priorities','Ignore the emails','Escalate to the deputy minister'],answer:[1],
   explanation:'Coaching stakeholders on the process while giving them a clear way to influence priorities manages expectations and protects the sprint.',
   ref:'Performance domain: Stakeholders · Principle: Build an empowered culture'},
  {id:'S3-H03',caseId:'H',domain:'Process',task:7,approach:'Agile',type:'single',
   stem:'At the sprint review, a stakeholder finds that the payment page does not meet government security standards, although the story was marked “done.” What should the team do?',
   options:['Ship the page and fix it later','Treat the story as not done, add the security standards to the definition of done and fix the work before release','Blame the tester','Remove the payment page'],answer:[1],
   explanation:'Work that does not meet the definition of done is not done. Strengthening the definition of done prevents recurrence.',
   ref:'Principle: Embed quality · Performance domain: Scope'},
  {id:'S3-H04',caseId:'H',domain:'People',task:3,approach:'Agile',type:'single',
   stem:'The ministry employees on the team ask the project manager to estimate the stories for them because the consultants “know better.” What should the project manager do?',
   options:['Provide the estimates','Facilitate team estimation—for example planning poker—so that all members contribute and learn, building shared ownership','Let the consultants estimate alone','Skip estimation'],answer:[1],
   explanation:'Estimates should come from the whole team doing the work. Collaborative estimation builds shared understanding and capability.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'S3-H05',caseId:'H',domain:'People',task:7,approach:'Agile',type:'multi',
   stem:'The consultants will leave at launch. Which TWO actions best ensure that the ministry team can run the service afterwards?',
   options:['Pair ministry employees with consultants on all types of work from now until launch','Ask consultants to write a manual in their last week','Have ministry employees lead some deployments and incident drills before launch, with consultants coaching','Keep consultants on the most complex work so that it is done quickly','Rely on the vendor’s support line'],answer:[0,2],
   explanation:'Knowledge transfer works best through shared work and guided practice well before the handover.',
   ref:'Performance domain: Resources · Focus area: Executing'},
  {id:'S3-H06',caseId:'H',domain:'Process',task:8,approach:'Agile',type:'single',
   stem:'The launch date is fixed by regulation. The backlog contains more work than the team can finish by then. What is the best approach?',
   options:['Ask the team to work overtime for every sprint','Work with the product owner to define the minimum set of features needed to legally sell licences at launch, and plan releases so that these are delivered first','Ask the ministry to change the regulation','Add consultants in the last sprint'],answer:[1],
   explanation:'With a fixed date, scope is the variable. Prioritizing the minimum viable release reduces the risk of missing the date.',
   ref:'Principle: Focus on value · Performance domain: Schedule'},
  {id:'S3-H07',caseId:'H',domain:'Business Environment',task:4,approach:'Agile',type:'single',
   stem:'Getting a new cloud test environment through government procurement takes three months, blocking the team. What should the project manager do?',
   options:['Ask the team to test in production','Work with procurement and IT to find a faster compliant route—such as an existing approved vendor arrangement—and escalate the impact if needed','Wait three months','Let consultants use their own company’s environment'],answer:[1],
   explanation:'Removing organizational impediments means working with the owners of the process to find compliant solutions quickly.',
   ref:'Performance domain: Governance · Focus area: Executing'},
  {id:'S3-H08',caseId:'H',domain:'People',task:5,approach:'Agile',type:'single',
   stem:'The ministry measures success by launch on time. The product owner believes success means that most anglers and hunters buy licences online. What should the project manager do?',
   options:['Use the ministry’s measure only','Facilitate agreement on success measures that include both the launch date and outcome measures such as online adoption and customer satisfaction','Use the product owner’s measure only','Avoid defining success'],answer:[1],
   explanation:'Aligning on outcome-based success criteria ensures that everyone works toward the same definition of value.',
   ref:'Principle: Focus on value · Performance domain: Stakeholders'},
  {id:'S3-H09',caseId:'H',domain:'Business Environment',task:3,approach:'Agile',type:'single',
   stem:'Mid-project, the legislature amends the eligibility rules for youth licences. What should happen?',
   options:['Ignore the change until after launch','The product owner assesses the impact with policy experts, updates the backlog and priorities, and the team adapts in upcoming sprints; any contract impact is handled through the contract’s change process','Stop the project','Ask developers to change the code immediately in the current sprint'],answer:[1],
   explanation:'Adaptive projects absorb change through the backlog, while contractual impacts still follow the agreed change mechanism.',
   ref:'Performance domain: Governance · Principle: Focus on value'},
  {id:'S3-H10',caseId:'H',domain:'Process',task:10,approach:'Agile',type:'single',
   stem:'The service has launched successfully. What should happen before the consultants’ engagement is formally closed?',
   options:['Nothing; launch is the end','Confirm acceptance of the contract deliverables, complete the handover to the ministry team, hold a final retrospective and close the contract','Extend the contract indefinitely','Archive the backlog and stop development'],answer:[1],
   explanation:'Closure includes acceptance, handover, lessons learned and contract closeout, even when the product continues to evolve.',
   ref:'Focus area: Closing · Performance domain: Governance'},

  // ---------- Case I ----------
  {id:'S3-I01',caseId:'I',domain:'Business Environment',task:5,approach:'Predictive',type:'hotspot',graphic:'risk-2',
   stem:'Click the risk with the highest probability-and-impact score.',
   options:['R1','R2','R3','R4','R5','R6'],answer:[1],
   explanation:'R2 has probability 5 and impact 4, giving a score of 20, the highest on the matrix. R3 scores 15, R6 scores 9, R4 scores 8, R1 scores 6 and R5 scores 4.',
   ref:'Performance domain: Risk · Focus area: Planning'},
  {id:'S3-I02',caseId:'I',domain:'Process',task:4,approach:'Predictive',type:'dropdown',graphic:'resource',
   stem:'Using the resource histogram, in how many weeks is the demand for electricians greater than the 6 available?',
   options:['2 weeks','3 weeks','4 weeks','5 weeks'],answer:[1],
   explanation:'Demand exceeds 6 in week 4 (8), week 5 (9) and week 6 (7)—3 weeks. Week 3 needs exactly 6, which is within capacity.',
   ref:'Performance domain: Resources · Focus area: Planning'},
  {id:'S3-I03',caseId:'I',domain:'Process',task:8,approach:'Predictive',type:'single',graphic:'resource',
   stem:'The electrical activities in weeks 4 to 6 have enough float to be moved without delaying the project. Which technique should be used to resolve the over-allocation?',
   options:['Crashing','Resource smoothing, which adjusts activities within their float so that the end date does not change','Fast tracking','Resource leveling that extends the critical path'],answer:[1],
   explanation:'Resource smoothing keeps the end date fixed by using float. Leveling may be needed if the float is not enough, but it can extend the schedule.',
   ref:'Performance domains: Resources, Schedule · Focus area: Planning'},
  {id:'S3-I04',caseId:'I',domain:'People',task:4,approach:'Predictive',type:'single',
   stem:'Businesses near the bridge fear that lane closures will drive customers away. What is the best way to engage them?',
   options:['Inform them only when closures start','Set up a business liaison, share the closure schedule early, consult them on timing (for example, avoiding peak shopping periods) and provide signage and detour information','Refer complaints to council','Offer compensation without discussion'],answer:[1],
   explanation:'Early, two-way engagement with affected stakeholders reduces impact and opposition.',
   ref:'Performance domain: Stakeholders · Principle: Integrate sustainability'},
  {id:'S3-I05',caseId:'I',domain:'People',task:2,approach:'Predictive',type:'single',
   stem:'The consultant’s inspector rejects the contractor’s steel repairs, and the contractor says the inspection criteria are stricter than the specifications. Tension is high. What should the project manager do?',
   options:['Side with the inspector','Bring the inspector and contractor together to review the specifications and inspection criteria, clarify the requirement and agree on the next steps','Side with the contractor to avoid delay','Escalate to council'],answer:[1],
   explanation:'Objective documents—the specifications—are the basis for resolving the disagreement collaboratively.',
   ref:'Performance domains: Resources, Stakeholders · Focus area: Executing'},
  {id:'S3-I06',caseId:'I',domain:'Business Environment',task:1,approach:'Predictive',type:'single',
   stem:'A change to the steel repair method will cost $310,000. The city manager suggests approving it administratively to avoid waiting for council. What should the project manager do?',
   options:['Approve it administratively','Prepare the impact analysis and submit it for council approval, as required for changes over $250,000, and propose ways to minimize the delay','Split the change into two smaller changes','Ask the contractor to proceed at risk'],answer:[1],
   explanation:'Governance thresholds define who decides. Bypassing them—even with good intentions—undermines accountability.',
   ref:'Performance domain: Governance · Principle: Be an accountable leader'},
  {id:'S3-I07',caseId:'I',domain:'Process',task:7,approach:'Predictive',type:'single',
   stem:'Reinforcing steel for the new deck must be inspected before concrete is poured, because defects cannot be seen afterwards. How should this be managed?',
   options:['Inspect after the concrete cures','Define a mandatory inspection hold point in the quality plan, so that the pour cannot proceed until the inspector signs off','Rely on the contractor’s self-inspection only','Inspect a random sample of decks next year'],answer:[1],
   explanation:'Hold points ensure that critical work is verified at the only time it can be checked, preventing costly hidden defects.',
   ref:'Principle: Embed quality · Focus area: Executing'},
  {id:'S3-I08',caseId:'I',domain:'Process',task:6,approach:'Predictive',type:'single',
   stem:'During paint removal, the contractor finds lead-based paint in an area that was not tested and not identified as a risk. Safe removal will cost $140,000. Where should the funding come from?',
   options:['Contingency reserve','Management reserve, with approval from the appropriate authority, because this is an unidentified risk','The contractor’s profit','Savings from other activities without approval'],answer:[1],
   explanation:'Management reserves cover unknown-unknowns and require management approval. Contingency reserves are for identified risks.',
   ref:'Performance domains: Finance, Risk · Focus area: Executing'},
  {id:'S3-I09',caseId:'I',domain:'People',task:6,approach:'Predictive',type:'single',
   stem:'Council members demand a guarantee that the bridge will reopen fully by Canada Day. The schedule shows a 60% chance of meeting that date. What should the project manager do?',
   options:['Guarantee the date','Present the probability, the main risks and options that could raise confidence—such as added shifts—so that council can decide with realistic expectations','Refuse to discuss the date','Report an earlier date to reduce pressure'],answer:[1],
   explanation:'Honest, risk-informed forecasts and options help decision-makers set realistic expectations.',
   ref:'Principle: Be an accountable leader · Performance domain: Stakeholders'},
  {id:'S3-I10',caseId:'I',domain:'Business Environment',task:6,approach:'Predictive',type:'single',
   stem:'The first deck pour had surface cracking. Several more pours are planned. What is the best action?',
   options:['Continue pouring and repair cracks later','Conduct a root-cause analysis with the contractor and inspector, adjust the method (for example, curing or timing), and verify the improvement on the next pour','Change contractors','Stop all pours for the rest of the year'],answer:[1],
   explanation:'Learning from early results and adjusting the process before repeating it is continuous improvement in action.',
   ref:'Principle: Embed quality · Focus area: Monitoring and Controlling'}
];
