import {ExamQuestion} from '../../exam-types';

const D='People' as const;

export const PEOPLE_QUESTIONS:ExamQuestion[]=[
  // Task 1 — Develop a common vision (7)
  {id:'S3-P01',domain:D,task:1,approach:'Agile',type:'single',
   stem:'A product team wants one measure that best captures the value its product delivers to customers, to guide all teams. What is this often called?',
   options:['A vanity metric','A “north star” metric that reflects the core customer value and long-term success','The sprint velocity','The defect count'],answer:[1],
   explanation:'A north star metric aligns teams around the outcome that matters most, helping them make consistent decisions.',
   ref:'Principle: Focus on value · Performance domain: Stakeholders'},
  {id:'S3-P02',domain:D,task:1,approach:'Hybrid',type:'single',
   stem:'A digital transformation program has five workstreams, each with its own goals. Workstream leads keep competing for resources. What should the program’s project manager do?',
   options:['Let the workstream with the biggest budget decide','Facilitate agreement on a program vision and shared outcomes, and show how each workstream contributes to them, so that resource decisions follow shared priorities','Split the program into five separate projects','Ask each lead to argue their case at every meeting'],answer:[1],
   explanation:'A shared vision with clear contributions turns competing workstreams into a coordinated program.',
   ref:'Principle: Adopt a holistic view · Performance domain: Governance'},
  {id:'S3-P03',domain:D,task:1,approach:'Predictive',type:'single',
   stem:'An external contractor team is focused only on contractual deliverables and is unaware of how the facility will serve the community. What should the project manager do?',
   options:['Leave the contractor to its contract','Share the project’s purpose and community outcomes with the contractor team—for example at a site kickoff—and link their work to those outcomes','Add penalties to the contract','Limit contact with the contractor'],answer:[1],
   explanation:'Connecting all parties to the project’s purpose encourages them to make decisions that serve the overall outcome.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'S3-P04',domain:D,task:1,approach:'Agile',type:'single',
   stem:'After user research, the product pivots from serving small businesses to serving non-profit organizations. What should the product owner do first?',
   options:['Continue with the existing backlog','Update the product vision and goal, communicate the reasons to the team and stakeholders, and reorder the backlog to reflect the new direction','Start a new team','Wait for the sponsor to update the charter'],answer:[1],
   explanation:'When strategy changes, the vision must be updated and communicated first, so that everyone can realign their work.',
   ref:'Principle: Focus on value · Performance domain: Scope'},
  {id:'S3-P05',domain:D,task:1,approach:'Hybrid',type:'single',
   stem:'A public service is being redesigned. Early vision workshops included only head-office staff. What is the risk, and how should it be addressed?',
   options:['There is no risk','The vision may not reflect the needs of diverse users and front-line staff; include representative users, front-line employees and accessibility advocates in refining it','The vision will be too detailed','The workshops took too long'],answer:[1],
   explanation:'An inclusive vision process captures diverse needs and builds broader ownership of the outcome.',
   ref:'Principle: Integrate sustainability · Performance domain: Stakeholders'},
  {id:'S3-P06',domain:D,task:1,approach:'Agile',type:'multi',
   stem:'Which TWO artifacts best help an agile team connect its daily work to the long-term vision?',
   options:['A product roadmap organized by themes or outcomes','The team’s timesheets','Sprint goals that describe the outcome each sprint contributes','A list of all defects','The office seating plan'],answer:[0,2],
   explanation:'Outcome-based roadmaps and sprint goals form the link between long-term vision and short-term work.',
   ref:'Performance domains: Scope, Schedule · Focus area: Planning'},
  {id:'S3-P07',domain:D,task:1,approach:'Predictive',type:'single',
   stem:'Halfway through a predictive project, a new sponsor is appointed who has different priorities. What should the project manager do first?',
   options:['Continue with the existing plan without discussion','Meet with the new sponsor to review the business case, objectives and progress, understand their priorities, and agree on any changes through governance','Ask the previous sponsor to stay involved','Change the scope to match the new sponsor’s wishes immediately'],answer:[1],
   explanation:'A change of sponsor requires re-establishing a shared vision and confirming whether objectives remain valid, using governance for any changes.',
   ref:'Performance domains: Governance, Stakeholders · Focus area: Executing'},

  // Task 2 — Manage conflicts (6)
  {id:'S3-P08',domain:D,task:2,approach:'Agile',type:'single',
   stem:'The product owner and the Scrum Master argue publicly about who decides the sprint goal. What should the project manager do?',
   options:['Decide personally','Meet with both privately, clarify roles—the Scrum team crafts the sprint goal during sprint planning, with the product owner proposing how the product can increase value—and agree on how they will collaborate','Let the team vote','Escalate to HR'],answer:[1],
   explanation:'Role confusion is a common source of conflict. Clarifying responsibilities privately resolves the root cause.',
   ref:'Performance domain: Resources · Principle: Build an empowered culture'},
  {id:'S3-P09',domain:D,task:2,approach:'Predictive',type:'single',
   stem:'Before negotiating a contract change with a vendor, the project manager identifies the best option available if the negotiation fails. What is this called?',
   options:['ZOPA','BATNA (best alternative to a negotiated agreement)','RACI','WBS'],answer:[1],
   explanation:'Knowing the BATNA strengthens a negotiator’s position and shows when to walk away.',
   ref:'Performance domain: Resources (procurement) · Focus area: Executing'},
  {id:'S3-P10',domain:D,task:2,approach:'Hybrid',type:'single',
   stem:'Two co-sponsors from different departments give the team conflicting instructions. What should the project manager do?',
   options:['Follow the more senior sponsor','Bring both sponsors together to agree on priorities and decision rights, and document the agreement in the governance plan','Follow both sets of instructions','Ask the team to choose'],answer:[1],
   explanation:'Conflicting direction from sponsors must be resolved at its source and clarified in governance.',
   ref:'Performance domain: Governance · Principle: Be an accountable leader'},
  {id:'S3-P11',domain:D,task:2,approach:'Agile',type:'single',
   stem:'Team members repeatedly argue about who should do certain tasks, because roles on a new hybrid team are unclear. What would help most?',
   options:['A stricter manager','Clarifying roles and responsibilities together—for example with a responsibility matrix or team working agreement','Separating the team','Replacing the most vocal member'],answer:[1],
   explanation:'Clear, agreed roles remove a structural cause of conflict.',
   ref:'Performance domain: Resources · Focus area: Planning'},
  {id:'S3-P12',domain:D,task:2,approach:'Hybrid',type:'single',
   stem:'A vendor and the internal IT team blame each other for integration delays. Each has evidence supporting its view. What is the best approach?',
   options:['Side with the internal team','Hold a joint, fact-based session to map the integration issues, agree on root causes and assign shared actions with dates','Penalize the vendor','Let them resolve it themselves'],answer:[1],
   explanation:'A joint, data-driven approach moves the parties from blame to problem solving.',
   ref:'Performance domains: Resources, Stakeholders · Focus area: Executing'},
  {id:'S3-P13',domain:D,task:2,approach:'Agile',type:'multi',
   stem:'Which TWO behaviours by the project manager help keep team conflict constructive?',
   options:['Encouraging people to debate ideas, not people','Avoiding all disagreement','Listening to all perspectives before helping the team decide','Making all decisions quickly without discussion','Discussing conflicts publicly to make examples of people'],answer:[0,2],
   explanation:'Healthy conflict focuses on ideas and is facilitated with active listening.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},

  // Task 3 — Lead the project team (7)
  {id:'S3-P14',domain:D,task:3,approach:'Predictive',type:'single',
   stem:'A manager believes that team members dislike work and must be closely supervised. Which theory describes this assumption?',
   options:['McGregor’s Theory Y','McGregor’s Theory X','Herzberg’s motivators','Maslow’s self-actualization'],answer:[1],
   explanation:'Theory X assumes that people need close supervision. Theory Y assumes that people are self-motivated—the assumption behind empowered agile teams.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'S3-P15',domain:D,task:3,approach:'Hybrid',type:'single',
   stem:'Which component of emotional intelligence involves recognizing and understanding the emotions of others?',
   options:['Self-regulation','Empathy (social awareness)','Self-awareness','Motivation'],answer:[1],
   explanation:'Empathy, or social awareness, lets leaders understand others’ feelings and respond appropriately.',
   ref:'Principle: Be an accountable leader · Performance domain: Resources'},
  {id:'S3-P16',domain:D,task:3,approach:'Agile',type:'multi',
   stem:'Which TWO behaviours are characteristic of servant leadership?',
   options:['Removing obstacles that prevent the team from delivering','Assigning detailed tasks to each person daily','Supporting team members’ growth and wellbeing','Making all technical decisions personally','Taking credit for the team’s success'],answer:[0,2],
   explanation:'Servant leaders serve the team: they remove impediments, coach and support growth.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'S3-P17',domain:D,task:3,approach:'Hybrid',type:'single',
   stem:'In meetings, a few outgoing members dominate, and the ideas of quieter members and of members working remotely are overlooked. What should the project manager do?',
   options:['Ask quieter members to speak up more','Use inclusive facilitation—such as sharing agendas in advance, round-robin input, written contributions and a remote-first meeting format—so that all voices are heard','Hold separate meetings for remote members','Continue as is'],answer:[1],
   explanation:'Inclusive facilitation ensures that diverse perspectives are heard, leading to better decisions.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'S3-P18',domain:D,task:3,approach:'Predictive',type:'single',
   stem:'A junior project manager on the team wants to develop leadership skills. What should the senior project manager do?',
   options:['Assign only administrative tasks','Mentor them, gradually delegate responsibilities with support—such as leading a workstream—and give regular feedback','Tell them to take a course','Let them learn by observing'],answer:[1],
   explanation:'Mentoring and progressive delegation develop people’s capability while managing risk.',
   ref:'Performance domain: Resources · Principle: Be an accountable leader'},
  {id:'S3-P19',domain:D,task:3,approach:'Agile',type:'single',
   stem:'An agile team wants to assess how well it is working together. Which approach is most appropriate?',
   options:['Individual performance rankings','A team self-assessment—for example of collaboration, ownership and delivery practices—discussed in a retrospective to choose improvements','A manager’s evaluation of each member','Comparing velocity with other teams'],answer:[1],
   explanation:'Team-level self-assessment encourages ownership of improvement without undermining collaboration.',
   ref:'Principle: Build an empowered culture · Focus area: Monitoring and Controlling'},
  {id:'S3-P20',domain:D,task:3,approach:'Hybrid',type:'single',
   stem:'According to Maslow’s hierarchy, a team member worried about job security after a reorganization is focused on which level of needs?',
   options:['Self-actualization','Esteem','Safety','Belonging'],answer:[2],
   explanation:'Job security is a safety need. Leaders should address such concerns honestly, because higher-level motivators have little effect until basic needs feel secure.',
   ref:'Performance domain: Resources · Principle: Be an accountable leader'},

  // Task 4 — Engage stakeholders (7)
  {id:'S3-P21',domain:D,task:4,approach:'Predictive',type:'hotspot',graphic:'grid-3',
   stem:'The grid shows four stakeholder groups for a transit construction project. Click the stakeholder group that should be managed closely.',
   options:['Provincial ministry','Union local','Daily commuters','Equipment supplier'],answer:[1],
   explanation:'The union local has high power and high interest, so it should be managed closely. The ministry (high power, low interest) is kept satisfied, commuters (low power, high interest) are kept informed, and the supplier (low/low) is monitored.',
   ref:'Performance domain: Stakeholders · Focus area: Planning'},
  {id:'S3-P22',domain:D,task:4,approach:'Hybrid',type:'matching',
   stem:'Match each direction of stakeholder influence to its example.',
   pairs:[{left:'Upward',right:0},{left:'Downward',right:1},{left:'Outward',right:2},{left:'Sideward',right:3}],
   choices:['Senior management and the sponsor','The project team and specialists','Customers, regulators and suppliers outside the project','Peer managers competing for the same resources'],
   explanation:'Mapping the direction of influence helps the project manager plan how to engage each group.',
   ref:'Performance domain: Stakeholders · Focus area: Initiating'},
  {id:'S3-P23',domain:D,task:4,approach:'Agile',type:'single',
   stem:'A software company wants regular strategic input from key customers on its product direction. What engagement mechanism is most suitable?',
   options:['An annual email survey','A customer advisory board that meets regularly to review the roadmap and give feedback','The support ticket system','Social media comments'],answer:[1],
   explanation:'Advisory boards provide structured, ongoing engagement with influential customers on strategic direction.',
   ref:'Performance domain: Stakeholders · Principle: Focus on value'},
  {id:'S3-P24',domain:D,task:4,approach:'Predictive',type:'single',
   stem:'A highway project will affect residents who are not directly consulted but whose views can influence elected officials. How should they be treated?',
   options:['As irrelevant because they are not customers','As stakeholders to identify, analyze and engage—for example through public information sessions—because they can affect the project','As the sponsor’s responsibility only','As risks to be avoided'],answer:[1],
   explanation:'Anyone who can affect, or is affected by, the project is a stakeholder and should be considered in engagement planning.',
   ref:'Performance domain: Stakeholders · Focus area: Initiating'},
  {id:'S3-P25',domain:D,task:4,approach:'Hybrid',type:'single',
   stem:'A video criticizing the project goes viral on social media and attracts media interest. What should the project manager do?',
   options:['Respond personally to every comment','Work with the organization’s communications team to assess the concerns, respond with accurate information through official channels, and engage the affected stakeholders directly','Ignore it','Delete the project’s social media accounts'],answer:[1],
   explanation:'Public concerns need a coordinated, factual response through the right channels, plus direct engagement with those affected.',
   ref:'Performance domain: Stakeholders · Principle: Be an accountable leader'},
  {id:'S3-P26',domain:D,task:4,approach:'Agile',type:'single',
   stem:'Executives say they have no time for sprint reviews but complain about surprises. What should the project manager do?',
   options:['Stop inviting executives','Agree on a short, regular executive review—for example a 20-minute monthly demo focused on outcomes and decisions—tailored to their availability','Send the full sprint backlog weekly','Escalate to the CEO'],answer:[1],
   explanation:'Tailoring engagement to stakeholders’ time and needs maintains alignment without overloading them.',
   ref:'Performance domain: Stakeholders · Focus area: Executing'},
  {id:'S3-P27',domain:D,task:4,approach:'Hybrid',type:'multi',
   stem:'Which TWO actions help maintain stakeholder engagement throughout a long project?',
   options:['Regularly reviewing and updating the stakeholder register and engagement plan','Engaging stakeholders only at the start','Monitoring engagement levels and adjusting strategies when they change','Communicating only when problems occur','Limiting stakeholder contact to the sponsor'],answer:[0,2],
   explanation:'Stakeholder engagement is continuous: analysis and strategies must be refreshed as the project and stakeholders evolve.',
   ref:'Performance domain: Stakeholders · Focus area: Monitoring and Controlling'},

  // Task 5 — Align stakeholder expectations (6)
  {id:'S3-P28',domain:D,task:5,approach:'Predictive',type:'single',
   stem:'Operations will take over a new system after go-live but has not agreed on the support levels the project must deliver. What should be agreed before handover?',
   options:['Nothing; operations will adapt','Service-level and operational acceptance criteria—such as availability, response times and documentation—agreed with operations','The project team’s vacation schedule','The vendor’s marketing plan'],answer:[1],
   explanation:'Agreeing on operational acceptance criteria aligns expectations and enables a smooth transition.',
   ref:'Focus area: Closing · Performance domain: Stakeholders'},
  {id:'S3-P29',domain:D,task:5,approach:'Hybrid',type:'single',
   stem:'Business users expect migrated data to be 100% clean, but the legacy data is known to have quality problems. What should the project manager do?',
   options:['Promise 100% clean data','Agree with business owners on data-quality targets, cleansing responsibilities and how exceptions will be handled before migration starts','Migrate the data as is','Delay the project until all data is perfect'],answer:[1],
   explanation:'Clear, agreed data-quality expectations prevent disputes and define who does the cleansing.',
   ref:'Principle: Embed quality · Performance domain: Stakeholders'},
  {id:'S3-P30',domain:D,task:5,approach:'Agile',type:'single',
   stem:'Stakeholders assume the pilot will cover all regions, but the team planned a pilot with one region. What should the project manager do?',
   options:['Expand the pilot to all regions','Clarify the pilot’s purpose, scope and success criteria with stakeholders, and explain how results will inform the wider rollout','Cancel the pilot','Proceed without discussing it'],answer:[1],
   explanation:'Explicit agreement on the pilot’s scope and purpose prevents misaligned expectations.',
   ref:'Performance domain: Scope · Principle: Focus on value'},
  {id:'S3-P31',domain:D,task:5,approach:'Predictive',type:'single',
   stem:'A sponsor says they are “comfortable with risk,” but becomes alarmed at every amber status. What should the project manager do?',
   options:['Report everything as green','Work with the sponsor to define explicit risk thresholds and what each status colour means, so that reporting matches their tolerance','Stop reporting status','Escalate every risk'],answer:[1],
   explanation:'Translating risk appetite into explicit thresholds aligns expectations about what deserves attention.',
   ref:'Performance domain: Risk · Performance domain: Governance'},
  {id:'S3-P32',domain:D,task:5,approach:'Hybrid',type:'single',
   stem:'A client and the delivery team disagree about whether the project is “on track,” because they use different measures. What should be done?',
   options:['Use the team’s measures','Agree on a shared set of progress and success measures and how they will be reported','Use the client’s measures only','Stop measuring progress'],answer:[1],
   explanation:'Shared measures create a common view of progress and remove a source of misaligned expectations.',
   ref:'Performance domain: Stakeholders · Focus area: Planning'},
  {id:'S3-P33',domain:D,task:5,approach:'Agile',type:'multi',
   stem:'Which TWO practices help keep expectations aligned during an agile project?',
   options:['Regular sprint reviews where stakeholders see working increments and give feedback','Sharing forecasts only at the end of the release','Keeping the product backlog and roadmap visible to stakeholders','Changing priorities without telling stakeholders','Relying on the original contract for all expectations'],answer:[0,2],
   explanation:'Frequent inspection and visible plans keep stakeholders’ expectations in step with reality.',
   ref:'Performance domain: Stakeholders · Focus area: Executing'},

  // Task 6 — Manage stakeholder expectations (5)
  {id:'S3-P34',domain:D,task:6,approach:'Hybrid',type:'single',
   stem:'Budget cuts require reducing scope. A key stakeholder group will lose a feature they were promised. What is the best approach?',
   options:['Announce the cut by email','Meet with the group to explain the reasons, show how priorities were decided, and explore alternatives or a later delivery','Keep the feature and cut testing instead','Avoid telling them until the release'],answer:[1],
   explanation:'Delivering difficult news personally, with transparency and options, maintains trust.',
   ref:'Performance domain: Stakeholders · Principle: Be an accountable leader'},
  {id:'S3-P35',domain:D,task:6,approach:'Predictive',type:'single',
   stem:'A vocal stakeholder criticizes the project in every meeting, which affects team morale. What should the project manager do first?',
   options:['Exclude the stakeholder from meetings','Meet privately with the stakeholder to understand the concerns behind the criticism and agree on how to address them','Ask the sponsor to silence them','Ignore the comments'],answer:[1],
   explanation:'Persistent criticism usually reflects unmet concerns. Understanding them is the first step to managing the stakeholder.',
   ref:'Performance domain: Stakeholders · Focus area: Executing'},
  {id:'S3-P36',domain:D,task:6,approach:'Agile',type:'single',
   stem:'Stakeholders are excited that an AI assistant will “write all the requirements.” What expectation should the project manager set?',
   options:['That AI will replace business analysts','That AI can speed up drafting, but requirements still need to be validated with stakeholders and reviewed by the team for accuracy and completeness','That AI should not be used','That AI requirements need no review'],answer:[1],
   explanation:'Setting realistic expectations about AI prevents over-reliance and keeps accountability with people.',
   ref:'AI in project management · Principle: Be an accountable leader'},
  {id:'S3-P37',domain:D,task:6,approach:'Hybrid',type:'single',
   stem:'A customer is unhappy with a vendor’s responsiveness and complains to the project manager. The vendor is managed under the project’s contract. What should the project manager do?',
   options:['Tell the customer to contact the vendor','Acknowledge the concern, review the vendor’s performance against the contract’s service terms, address it with the vendor and update the customer on actions taken','Terminate the vendor immediately','Ignore the complaint'],answer:[1],
   explanation:'The project manager owns the contract relationship and should close the loop with both the vendor and the customer.',
   ref:'Performance domains: Stakeholders, Resources (procurement)'},
  {id:'S3-P38',domain:D,task:6,approach:'Predictive',type:'multi',
   stem:'A stakeholder’s expectations have grown well beyond the approved scope. Which TWO actions should the project manager take?',
   options:['Remind the stakeholder of the approved scope and acceptance criteria','Quietly deliver the extra work','Explain that new needs can be submitted as change requests and assessed','Refuse to meet the stakeholder','Promise the extras in the next phase without approval'],answer:[0,2],
   explanation:'Anchoring expectations in approved scope while offering a legitimate path for change manages expectations constructively.',
   ref:'Performance domains: Scope, Stakeholders'},

  // Task 7 — Knowledge transfer (6)
  {id:'S3-P39',domain:D,task:7,approach:'Hybrid',type:'single',
   stem:'After a major incident, the team wants to capture what happened while memories are fresh. Which technique is most appropriate?',
   options:['An after-action review shortly after the event, focusing on what was expected, what happened, why and what to do differently','A note in the final report months later','A disciplinary review','An email asking for comments'],answer:[0],
   explanation:'After-action reviews capture timely, specific lessons in a blameless format.',
   ref:'Principle: Embed quality · Focus area: Monitoring and Controlling'},
  {id:'S3-P40',domain:D,task:7,approach:'Predictive',type:'single',
   stem:'Site supervisors work rotating shifts, and information is lost between shifts, causing errors. What should be put in place?',
   options:['Longer shifts','A structured shift handover—such as a standard checklist and a short face-to-face briefing—recorded in a shared log','A weekly summary email','Fewer supervisors'],answer:[1],
   explanation:'Structured handovers transfer critical knowledge reliably at each transition.',
   ref:'Performance domain: Resources · Focus area: Executing'},
  {id:'S3-P41',domain:D,task:7,approach:'Agile',type:'single',
   stem:'Knowledge about the product’s architecture sits with two senior developers. Which practice spreads it most effectively across the team?',
   options:['Asking the seniors to document everything','Regular short knowledge-sharing sessions and rotating developers through architecture work in pairs with the seniors','Restricting architecture changes to the seniors','Hiring an architect'],answer:[1],
   explanation:'Combining sharing sessions with hands-on rotation builds lasting, shared knowledge.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'S3-P42',domain:D,task:7,approach:'Hybrid',type:'single',
   stem:'An organization’s lessons-learned repository is hard to search, so people do not use it. What would most improve it?',
   options:['Adding more documents','Organizing lessons with consistent categories and tags (such as project type and topic), and making search and summaries easy','Restricting access','Deleting all old lessons'],answer:[1],
   explanation:'Knowledge has value only if people can find it. Consistent organization makes repositories usable.',
   ref:'Principle: Embed quality · Focus area: Closing'},
  {id:'S3-P43',domain:D,task:7,approach:'Agile',type:'multi',
   stem:'Which TWO practices help transfer knowledge from a project team to the users who will operate a new system?',
   options:['Training super-users who can support colleagues','Sending users a link to the code repository','Short recorded demonstrations and job aids for common tasks','Expecting users to learn by trial and error','Training only managers'],answer:[0,2],
   explanation:'Super-users and practical job aids give users accessible, ongoing support.',
   ref:'Focus area: Closing · Performance domain: Stakeholders'},
  {id:'S3-P44',domain:D,task:7,approach:'Predictive',type:'single',
   stem:'To build backup capability for critical roles, a project manager plans for team members to spend time working in each other’s areas. What is this practice called?',
   options:['Job rotation (cross-training)','Gold plating','Resource leveling','Fast tracking'],answer:[0],
   explanation:'Job rotation spreads knowledge and creates backup capability, reducing key-person risk.',
   ref:'Performance domain: Resources · Principle: Build an empowered culture'},

  // Task 8 — Plan and manage communication (6)
  {id:'S3-P45',domain:D,task:8,approach:'Predictive',type:'dropdown',
   stem:'A project has 12 stakeholders who need to communicate with each other. How many communication channels are there?',
   options:['24','66','78','132'],answer:[1],
   explanation:'Channels = n(n – 1) ÷ 2 = 12 × 11 ÷ 2 = 66.',
   ref:'Performance domain: Stakeholders · Focus area: Planning'},
  {id:'S3-P46',domain:D,task:8,approach:'Hybrid',type:'single',
   stem:'A key message to field staff was misunderstood because it was sent as a long, technical email during their busiest week. What communication factors were ignored?',
   options:['None','The audience’s context and the timing, format and medium of the message (communication “noise” and barriers)','The sender’s job title','The email’s font'],answer:[1],
   explanation:'Effective communication considers the receiver’s context, timing, language and medium to reduce noise.',
   ref:'Performance domain: Stakeholders · Focus area: Executing'},
  {id:'S3-P47',domain:D,task:8,approach:'Predictive',type:'single',
   stem:'A serious safety incident occurs on site, and the media and public are asking questions. Who should communicate with them?',
   options:['Any team member who is asked','The designated spokesperson, following the organization’s crisis communication plan','The project manager on social media','No one'],answer:[1],
   explanation:'Crisis communication should be coordinated through designated spokespeople and approved channels to ensure accuracy and consistency.',
   ref:'Performance domain: Stakeholders · Principle: Be an accountable leader'},
  {id:'S3-P48',domain:D,task:8,approach:'Agile',type:'single',
   stem:'When a team member presents a problem, the project manager paraphrases what was said and asks clarifying questions before responding. What is this technique?',
   options:['Active listening','Smoothing','Push communication','Benchmarking'],answer:[0],
   explanation:'Active listening confirms understanding and shows respect, reducing misunderstandings.',
   ref:'Principle: Be an accountable leader · Performance domain: Resources'},
  {id:'S3-P49',domain:D,task:8,approach:'Predictive',type:'single',
   stem:'On a government contract, all instructions to the contractor must be legally enforceable. How should contractual instructions be communicated?',
   options:['Verbally at site meetings','In formal written correspondence, as defined by the contract','Through text messages','Through the project newsletter'],answer:[1],
   explanation:'Contractual communication requires formal written methods so that it is clear, traceable and enforceable.',
   ref:'Performance domains: Governance, Resources (procurement)'},
  {id:'S3-P50',domain:D,task:8,approach:'Hybrid',type:'multi',
   stem:'Which TWO actions help a project manager check that communication is working?',
   options:['Asking stakeholders for feedback on the usefulness of communications','Increasing the number of emails','Monitoring indicators such as attendance, engagement and questions raised, and adjusting the plan','Assuming silence means understanding','Sending the same report to everyone'],answer:[0,2],
   explanation:'Monitoring communications means checking that they reach people and meet their needs, then adapting.',
   ref:'Performance domain: Stakeholders · Focus area: Monitoring and Controlling'}
];
