import {ExamQuestion} from '../../exam-types';

const D='Process' as const;

export const PROCESS_QUESTIONS:ExamQuestion[]=[
  // Task 1 — Integrated plan and plan delivery (7)
  {id:'S3-R01',domain:D,task:1,approach:'Predictive',type:'single',
   stem:'What is the main difference between the project charter and the project management plan?',
   options:['They are the same document','The charter formally authorizes the project and the project manager at a high level; the plan describes in detail how the project will be executed, monitored, controlled and closed','The plan is created before the charter','The charter contains the detailed schedule'],answer:[1],
   explanation:'The charter authorizes the project; the project management plan is the detailed, integrated guide to delivering it.',
   ref:'Performance domain: Governance · Focus areas: Initiating, Planning'},
  {id:'S3-R02',domain:D,task:1,approach:'Hybrid',type:'single',
   stem:'A small, low-risk internal project is required by the PMO to use the full set of templates designed for large programs. What should the project manager do?',
   options:['Use every template in full','Propose a tailored approach to the PMO that keeps the essential controls but scales documentation to the project’s size and risk','Ignore the PMO','Cancel the project'],answer:[1],
   explanation:'Tailoring adapts processes to the project’s context while keeping governance needs satisfied.',
   ref:'Principle: Adopt a holistic view · Performance domain: Governance'},
  {id:'S3-R03',domain:D,task:1,approach:'Hybrid',type:'single',
   stem:'A vendor uses its own proprietary delivery methodology. How should the project manager integrate it into the project plan?',
   options:['Force the vendor to use the organization’s methodology','Map the vendor’s phases and deliverables to the project’s milestones, governance points and reporting needs, and agree on interfaces in the contract and plan','Leave the vendor’s work out of the plan','Let the vendor manage the whole project'],answer:[1],
   explanation:'Integration means aligning different methods through shared milestones, reporting and interfaces.',
   ref:'Principle: Adopt a holistic view · Focus area: Planning'},
  {id:'S3-R04',domain:D,task:1,approach:'Predictive',type:'single',
   stem:'Which document records assumptions and constraints identified throughout the project?',
   options:['Assumption log','Issue log','Change log','Quality checklist'],answer:[0],
   explanation:'The assumption log records assumptions and constraints so that they can be validated and their risks managed.',
   ref:'Focus area: Planning · Performance domain: Risk'},
  {id:'S3-R05',domain:D,task:1,approach:'Agile',type:'single',
   stem:'A team plans to adopt an AI coding assistant during the project. What should the project manager include in planning?',
   options:['Nothing; it is a personal tool','Guidelines on approved tools and data, review requirements for AI-generated code, licensing and security checks, and how productivity effects will be measured','A ban on code reviews to save time','An assumption that velocity will double'],answer:[1],
   explanation:'New tools, especially AI, should be planned with clear guardrails, quality controls and realistic expectations.',
   ref:'AI in project management · Principle: Embed quality'},
  {id:'S3-R06',domain:D,task:1,approach:'Hybrid',type:'single',
   stem:'Which characteristic distinguishes a project from operations?',
   options:['Projects use people; operations do not','Projects are temporary endeavours that create a unique product, service or result; operations are ongoing and repetitive','Operations always cost more','Projects never involve repetitive work'],answer:[1],
   explanation:'Projects are temporary and unique; operations sustain the organization on an ongoing basis.',
   ref:'Performance domain: Governance · Focus area: Initiating'},
  {id:'S3-R07',domain:D,task:1,approach:'Hybrid',type:'multi',
   stem:'When selecting a development approach, which TWO characteristics suggest an adaptive approach?',
   options:['High uncertainty about requirements, with value in early feedback','Fixed, well-understood requirements that are unlikely to change','The ability to deliver the product in small, usable increments','A deliverable that can only be used when 100% complete','Heavy regulation that requires sign-off before any work begins'],answer:[0,2],
   explanation:'Adaptive approaches suit uncertain requirements and products that can be delivered and tested incrementally.',
   ref:'Principle: Adopt a holistic view · Focus area: Planning'},

  // Task 2 — Scope (7)
  {id:'S3-R08',domain:D,task:2,approach:'Predictive',type:'matching',
   stem:'Match each type of requirement to its example.',
   pairs:[{left:'Business requirement',right:0},{left:'Stakeholder requirement',right:1},{left:'Functional requirement',right:2},{left:'Non-functional requirement',right:3}],
   choices:['Reduce customer onboarding time by 30% this year','Call-centre agents need to see a customer’s full history on one screen','The system shall generate a monthly statement for each account','Pages shall load in under two seconds for 95% of requests'],
   explanation:'Business requirements describe organizational needs; stakeholder requirements describe needs of groups; functional requirements describe behaviour; non-functional requirements describe qualities such as performance.',
   ref:'Performance domain: Scope · Focus area: Planning'},
  {id:'S3-R09',domain:D,task:2,approach:'Agile',type:'single',
   stem:'In an agile project, how is completed work validated with stakeholders?',
   options:['At a formal sign-off at the end of the project only','At the sprint review, where stakeholders inspect the increment and the product owner accepts work that meets the definition of done and acceptance criteria','By the developers alone','Through a quality audit'],answer:[1],
   explanation:'Agile teams validate scope frequently through reviews of working increments and product-owner acceptance.',
   ref:'Performance domain: Scope · Focus area: Monitoring and Controlling'},
  {id:'S3-R10',domain:D,task:2,approach:'Agile',type:'single',
   stem:'What is the purpose of product backlog refinement?',
   options:['To plan the team’s vacations','To add detail, estimates and order to backlog items so that they are ready for upcoming sprints','To review completed work','To assign tasks to individuals'],answer:[1],
   explanation:'Refinement is an ongoing activity that keeps the backlog ready, clear and ordered.',
   ref:'Performance domain: Scope · Focus area: Planning'},
  {id:'S3-R11',domain:D,task:2,approach:'Predictive',type:'single',
   stem:'Which diagram shows the system in scope and its interactions with external users and systems?',
   options:['Context diagram','Fishbone diagram','Control chart','Histogram'],answer:[0],
   explanation:'A context diagram visualizes the product scope boundary and its inputs and outputs with external entities.',
   ref:'Performance domain: Scope · Focus area: Planning'},
  {id:'S3-R12',domain:D,task:2,approach:'Predictive',type:'single',
   stem:'Stakeholders assume data migration from the old system is included, but the scope statement is silent on it. What could have prevented this?',
   options:['A longer charter','Explicitly listing exclusions in the scope statement','More team members','A bigger budget'],answer:[1],
   explanation:'Stating exclusions makes the scope boundary clear and prevents false assumptions.',
   ref:'Performance domain: Scope · Focus area: Planning'},
  {id:'S3-R13',domain:D,task:2,approach:'Hybrid',type:'single',
   stem:'Performance, security and accessibility requirements were discovered late on a previous project. How should they be handled this time?',
   options:['Leave them for testing','Identify non-functional requirements early with stakeholders and specialists, and build them into the backlog, the definition of done and acceptance criteria','Assume the vendor will cover them','Handle them after go-live'],answer:[1],
   explanation:'Non-functional requirements shape the solution and are expensive to retrofit, so they need early attention.',
   ref:'Principle: Embed quality · Performance domain: Scope'},
  {id:'S3-R14',domain:D,task:2,approach:'Agile',type:'multi',
   stem:'Which TWO characteristics make a user story well formed (for example, using the INVEST criteria)?',
   options:['Independent and negotiable','Dependent on many other stories','Small and testable','Fixed and non-negotiable','Too large to finish in one sprint'],answer:[0,2],
   explanation:'INVEST: Independent, Negotiable, Valuable, Estimable, Small and Testable.',
   ref:'Performance domain: Scope · Principle: Embed quality'},

  // Task 3 — Value-based delivery (8)
  {id:'S3-R15',domain:D,task:3,approach:'Predictive',type:'dropdown',
   stem:'A project costs $300,000 and produces a total net gain of $450,000. What is its return on investment (ROI)?',
   options:['33%','50%','67%','150%'],answer:[1],
   explanation:'ROI = (gain – cost) ÷ cost = (450,000 – 300,000) ÷ 300,000 = 50%.',
   ref:'Principle: Focus on value · Performance domain: Finance'},
  {id:'S3-R16',domain:D,task:3,approach:'Predictive',type:'single',
   stem:'Two projects have similar risk. Project X has an internal rate of return (IRR) of 18%; Project Y has an IRR of 12%. Based on IRR, which should be chosen?',
   options:['Project Y, because it is lower','Project X, because a higher IRR indicates a better return','Either, because IRR does not matter','Neither'],answer:[1],
   explanation:'A higher IRR is generally better when comparing projects of similar risk and scale.',
   ref:'Principle: Focus on value · Performance domain: Governance'},
  {id:'S3-R17',domain:D,task:3,approach:'Predictive',type:'single',
   stem:'An organization can fund only one of two projects: Project A (NPV $200,000) or Project B (NPV $150,000). It chooses A. What is the opportunity cost?',
   options:['$50,000','$150,000','$200,000','$350,000'],answer:[1],
   explanation:'The opportunity cost is the value of the best alternative given up—Project B’s $150,000.',
   ref:'Principle: Focus on value · Performance domain: Finance'},
  {id:'S3-R18',domain:D,task:3,approach:'Agile',type:'single',
   stem:'The team is unsure which of two checkout designs increases completed purchases. What is the most value-focused way to decide?',
   options:['Ask the most senior manager','Run an A/B test with real users and measure the completion rate for each design','Build both and release them together','Choose the cheaper design'],answer:[1],
   explanation:'Experiments with real users provide evidence about which option delivers more value.',
   ref:'Principle: Focus on value · Performance domain: Scope'},
  {id:'S3-R19',domain:D,task:3,approach:'Hybrid',type:'single',
   stem:'Which document lists the planned benefits of a project, with their measures, owners and timing?',
   options:['Benefits register (or benefits management plan)','Issue log','Resource calendar','Configuration plan'],answer:[0],
   explanation:'The benefits register and plan define what value is expected, how it will be measured and who is accountable.',
   ref:'Principle: Focus on value · Focus area: Planning'},
  {id:'S3-R20',domain:D,task:3,approach:'Agile',type:'single',
   stem:'Why does incremental delivery often produce more value than a single “big bang” release?',
   options:['It always costs less','Users start benefiting from early increments sooner, and feedback improves later increments','It needs no testing','It removes the need for a product owner'],answer:[1],
   explanation:'Incremental delivery brings forward benefits and reduces risk through learning.',
   ref:'Principle: Focus on value · Performance domain: Schedule'},
  {id:'S3-R21',domain:D,task:3,approach:'Hybrid',type:'single',
   stem:'A project delivered all its features on time, but customer complaints did not decrease as expected. What does this indicate?',
   options:['The project was a complete success','The outputs were delivered, but the intended outcome was not achieved; the team should investigate why and adjust','The complaints are not related to the project','The schedule was wrong'],answer:[1],
   explanation:'Value is measured by outcomes. Delivering outputs is not enough if the intended benefit is not achieved.',
   ref:'Principle: Focus on value · Focus area: Monitoring and Controlling'},
  {id:'S3-R22',domain:D,task:3,approach:'Agile',type:'multi',
   stem:'Which TWO practices help a team avoid building features that customers do not value?',
   options:['Validating assumptions early with prototypes or experiments','Building every requested feature','Reviewing usage data and feedback to reprioritize the backlog','Freezing the backlog at the start','Measuring success by the number of features delivered'],answer:[0,2],
   explanation:'Early validation and continuous use of feedback keep the team focused on what customers actually value.',
   ref:'Principle: Focus on value · Performance domain: Scope'},

  // Task 4 — Resources (6)
  {id:'S3-R23',domain:D,task:4,approach:'Predictive',type:'single',
   stem:'Which hierarchical representation organizes resources by category and type, such as labour, materials and equipment?',
   options:['Resource breakdown structure','Work breakdown structure','Organizational chart','Risk breakdown structure'],answer:[0],
   explanation:'The resource breakdown structure categorizes resources to support estimating, acquisition and control.',
   ref:'Performance domain: Resources · Focus area: Planning'},
  {id:'S3-R24',domain:D,task:4,approach:'Hybrid',type:'single',
   stem:'Contractors joining mid-project take weeks to get system access and equipment. What should the project manager put in place?',
   options:['Ask contractors to bring their own equipment','A standard onboarding checklist, started before arrival, that covers access, equipment, security training and an introduction to the team','Delay contractor start dates','Have current team members share accounts'],answer:[1],
   explanation:'Planned onboarding reduces lost productivity. Sharing accounts would breach security.',
   ref:'Performance domain: Resources · Focus area: Executing'},
  {id:'S3-R25',domain:D,task:4,approach:'Agile',type:'single',
   stem:'Management wants to move developers between teams every sprint to “use resources efficiently.” What is the main concern?',
   options:['None; it maximizes utilization','Frequent changes prevent teams from forming, reduce productivity and increase coordination cost; stable teams usually deliver more value','It is too expensive to update badges','The product owner will object'],answer:[1],
   explanation:'Stable, long-lived teams build trust and shared knowledge, which outweighs short-term utilization gains.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'S3-R26',domain:D,task:4,approach:'Predictive',type:'single',
   stem:'A project needs specialized testing equipment for only two weeks. What is the most appropriate way to obtain it?',
   options:['Buy it outright','Compare renting or leasing with purchasing, considering cost, availability and lead time, and choose the best option','Ask the team to improvise','Remove the testing'],answer:[1],
   explanation:'Physical resource acquisition should be based on analysis of cost, timing and availability—often a make-or-buy or lease-or-buy decision.',
   ref:'Performance domains: Resources, Finance · Focus area: Planning'},
  {id:'S3-R27',domain:D,task:4,approach:'Hybrid',type:'single',
   stem:'A team member is assigned 60% to the project, but functional work keeps taking 80% of their time. What should the project manager do?',
   options:['Accept the reduced availability','Raise the gap with the functional manager, using the agreed allocation and its effect on the schedule, and agree on a solution','Ask the member to work weekends','Report the member to HR'],answer:[1],
   explanation:'Resource commitments in a matrix organization are managed through negotiation with functional managers, based on agreements and impacts.',
   ref:'Performance domain: Resources · Focus area: Monitoring and Controlling'},
  {id:'S3-R28',domain:D,task:4,approach:'Agile',type:'multi',
   stem:'Which TWO practices help a team build its capability to meet changing project needs?',
   options:['Cross-training team members in adjacent skills','Keeping each person in a narrow specialty','Allowing time for learning and experimentation in the team’s capacity','Assigning all complex work to one expert','Avoiding feedback'],answer:[0,2],
   explanation:'Cross-training and protected learning time build a flexible, resilient team.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},

  // Task 5 — Procurement (6)
  {id:'S3-R29',domain:D,task:5,approach:'Predictive',type:'dropdown',
   stem:'A cost-plus-incentive-fee contract has a target cost of $200,000, a target fee of $20,000 and an 80/20 buyer/seller share ratio. Actual costs are $230,000. What is the total amount the buyer pays?',
   options:['$230,000','$244,000','$250,000','$256,000'],answer:[1],
   explanation:'The overrun is $30,000. The seller’s 20% share is $6,000, which reduces the fee to $14,000. Total = $230,000 + $14,000 = $244,000.',
   ref:'Performance domains: Finance, Resources (procurement)'},
  {id:'S3-R30',domain:D,task:5,approach:'Predictive',type:'single',
   stem:'Vendors are scored on technical capability (50%), cost (30%) and experience (20%). Vendor A scores 8, 6 and 9; Vendor B scores 7, 9 and 6; Vendor C scores 9, 4 and 8. Which vendor has the highest weighted score?',
   options:['Vendor A','Vendor B','Vendor C','They are tied'],answer:[0],
   explanation:'A: 4.0 + 1.8 + 1.8 = 7.6. B: 3.5 + 2.7 + 1.2 = 7.4. C: 4.5 + 1.2 + 1.6 = 7.3. Vendor A has the highest weighted score.',
   ref:'Performance domain: Resources (procurement) · Focus area: Executing'},
  {id:'S3-R31',domain:D,task:5,approach:'Predictive',type:'matching',
   stem:'Match each contract type to its main characteristic.',
   pairs:[{left:'Firm fixed price',right:0},{left:'Cost plus fixed fee',right:1},{left:'Cost plus award fee',right:2},{left:'Time and materials',right:3}],
   choices:['The seller is paid an agreed price regardless of its actual costs','The seller is reimbursed for allowable costs plus a fixed fee','The seller is reimbursed for costs, plus a fee based on the buyer’s subjective assessment of performance','The buyer pays agreed rates for time and materials used'],
   explanation:'Each contract type allocates risk differently between buyer and seller.',
   ref:'Performance domain: Resources (procurement) · Focus area: Planning'},
  {id:'S3-R32',domain:D,task:5,approach:'Hybrid',type:'single',
   stem:'Only one supplier in the world makes a required component. What procurement approach applies, and what is the main risk?',
   options:['Competitive bidding; there is no risk','Sole-source procurement; the buyer has less negotiating leverage and depends on one supplier, so the risk should be managed—for example through contract terms and contingency stock','Make-or-buy analysis; the risk is quality','Teaming agreement; the risk is overlap'],answer:[1],
   explanation:'Sole-source situations reduce leverage and increase dependency risk, which must be actively managed.',
   ref:'Performance domains: Resources (procurement), Risk'},
  {id:'S3-R33',domain:D,task:5,approach:'Predictive',type:'single',
   stem:'The buyer’s strategy changes, and it no longer needs the remaining contract work. The contract allows termination for convenience. What typically applies?',
   options:['The seller receives nothing','The buyer may end the contract, and the seller is usually paid for work completed and certain costs, as defined in the contract','The seller can refuse termination','The buyer must pay the full contract value'],answer:[1],
   explanation:'Termination for convenience lets the buyer end the contract but usually requires payment for completed work and agreed costs.',
   ref:'Performance domains: Resources (procurement), Governance'},
  {id:'S3-R34',domain:D,task:5,approach:'Hybrid',type:'multi',
   stem:'Which TWO items should a statement of work (SOW) for a contracted service include?',
   options:['A clear description of the work, deliverables and acceptance criteria','The buyer’s internal salary information','Performance requirements and the timeframe for delivery','The project team’s personal phone numbers','Unrelated future projects'],answer:[0,2],
   explanation:'An SOW describes the work in enough detail for sellers to decide whether they can provide it and for the buyer to manage performance.',
   ref:'Performance domain: Resources (procurement) · Focus area: Planning'},

  // Task 6 — Finance (6)
  {id:'S3-R35',domain:D,task:6,approach:'Predictive',type:'dropdown',
   stem:'PV = $300,000 and EV = $270,000. What is the schedule variance percentage (SV%)?',
   options:['–30%','–11%','–10%','+10%'],answer:[2],
   explanation:'SV = EV – PV = –$30,000. SV% = SV ÷ PV = –30,000 ÷ 300,000 = –10%.',
   ref:'Performance domains: Schedule, Finance · Focus area: Monitoring and Controlling'},
  {id:'S3-R36',domain:D,task:6,approach:'Predictive',type:'dropdown',
   stem:'BAC = $500,000, PV = $250,000, EV = $200,000 and AC = $250,000. Both cost and schedule performance are expected to affect the remaining work. What is the EAC? Select the closest value.',
   options:['$550,000','$625,000','$719,000','$780,000'],answer:[2],
   explanation:'CPI = 200 ÷ 250 = 0.8 and SPI = 200 ÷ 250 = 0.8. EAC = AC + (BAC – EV) ÷ (CPI × SPI) = 250,000 + 300,000 ÷ 0.64 ≈ $719,000.',
   ref:'Performance domain: Finance · Focus area: Monitoring and Controlling'},
  {id:'S3-R37',domain:D,task:6,approach:'Predictive',type:'single',
   stem:'What does a cumulative cost curve (S-curve) for a project typically show?',
   options:['Spending that is equal every month','Slow spending at the start, faster spending in the middle and slower spending near the end','Spending only at the end','Decreasing total cost over time'],answer:[1],
   explanation:'Cumulative costs usually follow an S-shape as resource use ramps up and then tapers off.',
   ref:'Performance domain: Finance · Focus area: Planning'},
  {id:'S3-R38',domain:D,task:6,approach:'Hybrid',type:'single',
   stem:'The contingency reserve is being used faster than identified risks are occurring. What should the project manager do?',
   options:['Ignore it','Review reserve use against the risk register to confirm that each draw relates to an identified risk, and reassess the remaining reserve against remaining risk','Move management reserve into contingency without approval','Stop recording reserve use'],answer:[1],
   explanation:'Reserve analysis compares remaining reserves with remaining risk to confirm that the reserve is adequate and properly used.',
   ref:'Performance domains: Finance, Risk · Focus area: Monitoring and Controlling'},
  {id:'S3-R39',domain:D,task:6,approach:'Agile',type:'single',
   stem:'An agile team’s run rate is $40,000 per sprint. The product owner asks how much the next six features will cost. The team estimates they will take about 3.5 sprints. What is a reasonable estimate?',
   options:['$40,000','About $140,000, presented as a range and updated as work progresses','$240,000','It cannot be estimated'],answer:[1],
   explanation:'Cost forecasts in agile often use team run rate × forecast sprints (40,000 × 3.5 = $140,000), shown as a range.',
   ref:'Performance domain: Finance · Focus area: Planning'},
  {id:'S3-R40',domain:D,task:6,approach:'Hybrid',type:'multi',
   stem:'Which TWO practices support good financial control on a project?',
   options:['Comparing actual costs with the time-phased budget regularly','Recording costs only at the end of the project','Forecasting the estimate at completion and reporting variances against thresholds','Spending contingency on new scope','Mixing project and operational costs'],answer:[0,2],
   explanation:'Regular comparison, forecasting and threshold-based reporting allow timely financial decisions.',
   ref:'Performance domain: Finance · Focus area: Monitoring and Controlling'},

  // Task 7 — Quality (5)
  {id:'S3-R41',domain:D,task:7,approach:'Predictive',type:'single',
   stem:'The team wants to find the possible causes of late deliveries by grouping them into categories such as people, process, tools and materials. Which tool should it use?',
   options:['Cause-and-effect (fishbone) diagram','Pareto chart','Control chart','Scatter diagram'],answer:[0],
   explanation:'A fishbone diagram helps teams brainstorm and organize potential causes of a problem by category.',
   ref:'Principle: Embed quality · Focus area: Monitoring and Controlling'},
  {id:'S3-R42',domain:D,task:7,approach:'Predictive',type:'single',
   stem:'What does a quality management plan describe?',
   options:['Only the testing schedule','How applicable quality policies, standards, roles, activities and metrics will be implemented to meet quality requirements','The team’s performance reviews','The procurement strategy'],answer:[1],
   explanation:'The quality management plan explains how the project will achieve and verify its quality objectives.',
   ref:'Principle: Embed quality · Focus area: Planning'},
  {id:'S3-R43',domain:D,task:7,approach:'Hybrid',type:'single',
   stem:'Who should perform user acceptance testing (UAT), and why?',
   options:['The developers, because they know the code','Business users or their representatives, to confirm that the solution meets their needs in realistic scenarios','The vendor alone','The project sponsor only'],answer:[1],
   explanation:'UAT validates fitness for use from the users’ perspective, which developers cannot fully judge.',
   ref:'Principle: Embed quality · Performance domain: Scope'},
  {id:'S3-R44',domain:D,task:7,approach:'Agile',type:'single',
   stem:'An agile team keeps deferring refactoring to deliver features faster, and its velocity is now falling. What should it do?',
   options:['Continue deferring refactoring','Make technical debt visible and agree with the product owner to invest some capacity in refactoring each sprint','Stop delivering features for six months','Rewrite the whole product'],answer:[1],
   explanation:'Regular, planned refactoring sustains quality and speed. Accumulated technical debt slows delivery.',
   ref:'Principle: Embed quality · Performance domain: Scope'},
  {id:'S3-R45',domain:D,task:7,approach:'Predictive',type:'multi',
   stem:'Which TWO are examples of quality metrics?',
   options:['Defect density (defects per thousand lines of code or per unit)','The project manager’s years of experience','Percentage of deliverables accepted on first submission','Number of team meetings','The colour of the logo'],answer:[0,2],
   explanation:'Quality metrics are measurable attributes of a product or process used to assess quality.',
   ref:'Principle: Embed quality · Focus area: Planning'},

  // Task 8 — Schedule (6)
  {id:'S3-R46',domain:D,task:8,approach:'Predictive',type:'dropdown',graphic:'network-3',
   stem:'Using the network diagram, what is the total project duration?',
   options:['10 days','12 days','14 days','19 days'],answer:[2],
   explanation:'Paths: A-B-D-F = 4+3+2+1 = 10; A-C-D-F = 4+5+2+1 = 12; A-C-E-F = 4+5+4+1 = 14. The critical path is A-C-E-F, so the duration is 14 days.',
   ref:'Performance domain: Schedule · Focus area: Planning'},
  {id:'S3-R47',domain:D,task:8,approach:'Predictive',type:'hotspot',graphic:'network-3',
   stem:'Using the network diagram, click the activity with the most total float.',
   options:['A','B','C','D','E','F'],answer:[1],
   explanation:'B can start on day 4 and must finish by day 11 (the late start of D), so it has 4 days of float. D has 2 days (its only paths, A-B-D-F and A-C-D-F, are 10 and 12 days long). A, C, E and F are on the critical path with zero float.',
   ref:'Performance domain: Schedule · Focus area: Planning'},
  {id:'S3-R48',domain:D,task:8,approach:'Predictive',type:'single',
   stem:'Which scheduling method adds project and feeding buffers and focuses on managing them, rather than padding individual activity estimates?',
   options:['Critical path method','Critical chain method','Rolling-wave planning','Fast tracking'],answer:[1],
   explanation:'The critical chain method aggregates safety time into buffers and monitors buffer consumption to protect the end date.',
   ref:'Performance domain: Schedule · Focus area: Planning'},
  {id:'S3-R49',domain:D,task:8,approach:'Predictive',type:'single',
   stem:'Executives want a schedule view showing only the key dates. What should the project manager provide?',
   options:['The full detailed schedule','A milestone schedule','The resource histogram','The network diagram'],answer:[1],
   explanation:'Milestone schedules summarize key events for executive audiences.',
   ref:'Performance domain: Schedule · Focus area: Executing'},
  {id:'S3-R50',domain:D,task:8,approach:'Agile',type:'single',
   stem:'How does a Kanban team typically plan and deliver work, compared with a Scrum team?',
   options:['Kanban uses fixed sprints like Scrum','Kanban uses continuous flow with WIP limits, pulling work when capacity is available, rather than fixed-length sprints','Kanban has no planning at all','Kanban requires a project manager to assign tasks'],answer:[1],
   explanation:'Kanban focuses on continuous flow and WIP limits; Scrum uses time-boxed sprints with sprint planning.',
   ref:'Performance domain: Schedule · Focus area: Executing'},
  {id:'S3-R51',domain:D,task:8,approach:'Hybrid',type:'multi',
   stem:'The project is three weeks behind on a fixed deadline. Which TWO options are valid schedule-recovery approaches?',
   options:['Crashing critical-path activities by adding resources','Reducing quality checks without approval','Fast tracking critical-path activities where the extra risk is acceptable','Compressing non-critical activities','Reporting the original dates as unchanged'],answer:[0,2],
   explanation:'Crashing and fast tracking compress the critical path. Compressing non-critical work does not shorten the project.',
   ref:'Performance domain: Schedule · Focus area: Monitoring and Controlling'},

  // Task 9 — Evaluate status (6)
  {id:'S3-R52',domain:D,task:9,approach:'Predictive',type:'dropdown',
   stem:'A project has 10 work packages worth $10,000 each. Four are complete, and three have started but are not finished. Using the 50/50 rule, what is the earned value?',
   options:['$40,000','$55,000','$70,000','$35,000'],answer:[1],
   explanation:'Under the 50/50 rule, a started work package earns 50% and a completed one earns 100%: 4 × 10,000 + 3 × 5,000 = $55,000.',
   ref:'Performance domain: Finance · Focus area: Monitoring and Controlling'},
  {id:'S3-R53',domain:D,task:9,approach:'Agile',type:'single',
   stem:'What is the difference between lead time and cycle time in Kanban?',
   options:['They are the same','Lead time runs from when a request is made until it is delivered; cycle time runs from when work starts until it is finished','Cycle time is always longer','Lead time measures only testing'],answer:[1],
   explanation:'Lead time reflects the customer’s wait; cycle time reflects the team’s processing time.',
   ref:'Performance domain: Schedule · Focus area: Monitoring and Controlling'},
  {id:'S3-R54',domain:D,task:9,approach:'Hybrid',type:'single',
   stem:'A dashboard uses red, amber and green status, but different workstreams use different rules for each colour. What should the project manager do?',
   options:['Let each workstream continue','Define and communicate consistent criteria for each status colour across the project','Remove colours from the dashboard','Report everything as amber'],answer:[1],
   explanation:'Consistent status criteria make reporting comparable and trustworthy.',
   ref:'Performance domain: Governance · Focus area: Monitoring and Controlling'},
  {id:'S3-R55',domain:D,task:9,approach:'Agile',type:'single',
   stem:'A Kanban team wants to forecast how many items it can finish in the next eight weeks. What is a robust approach?',
   options:['Use the best week ever multiplied by eight','Use a Monte Carlo forecast based on historical weekly throughput, giving a range with probabilities','Ask each person to guess','Assume the same number as last quarter'],answer:[1],
   explanation:'Probabilistic forecasting from historical throughput reflects real variability and supports honest planning.',
   ref:'Performance domain: Schedule · Focus area: Monitoring and Controlling'},
  {id:'S3-R56',domain:D,task:9,approach:'Predictive',type:'single',
   stem:'A work package shows a significant cost variance. What should the project manager do after identifying it?',
   options:['Report the number only','Perform variance analysis to find the cause, assess the impact on the project, and decide on corrective or preventive actions','Ignore it if the total budget is fine','Rebaseline immediately'],answer:[1],
   explanation:'Variance analysis explains the cause and supports appropriate corrective action.',
   ref:'Performance domain: Finance · Focus area: Monitoring and Controlling'},
  {id:'S3-R57',domain:D,task:9,approach:'Hybrid',type:'multi',
   stem:'Which TWO practices improve the reliability of project status information?',
   options:['Basing status on objective evidence such as completed deliverables and measured data','Relying on team members’ estimates of percentage complete','Using consistent, agreed definitions of “done” and status criteria','Reporting only good news','Updating status only at phase ends'],answer:[0,2],
   explanation:'Objective evidence and consistent definitions make status reporting accurate and comparable.',
   ref:'Principle: Be an accountable leader · Focus area: Monitoring and Controlling'},

  // Task 10 — Closure (5)
  {id:'S3-R58',domain:D,task:10,approach:'Predictive',type:'single',
   stem:'Before closing the project, the project manager wants to know how satisfied the customer is with the results. What should be done?',
   options:['Assume satisfaction because deliverables were accepted','Gather customer feedback—for example through a satisfaction survey or interview—and include the findings in the final report and lessons learned','Ask the team’s opinion','Skip this step'],answer:[1],
   explanation:'Customer feedback at closure measures stakeholder satisfaction and informs future projects.',
   ref:'Focus area: Closing · Performance domain: Stakeholders'},
  {id:'S3-R59',domain:D,task:10,approach:'Predictive',type:'single',
   stem:'A vendor defaults, and the project is terminated early. What should the project manager do regarding closure?',
   options:['Simply stop work','Document the reasons for termination and the status of all deliverables, settle the contract according to its terms, transfer any usable work, capture lessons and archive records','Restart with a new vendor without closing','Hide the termination from stakeholders'],answer:[1],
   explanation:'Early termination still requires a structured closure to protect the organization and preserve value and learning.',
   ref:'Focus area: Closing · Performance domain: Governance'},
  {id:'S3-R60',domain:D,task:10,approach:'Agile',type:'single',
   stem:'An agile release has been delivered, and the team will continue working on the product. What closure activity is still appropriate for the release?',
   options:['None','A release retrospective and review of the release goals and outcomes with stakeholders','Disbanding the team','Archiving the product backlog'],answer:[1],
   explanation:'Release-level reflection captures learning and confirms outcomes, even when the product continues.',
   ref:'Focus area: Closing · Principle: Embed quality'},
  {id:'S3-R61',domain:D,task:10,approach:'Hybrid',type:'single',
   stem:'Why is it important to recognize and celebrate the team’s achievements at project closure?',
   options:['It is required by contract','It reinforces motivation, acknowledges contributions and supports team members’ careers and future engagement','It replaces the final report','It closes the contracts'],answer:[1],
   explanation:'Recognition at closure acknowledges effort and builds morale and goodwill for future work.',
   ref:'Principle: Build an empowered culture · Focus area: Closing'},
  {id:'S3-R62',domain:D,task:10,approach:'Predictive',type:'multi',
   stem:'Which TWO items should be handed over to the operations team at project closure?',
   options:['Operating and maintenance documentation, warranties and support contacts','The project team’s timesheets','Training materials and records of known issues and workarounds','The project manager’s personal notes','Draft versions of the charter'],answer:[0,2],
   explanation:'Operations needs the information and support required to run and maintain the product.',
   ref:'Focus area: Closing · Performance domain: Resources'}
];
