import {CaseStudy,ExamQuestion} from '../../exam-types';

export const CASE_STUDIES:CaseStudy[]=[
  {id:'A',title:'Case A · Prairie Power: Customer Billing Modernization (hybrid)',graphic:'ev-curve',context:[
    'Prairie Power, a regulated electricity utility in Western Canada, is replacing a 25-year-old billing system. The project has a budget at completion (BAC) of $1,000,000 and a planned duration of 10 months.',
    'The billing engine and data migration follow a predictive plan with a fixed regulatory cut-over date. A customer self-service portal is being built by an agile team in two-week sprints. A vendor supplies integration specialists on a time-and-materials contract.',
    'The operations team wants to use an AI tool that forecasts customer bills from historical consumption data. Call-centre staff, represented by a union, have raised concerns about how the portal will affect their jobs. The chart shows cumulative planned value (PV), earned value (EV) and actual cost (AC) at the end of month 6.'
  ]},
  {id:'B',title:'Case B · Northwind Credit Union: Mobile Banking App (agile)',graphic:'burndown',context:[
    'Northwind Credit Union is building a new mobile banking app. Three Scrum teams of seven people each work in two-week sprints from one shared product backlog. The teams are distributed across Regina, Toronto and Halifax.',
    'The product owner (PO) also manages two other products. Security and privacy requirements from the credit union’s regulator must be met before any public release. Marketing wants to announce a launch date at an industry conference in four months.',
    'You are the project manager supporting the three teams, working alongside their Scrum Masters. The chart shows the sprint burndown for Team 1 at the end of day 7 of the current 10-day sprint.'
  ]},
  {id:'C',title:'Case C · Riverside Community Health Centre (predictive)',graphic:'risk-matrix',context:[
    'A municipality is building a three-storey community health centre with a $14 million budget. Provincial infrastructure funding requires the building to meet a net-zero-energy-ready performance standard and to open within 24 months.',
    'You manage the project for the municipality using a predictive approach. A general contractor works under a fixed-price contract, and an architecture firm is responsible for the design. The project is in month 9 of construction.',
    'The risk team has plotted six active risks (R1–R6) on a probability-and-impact matrix, shown in the chart. Recent global tariffs have increased structural steel prices, and residents near the site have begun to complain about noise and traffic.'
  ]}
];

export const CASE_QUESTIONS:ExamQuestion[]=[
  // ---------- Case A ----------
  {id:'A1',caseId:'A',domain:'Process',task:9,approach:'Hybrid',type:'single',graphic:'ev-curve',
   stem:'Based on the chart at the end of month 6, which statement best describes the project’s performance?',
   options:['Ahead of schedule and under budget','Behind schedule and over budget','Behind schedule but under budget','On schedule but over budget'],answer:[1],
   explanation:'EV ($480k) is below PV ($600k), so SV = –$120k and SPI = 0.80: behind schedule. EV ($480k) is also below AC ($540k), so CV = –$60k and CPI ≈ 0.89: over budget for the work completed.',
   ref:'Performance domains: Schedule, Finance · Focus area: Monitoring and Controlling'},
  {id:'A2',caseId:'A',domain:'Process',task:6,approach:'Hybrid',type:'dropdown',graphic:'ev-curve',
   stem:'If the current cost performance continues for the rest of the project, what is the estimate at completion (EAC)? Select the closest value.',
   options:['$1,000,000','$1,060,000','$1,125,000','$1,250,000'],answer:[2],
   explanation:'CPI = EV ÷ AC = 480 ÷ 540 ≈ 0.889. With typical (continuing) variance, EAC = BAC ÷ CPI = 1,000,000 ÷ 0.889 ≈ $1,125,000. $1,060,000 is AC + (BAC – EV), which assumes the past variance will not repeat.',
   ref:'Performance domain: Finance · Focus area: Monitoring and Controlling'},
  {id:'A3',caseId:'A',domain:'People',task:5,approach:'Hybrid',type:'single',
   stem:'The sponsor wants the portal’s bill-payment feature released two months early to reduce call volumes. The VP of Operations insists that no portal feature goes live before the billing cut-over because of data accuracy concerns. What should the project manager do first?',
   options:['Ask the agile team to start the bill-payment feature immediately because the sponsor has the highest authority','Facilitate a session with the sponsor and VP to review the business case, dependencies and risks, and agree on release priorities','Escalate the disagreement to the steering committee and wait for a decision','Add the feature to the predictive schedule so that it follows the cut-over'],answer:[1],
   explanation:'The stakeholders have conflicting expectations about outcomes. The project manager should first bring them together around shared information—value, dependencies and risks—to reach an aligned decision. Escalation is appropriate only if alignment cannot be reached within the project manager’s authority.',
   ref:'Principle: Focus on value · Performance domain: Stakeholders'},
  {id:'A4',caseId:'A',domain:'Business Environment',task:2,approach:'Hybrid',type:'single',
   stem:'The operations team is ready to load three years of identifiable customer consumption data into the AI forecasting tool, which is hosted by a third party. What should the project manager do?',
   options:['Allow the load because the data belongs to the utility','Ask the vendor to sign a non-disclosure agreement and proceed','Pause the load and engage the privacy and compliance team to assess requirements, such as a privacy impact assessment, before any data is shared','Anonymize a sample of the data personally and test the tool'],answer:[2],
   explanation:'Personal information in a regulated utility is subject to privacy legislation and organizational policy. The project manager must confirm compliance requirements with the accountable compliance function before data leaves the organization. An NDA alone does not satisfy privacy obligations.',
   ref:'Performance domains: Governance, Risk · AI and data ethics'},
  {id:'A5',caseId:'A',domain:'People',task:2,approach:'Hybrid',type:'single',
   stem:'Billing subject-matter experts and the portal team keep arguing in meetings about what “active account” means, and stories are being rejected at sprint review as a result. What is the best way to resolve the conflict?',
   options:['Let the billing experts decide because they own the legacy data','Bring both groups together to agree on a shared definition, record it in a data dictionary and add it to the definition of ready','Ask the sponsor to choose a definition','Tell the portal team to follow whatever definition the testers use'],answer:[1],
   explanation:'Collaborating and problem solving addresses the root cause—an undefined shared term—and produces a durable agreement. Recording the definition prevents the same conflict from recurring.',
   ref:'Principle: Build an empowered culture · Performance domain: Stakeholders'},
  {id:'A6',caseId:'A',domain:'Business Environment',task:7,approach:'Hybrid',type:'single',
   stem:'Call-centre staff are anxious that the self-service portal will eliminate their jobs, and the union has requested a meeting. Which response best supports organizational change?',
   options:['Delay communication until the portal is live to avoid rumours','Refer all questions to human resources','Work with HR and union representatives to assess change impacts, communicate openly about role changes, and plan training and change champions','Tell staff that no jobs will be affected so that they stay motivated'],answer:[2],
   explanation:'Organizational change succeeds when affected people are engaged early, impacts are assessed honestly and support is planned. Promising outcomes the project cannot guarantee damages trust.',
   ref:'Principle: Be an accountable leader · Performance domains: Stakeholders, Resources'},
  {id:'A7',caseId:'A',domain:'Process',task:5,approach:'Hybrid',type:'single',
   stem:'The integration vendor’s invoices on the time-and-materials contract are 35% higher than planned, while integration progress is behind. What should the project manager do?',
   options:['Stop paying invoices until progress improves','Verify invoiced hours against approved work and contract terms, then work with procurement to negotiate a not-to-exceed limit or clearer deliverables for the remaining work','Terminate the contract and bring in a new vendor','Accept the cost because time-and-materials contracts place the risk on the buyer'],answer:[1],
   explanation:'Under time-and-materials contracts the buyer carries cost risk, so it must control the contract actively: validate charges against the terms, and work through procurement to cap or restructure the remaining work. Withholding payment or terminating without analysis can breach the contract.',
   ref:'Performance domains: Finance, Resources (procurement) · Focus area: Monitoring and Controlling'},
  {id:'A8',caseId:'A',domain:'Process',task:1,approach:'Hybrid',type:'multi',
   stem:'The project manager is updating the integrated plan for this hybrid project. Which TWO elements should be included?',
   options:['A release roadmap for the portal, aligned with the milestone schedule for the billing cut-over','One detailed WBS listing every portal feature for the full 10 months','A change approach that defines which changes go to the change control board and which are handled in the portal backlog','Removing sprint reviews to save time before the cut-over','A requirement that the agile team submit change requests for every backlog reorder'],answer:[0,2],
   explanation:'A hybrid plan integrates adaptive and predictive components: a roadmap linked to fixed milestones, and a tailored change approach. Fully detailing adaptive scope up front or forcing formal change control on backlog ordering defeats the purpose of the agile component.',
   ref:'Principle: Adopt a holistic view · Performance domain: Governance · Focus area: Planning'},
  {id:'A9',caseId:'A',domain:'Business Environment',task:8,approach:'Hybrid',type:'single',
   stem:'The provincial government announces amendments to energy-billing regulations, effective in nine months. They will require new itemized charges on every bill. What should the project manager do first?',
   options:['Add the new charges to the portal backlog for the next sprint','Analyze the amendments with compliance and business experts to determine their impact on scope, schedule and cost, then update the risk register and raise any changes through change control','Ignore the change until the regulation is final','Ask the vendor to quote for the change'],answer:[1],
   explanation:'External changes must first be evaluated for their impact on the project and its business case. Only then are the appropriate responses—risk updates, change requests or backlog items—chosen.',
   ref:'Principle: Adopt a holistic view · Performance domains: Risk, Governance'},
  {id:'A10',caseId:'A',domain:'People',task:8,approach:'Hybrid',type:'single',
   stem:'Executives say they do not read the 30-page monthly status report and feel surprised by issues. What is the best action?',
   options:['Send the report weekly instead of monthly','Confirm executives’ information needs and provide a concise dashboard showing key metrics, decisions needed and exceptions, with detail available on request','Shorten the report by removing risks','Present the full report at every steering meeting'],answer:[1],
   explanation:'Communication should be tailored to the audience. Executives need concise, decision-oriented information. The communications plan should be updated to reflect their confirmed needs.',
   ref:'Performance domain: Stakeholders · Focus area: Executing'},

  // ---------- Case B ----------
  {id:'B1',caseId:'B',domain:'Process',task:9,approach:'Agile',type:'single',graphic:'burndown',
   stem:'Based on Team 1’s burndown at the end of day 7, what is the most appropriate action?',
   options:['Extend the sprint by three days so that all items can be completed','At the daily scrum, have the team inspect progress toward the sprint goal and, with the product owner, renegotiate sprint backlog scope if needed','Add two developers from Team 2 for the rest of the sprint','Do nothing until the sprint review'],answer:[1],
   explanation:'With 66 points remaining and three days left, the team is far behind the ideal line. Scrum keeps the sprint length fixed. The team re-plans daily, and the developers and the product owner can renegotiate scope while protecting the sprint goal.',
   ref:'Performance domain: Schedule · Focus area: Monitoring and Controlling'},
  {id:'B2',caseId:'B',domain:'People',task:3,approach:'Agile',type:'single',
   stem:'In retrospectives, two senior developers dominate discussion and the junior developers rarely speak. What should you do as a servant leader?',
   options:['Ask the senior developers to stop attending retrospectives','Use facilitation techniques—such as silent brainstorming and round-robin input—and coach the senior developers on creating space for others','Run the retrospective yourself and assign improvement actions','Meet individually with junior developers to collect their feedback instead'],answer:[1],
   explanation:'A servant leader builds psychological safety and equal participation through facilitation and coaching, keeping ownership of improvements with the team.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'B3',caseId:'B',domain:'Process',task:3,approach:'Agile',type:'single',
   stem:'The product owner has missed refinement sessions for three sprints, and teams are pulling items with unclear acceptance criteria. What should you do?',
   options:['Ask the most senior developer to act as product owner','Discuss the impact on value and flow with the product owner and sponsor, and agree on dedicated availability or an empowered delegate with decision authority','Write the acceptance criteria yourself','Stop the sprints until the product owner is available'],answer:[1],
   explanation:'Value-based delivery depends on an available, empowered product owner who maximizes value. The issue must be made visible and resolved with the people who can fix it, without taking over the role.',
   ref:'Principle: Focus on value · Performance domain: Scope'},
  {id:'B4',caseId:'B',domain:'Business Environment',task:2,approach:'Agile',type:'single',
   stem:'The teams want to release a minimum viable product to the public next month. The regulator’s security guidelines require an independent penetration test before any public release, and none has been scheduled. What should you do?',
   options:['Release to the public and schedule the test for the following quarter','Release only to iOS users first','Work with the product owner and security team to schedule the test, add the compliance requirement to the release definition of done, and adjust the release plan','Ask the teams to run their own security scan instead'],answer:[2],
   explanation:'Compliance requirements are non-negotiable constraints. Building them into the definition of done and the release plan ensures that value is delivered without regulatory exposure.',
   ref:'Principle: Embed quality · Performance domain: Governance'},
  {id:'B5',caseId:'B',domain:'People',task:1,approach:'Agile',type:'single',
   stem:'Six new developers have joined the three teams. In planning, they ask why certain features matter and seem unsure what “done” looks like for the product. What is the best action?',
   options:['Give them the requirements document to read','Ask the product owner to lead a product vision and goal session with all teams, connecting the roadmap to customer outcomes','Assign them to bug fixes until they understand the product','Ask the Scrum Masters to explain the backlog items one by one'],answer:[1],
   explanation:'A shared vision gives teams purpose and helps them make decisions on their own. The product owner is accountable for communicating the product goal.',
   ref:'Principle: Build an empowered culture · Performance domain: Stakeholders'},
  {id:'B6',caseId:'B',domain:'Process',task:7,approach:'Agile',type:'single',
   stem:'Escaped defects found by users in the beta group have doubled over the last three sprints. Developers say technical debt is slowing them down. What should you do?',
   options:['Add a dedicated testing sprint before release','Work with the teams and product owner to make technical debt visible in the backlog, reserve capacity for it, and strengthen the definition of done with automated tests','Ask testers to work overtime','Track defects in a separate spreadsheet for the sponsor'],answer:[1],
   explanation:'Quality is built in, not inspected in. A stronger definition of done and planned capacity for technical debt address the root cause rather than adding late-stage testing.',
   ref:'Principle: Embed quality · Performance domain: Scope'},
  {id:'B7',caseId:'B',domain:'People',task:7,approach:'Agile',type:'single',
   stem:'The only developer who understands the payment-gateway integration will leave the organization in six weeks. What is the most effective action?',
   options:['Ask HR to offer a retention bonus','Plan pair programming, knowledge-sharing sessions and lightweight documentation so that at least two other developers can maintain the integration before the developer leaves','Ask the developer to write a detailed manual during the last week','Hire a contractor after the developer leaves'],answer:[1],
   explanation:'Knowledge transfer is most effective when it happens through practice and shared work, started early enough to verify that others can perform the work independently.',
   ref:'Performance domain: Resources · Focus area: Executing'},
  {id:'B8',caseId:'B',domain:'Business Environment',task:4,approach:'Agile',type:'single',
   stem:'Every user story that touches customer data waits about five days for approval from a central security team, and teams are stalling. What should you do?',
   options:['Allow teams to skip security approval for low-risk stories','Raise it at the next steering committee meeting in a month','Work with the security team lead on a faster approach, such as an embedded security champion or pre-approved patterns, and track the impediment until it is resolved','Tell teams to start other work while they wait'],answer:[2],
   explanation:'Removing impediments means collaborating with the source of the constraint to improve flow while keeping necessary controls. Bypassing security is not acceptable.',
   ref:'Performance domain: Governance · Focus area: Executing'},
  {id:'B9',caseId:'B',domain:'Process',task:8,approach:'Agile',type:'dropdown',
   stem:'The three teams have a stable combined velocity of 60 story points per sprint. The release backlog contains 480 points of estimated work. Sprints are two weeks long. About how many sprints will the release take?',
   options:['6 sprints','8 sprints','10 sprints','12 sprints'],answer:[1],
   explanation:'480 ÷ 60 = 8 sprints (about 16 weeks). This forecast should be communicated as a range and updated as velocity and scope change.',
   ref:'Performance domain: Schedule · Focus area: Planning'},
  {id:'B10',caseId:'B',domain:'People',task:6,approach:'Agile',type:'multi',
   stem:'Marketing has hinted on social media at features that are not in the release forecast. Which TWO actions best manage marketing’s expectations?',
   options:['Share the velocity-based release forecast as a range and explain which features are likely, possible or unlikely','Invite the marketing lead to sprint reviews so they can see progress and give feedback','Ask the teams to work overtime to include the extra features','Remove marketing from the stakeholder register','Promise the features to avoid damaging the brand'],answer:[0,1],
   explanation:'Transparency through forecasts and regular inspection at sprint reviews keeps expectations realistic. Overtime and unrealistic promises create unsustainable pace and erode trust.',
   ref:'Principle: Be an accountable leader · Performance domain: Stakeholders'},

  // ---------- Case C ----------
  {id:'C1',caseId:'C',domain:'Business Environment',task:5,approach:'Predictive',type:'hotspot',graphic:'risk-matrix',
   stem:'Click the risk that should receive the highest priority for response planning.',
   options:['R1','R2','R3','R4','R5','R6'],answer:[0],
   explanation:'R1 has both high probability (4) and the highest impact (5), giving the highest probability-impact score (20) and placing it in the red zone. It should be addressed first.',
   ref:'Performance domain: Risk · Focus area: Planning'},
  {id:'C2',caseId:'C',domain:'Business Environment',task:8,approach:'Predictive',type:'single',
   stem:'New tariffs have increased structural steel prices by 18%. The general contractor’s fixed-price contract has a price-adjustment clause for steel. What should the project manager do first?',
   options:['Approve the price increase to avoid delays','Reject any increase because the contract is fixed-price','Review the contract clause and quantify the impact on budget and schedule, assess alternatives, and process any baseline change through change control','Ask the architect to redesign the building in timber'],answer:[2],
   explanation:'External market changes require impact analysis against the contract and baselines before any decision. The clause may entitle the contractor to an adjustment, so the project manager must understand it rather than simply approve or reject.',
   ref:'Performance domains: Finance, Risk · Principle: Adopt a holistic view'},
  {id:'C3',caseId:'C',domain:'Process',task:6,approach:'Predictive',type:'single',
   stem:'An identified risk—contaminated soil in the parking area—occurs, and the planned response costs $80,000. Where should the funding come from?',
   options:['Management reserve','Contingency reserve','The sponsor’s operating budget','Savings from other work packages'],answer:[1],
   explanation:'Contingency reserves are part of the cost baseline and cover identified risks (“known-unknowns”). Management reserves cover unidentified risks and usually require higher approval.',
   ref:'Performance domains: Finance, Risk · Focus area: Executing'},
  {id:'C4',caseId:'C',domain:'Process',task:7,approach:'Predictive',type:'single',graphic:'control-chart',
   stem:'The control chart shows 28-day compressive strength results for recent concrete pours. All points are within the control limits. What should the project manager conclude?',
   options:['The process is in control and no action is needed','The process shows a non-random pattern: eight consecutive results fall above the mean, so the cause should be investigated','The specification limits must be widened','Testing frequency should be reduced'],answer:[1],
   explanation:'The last eight results are all above the mean. Under the “rule of seven,” seven or more consecutive points on one side of the mean indicate a non-random pattern, even when every point is within the control limits. An assignable cause should be investigated.',
   ref:'Principle: Embed quality · Focus area: Monitoring and Controlling'},
  {id:'C5',caseId:'C',domain:'Business Environment',task:2,approach:'Predictive',type:'single',
   stem:'The general contractor proposes a cheaper heating and ventilation system that would save $300,000 but would not meet the net-zero-energy-ready standard required by the funding agreement. What should the project manager do?',
   options:['Accept the savings because the project is over budget','Evaluate the proposal through change control against the funding agreement’s compliance requirements, and do not approve it unless compliance can be maintained','Approve it and seek a waiver later','Let the architect decide because it is a design matter'],answer:[1],
   explanation:'Compliance with funding conditions and sustainability commitments is a governance constraint. Changes that would breach them cannot be approved for cost savings alone, and any decision must follow change control.',
   ref:'Principle: Integrate sustainability · Performance domain: Governance'},
  {id:'C6',caseId:'C',domain:'People',task:4,approach:'Predictive',type:'single',
   stem:'Residents near the site have complained to the city council about noise and truck traffic, and a councillor has asked for a response. What is the best action?',
   options:['Refer residents to the general contractor','Engage residents directly—hold a community meeting, share the work schedule and planned mitigations, and set up a contact channel for concerns','Continue work because the permits allow it','Reduce working hours without analysis'],answer:[1],
   explanation:'Community members are stakeholders who can affect the project. Proactive engagement and transparent communication reduce opposition and protect the project’s licence to operate.',
   ref:'Performance domain: Stakeholders · Principle: Integrate sustainability'},
  {id:'C7',caseId:'C',domain:'Process',task:10,approach:'Predictive',type:'single',
   stem:'Construction is complete and the occupancy permit has been issued, but the facility operations team has not been trained on the building automation system. The sponsor wants to close the project. What should the project manager do?',
   options:['Close the project; training is an operations responsibility','Complete the transition plan, including training, handover documentation and formal acceptance by operations, before administrative closure','Hand over the keys and send the manuals by email','Keep the project open indefinitely as a support team'],answer:[1],
   explanation:'Closure includes transitioning the product to the receiving organization so that benefits can be realized. Formal acceptance and knowledge transfer are part of closing the project properly.',
   ref:'Focus area: Closing · Principle: Focus on value'},
  {id:'C8',caseId:'C',domain:'People',task:2,approach:'Predictive',type:'single',
   stem:'The architect and the general contractor are disputing who must resolve conflicting dimensions on the structural drawings. Work is waiting. What should the project manager do first?',
   options:['Instruct the contractor to proceed with the dimensions that are cheapest to build','Meet with both parties, review the contract terms and responsibility matrix, and agree on who resolves the conflict and by when','Escalate to the municipality’s legal department','Ask the sponsor to decide'],answer:[1],
   explanation:'The first step is to address the conflict directly with the parties, using the agreed documents (contract and RACI) as an objective basis. Legal escalation is a last resort.',
   ref:'Performance domains: Resources, Stakeholders · Focus area: Executing'},
  {id:'C9',caseId:'C',domain:'Process',task:4,approach:'Predictive',type:'single',
   stem:'The site has one tower crane. Next week, the steel and mechanical subcontractors both need it full-time. The mechanical work has 10 days of float. What is the best approach?',
   options:['Rent a second crane immediately','Level the resource by scheduling the mechanical lifts after the steel work, using its float','Let the subcontractors share the crane on alternate days','Ask the sponsor to approve overtime'],answer:[1],
   explanation:'Resource leveling resolves the over-allocation without extending the project because the mechanical work has enough float. Renting a crane adds cost that may be unnecessary.',
   ref:'Performance domains: Resources, Schedule · Focus area: Planning'},
  {id:'C10',caseId:'C',domain:'Business Environment',task:1,approach:'Predictive',type:'single',
   stem:'A change request will add $220,000 to the budget. The governance plan allows the project manager to approve changes up to $50,000. What should the project manager do?',
   options:['Approve the change because it is needed','Split the change into five smaller changes','Prepare an impact analysis and submit the change to the change control board, as defined in the governance plan','Ask the general contractor to absorb the cost'],answer:[2],
   explanation:'Governance defines decision rights and escalation thresholds. Changes above the project manager’s authority must go to the designated body with a clear impact analysis. Splitting the change to avoid thresholds is unethical.',
   ref:'Performance domain: Governance · Principle: Be an accountable leader'}
];
