import {ExamQuestion} from '../../exam-types';

const D='People' as const;

export const PEOPLE_QUESTIONS:ExamQuestion[]=[
  // Task 1 — Develop a common vision (7)
  {id:'P01',domain:D,task:1,approach:'Agile',type:'single',
   stem:'A newly formed agile team is starting a product that will replace three internal tools. Team members describe the goal differently, and some think it is only a technical upgrade. What should the project manager do first?',
   options:['Ask the team lead to write a vision statement and email it to everyone','Facilitate a vision workshop with the product owner, team and key users to co-create a product vision and measurable outcomes','Start the first sprint and let the vision emerge','Ask the sponsor to present the business case at the next all-hands meeting'],answer:[1],
   explanation:'A common vision is strongest when it is created together with the people who will deliver and use the product. A co-created vision builds understanding and commitment that a document alone cannot.',
   ref:'Principle: Build an empowered culture · Performance domain: Stakeholders · Focus area: Initiating'},
  {id:'P02',domain:D,task:1,approach:'Predictive',type:'single',
   stem:'During planning for a hospital expansion, the facilities team focuses on finishing on time, while clinical leaders focus on patient-flow improvements. What is the best way to establish a shared vision?',
   options:['Document both views in the charter and let the steering committee resolve differences later','Facilitate a session that links the project objectives to the strategic benefits both groups care about, and agree on success criteria that include patient-flow outcomes','Prioritize the schedule because it is easier to measure','Ask clinical leaders to prepare a separate benefits plan'],answer:[1],
   explanation:'A common vision connects outputs (an on-time building) with outcomes (better patient flow). Agreed success criteria that reflect value give both groups a shared definition of success.',
   ref:'Principle: Focus on value · Performance domain: Governance · Focus area: Initiating'},
  {id:'P03',domain:D,task:1,approach:'Hybrid',type:'multi',
   stem:'Which TWO practices help keep a team aligned with the project vision over time?',
   options:['Referring to the vision and outcome measures when prioritizing work and making decisions','Limiting discussion of the vision to the kickoff meeting','Revisiting the vision with stakeholders when significant changes occur','Allowing each team to define its own separate vision','Keeping the vision confidential to the leadership team'],answer:[0,2],
   explanation:'A vision only guides behaviour if it is used: referenced in decisions and refreshed when the context changes. Separate team visions and secrecy fragment alignment.',
   ref:'Principle: Adopt a holistic view · Performance domain: Stakeholders'},
  {id:'P04',domain:D,task:1,approach:'Agile',type:'single',
   stem:'Mid-way through a project, the organization changes its strategy from growth to cost reduction. The team asks whether the product goal still makes sense. What should the project manager do?',
   options:['Tell the team to continue as planned until the sponsor says otherwise','Work with the product owner and sponsor to reassess the product goal and roadmap against the new strategy, and share the outcome with the team','Cancel the remaining sprints','Ask the team to vote on whether to continue'],answer:[1],
   explanation:'The vision must stay aligned with organizational strategy. The project manager facilitates reassessment with the accountable decision-makers and communicates the result transparently.',
   ref:'Principle: Focus on value · Performance domain: Governance'},
  {id:'P05',domain:D,task:1,approach:'Hybrid',type:'single',
   stem:'A cross-functional team includes contractors from two vendors who see their role as “just delivering tickets.” Engagement and initiative are low. What is the best approach?',
   options:['Include vendor team members in vision and planning sessions so they understand the customer outcomes their work supports','Remind the vendors of their contractual obligations','Assign all decisions to internal staff','Offer bonuses for completing more tickets'],answer:[0],
   explanation:'People engage more when they understand purpose. Including contracted members in the vision builds a one-team culture focused on outcomes rather than activities.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'P06',domain:D,task:1,approach:'Agile',type:'single',
   stem:'Which artifact best communicates the long-term direction of a product to an agile team and its stakeholders?',
   options:['Sprint backlog','Product vision supported by a product roadmap','Burndown chart','Definition of done'],answer:[1],
   explanation:'The product vision describes the desired future state, and the roadmap shows how it is expected to evolve over time. The other artifacts serve short-term planning and quality.',
   ref:'Performance domain: Scope · Focus area: Planning'},
  {id:'P07',domain:D,task:1,approach:'Predictive',type:'single',
   stem:'A sponsor asks the project manager to “just get the system installed.” Users have not been consulted, and the benefits are unclear. What should the project manager do?',
   options:['Install the system as requested to keep the sponsor satisfied','Work with the sponsor to clarify the business need and expected benefits, and involve key users in defining success before planning in detail','Write the requirements based on the vendor’s standard configuration','Delay the project until users complain'],answer:[1],
   explanation:'Without a clear purpose and benefits, the project risks delivering an output with no value. Clarifying the need and success criteria early is essential to a shared vision.',
   ref:'Principle: Focus on value · Focus area: Initiating'},

  // Task 2 — Manage conflicts (5)
  {id:'P08',domain:D,task:2,approach:'Agile',type:'single',
   stem:'Two developers disagree strongly about the architecture for a new feature, and the disagreement is delaying the sprint. What should the project manager do first?',
   options:['Make the decision to keep the sprint moving','Ask the team to vote','Facilitate a discussion where both developers explain their options against agreed criteria, and help the team reach a decision','Escalate to the enterprise architect'],answer:[2],
   explanation:'Collaborating and problem solving—using objective criteria—is the preferred approach. It respects the team’s ownership of technical decisions and produces a decision people support.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'P09',domain:D,task:2,approach:'Predictive',type:'matching',
   stem:'Match each situation to the conflict-resolution approach that is most appropriate.',
   pairs:[{left:'An emergency safety issue requires an immediate decision',right:0},{left:'Both parties’ concerns are important and there is time to find a win-win solution',right:1},{left:'A minor issue is likely to resolve itself and emotions are high',right:2},{left:'Time is limited and both parties can accept a partial solution',right:3}],
   choices:['Forcing / directing','Collaborating / problem solving','Withdrawing / avoiding (temporarily)','Compromising / reconciling'],
   explanation:'Forcing suits emergencies; collaborating is preferred when time allows; temporary withdrawal can let emotions cool on minor issues; compromising fits time pressure when partial satisfaction is acceptable.',
   ref:'Performance domain: Resources · Focus area: Executing'},
  {id:'P10',domain:D,task:2,approach:'Hybrid',type:'single',
   stem:'A functional manager keeps pulling a key analyst off the project for operational work, causing tension with the team. What is the best action?',
   options:['Report the functional manager to the sponsor','Meet with the functional manager to understand their constraints, review the agreed resource commitment and negotiate a workable allocation','Ask the analyst to refuse operational work','Replace the analyst with a contractor'],answer:[1],
   explanation:'In a matrix environment, resource conflicts are best resolved through direct negotiation based on agreed commitments. Escalation is appropriate only if negotiation fails.',
   ref:'Performance domain: Resources · Principle: Be an accountable leader'},
  {id:'P11',domain:D,task:2,approach:'Agile',type:'single',
   stem:'During a retrospective, a tester accuses a developer of “throwing code over the wall,” and the conversation becomes personal. What should the facilitator do?',
   options:['End the retrospective','Refocus the discussion on the working process and its effects, using the team’s working agreements, and invite both to propose improvements','Ask the developer to apologize','Note the issue and raise it with HR'],answer:[1],
   explanation:'Separating people from the problem and anchoring the conversation in team agreements keeps conflict constructive and focused on improvement.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'P12',domain:D,task:2,approach:'Predictive',type:'single',
   stem:'Two senior stakeholders publicly disagree in a steering meeting about project priorities. What should the project manager do?',
   options:['Side with the more senior stakeholder','Acknowledge both views, propose a follow-up session to evaluate the options against the business case, and document the decision','Ignore the disagreement and continue the agenda','Ask the team to choose'],answer:[1],
   explanation:'Conflict between stakeholders should be handled respectfully and resolved with objective information. A follow-up session lets the parties work it through without derailing the meeting.',
   ref:'Performance domain: Stakeholders · Focus area: Executing'},

  // Task 3 — Lead the project team (7)
  {id:'P13',domain:D,task:3,approach:'Agile',type:'single',
   stem:'An agile team keeps asking the project manager to assign tasks at the daily standup. What should the project manager do?',
   options:['Assign tasks each day to keep things moving','Coach the team to self-organize by pulling work based on priority and capacity, and gradually step back from assigning work','Ask the product owner to assign tasks','Create a detailed task schedule for the sprint'],answer:[1],
   explanation:'Agile teams self-organize. A servant leader coaches the team toward autonomy rather than directing daily work.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'P14',domain:D,task:3,approach:'Predictive',type:'matching',
   stem:'Match each team behaviour to the stage of team development (Tuckman model) it most likely represents.',
   pairs:[{left:'Members are polite, unsure of roles and look to the leader for direction',right:0},{left:'Members challenge each other’s ideas and compete for influence',right:1},{left:'The team agrees on working norms and begins to trust one another',right:2},{left:'The team works interdependently and resolves issues on its own',right:3}],
   choices:['Forming','Storming','Norming','Performing'],
   explanation:'Forming is orientation, storming is conflict, norming is agreement on ways of working, and performing is effective interdependence. Leadership style should adapt to each stage.',
   ref:'Performance domain: Resources · Principle: Be an accountable leader'},
  {id:'P15',domain:D,task:3,approach:'Hybrid',type:'single',
   stem:'A high-performing team member’s work quality has suddenly declined, and they seem withdrawn. What should the project manager do first?',
   options:['Document the performance issue for HR','Meet privately with the team member to understand what is happening and how to support them','Reassign their work to others','Raise the issue at the team meeting'],answer:[1],
   explanation:'Emotional intelligence starts with understanding. A private, supportive conversation identifies the cause before any corrective action is considered.',
   ref:'Principle: Be an accountable leader · Performance domain: Resources'},
  {id:'P16',domain:D,task:3,approach:'Agile',type:'single',
   stem:'Developers say they are interrupted constantly by stakeholders asking for “quick favours,” which hurts their focus. What should the project manager do?',
   options:['Ask developers to say no to all requests','Shield the team by routing requests through the product owner and backlog, and make the impact of interruptions visible to stakeholders','Schedule the favours into the next sprint automatically','Allow the requests because stakeholders are important'],answer:[1],
   explanation:'Servant leaders protect the team’s focus and channel requests through the right mechanism—the product owner and the backlog—so that work is prioritized by value.',
   ref:'Performance domain: Resources · Focus area: Executing'},
  {id:'P17',domain:D,task:3,approach:'Hybrid',type:'multi',
   stem:'A project team is newly distributed across three time zones. Which TWO actions will most help the project manager lead the team effectively?',
   options:['Create working agreements covering core overlap hours, response times and communication tools','Require all meetings to be held in the head office’s time zone','Use collaborative tools and rotate meeting times so that no location is always disadvantaged','Replace all synchronous meetings with email','Monitor team members’ online status to confirm they are working'],answer:[0,2],
   explanation:'Clear agreements and fair, collaborative practices build trust and effectiveness in virtual teams. Surveillance and one-sided meeting times undermine engagement.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'P18',domain:D,task:3,approach:'Predictive',type:'single',
   stem:'A team member lacks the skills needed for a new reporting tool, which is causing delays. What is the best approach?',
   options:['Replace the team member','Arrange targeted training or mentoring, and adjust the plan to allow for the learning curve','Do the work yourself','Remove the reporting tool from scope'],answer:[1],
   explanation:'When a performance gap is caused by a lack of skills, training and mentoring address the root cause and build team capability.',
   ref:'Performance domain: Resources · Focus area: Executing'},
  {id:'P19',domain:D,task:3,approach:'Agile',type:'single',
   stem:'The team has delivered three difficult releases on time. Morale is high, but several members say their contributions are not visible to leadership. What should the project manager do?',
   options:['Nothing; delivery is its own reward','Recognize individual and team contributions publicly—for example in reviews and leadership updates—and ask members how they prefer to be recognized','Give the team lead a performance bonus','Assign the team more work to show confidence'],answer:[1],
   explanation:'Recognition reinforces desired behaviours and motivation. Asking people how they prefer to be recognized respects individual differences.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},

  // Task 4 — Engage stakeholders (7)
  {id:'P20',domain:D,task:4,approach:'Predictive',type:'hotspot',graphic:'stakeholder-grid',
   stem:'The grid shows four stakeholder groups plotted by power and interest. Click the stakeholder who should be engaged with a “keep satisfied” strategy.',
   options:['Regional VP','Union representative','Call-centre agents','Vendor account manager'],answer:[0],
   explanation:'The Regional VP has high power but low interest, so they should be kept satisfied. The union representative (high/high) is managed closely, agents (low power, high interest) are kept informed, and the vendor account manager (low/low) is monitored.',
   ref:'Performance domain: Stakeholders · Focus area: Planning'},
  {id:'P21',domain:D,task:4,approach:'Hybrid',type:'single',
   stem:'Halfway through a project, a new department is affected by a scope change. The department head was never identified as a stakeholder. What should the project manager do first?',
   options:['Continue as planned and inform the department at go-live','Add the department head to the stakeholder register, analyze their interests and influence, and plan engagement','Ask the sponsor to manage the department','Reverse the scope change'],answer:[1],
   explanation:'Stakeholder identification is continuous. New stakeholders must be analyzed and engaged as soon as they are identified.',
   ref:'Performance domain: Stakeholders · Focus area: Executing'},
  {id:'P22',domain:D,task:4,approach:'Agile',type:'single',
   stem:'End users have stopped attending sprint reviews, and recent features have had low adoption. What is the best action?',
   options:['Stop holding sprint reviews','Find out why users stopped attending, and adjust timing, format or channels—such as short demos in their workplace—to re-engage them','Ask the sponsor to require attendance','Increase the number of features to compensate'],answer:[1],
   explanation:'Engagement approaches should be tailored. Understanding why users disengaged allows the team to restore the feedback loop that drives adoption.',
   ref:'Principle: Focus on value · Performance domain: Stakeholders'},
  {id:'P23',domain:D,task:4,approach:'Predictive',type:'single',
   stem:'A stakeholder engagement assessment matrix shows that a key department head is currently “resistant” but needs to be “supportive.” What should the project manager do?',
   options:['Escalate to the sponsor immediately','Meet with the department head to understand their concerns and develop actions that address them','Exclude the department head from project communications','Document the gap and monitor it'],answer:[1],
   explanation:'Closing an engagement gap starts with understanding the stakeholder’s concerns, then taking targeted actions to move them toward the desired level.',
   ref:'Performance domain: Stakeholders · Focus area: Executing'},
  {id:'P24',domain:D,task:4,approach:'Hybrid',type:'multi',
   stem:'Which TWO sources are most useful when identifying stakeholders at the start of a project?',
   options:['The project charter and business case','The team’s sprint velocity','Interviews and expert judgment from people familiar with the affected organization','The quality control checklist','The final lessons-learned report from closure'],answer:[0,2],
   explanation:'The charter and business case identify key parties and impacts, and interviews with experienced people reveal less obvious stakeholders. The other items are not identification inputs.',
   ref:'Performance domain: Stakeholders · Focus area: Initiating'},
  {id:'P25',domain:D,task:4,approach:'Agile',type:'single',
   stem:'An influential operations manager says agile is “chaos” and refuses to give feedback until the product is complete. What should the project manager do?',
   options:['Remove the manager from the stakeholder list','Show working increments in a short, focused session tied to the manager’s goals, and explain how early feedback reduces risk','Switch the project to a predictive approach','Ask HR to intervene'],answer:[1],
   explanation:'Engagement improves when stakeholders see value that matters to them. Demonstrating working results and explaining the benefits of early feedback builds trust.',
   ref:'Performance domain: Stakeholders · Principle: Focus on value'},
  {id:'P26',domain:D,task:4,approach:'Hybrid',type:'single',
   stem:'Indigenous community leaders near a proposed transmission line want to be consulted before routing decisions are made. What should the project manager do?',
   options:['Consult them after the route is finalized','Engage the community early, respectfully and in line with legal and organizational consultation requirements, and incorporate their input into decision-making','Ask the legal team to manage all contact','Proceed with the route the engineers prefer'],answer:[1],
   explanation:'Meaningful, early, respectful engagement is required both ethically and, often, legally. Input should influence decisions, not be collected after the fact.',
   ref:'Principle: Integrate sustainability · Performance domain: Stakeholders'},

  // Task 5 — Align stakeholder expectations (6)
  {id:'P27',domain:D,task:5,approach:'Agile',type:'single',
   stem:'The sponsor expects a fixed set of features by a fixed date, while the team is using an adaptive approach with evolving scope. How should the project manager align expectations?',
   options:['Commit to all features and the date','Explain how a fixed date with flexible scope works, agree on the minimum valuable features, and show progress through regular reviews and release forecasts','Switch to a predictive approach','Avoid discussing scope until the end'],answer:[1],
   explanation:'Aligning expectations means making trade-offs explicit. A fixed date with prioritized, flexible scope—supported by transparency—is a common adaptive agreement.',
   ref:'Principle: Focus on value · Performance domain: Stakeholders'},
  {id:'P28',domain:D,task:5,approach:'Predictive',type:'single',
   stem:'During requirements sign-off, two business units define “on-time delivery” differently. What is the best action?',
   options:['Use the definition from the larger business unit','Facilitate agreement on a single measurable definition and record it in the requirements and success criteria','Include both definitions','Leave the term undefined'],answer:[1],
   explanation:'Shared, measurable definitions prevent future disputes about whether the project met expectations.',
   ref:'Performance domain: Scope · Focus area: Planning'},
  {id:'P29',domain:D,task:5,approach:'Hybrid',type:'single',
   stem:'Stakeholders have different risk appetites: finance wants minimal risk, and marketing wants to launch quickly. What should the project manager do?',
   options:['Follow marketing because revenue matters most','Facilitate a discussion to agree on risk thresholds and decision criteria, and document them for governance','Follow finance because it controls the budget','Avoid the topic to prevent conflict'],answer:[1],
   explanation:'Agreed risk thresholds turn conflicting preferences into a shared basis for decisions.',
   ref:'Performance domains: Risk, Stakeholders · Focus area: Planning'},
  {id:'P30',domain:D,task:5,approach:'Agile',type:'single',
   stem:'After a sprint review, a stakeholder says the feature “is not what we asked for,” although it meets the acceptance criteria written by the product owner. What should the project manager recommend?',
   options:['Reject the stakeholder’s feedback because the criteria were met','Use the feedback to refine the backlog with the product owner, and involve the stakeholder earlier in refining future acceptance criteria','Rebuild the feature immediately in the current sprint','Ask the stakeholder to submit a formal change request'],answer:[1],
   explanation:'Sprint reviews exist to inspect and adapt. The feedback should inform the backlog, and earlier stakeholder involvement aligns expectations before work starts.',
   ref:'Principle: Focus on value · Performance domain: Scope'},
  {id:'P31',domain:D,task:5,approach:'Predictive',type:'single',
   stem:'A sponsor expects the project to deliver a 20% productivity gain, but the business case shows 8%. What should the project manager do?',
   options:['Say nothing and hope the gain is higher','Review the business case assumptions with the sponsor, clarify realistic benefits and agree on how benefits will be measured','Increase the scope to reach 20%','Change the business case to show 20%'],answer:[1],
   explanation:'Misaligned benefit expectations must be addressed early and honestly. The project manager should never alter the business case to match wishes.',
   ref:'Principle: Be an accountable leader · Performance domain: Governance'},
  {id:'P32',domain:D,task:5,approach:'Hybrid',type:'multi',
   stem:'Which TWO actions best help align stakeholder expectations at the start of a hybrid project?',
   options:['Agree on the delivery approach, cadence of reviews and how changes will be handled','Promise each stakeholder their top priority','Define success criteria and acceptance processes with key stakeholders','Delay all communication until the plan is final','Ask the team to choose the success criteria'],answer:[0,2],
   explanation:'Shared agreement on how the work will be delivered, reviewed and changed—and on what success means—is the foundation of aligned expectations.',
   ref:'Performance domains: Governance, Stakeholders · Focus area: Initiating'},

  // Task 6 — Manage stakeholder expectations (6)
  {id:'P33',domain:D,task:6,approach:'Predictive',type:'single',
   stem:'A critical vendor delivery is delayed, so a milestone will be missed by two weeks. The sponsor does not yet know. What should the project manager do?',
   options:['Wait to see whether the team can recover the time','Inform the sponsor promptly with the facts, the impact and the recovery options being evaluated','Ask the vendor to inform the sponsor','Report the milestone as “at risk” without details'],answer:[1],
   explanation:'Transparency builds trust. Bad news should be communicated early, together with impact analysis and options.',
   ref:'Principle: Be an accountable leader · Performance domain: Stakeholders'},
  {id:'P34',domain:D,task:6,approach:'Agile',type:'single',
   stem:'A stakeholder frequently asks developers directly for status and small changes, which disrupts the sprint. What should the project manager do?',
   options:['Tell the stakeholder to stop contacting the team','Invite the stakeholder to sprint reviews, share the information radiator, and route requests through the product owner','Give the stakeholder daily status emails','Ask developers to make the changes quickly'],answer:[1],
   explanation:'Providing transparent, regular access to progress—and a clear path for requests—meets the stakeholder’s needs while protecting the team.',
   ref:'Performance domain: Stakeholders · Focus area: Executing'},
  {id:'P35',domain:D,task:6,approach:'Hybrid',type:'single',
   stem:'A key user group is unhappy that a feature was deferred to a later release. What is the best response?',
   options:['Reinstate the feature to keep them happy','Explain the prioritization rationale, show when the feature is planned, and invite their input on interim workarounds','Ignore the complaint because the product owner decided','Escalate to the sponsor'],answer:[1],
   explanation:'Managing expectations means explaining decisions transparently and showing stakeholders that their needs remain on the roadmap.',
   ref:'Performance domain: Stakeholders · Principle: Focus on value'},
  {id:'P36',domain:D,task:6,approach:'Predictive',type:'single',
   stem:'A stakeholder’s satisfaction survey score has dropped sharply. What should the project manager do first?',
   options:['Change the communication plan','Meet with the stakeholder to understand the reasons for the drop','Escalate to the sponsor','Increase the frequency of status reports'],answer:[1],
   explanation:'Understand before acting. A direct conversation reveals the cause, so that the response addresses the real issue.',
   ref:'Performance domain: Stakeholders · Focus area: Monitoring and Controlling'},
  {id:'P37',domain:D,task:6,approach:'Agile',type:'single',
   stem:'Executives ask for a guaranteed completion date for a large agile initiative with significant uncertainty. What should the project manager provide?',
   options:['A single date based on the best-case velocity','A probabilistic forecast or date range based on historical velocity, with the assumptions explained and regular updates','No date, because agile projects do not have dates','The date the executives prefer'],answer:[1],
   explanation:'Range-based or probabilistic forecasts communicate uncertainty honestly, and regular updates keep expectations current.',
   ref:'Performance domain: Schedule · Principle: Be an accountable leader'},
  {id:'P38',domain:D,task:6,approach:'Hybrid',type:'multi',
   stem:'A project is likely to exceed its budget by 6%. Which TWO actions best manage stakeholder expectations?',
   options:['Share the forecast early with the cause and the options to recover or re-baseline','Wait until the variance is confirmed at month-end close','Present the options and their trade-offs, and agree on the decision path with the sponsor','Reduce quality to stay within budget without telling anyone','Report only the positive indicators'],answer:[0,2],
   explanation:'Early, transparent communication with options and an agreed decision path protects trust and supports good governance.',
   ref:'Performance domains: Finance, Stakeholders'},

  // Task 7 — Help ensure knowledge transfer (6)
  {id:'P39',domain:D,task:7,approach:'Predictive',type:'single',
   stem:'When is the best time to capture lessons learned on a predictive project?',
   options:['Only at project closure','Throughout the project, at key milestones and phase ends, with a final review at closure','Only when something goes wrong','After the sponsor requests it'],answer:[1],
   explanation:'Capturing lessons learned throughout the project allows improvements to be applied during the project and preserves details that would otherwise be forgotten.',
   ref:'Focus areas: Executing, Closing · Principle: Embed quality'},
  {id:'P40',domain:D,task:7,approach:'Agile',type:'single',
   stem:'Which agile practice best supports ongoing knowledge transfer within a team?',
   options:['Detailed handover documents at the end of each sprint','Pair or mob programming and swarming on complex items','Assigning specialists to their own components only','Annual training courses'],answer:[1],
   explanation:'Working together on the same work spreads knowledge in real time and reduces single points of failure.',
   ref:'Performance domain: Resources · Principle: Build an empowered culture'},
  {id:'P41',domain:D,task:7,approach:'Hybrid',type:'single',
   stem:'An organization repeats the same procurement mistakes on every project. What should the project manager recommend?',
   options:['Include procurement lessons in the organizational lessons-learned repository, and review the repository at the start of each new project','Ask procurement staff to be more careful','Avoid procurement on future projects','Create a new procurement team'],answer:[0],
   explanation:'Lessons learned add value only if they are stored where others can find them and are actively reviewed when planning new work.',
   ref:'Principle: Embed quality · Focus area: Closing'},
  {id:'P42',domain:D,task:7,approach:'Predictive',type:'multi',
   stem:'A system is being handed over to an operations support team. Which TWO actions best ensure effective knowledge transfer?',
   options:['Joint working sessions in which operations staff perform support tasks with the project team before go-live','Emailing the technical documentation on the last day','A runbook validated by the operations team, with contact points for the warranty period','Asking operations to learn from production incidents','Removing access to the project team immediately after go-live'],answer:[0,2],
   explanation:'Hands-on practice and validated documentation, supported during a transition period, make knowledge transfer effective.',
   ref:'Focus area: Closing · Performance domain: Resources'},
  {id:'P43',domain:D,task:7,approach:'Agile',type:'single',
   stem:'A team uses an AI assistant to summarize retrospectives and store improvement actions in a shared wiki. What should the project manager make sure of?',
   options:['That the AI summaries are published without review to save time','That the team reviews the summaries for accuracy, sensitive information is handled according to policy, and actions have owners','That only the Scrum Master can read the wiki','That the AI tool replaces the retrospective meeting'],answer:[1],
   explanation:'AI can support knowledge management, but humans remain accountable for accuracy, confidentiality and follow-through.',
   ref:'Principle: Be an accountable leader · AI in project management'},
  {id:'P44',domain:D,task:7,approach:'Hybrid',type:'single',
   stem:'A subject-matter expert holds critical knowledge but says they are too busy to document it. What is the best approach?',
   options:['Escalate to their manager','Use short, structured interviews or recorded walkthroughs led by another team member, and have the expert validate the result','Accept the risk','Ask the expert to work weekends'],answer:[1],
   explanation:'Lowering the effort required from busy experts—through interviews or recordings—makes knowledge capture practical, while validation keeps it accurate.',
   ref:'Performance domain: Resources · Focus area: Executing'},

  // Task 8 — Plan and manage communication (6)
  {id:'P45',domain:D,task:8,approach:'Predictive',type:'dropdown',
   stem:'A project team grows from 6 to 10 members (including the project manager). How many additional communication channels does this create?',
   options:['4','15','30','45'],answer:[2],
   explanation:'Channels = n(n – 1) ÷ 2. For 6 people: 15. For 10 people: 45. The increase is 45 – 15 = 30.',
   ref:'Performance domain: Stakeholders · Focus area: Planning'},
  {id:'P46',domain:D,task:8,approach:'Hybrid',type:'single',
   stem:'Which communication method is most appropriate for discussing a sensitive scope reduction with a key client?',
   options:['Email with the updated scope attached','A face-to-face or video meeting, followed by written confirmation','A post on the project collaboration site','The monthly newsletter'],answer:[1],
   explanation:'Interactive communication suits sensitive or complex topics because it allows immediate clarification. Written follow-up records the agreement.',
   ref:'Performance domain: Stakeholders · Focus area: Executing'},
  {id:'P47',domain:D,task:8,approach:'Agile',type:'single',
   stem:'An agile team wants stakeholders to be able to see progress at any time without extra reports. What should the team use?',
   options:['Weekly status emails','Information radiators, such as a visible task board and burnup chart','A monthly executive presentation','A detailed Gantt chart'],answer:[1],
   explanation:'Information radiators make progress transparent and self-serve, reducing reporting overhead.',
   ref:'Performance domain: Stakeholders · Focus area: Monitoring and Controlling'},
  {id:'P48',domain:D,task:8,approach:'Predictive',type:'single',
   stem:'A stakeholder complains that they never receive project updates, although they are listed in the communications plan. What should the project manager do first?',
   options:['Resend all previous updates','Verify the distribution and the stakeholder’s preferred channel, then correct the communication plan and its execution','Add the stakeholder to more meetings','Ask the stakeholder to check their spam folder'],answer:[1],
   explanation:'Investigate the cause—wrong channel, wrong address or a process gap—and fix it in the plan so that it does not recur.',
   ref:'Performance domain: Stakeholders · Focus area: Monitoring and Controlling'},
  {id:'P49',domain:D,task:8,approach:'Hybrid',type:'single',
   stem:'The project manager wants to use an AI tool to draft weekly status reports from project data. What is the most appropriate approach?',
   options:['Send AI-generated reports directly to stakeholders','Use the AI drafts as a starting point, verify facts and figures, check tone and sensitivity, and remain accountable for the final message','Avoid AI because it is never accurate','Let the team decide whether to review reports'],answer:[1],
   explanation:'AI can improve efficiency, but the project manager remains accountable for accurate, appropriate communication.',
   ref:'Principle: Be an accountable leader · AI in project management'},
  {id:'P50',domain:D,task:8,approach:'Agile',type:'multi',
   stem:'Which TWO factors should most influence how the project manager plans communications for a multicultural, distributed team?',
   options:['Cultural differences in communication styles and language preferences','The project manager’s personal preference for email','Time-zone overlap and access to collaboration technology','Using the same message for every audience','Limiting communication to reduce noise'],answer:[0,2],
   explanation:'Effective communication planning considers the audience’s culture, language and practical constraints such as time zones and technology.',
   ref:'Performance domain: Stakeholders · Focus area: Planning'}
];
