import {ExamQuestion} from '../../exam-types';

const D='Business Environment' as const;

export const BUSINESS_ENVIRONMENT_QUESTIONS:ExamQuestion[]=[
  // Task 1 — Governance (6)
  {id:'S4-B01',domain:D,task:1,approach:'Predictive',type:'single',
   stem:'Who typically issues the project charter and provides the project manager with authority?',
   options:['The project team','The sponsor or another authorized person outside the project','The vendor','The project manager personally'],answer:[1],
   explanation:'The charter is issued by the sponsor (or initiator) at a level appropriate to fund the project and assign authority.',
   ref:'Performance domain: Governance · Focus area: Initiating'},
  {id:'S4-B02',domain:D,task:1,approach:'Hybrid',type:'single',
   stem:'A program has many interdependent projects, and decisions in one project often affect others. What governance mechanism helps?',
   options:['Letting each project decide alone','A program-level governance board that coordinates cross-project decisions, dependencies and priorities','Weekly all-hands meetings for every team member','Removing dependencies by cancelling projects'],answer:[1],
   explanation:'Program governance coordinates decisions across related projects to achieve combined benefits.',
   ref:'Performance domain: Governance · Principle: Adopt a holistic view'},
  {id:'S4-B03',domain:D,task:1,approach:'Agile',type:'single',
   stem:'An agile team asks who can approve release to production. The organization has no defined policy. What should the project manager do?',
   options:['Let any developer release','Work with the sponsor, product owner and IT operations to define release decision rights and criteria, and document them','Release only once a year','Ask the vendor to decide'],answer:[1],
   explanation:'Clear decision rights for releases are part of governance and reduce both delays and risk.',
   ref:'Performance domain: Governance · Focus area: Planning'},
  {id:'S4-B04',domain:D,task:1,approach:'Predictive',type:'single',
   stem:'A phase-gate review is scheduled, but the project manager knows the phase deliverables are incomplete. What should the project manager do?',
   options:['Present the deliverables as complete','Present the actual status, the reasons and a recommendation, so that the gate reviewers can decide whether to proceed, hold or change course','Cancel the review','Ask the team to rush and skip testing'],answer:[1],
   explanation:'Gate reviews depend on honest information so that decision-makers can exercise governance.',
   ref:'Principle: Be an accountable leader · Performance domain: Governance'},
  {id:'S4-B05',domain:D,task:1,approach:'Hybrid',type:'single',
   stem:'The project manager wants to know which organizational policies, templates and historical information apply to the project. What are these called?',
   options:['Enterprise environmental factors','Organizational process assets','Work performance data','Deliverables'],answer:[1],
   explanation:'Organizational process assets include policies, procedures, templates and knowledge repositories. Enterprise environmental factors are conditions outside the team’s control.',
   ref:'Performance domain: Governance · Focus area: Initiating'},
  {id:'S4-B06',domain:D,task:1,approach:'Agile',type:'multi',
   stem:'Which TWO practices help leaders govern agile projects effectively?',
   options:['Reviewing working increments and outcome measures at a regular cadence','Approving every story individually','Setting clear guardrails such as budget, risk and compliance limits','Requiring detailed task reports daily','Changing team members every sprint'],answer:[0,2],
   explanation:'Effective agile governance relies on evidence from increments and clear guardrails, not micromanagement.',
   ref:'Performance domain: Governance · Principle: Build an empowered culture'},

  // Task 2 — Compliance (3)
  {id:'S4-B07',domain:D,task:2,approach:'Predictive',type:'single',
   stem:'A project manager discovers that a team member has been sharing confidential bid information with a friend at a competing company. What should the project manager do?',
   options:['Ignore it to avoid conflict','Stop the disclosure, report it according to the organization’s policies and the professional code of ethics, and protect the remaining information','Confront the competitor','Wait until the bid is awarded'],answer:[1],
   explanation:'Confidentiality breaches must be addressed and reported. Professional ethics require action, not silence.',
   ref:'Principle: Be an accountable leader · Ethics'},
  {id:'S4-B08',domain:D,task:2,approach:'Hybrid',type:'single',
   stem:'A project in a regulated industry must prove that every change to its software was reviewed and approved. How can the team meet this requirement efficiently?',
   options:['Write a memo at the end of the project','Use tooling that records reviews and approvals automatically—such as required peer reviews in the code repository linked to work items','Skip reviews for small changes','Rely on developers’ memories'],answer:[1],
   explanation:'Automated, traceable controls provide reliable compliance evidence with little overhead.',
   ref:'Performance domain: Governance · Principle: Embed quality'},
  {id:'S4-B09',domain:D,task:2,approach:'Predictive',type:'multi',
   stem:'Which TWO actions help a project stay compliant when regulations apply to its deliverables?',
   options:['Identifying applicable regulations early and recording them as requirements with owners','Assuming the vendor handles all compliance','Planning compliance checks and audits into the schedule','Ignoring regulations until an inspection','Keeping compliance knowledge with one person only'],answer:[0,2],
   explanation:'Compliance needs early identification, clear ownership and planned verification.',
   ref:'Performance domain: Governance · Focus area: Planning'},

  // Task 3 — Changes (6)
  {id:'S4-B10',domain:D,task:3,approach:'Predictive',type:'single',
   stem:'A team member notices that a small design improvement would make the product easier to maintain. It is not in the approved scope. What should the team member do?',
   options:['Implement it quietly','Raise it with the project manager so that it can be assessed and, if worthwhile, approved through change control','Ignore the idea','Ask the customer directly to approve it'],answer:[1],
   explanation:'Even beneficial changes follow change control to protect baselines and avoid unapproved scope.',
   ref:'Performance domain: Governance · Performance domain: Scope'},
  {id:'S4-B11',domain:D,task:3,approach:'Hybrid',type:'single',
   stem:'A change request was approved, but the team implemented it differently from what was approved. What should the project manager do?',
   options:['Accept the difference','Verify the implementation against the approved change, correct the deviation or submit a new change request, and update the records','Close the change request','Blame the change control board'],answer:[1],
   explanation:'Approved changes must be implemented as approved and verified. Deviations need correction or approval.',
   ref:'Performance domain: Governance · Focus area: Monitoring and Controlling'},
  {id:'S4-B12',domain:D,task:3,approach:'Agile',type:'single',
   stem:'In an agile project, the customer wants to change the priority of several backlog items. Who decides?',
   options:['The developers','The product owner, considering stakeholder input and value','The Scrum Master','The change control board for every reorder'],answer:[1],
   explanation:'Backlog ordering is the product owner’s responsibility. It is how agile projects absorb routine change.',
   ref:'Performance domain: Scope · Focus area: Executing'},
  {id:'S4-B13',domain:D,task:3,approach:'Predictive',type:'single',
   stem:'A change control board approves a change that adds three weeks to the schedule. What should the project manager do with the schedule baseline?',
   options:['Leave it unchanged','Update the schedule baseline to reflect the approved change, and communicate the new dates','Hide the delay','Start a new project'],answer:[1],
   explanation:'Approved changes are reflected in updated baselines, so that performance is measured against the current approved plan.',
   ref:'Performance domain: Schedule · Focus area: Monitoring and Controlling'},
  {id:'S4-B14',domain:D,task:3,approach:'Hybrid',type:'single',
   stem:'The change control board meets monthly, but some low-risk changes are urgent. What would improve the process?',
   options:['Bypass the board for anything urgent','Tailor the process: define categories of low-risk “standard” changes with pre-approved handling, and an expedited path for urgent changes','Hold board meetings daily','Stop making changes'],answer:[1],
   explanation:'Tailoring change control by risk level keeps control proportionate and avoids unnecessary delays.',
   ref:'Principle: Adopt a holistic view · Performance domain: Governance'},
  {id:'S4-B15',domain:D,task:3,approach:'Predictive',type:'multi',
   stem:'Which TWO pieces of information should the project manager provide to the change control board for a significant change request?',
   options:['The impact on objectives, including cost, schedule, scope, quality and risk','The requester’s personal history','Options considered and a recommendation','A list of all previous meetings','The project manager’s vacation plans'],answer:[0,2],
   explanation:'Decision-makers need impacts, options and a recommendation to make informed choices.',
   ref:'Performance domain: Governance · Focus area: Monitoring and Controlling'},

  // Task 4 — Impediments and issues (5)
  {id:'S4-B16',domain:D,task:4,approach:'Agile',type:'single',
   stem:'An impediment has been raised at three daily scrums, but no one has taken action. What should the Scrum Master or project manager do?',
   options:['Keep noting it','Take ownership of removing it—or assign a clear owner—and follow up until it is resolved','Remove it from the board','Wait for the retrospective'],answer:[1],
   explanation:'Impediments need clear ownership and follow-through, not just repeated mention.',
   ref:'Focus area: Executing · Principle: Be an accountable leader'},
  {id:'S4-B17',domain:D,task:4,approach:'Predictive',type:'single',
   stem:'A key decision is stuck because two departments each believe the other owns it. What should the project manager do?',
   options:['Make the decision personally','Escalate to the sponsor or governance body to clarify ownership and obtain a decision, using the RACI to show the gap','Wait for the departments to agree','Avoid the decision'],answer:[1],
   explanation:'Unclear ownership is resolved by the authority that can assign decision rights.',
   ref:'Performance domain: Governance · Focus area: Executing'},
  {id:'S4-B18',domain:D,task:4,approach:'Hybrid',type:'single',
   stem:'A recurring technical issue affects the team every week. The team has been using a workaround that costs several hours each time. What should the project manager do?',
   options:['Continue with the workaround','Quantify the cumulative cost, raise it with the right owner, and plan a permanent fix','Ask the team to work faster','Stop reporting it'],answer:[1],
   explanation:'Recurring issues should be fixed at the root. Showing their cumulative cost helps prioritize the fix.',
   ref:'Principle: Embed quality · Focus area: Monitoring and Controlling'},
  {id:'S4-B19',domain:D,task:4,approach:'Agile',type:'single',
   stem:'An external team the project depends on has missed two agreed delivery dates. What is the best approach?',
   options:['Ignore the other team','Meet with the other team to understand its constraints, agree on a realistic date, and escalate through governance if the dependency continues to put goals at risk','Build the dependency yourselves without discussion','Complain to the other team’s staff'],answer:[1],
   explanation:'Dependencies are managed through collaboration first, then escalation if needed.',
   ref:'Principle: Adopt a holistic view · Focus area: Executing'},
  {id:'S4-B20',domain:D,task:4,approach:'Predictive',type:'multi',
   stem:'Which TWO practices help ensure that issues are resolved in time?',
   options:['Assigning an owner and a due date to each issue','Recording issues only in personal notes','Reviewing open issues regularly and escalating overdue ones','Closing issues without resolution','Waiting until project closure'],answer:[0,2],
   explanation:'Ownership, due dates and regular review with escalation keep issues moving.',
   ref:'Focus area: Monitoring and Controlling · Performance domain: Governance'},

  // Task 5 — Risk (6)
  {id:'S4-B21',domain:D,task:5,approach:'Predictive',type:'single',
   stem:'A project team is identifying risks. Which technique gathers anonymous input from experts in several rounds until they reach consensus?',
   options:['Delphi technique','Brainstorming','Pareto analysis','Critical path method'],answer:[0],
   explanation:'The Delphi technique reduces bias and dominance by collecting anonymous expert opinions in rounds.',
   ref:'Performance domain: Risk · Focus area: Planning'},
  {id:'S4-B22',domain:D,task:5,approach:'Hybrid',type:'single',
   stem:'How should a risk be described so that it is clear and actionable?',
   options:['“Budget risk”','Using a cause–event–effect format—for example, “Because the vendor is new, it may deliver late, which would delay testing by two weeks”','“Something might go wrong”','Only with a probability number'],answer:[1],
   explanation:'Structured risk statements clarify causes and effects, which helps in choosing responses.',
   ref:'Performance domain: Risk · Focus area: Planning'},
  {id:'S4-B23',domain:D,task:5,approach:'Predictive',type:'single',
   stem:'After all planned responses, some risk remains. What is this remaining risk called, and what should be done with it?',
   options:['Secondary risk; ignore it','Residual risk; document it and make sure it is within the acceptable threshold, with contingency where appropriate','Primary risk; transfer it','Overall risk; delete it'],answer:[1],
   explanation:'Residual risk is the risk left after responses. It must be acceptable and monitored.',
   ref:'Performance domain: Risk · Focus area: Monitoring and Controlling'},
  {id:'S4-B24',domain:D,task:5,approach:'Agile',type:'single',
   stem:'How can an agile team make risks visible to stakeholders without a heavy risk register?',
   options:['Hide risks to avoid concern','Use a visible risk board or burndown, include risk items in the backlog, and discuss key risks at reviews','Report risks only at the end','Let the product owner track risks privately'],answer:[1],
   explanation:'Agile teams make risks transparent through visual tools and regular conversations.',
   ref:'Performance domain: Risk · Focus area: Monitoring and Controlling'},
  {id:'S4-B25',domain:D,task:5,approach:'Predictive',type:'single',
   stem:'Which document describes how risk management will be performed—including methods, roles, timing, categories and probability-and-impact definitions?',
   options:['Risk register','Risk management plan','Risk report','Issue log'],answer:[1],
   explanation:'The risk management plan defines the approach; the register records individual risks.',
   ref:'Performance domain: Risk · Focus area: Planning'},
  {id:'S4-B26',domain:D,task:5,approach:'Hybrid',type:'multi',
   stem:'Which TWO actions are part of monitoring risks during execution?',
   options:['Watching for risk triggers and implementing responses when they occur','Identifying risks only at the start','Identifying new risks and reassessing existing ones','Removing the risk register after planning','Ignoring risks with low probability forever'],answer:[0,2],
   explanation:'Risk monitoring tracks triggers, implements responses and keeps the risk picture current.',
   ref:'Performance domain: Risk · Focus area: Monitoring and Controlling'},

  // Task 6 — Continuous improvement (4)
  {id:'S4-B27',domain:D,task:6,approach:'Agile',type:'single',
   stem:'A retrospective format asks the team what it should start doing, stop doing and continue doing. What is the main purpose?',
   options:['To assign blame','To identify concrete changes to the team’s way of working','To plan the next release','To evaluate individuals'],answer:[1],
   explanation:'“Start, stop, continue” is a simple structure for identifying improvements.',
   ref:'Principle: Build an empowered culture · Focus area: Monitoring and Controlling'},
  {id:'S4-B28',domain:D,task:6,approach:'Predictive',type:'single',
   stem:'The organization wants to understand why approvals take so long across all projects. Which technique maps each step, handoff and wait time?',
   options:['Process mapping or value stream mapping','A RACI chart','A burnup chart','A tornado diagram'],answer:[0],
   explanation:'Mapping the process makes delays and waste visible so that improvements can be targeted.',
   ref:'Principle: Embed quality · Focus area: Monitoring and Controlling'},
  {id:'S4-B29',domain:D,task:6,approach:'Hybrid',type:'single',
   stem:'An improvement was implemented to reduce defects. How should the team know whether it worked?',
   options:['Assume it worked','Compare defect measures before and after the change, and keep or adjust the change based on the evidence','Ask the sponsor','Stop measuring defects'],answer:[1],
   explanation:'Measuring results confirms whether an improvement achieved its goal (the “check” step of PDCA).',
   ref:'Principle: Embed quality · Focus area: Monitoring and Controlling'},
  {id:'S4-B30',domain:D,task:6,approach:'Agile',type:'multi',
   stem:'Which TWO conditions help continuous improvement thrive in a team?',
   options:['Psychological safety to raise problems without blame','Punishing mistakes','Time and capacity reserved for improvement work','Discouraging experiments','Keeping metrics hidden'],answer:[0,2],
   explanation:'Safety and protected capacity let teams surface problems and act on them.',
   ref:'Principle: Build an empowered culture · Principle: Embed quality'},

  // Task 7 — Organizational change (4)
  {id:'S4-B31',domain:D,task:7,approach:'Predictive',type:'single',
   stem:'A new system changes how 400 employees work. Who should lead communication about why the change is happening?',
   options:['The vendor','Senior leaders and the sponsor, supported by direct managers who explain what it means for their teams','The newest team member','No one; employees will understand'],answer:[1],
   explanation:'People look to senior leaders for the reasons behind change and to their own managers for what it means for them.',
   ref:'Performance domain: Stakeholders · Principle: Be an accountable leader'},
  {id:'S4-B32',domain:D,task:7,approach:'Hybrid',type:'single',
   stem:'Different departments will be affected by a new process in different ways. What should the project manager do before planning change activities?',
   options:['Use one communication for everyone','Conduct a change impact assessment for each group to understand how their work, skills and tools will change','Train everyone the same way','Assume impacts are small'],answer:[1],
   explanation:'Impact assessments allow change activities to be tailored to each group’s needs.',
   ref:'Performance domain: Stakeholders · Focus area: Planning'},
  {id:'S4-B33',domain:D,task:7,approach:'Agile',type:'single',
   stem:'Users are given frequent new releases and feel overwhelmed by constant change. What should the team do?',
   options:['Stop releasing','Batch user-facing changes into predictable release notes and short guidance, and gather feedback on the pace of change','Release without telling users','Release more often'],answer:[1],
   explanation:'Delivery speed should be balanced with users’ ability to absorb change, through communication and support.',
   ref:'Performance domain: Stakeholders · Principle: Focus on value'},
  {id:'S4-B34',domain:D,task:7,approach:'Hybrid',type:'multi',
   stem:'Which TWO actions help sustain a change after the project ends?',
   options:['Updating policies, procedures and performance measures to reflect the new way of working','Removing support immediately after go-live','Recognizing and reinforcing people who adopt the new practices','Allowing the old system to run in parallel indefinitely','Avoiding follow-up'],answer:[0,2],
   explanation:'Embedding the change in the organization’s systems and reinforcing it helps it last.',
   ref:'Principle: Focus on value · Focus area: Closing'},

  // Task 8 — External environment (4)
  {id:'S4-B35',domain:D,task:8,approach:'Predictive',type:'single',
   stem:'A new provincial minimum-wage increase will raise the cost of the project’s contracted labour next year. What should the project manager do?',
   options:['Ignore it','Estimate the impact on the budget and contracts, update the cost forecast and risk register, and inform governance','Delay all work','Ask contractors to absorb the cost'],answer:[1],
   explanation:'Changes in the external economic and legal environment must be analyzed for their effect on the project.',
   ref:'Performance domains: Finance, Risk'},
  {id:'S4-B36',domain:D,task:8,approach:'Agile',type:'single',
   stem:'A major technology platform the product uses announces that it will end support for an important feature in nine months. What should the team do?',
   options:['Wait until support ends','Assess the impact and alternatives, add the migration work to the backlog and prioritize it early enough to avoid disruption','Remove the product from the market','Hope that the vendor changes its mind'],answer:[1],
   explanation:'Technology changes in the external environment are handled through early assessment and prioritized backlog work.',
   ref:'Performance domain: Risk · Performance domain: Scope'},
  {id:'S4-B37',domain:D,task:8,approach:'Hybrid',type:'single',
   stem:'A severe flood in a supplier’s region is reported in the news. The supplier has not contacted the project. What should the project manager do?',
   options:['Wait for the supplier to call','Contact the supplier proactively to understand the impact, assess the effect on the project and activate contingency plans if needed','Cancel the contract','Ignore the news'],answer:[1],
   explanation:'Proactive monitoring of external events allows early responses to emerging risks.',
   ref:'Performance domain: Risk · Principle: Adopt a holistic view'},
  {id:'S4-B38',domain:D,task:8,approach:'Predictive',type:'multi',
   stem:'Which TWO external factors are examples of enterprise environmental factors that can affect a project?',
   options:['Government regulations and industry standards','The project’s lessons-learned register','Market conditions and economic trends','The project’s WBS','The team’s working agreement'],answer:[0,2],
   explanation:'Enterprise environmental factors include external conditions such as regulations and markets that the team cannot control.',
   ref:'Principle: Adopt a holistic view · Performance domain: Governance'}
];
