import {CaseStudy,ExamQuestion} from '../../exam-types';

export const CASE_STUDIES:CaseStudy[]=[
  {id:'J',title:'Case J · Lakeside Regional Airport: Terminal Expansion and Digital Wayfinding (hybrid)',graphic:'ev-4',context:[
    'Lakeside Regional Airport is expanding its passenger terminal while it stays open. The construction work ($3.6 million budget, 12 months) follows a predictive plan, and most work happens at night to avoid disrupting flights.',
    'An agile team is building a digital wayfinding app and terminal display system in two-week sprints. It must be ready when each new gate area opens. Airlines, concession tenants, the airport authority board and security agencies all have a stake in the project.',
    'The chart shows planned value (PV), earned value (EV) and actual cost (AC) for the construction work, in thousands of dollars, at the end of month 7.'
  ]},
  {id:'K',title:'Case K · CoastCare Insurance: Claims Automation with AI (agile)',graphic:'burnup-4',context:[
    'CoastCare Insurance is building an AI-assisted claims platform that recommends approval amounts for simple auto-glass and windshield claims. Two Scrum teams—data scientists and software developers—share one product backlog and work in two-week sprints.',
    'The insurance regulator expects automated decisions to be explainable and fair. Claims adjusters will review the AI’s recommendations, and many worry that the system will replace them.',
    'The chart shows the release burnup. Stakeholders have added scope twice since the release started.'
  ]},
  {id:'L',title:'Case L · Northern Water Treatment Plant Upgrade (predictive)',graphic:'network-4',context:[
    'A northern municipality is upgrading its water treatment plant to meet new drinking-water standards. The plant must keep supplying safe water to 18,000 residents throughout the work.',
    'An engineering firm completed the design, and a general contractor is building the upgrade under a unit-price contract. Plant operators will run the new automated control system after handover.',
    'The network diagram shows the activities for the first process train, with durations in days.'
  ]}
];

export const CASE_QUESTIONS:ExamQuestion[]=[
  // ---------- Case J ----------
  {id:'S4-J01',caseId:'J',domain:'Process',task:9,approach:'Hybrid',type:'single',graphic:'ev-4',
   stem:'Based on the chart at the end of month 7, how is the construction work performing?',
   options:['Ahead of schedule and under budget','Behind schedule and under budget','Behind schedule and over budget','Ahead of schedule and over budget'],answer:[1],
   explanation:'EV ($1,800k) is below PV ($2,000k), so SPI = 0.90: behind schedule. EV is above AC ($1,600k), so CPI = 1.125: under budget for the work completed.',
   ref:'Performance domains: Schedule, Finance · Focus area: Monitoring and Controlling'},
  {id:'S4-J02',caseId:'J',domain:'Process',task:6,approach:'Hybrid',type:'dropdown',graphic:'ev-4',
   stem:'The construction team expects its month-7 cost efficiency to hold for the remaining work. What is the forecast estimate at completion (EAC) for construction?',
   options:['$3,200,000','$3,400,000','$3,600,000','$4,000,000'],answer:[0],
   explanation:'CPI = EV ÷ AC = 1,800 ÷ 1,600 = 1.125. EAC = BAC ÷ CPI = 3,600 ÷ 1.125 = $3,200,000—$400,000 below budget if the trend continues.',
   ref:'Performance domain: Finance · Focus area: Monitoring and Controlling'},
  {id:'S4-J03',caseId:'J',domain:'People',task:5,approach:'Hybrid',type:'single',
   stem:'Airlines want the wayfinding app to show live gate changes from day one. The airport authority board expects only static maps in the first release. What should the project manager do?',
   options:['Promise live gate changes to keep the airlines satisfied','Bring the airlines, the board and the product owner together to agree on the first release’s scope and success criteria, and show when live data can follow','Let the development team decide','Build static maps without telling the airlines'],answer:[1],
   explanation:'Different stakeholders hold different expectations about the same release. A joint session aligns scope and success criteria and gives a visible path for later features.',
   ref:'Performance domain: Stakeholders · Principle: Focus on value'},
  {id:'S4-J04',caseId:'J',domain:'Business Environment',task:2,approach:'Hybrid',type:'single',
   stem:'The contractor wants to start night work in the restricted area next to the gates next week. Several workers do not yet have airport security clearance. What should the project manager do?',
   options:['Let the workers start under escort by a supervisor','Ensure that only workers with valid security clearance enter the restricted area, help expedite the clearance process, and adjust the work sequence in the meantime','Ask the airport police to waive clearance for one week','Start the work and complete the paperwork later'],answer:[1],
   explanation:'Aviation security requirements are mandatory. The project manager adjusts the plan to comply rather than bypassing controls.',
   ref:'Performance domain: Governance · Principle: Be an accountable leader'},
  {id:'S4-J05',caseId:'J',domain:'Process',task:4,approach:'Hybrid',type:'single',
   stem:'Most construction work can happen only between 11 p.m. and 5 a.m., when flights stop. How should this constraint be reflected in planning?',
   options:['Ignore it and plan normal day shifts','Use resource and project calendars that reflect the night-work windows, and plan crews, equipment and durations accordingly','Ask airlines to cancel flights','Add weekend overtime to every activity'],answer:[1],
   explanation:'Calendars capture when resources can work. Using them produces realistic durations and resource plans.',
   ref:'Performance domains: Resources, Schedule · Focus area: Planning'},
  {id:'S4-J06',caseId:'J',domain:'People',task:4,approach:'Hybrid',type:'single',
   stem:'Concession tenants fear that construction hoarding will hide their shops and cut sales. Several have complained to the airport authority. What is the best action?',
   options:['Refer them to their lease terms','Meet with the tenants, share the construction sequence early, and agree on mitigations such as temporary signage and wayfinding app promotions','Ignore the complaints because construction is temporary','Offer rent reductions without analysis'],answer:[1],
   explanation:'Engaging affected stakeholders early and agreeing on practical mitigations reduces opposition and protects the airport’s relationships.',
   ref:'Performance domain: Stakeholders · Focus area: Executing'},
  {id:'S4-J07',caseId:'J',domain:'Business Environment',task:7,approach:'Hybrid',type:'single',
   stem:'Terminal staff will switch from radio calls to a new digital operations dashboard. Supervisors say staff are anxious about using it during busy periods. What should the project manager do?',
   options:['Launch the dashboard everywhere on one day','Involve supervisors and front-line staff in testing, provide hands-on practice in quiet periods, and phase the rollout with support available','Keep radio calls as the only method','Send a user guide by email'],answer:[1],
   explanation:'Involvement, practice and phased adoption with support help people build confidence in a new way of working.',
   ref:'Performance domain: Stakeholders · Principle: Build an empowered culture'},
  {id:'S4-J08',caseId:'J',domain:'Process',task:1,approach:'Hybrid',type:'single',
   stem:'Each new gate area opens on a fixed construction milestone, and the wayfinding app must support it on opening day. How should the project manager integrate the two delivery streams?',
   options:['Ask the app team to wait until construction is complete','Align the app’s release goals with each gate-opening milestone in an integrated roadmap, and hold joint readiness reviews before each opening','Plan the streams separately','Ask the construction team to work in sprints'],answer:[1],
   explanation:'A hybrid plan links adaptive releases to predictive milestones and confirms joint readiness before each dependent event.',
   ref:'Principle: Adopt a holistic view · Focus area: Planning'},
  {id:'S4-J09',caseId:'J',domain:'Business Environment',task:8,approach:'Hybrid',type:'single',
   stem:'One of the airport’s two largest airlines announces that it will cut its regional routes by 40% next year. Passenger forecasts that justified the expansion will fall. What should the project manager do?',
   options:['Continue as planned','Work with the sponsor and finance team to update the business case and present options to governance—such as phasing or reducing the scope of later gate areas','Stop construction immediately','Wait until the cuts take effect'],answer:[1],
   explanation:'Significant external changes require the business case to be reassessed so that governance can make informed decisions.',
   ref:'Principle: Focus on value · Performance domain: Governance'},
  {id:'S4-J10',caseId:'J',domain:'People',task:8,approach:'Hybrid',type:'multi',
   stem:'Passengers need to know about construction changes to walking routes and gate locations. Which TWO communication approaches are most appropriate?',
   options:['Clear temporary signage and announcements in the terminal, updated as routes change','A single notice on the airport website at the start of construction','Real-time route and gate information in the wayfinding app and on terminal displays','An annual newsletter','Information only for frequent flyers'],answer:[0,2],
   explanation:'Passengers need timely information where and when they make decisions—on site and through real-time digital channels.',
   ref:'Performance domain: Stakeholders · Focus area: Executing'},

  // ---------- Case K ----------
  {id:'S4-K01',caseId:'K',domain:'Process',task:9,approach:'Agile',type:'dropdown',graphic:'burnup-4',
   stem:'Based on the burnup chart, if velocity stays at its current rate and no more scope is added, at the end of which sprint will the release be complete?',
   options:['Sprint 10','Sprint 11','Sprint 12','Sprint 14'],answer:[2],
   explanation:'After sprint 8, 320 of 480 points are done. Velocity is 40 points per sprint, so the remaining 160 points take 4 sprints: the release completes at the end of sprint 12.',
   ref:'Performance domain: Schedule · Focus area: Monitoring and Controlling'},
  {id:'S4-K02',caseId:'K',domain:'Process',task:2,approach:'Agile',type:'single',graphic:'burnup-4',
   stem:'The burnup chart shows that scope has grown twice, by 40 points each time. What should the product owner do?',
   options:['Accept all new scope because agile welcomes change','Make the effect of scope growth on the forecast visible, and work with stakeholders to prioritize—adding new items only by deferring lower-value ones if the date matters','Freeze the backlog permanently','Ask the teams to increase velocity'],answer:[1],
   explanation:'Agile welcomes change, but the product owner must manage the trade-offs openly so that stakeholders understand the effect on dates.',
   ref:'Performance domain: Scope · Principle: Focus on value'},
  {id:'S4-K03',caseId:'K',domain:'Business Environment',task:5,approach:'Agile',type:'single',
   stem:'Testing shows that the model recommends lower settlement amounts for claimants in certain postal codes, which may reflect bias in the historical data. What should the team do?',
   options:['Release the model because it is accurate overall','Treat this as a high-priority risk: investigate the cause, apply fairness testing and mitigation, involve compliance and ethics reviewers, and do not release until the results are acceptable','Remove postal codes from the reports only','Ask adjusters to watch for unfair results after release'],answer:[1],
   explanation:'Potential bias in automated decisions is a serious ethical, legal and reputational risk that must be investigated and mitigated before release.',
   ref:'AI in project management · Performance domain: Risk · Principle: Be an accountable leader'},
  {id:'S4-K04',caseId:'K',domain:'People',task:3,approach:'Agile',type:'single',
   stem:'Data scientists and developers work in separate silos, so models often cannot be deployed without rework. What should the project manager do?',
   options:['Create a formal handover document between the groups','Help the teams organize around shared backlog items—for example by pairing data scientists and developers on each model from experiment to deployment','Assign a manager to each group','Ask developers to rebuild every model'],answer:[1],
   explanation:'Cross-functional collaboration on shared work removes handoffs and rework.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'S4-K05',caseId:'K',domain:'Business Environment',task:2,approach:'Agile',type:'single',
   stem:'The regulator expects insurers to explain automated claim decisions to customers. How should this requirement be handled?',
   options:['Add an explanation feature after launch','Treat explainability as a compliance requirement: include it in acceptance criteria and the definition of done, keep a human adjuster in the decision for each claim, and document the model’s logic','Ignore it because the AI only recommends','Ask the vendor to provide a generic statement'],answer:[1],
   explanation:'Regulatory requirements for AI must be built into the product and its controls from the start.',
   ref:'Performance domain: Governance · AI in project management'},
  {id:'S4-K06',caseId:'K',domain:'Process',task:7,approach:'Agile',type:'single',
   stem:'A model that performed well in testing could become less accurate as claim patterns change. How should the team protect quality after release?',
   options:['Retrain the model once a year','Define quality thresholds, monitor model performance in production, and plan retraining and review when performance drifts','Rely on customer complaints','Turn off the model after six months'],answer:[1],
   explanation:'AI quality must be monitored continuously, because data and behaviour change over time (model drift).',
   ref:'Principle: Embed quality · AI in project management'},
  {id:'S4-K07',caseId:'K',domain:'People',task:1,approach:'Agile',type:'single',
   stem:'Claims adjusters believe the project’s real goal is to replace them, and they are reluctant to help test the model. What should the project manager do?',
   options:['Tell adjusters that their roles are secure no matter what','Work with leadership to communicate an honest vision—AI handles routine simple claims so that adjusters can focus on complex cases—and involve adjusters in shaping and testing the solution','Test the model without adjusters','Ask HR to manage the concerns'],answer:[1],
   explanation:'A clear, honest vision and real involvement build trust. Promises the project cannot guarantee damage credibility.',
   ref:'Principle: Build an empowered culture · Performance domain: Stakeholders'},
  {id:'S4-K08',caseId:'K',domain:'People',task:6,approach:'Agile',type:'single',
   stem:'Executives expected the AI to automate 90% of simple claims. The pilot shows that 40% can be automated safely. What should the project manager do?',
   options:['Report 90% to avoid disappointing executives','Share the pilot results transparently, explain the reasons and the improvement options, and agree on realistic targets with the executives','Lower the safety threshold to reach 90%','Delay reporting until the next release'],answer:[1],
   explanation:'Honest reporting with options helps leaders reset expectations without compromising safety or fairness.',
   ref:'Principle: Be an accountable leader · Performance domain: Stakeholders'},
  {id:'S4-K09',caseId:'K',domain:'Business Environment',task:4,approach:'Agile',type:'single',
   stem:'The data scientists cannot improve the model because labelled training data depends on adjusters, who have no time for labelling. What should the project manager do?',
   options:['Ask data scientists to label the data themselves','Raise the impediment with the claims managers and product owner, show its impact, and agree on dedicated adjuster time or another practical labelling approach','Wait until adjusters have spare time','Use unlabelled data'],answer:[1],
   explanation:'Impediments that depend on other parts of the organization need to be made visible and resolved with the people who control the resources.',
   ref:'Focus area: Executing · Performance domain: Resources'},
  {id:'S4-K10',caseId:'K',domain:'Process',task:3,approach:'Agile',type:'single',
   stem:'Which measure best shows that the claims platform is delivering business value?',
   options:['Number of models trained','Reduction in the average time to settle simple claims, with stable accuracy and customer satisfaction','Number of story points completed','Lines of code written'],answer:[1],
   explanation:'Value is shown by business outcomes such as faster, accurate settlements and satisfied customers.',
   ref:'Principle: Focus on value · Focus area: Monitoring and Controlling'},

  // ---------- Case L ----------
  {id:'S4-L01',caseId:'L',domain:'Process',task:8,approach:'Predictive',type:'dropdown',graphic:'network-4',
   stem:'Using the network diagram, what is the duration of the first process train?',
   options:['16 days','17 days','19 days','30 days'],answer:[2],
   explanation:'Paths: A-B-D-G-H = 5+3+6+3+2 = 19; A-C-E-G-H = 5+4+2+3+2 = 16; A-C-F-H = 5+4+5+2 = 16. The critical path is A-B-D-G-H, so the duration is 19 days.',
   ref:'Performance domain: Schedule · Focus area: Planning'},
  {id:'S4-L02',caseId:'L',domain:'Process',task:8,approach:'Predictive',type:'single',graphic:'network-4',
   stem:'Activity C is delayed by 4 days. What is the effect on the duration of the process train?',
   options:['No effect','1 day later','3 days later','4 days later'],answer:[1],
   explanation:'Both paths through C (A-C-E-G-H and A-C-F-H) take 16 days, so C has 3 days of total float. A 4-day delay uses the float and makes those paths 20 days, 1 day longer than the current 19.',
   ref:'Performance domain: Schedule · Focus area: Monitoring and Controlling'},
  {id:'S4-L03',caseId:'L',domain:'Business Environment',task:2,approach:'Predictive',type:'single',
   stem:'During commissioning, a new filter must be tested while the plant continues to supply residents. What is the most important compliance consideration?',
   options:['Finishing commissioning as quickly as possible','Maintaining drinking-water quality requirements throughout, with sampling, monitoring and approval from the responsible authority before switching supply to the new filter','Letting the contractor decide the test sequence','Switching supply first and testing later'],answer:[1],
   explanation:'Public-health regulations require that water quality is never compromised. Commissioning must be planned around monitoring and regulatory approval.',
   ref:'Performance domain: Governance · Principle: Be an accountable leader'},
  {id:'S4-L04',caseId:'L',domain:'Process',task:5,approach:'Predictive',type:'single',
   stem:'Under the unit-price contract, the contractor reports 30% more excavated rock than estimated. What should the project manager do?',
   options:['Pay the contractor’s claim immediately','Verify the actual quantities through the agreed measurement method, confirm that the unit rates apply, assess the impact on the budget and process any change through change control','Refuse to pay for extra quantities','Ask the contractor to absorb the cost'],answer:[1],
   explanation:'Unit-price contracts pay for actual measured quantities at agreed rates. Quantities must be verified and budget impacts managed through governance.',
   ref:'Performance domains: Resources (procurement), Finance'},
  {id:'S4-L05',caseId:'L',domain:'People',task:2,approach:'Predictive',type:'single',
   stem:'Plant operators want commissioning tests done during low-demand nights, but the engineering firm wants daytime tests when its specialists are available. Tension is rising. What should the project manager do?',
   options:['Side with the engineers because they designed the system','Bring both groups together to understand their constraints and agree on a test schedule that protects water supply and makes specialists available, such as an evening window','Side with the operators','Let the contractor decide'],answer:[1],
   explanation:'Collaborative problem solving that addresses both groups’ underlying constraints produces a workable and supported solution.',
   ref:'Performance domains: Resources, Stakeholders · Focus area: Executing'},
  {id:'S4-L06',caseId:'L',domain:'Business Environment',task:3,approach:'Predictive',type:'single',
   stem:'Council asks the project to add rooftop solar panels to the new building, which was not in the approved scope. What should the project manager do?',
   options:['Add the panels because council is the sponsor','Document the request as a change, analyze its effects on scope, cost, schedule, structure and risk, and submit it for decision through change control','Refuse the request','Ask the contractor to add the panels at no cost'],answer:[1],
   explanation:'Even sponsor requests follow change control so that impacts are understood and baselines updated.',
   ref:'Performance domain: Governance · Principle: Integrate sustainability'},
  {id:'S4-L07',caseId:'L',domain:'Process',task:10,approach:'Predictive',type:'multi',
   stem:'The upgraded plant has been commissioned. Which TWO activities should be completed before the project is closed?',
   options:['Formal acceptance by the municipality and handover of operating manuals, warranties and as-built drawings to the operators','Starting design work for the next upgrade','Confirming that operators are trained and able to run the new control system','Releasing the contractor’s retention before defects are corrected','Rebaselining the budget'],answer:[0,2],
   explanation:'Closure requires formal acceptance, documented handover and a capable receiving organization.',
   ref:'Focus area: Closing · Performance domain: Resources'},
  {id:'S4-L08',caseId:'L',domain:'People',task:7,approach:'Predictive',type:'single',
   stem:'The control-system vendor will leave after commissioning. Operators must be able to troubleshoot alarms on their own. What is the most effective knowledge-transfer approach?',
   options:['A one-day classroom session at the end','Hands-on training during commissioning in which operators run the system with vendor coaching, supported by procedures and a list of alarm responses','Leaving the vendor manual on site','Recording a video of the vendor using the system'],answer:[1],
   explanation:'Practising real tasks with expert coaching, supported by written procedures, gives operators lasting capability.',
   ref:'Performance domain: Resources · Focus area: Executing'},
  {id:'S4-L09',caseId:'L',domain:'Business Environment',task:6,approach:'Predictive',type:'single',
   stem:'Installing the first process train took longer than planned because of piping clashes. The second train will be built next. What should the project manager do?',
   options:['Repeat the same approach for the second train','Hold a lessons-learned review, identify the causes of the clashes, and apply the improvements—such as a 3D clash check—before starting the second train','Blame the designer','Skip the review to save time'],answer:[1],
   explanation:'Applying lessons from the first repetition before the next is continuous improvement within the project.',
   ref:'Principle: Embed quality · Focus area: Monitoring and Controlling'},
  {id:'S4-L10',caseId:'L',domain:'People',task:4,approach:'Predictive',type:'single',
   stem:'Residents near the plant are worried about odours and truck traffic during construction and have started a petition. What should the project manager do?',
   options:['Ignore the petition because permits are in place','Engage residents through information sessions and a contact point, explain the schedule and the mitigations being used, and respond to concerns promptly','Refer residents to council','Stop work until the petition is withdrawn'],answer:[1],
   explanation:'Proactive, two-way engagement addresses concerns and maintains community support.',
   ref:'Performance domain: Stakeholders · Principle: Integrate sustainability'}
];
