import {ExamQuestion} from '../../exam-types';

const D='People' as const;

export const PEOPLE_QUESTIONS:ExamQuestion[]=[
  // Task 1 — Develop a common vision (7)
  {id:'S4-P01',domain:D,task:1,approach:'Predictive',type:'single',
   stem:'A project exists only because a new regulation requires it. Team members see it as “paperwork” and are unmotivated. What should the project manager do?',
   options:['Remind the team that the project is mandatory','Help the team see the value behind the regulation—such as protecting customers—and agree on goals that go beyond minimum compliance where they add value','Reduce the project to the minimum effort','Ask the sponsor to offer bonuses'],answer:[1],
   explanation:'Even compliance-driven projects benefit from a shared vision that connects the work to the outcomes it protects or enables.',
   ref:'Principle: Focus on value · Performance domain: Stakeholders'},
  {id:'S4-P02',domain:D,task:1,approach:'Agile',type:'single',
   stem:'To build a shared vision, a product owner asks small groups to design the “box” the product would be sold in, with its name, key benefits and target customer. What is the main purpose of this exercise?',
   options:['To design the real packaging','To help the team and stakeholders agree, in simple customer terms, on what the product is for and why it matters','To estimate the budget','To assign roles'],answer:[1],
   explanation:'A product vision box makes the vision concrete and customer-focused, and builds shared understanding through collaboration.',
   ref:'Performance domain: Scope · Principle: Focus on value'},
  {id:'S4-P03',domain:D,task:1,approach:'Hybrid',type:'single',
   stem:'A community non-profit is running a project with volunteers who give a few hours a week. Commitment is uneven. What is the most effective way to build a common vision?',
   options:['Assign tasks with strict deadlines','Connect volunteers to the community impact they will create, agree on goals together and celebrate visible progress','Replace volunteers with paid staff','Limit volunteers to simple tasks'],answer:[1],
   explanation:'Volunteers are motivated by purpose and impact. A shared vision and visible progress sustain their engagement.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'S4-P04',domain:D,task:1,approach:'Hybrid',type:'single',
   stem:'During a period of organizational layoffs, team members question whether their project will survive and whether it still matters. What should the project manager do?',
   options:['Avoid the topic','Share what is known honestly, reconfirm the project’s purpose and priority with the sponsor, and communicate it clearly to the team','Promise that the project is safe','Tell the team to focus on their tasks'],answer:[1],
   explanation:'In uncertain times, honest communication and confirmed purpose from leadership help maintain focus and trust.',
   ref:'Principle: Be an accountable leader · Performance domain: Stakeholders'},
  {id:'S4-P05',domain:D,task:1,approach:'Agile',type:'single',
   stem:'Different executives describe the project’s purpose in different ways in town-hall meetings, which confuses the team. What should the project manager do?',
   options:['Ignore the differences','Work with the sponsor to agree on a short, consistent statement of the project’s purpose and outcomes for all leaders to use','Ask each executive to present their own version','Stop holding town halls'],answer:[1],
   explanation:'Consistent messages from leaders reinforce a common vision. The sponsor is accountable for alignment at the top.',
   ref:'Performance domain: Governance · Principle: Be an accountable leader'},
  {id:'S4-P06',domain:D,task:1,approach:'Predictive',type:'single',
   stem:'The project manager wants every team member to be able to explain the project’s purpose in under 30 seconds. Which tool helps most?',
   options:['A detailed WBS','A short elevator pitch that states the problem, who benefits and the expected outcome','A Gantt chart','The risk register'],answer:[1],
   explanation:'A concise elevator pitch is an easy way to share and repeat the vision consistently.',
   ref:'Performance domain: Stakeholders · Focus area: Initiating'},
  {id:'S4-P07',domain:D,task:1,approach:'Hybrid',type:'multi',
   stem:'Which TWO signs suggest that a team lacks a common vision?',
   options:['Team members make conflicting decisions about priorities','Team members can describe the same goal in similar words','Work is often redone because people understood the goal differently','The team regularly refers to its success measures','Stakeholders agree on what success looks like'],answer:[0,2],
   explanation:'Conflicting priorities and rework from different interpretations are classic symptoms of an unclear or unshared vision.',
   ref:'Principle: Adopt a holistic view · Focus area: Monitoring and Controlling'},

  // Task 2 — Manage conflicts (6)
  {id:'S4-P08',domain:D,task:2,approach:'Agile',type:'single',
   stem:'A tester and a developer disagree about whether a defect is “critical” or “minor,” which blocks the release decision. What should happen?',
   options:['The developer decides because they wrote the code','Use the team’s agreed defect-severity definitions; if the disagreement remains, the product owner decides based on business impact','The tester decides','The release is cancelled'],answer:[1],
   explanation:'Agreed definitions provide an objective basis, and the product owner holds decision rights on business value and release scope.',
   ref:'Principle: Embed quality · Performance domain: Scope'},
  {id:'S4-P09',domain:D,task:2,approach:'Hybrid',type:'single',
   stem:'Two team members argue about who deserves credit for a successful feature. The argument is harming collaboration. What should the project manager do?',
   options:['Give credit to the more senior member','Talk with them privately, recognize both contributions, and reinforce team-level recognition for shared work','Ignore it','Remove one of them from the team'],answer:[1],
   explanation:'Addressing the issue privately and emphasizing shared recognition restores collaboration.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'S4-P10',domain:D,task:2,approach:'Predictive',type:'single',
   stem:'The project manager is personally involved in a conflict with a functional manager, and direct discussion has failed. What is an appropriate next step?',
   options:['Escalate publicly at a team meeting','Ask a neutral, respected third party to mediate, or escalate through the agreed governance path','Stop working with the functional manager','Ignore the conflict'],answer:[1],
   explanation:'When the parties cannot resolve a conflict directly, a neutral mediator or a governance escalation is appropriate.',
   ref:'Performance domain: Governance · Focus area: Executing'},
  {id:'S4-P11',domain:D,task:2,approach:'Hybrid',type:'single',
   stem:'Steering committee members disagree sharply about cutting the budget. The project manager is asked to facilitate. What approach is best?',
   options:['Recommend whatever the most senior member wants','Present objective information about the options and their impacts on objectives, and help the committee reach a decision against agreed criteria','Avoid taking part','Postpone the meeting indefinitely'],answer:[1],
   explanation:'Facilitating with objective data and agreed criteria supports a fair, informed decision by the people who own it.',
   ref:'Performance domain: Governance · Principle: Focus on value'},
  {id:'S4-P12',domain:D,task:2,approach:'Agile',type:'single',
   stem:'Some team members want to work fully remotely, while others want everyone in the office three days a week. The debate is affecting morale. What should the project manager do?',
   options:['Decide personally and announce it','Facilitate a discussion within the organization’s policy so that the team can agree on working arrangements and collaboration norms that support its goals','Let each member do as they wish without agreement','Escalate to HR immediately'],answer:[1],
   explanation:'Within organizational policy, teams that co-create their working agreements are more committed to them.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'S4-P13',domain:D,task:2,approach:'Hybrid',type:'multi',
   stem:'Which TWO early warning signs suggest that conflict is developing within a team?',
   options:['Team members stop sharing information or avoid each other','Team members ask each other for help','Comments in meetings become sarcastic or personal','The team completes its sprint goals','Members volunteer for shared tasks'],answer:[0,2],
   explanation:'Withdrawal and personal or sarcastic remarks signal growing conflict that should be addressed early.',
   ref:'Performance domain: Resources · Focus area: Monitoring and Controlling'},

  // Task 3 — Lead the project team (7)
  {id:'S4-P14',domain:D,task:3,approach:'Hybrid',type:'matching',
   stem:'Match each leadership style to its description.',
   pairs:[{left:'Transactional',right:0},{left:'Transformational',right:1},{left:'Laissez-faire',right:2},{left:'Servant',right:3}],
   choices:['Focuses on goals, feedback and rewards for performance','Inspires followers through vision and ideals, encouraging innovation','Leaves the team to make its own decisions with little involvement','Puts the team first, removing obstacles and supporting growth'],
   explanation:'Effective project leaders adapt their style to the situation, often combining elements of several styles.',
   ref:'Principle: Be an accountable leader · Performance domain: Resources'},
  {id:'S4-P15',domain:D,task:3,approach:'Predictive',type:'single',
   stem:'The project is ending, and team members are anxious about their next assignments. Which stage of team development is this, and what should the project manager do?',
   options:['Storming; resolve conflicts','Adjourning; recognize contributions, support transitions and capture lessons learned','Forming; set up working agreements','Norming; agree on roles'],answer:[1],
   explanation:'The adjourning stage happens as a team disbands. Leaders support people through the transition and celebrate what was achieved.',
   ref:'Performance domain: Resources · Focus area: Closing'},
  {id:'S4-P16',domain:D,task:3,approach:'Agile',type:'single',
   stem:'A new team shows low trust: members hide problems and avoid asking for help. What should the project manager do first?',
   options:['Demand more transparency','Model openness—for example by sharing their own mistakes—create safe forums such as retrospectives, and respond to problems without blame','Introduce detailed time tracking','Reorganize the team'],answer:[1],
   explanation:'Trust grows when leaders model vulnerability and respond to problems constructively.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'S4-P17',domain:D,task:3,approach:'Hybrid',type:'single',
   stem:'A team member’s status updates are often late. The project manager wants to give feedback that is clear and constructive. Which approach is best?',
   options:['Mention it in the team meeting','Describe the specific situation, the behaviour and its impact, then ask for their perspective and agree on next steps privately','Send an email saying they need to improve','Wait for the annual review'],answer:[1],
   explanation:'Specific, private, two-way feedback focused on behaviour and impact (such as the situation–behaviour–impact model) is the most effective.',
   ref:'Principle: Be an accountable leader · Performance domain: Resources'},
  {id:'S4-P18',domain:D,task:3,approach:'Predictive',type:'single',
   stem:'A highly skilled engineer delivers excellent work but regularly belittles colleagues in meetings. Others have stopped contributing. What should the project manager do?',
   options:['Tolerate it because of the engineer’s skills','Address the behaviour privately and promptly, explain its impact on the team and agree on expectations, and follow up—escalating through HR if the behaviour continues','Move all meetings to email','Ask the team to toughen up'],answer:[1],
   explanation:'Harmful behaviour damages team performance and safety regardless of individual skill, so it must be addressed.',
   ref:'Principle: Build an empowered culture · Principle: Be an accountable leader'},
  {id:'S4-P19',domain:D,task:3,approach:'Agile',type:'single',
   stem:'An experienced team asks for more autonomy in how it plans its work. The team has delivered reliably. How should the project manager respond?',
   options:['Keep full control to avoid risk','Agree on clear boundaries and outcomes, then delegate more planning decisions to the team while staying available for support','Give complete autonomy without any agreement','Refuse until the next annual review'],answer:[1],
   explanation:'Delegating decisions within clear boundaries builds ownership while keeping accountability clear.',
   ref:'Principle: Build an empowered culture · Performance domain: Governance'},
  {id:'S4-P20',domain:D,task:3,approach:'Hybrid',type:'single',
   stem:'Three experienced members leave the team mid-project and are replaced by newcomers. Velocity drops and roles are unclear. What should the project manager do?',
   options:['Expect the same velocity immediately','Recognize that the team has reset to an earlier development stage: revisit roles and working agreements, support onboarding and adjust forecasts','Push the team harder','Ask the sponsor to cancel the project'],answer:[1],
   explanation:'Significant membership changes reset team dynamics. Leaders re-establish norms and adjust expectations.',
   ref:'Performance domain: Resources · Principle: Be an accountable leader'},

  // Task 4 — Engage stakeholders (6)
  {id:'S4-P21',domain:D,task:4,approach:'Predictive',type:'hotspot',graphic:'grid-4',
   stem:'The grid shows four stakeholder groups for an airport project. Click the group that should be engaged with a “keep satisfied” strategy.',
   options:['Airport authority board','Airline station managers','Concession tenants','Taxi dispatch'],answer:[0],
   explanation:'The airport authority board has high power but low day-to-day interest, so it should be kept satisfied. Airline station managers (high/high) are managed closely, concession tenants (low power, high interest) are kept informed, and taxi dispatch (low/low) is monitored.',
   ref:'Performance domain: Stakeholders · Focus area: Planning'},
  {id:'S4-P22',domain:D,task:4,approach:'Hybrid',type:'single',
   stem:'A local advocacy group opposes the project and is organizing protests. What is the most constructive approach?',
   options:['Avoid all contact with the group','Seek to understand the group’s concerns through respectful dialogue, share accurate information and consider reasonable changes or mitigations','Ask the police to intervene immediately','Launch a counter-campaign'],answer:[1],
   explanation:'Engaging opponents respectfully can reduce conflict, surface valid concerns and improve outcomes.',
   ref:'Performance domain: Stakeholders · Principle: Integrate sustainability'},
  {id:'S4-P23',domain:D,task:4,approach:'Agile',type:'single',
   stem:'A new system will be used by staff who have not yet been hired. How can their needs be represented?',
   options:['Ignore them until they are hired','Use personas and input from people in similar roles, and involve new staff in testing as soon as they join','Let the vendor decide','Wait until the system is complete'],answer:[1],
   explanation:'Personas and proxy users represent future stakeholders until real users can be involved.',
   ref:'Performance domain: Stakeholders · Principle: Focus on value'},
  {id:'S4-P24',domain:D,task:4,approach:'Predictive',type:'single',
   stem:'The stakeholder register includes frank notes about some stakeholders’ attitudes and influence. How should it be handled?',
   options:['Publish it on the team site for transparency','Treat the sensitive parts as confidential, share them only with people who need them, and use professional, factual language','Delete it after initiation','Email it to all stakeholders'],answer:[1],
   explanation:'Stakeholder analysis can contain sensitive information that must be handled discreetly and professionally.',
   ref:'Performance domain: Stakeholders · Principle: Be an accountable leader'},
  {id:'S4-P25',domain:D,task:4,approach:'Hybrid',type:'single',
   stem:'The executive sponsor has missed the last three steering meetings, and decisions are waiting. What should the project manager do?',
   options:['Make the decisions personally','Meet with the sponsor to understand their availability, explain the decisions needed and their impact, and agree on a workable way to keep them engaged—such as short decision briefings','Escalate to the CEO immediately','Cancel steering meetings'],answer:[1],
   explanation:'Sponsor engagement is critical. Understanding constraints and tailoring the engagement keeps decisions moving.',
   ref:'Performance domain: Stakeholders · Performance domain: Governance'},
  {id:'S4-P26',domain:D,task:4,approach:'Agile',type:'multi',
   stem:'An organization is launching a product in a new province where it has no existing relationships. Which TWO actions help identify and engage stakeholders there?',
   options:['Researching local regulators, associations and community groups and meeting key representatives','Assuming stakeholders are the same as in the home province','Running early discovery sessions with potential local customers and partners','Waiting until launch to see who responds','Relying only on the sales team’s opinions'],answer:[0,2],
   explanation:'New contexts need fresh stakeholder identification through research and direct early engagement.',
   ref:'Performance domain: Stakeholders · Focus area: Initiating'},

  // Task 5 — Align stakeholder expectations (6)
  {id:'S4-P27',domain:D,task:5,approach:'Hybrid',type:'single',
   stem:'A client expects all of its requests to be implemented immediately because it is paying for the project. What should the project manager do at the start?',
   options:['Accept all requests','Agree with the client on how requests will be assessed, prioritized and approved, and how changes affect cost and schedule','Refuse all requests','Avoid discussing changes'],answer:[1],
   explanation:'Agreeing on the change process early aligns expectations and avoids disputes later.',
   ref:'Performance domain: Governance · Focus area: Initiating'},
  {id:'S4-P28',domain:D,task:5,approach:'Predictive',type:'single',
   stem:'The vendor assumes the client will write and run user acceptance tests, but the client assumes the vendor will. When should this be clarified?',
   options:['During acceptance testing','Early in planning, by agreeing on responsibilities for acceptance testing in the contract, plan and RACI','At closure','It does not need clarifying'],answer:[1],
   explanation:'Clarifying responsibilities early prevents gaps and disputes at a critical stage.',
   ref:'Principle: Embed quality · Performance domain: Resources'},
  {id:'S4-P29',domain:D,task:5,approach:'Predictive',type:'single',
   stem:'The business expects the vendor to fix any problem for free for two years after go-live. The contract has a 90-day warranty. What should the project manager do?',
   options:['Ignore the gap','Clarify the warranty terms with the business before go-live and, if longer support is needed, arrange a support agreement','Promise two years of free support','Ask the vendor to extend the warranty informally'],answer:[1],
   explanation:'Aligning expectations with contract terms prevents disappointment and unplanned costs.',
   ref:'Performance domain: Resources (procurement) · Performance domain: Stakeholders'},
  {id:'S4-P30',domain:D,task:5,approach:'Agile',type:'single',
   stem:'Business stakeholders keep bringing vague ideas to sprint planning and expecting them to be built in that sprint. What would help align expectations?',
   options:['Accept the ideas into the sprint','Agree on a definition of ready with stakeholders, and explain how ideas are refined in the backlog before they are planned','Ban stakeholders from sprint planning','Ask developers to guess the requirements'],answer:[1],
   explanation:'A shared definition of ready sets expectations about the information needed before work can be committed.',
   ref:'Performance domain: Scope · Principle: Embed quality'},
  {id:'S4-P31',domain:D,task:5,approach:'Hybrid',type:'single',
   stem:'Operations expects the new platform to be available 99.99% of the time, but the architecture is designed for 99.5%. What should the project manager do?',
   options:['Hope that the difference goes unnoticed','Make the gap visible early, explain the cost and design implications of higher availability, and agree on the target with the sponsor and operations','Change the architecture without approval','Promise 99.99% availability'],answer:[1],
   explanation:'Non-functional expectations must be aligned with the design and budget, and decided by the right stakeholders.',
   ref:'Principle: Embed quality · Performance domain: Scope'},
  {id:'S4-P32',domain:D,task:5,approach:'Agile',type:'multi',
   stem:'Which TWO practices help align stakeholders on what a release will include?',
   options:['A shared release goal and a visible, prioritized backlog','Hiding the backlog from stakeholders','Agreeing on acceptance criteria for the key features with stakeholders','Changing the release scope without explanation','Discussing scope only after the release'],answer:[0,2],
   explanation:'Shared goals, visible priorities and agreed acceptance criteria align expectations about release content.',
   ref:'Performance domain: Scope · Focus area: Planning'},

  // Task 6 — Manage stakeholder expectations (6)
  {id:'S4-P33',domain:D,task:6,approach:'Agile',type:'single',
   stem:'A stakeholder is visibly frustrated during a sprint review because a feature works differently from what they imagined. What should the project manager do?',
   options:['Defend the team’s implementation','Listen to the feedback, capture it for the product owner to prioritize, and explain how it can shape the next increments','End the review early','Promise to change the feature tonight'],answer:[1],
   explanation:'Reviews are designed to capture feedback. Turning frustration into backlog input manages expectations constructively.',
   ref:'Performance domain: Stakeholders · Principle: Focus on value'},
  {id:'S4-P34',domain:D,task:6,approach:'Predictive',type:'single',
   stem:'A business owner repeatedly changes their mind about approved requirements, causing rework. What should the project manager do?',
   options:['Implement each change immediately','Discuss the impact of the changes with the business owner, route future changes through change control, and identify the underlying uncertainty—such as unclear objectives','Refuse to talk to the business owner','Ignore the changes'],answer:[1],
   explanation:'Showing the impact and applying change control manages expectations, while exploring the cause addresses the root problem.',
   ref:'Performance domains: Scope, Governance'},
  {id:'S4-P35',domain:D,task:6,approach:'Hybrid',type:'single',
   stem:'A key vendor will deliver three weeks late, which affects a milestone that customers have been promised. What should the project manager do first?',
   options:['Wait to see whether the vendor recovers','Assess the impact and options, then inform the affected stakeholders promptly with a revised plan','Blame the vendor publicly','Tell customers nothing'],answer:[1],
   explanation:'Timely, honest communication with a plan maintains trust when commitments are at risk.',
   ref:'Principle: Be an accountable leader · Performance domain: Stakeholders'},
  {id:'S4-P36',domain:D,task:6,approach:'Agile',type:'single',
   stem:'A senior stakeholder expects the project manager to answer messages at any hour, including weekends. What is the best approach?',
   options:['Always respond immediately','Agree on response times and escalation channels for urgent matters, and include them in the communication plan','Ignore messages outside office hours without explanation','Ask the team to take turns responding'],answer:[1],
   explanation:'Agreeing on communication norms sets realistic expectations and protects sustainable work.',
   ref:'Performance domain: Stakeholders · Principle: Build an empowered culture'},
  {id:'S4-P37',domain:D,task:6,approach:'Hybrid',type:'single',
   stem:'A sales director insists that the product must copy a feature that a competitor just released. What should the project manager do?',
   options:['Add the feature immediately','Refer the request to the product owner, who assesses its value and urgency against the product goal and other priorities, and communicates the decision','Reject the request','Ask the team to build it secretly'],answer:[1],
   explanation:'Requests are managed through value-based prioritization, with the decision explained to the stakeholder.',
   ref:'Principle: Focus on value · Performance domain: Scope'},
  {id:'S4-P38',domain:D,task:6,approach:'Predictive',type:'multi',
   stem:'Which TWO actions help maintain stakeholder trust when a project runs into serious problems?',
   options:['Communicating early and honestly, with facts','Presenting only good news','Sharing options and a recommended path forward','Delaying updates until the problem is solved','Blaming individuals'],answer:[0,2],
   explanation:'Early honesty combined with a constructive plan maintains credibility.',
   ref:'Principle: Be an accountable leader · Performance domain: Stakeholders'},

  // Task 7 — Knowledge transfer (6)
  {id:'S4-P39',domain:D,task:7,approach:'Agile',type:'single',
   stem:'Developers often cannot remember why certain architecture choices were made. What lightweight practice helps?',
   options:['A 100-page architecture document updated yearly','Architecture decision records that briefly capture each significant decision, its context and its consequences','Relying on the architect’s memory','Recording all meetings'],answer:[1],
   explanation:'Short, structured decision records preserve the reasoning behind decisions for current and future team members.',
   ref:'Principle: Embed quality · Performance domain: Resources'},
  {id:'S4-P40',domain:D,task:7,approach:'Predictive',type:'single',
   stem:'On a long predictive project, when is it most useful to hold lessons-learned sessions?',
   options:['Only at the end','At the end of each phase or major milestone, so that lessons can be applied to the remaining work','Only when the sponsor asks','Never, because they take time'],answer:[1],
   explanation:'Capturing lessons during the project lets the team improve while there is still work left to benefit.',
   ref:'Principle: Embed quality · Focus area: Monitoring and Controlling'},
  {id:'S4-P41',domain:D,task:7,approach:'Hybrid',type:'single',
   stem:'After training, users say they understand the new process, but they make mistakes in practice. Which technique confirms understanding?',
   options:['Asking “Do you understand?”','Teach-back: asking users to explain or demonstrate the process in their own words','A longer slide presentation','Sending the slides by email'],answer:[1],
   explanation:'Teach-back reveals gaps in understanding that simple questions miss.',
   ref:'Performance domain: Stakeholders · Focus area: Executing'},
  {id:'S4-P42',domain:D,task:7,approach:'Agile',type:'single',
   stem:'A vendor team new to the insurance industry is making poor design choices because it does not understand how claims work. What should the project manager arrange?',
   options:['A thicker requirements document','Domain immersion—such as shadowing claims staff and regular sessions with subject-matter experts—so that the team learns the business context','A replacement vendor','More detailed task assignments'],answer:[1],
   explanation:'Direct exposure to the business domain helps teams understand the context behind requirements.',
   ref:'Performance domain: Resources · Principle: Focus on value'},
  {id:'S4-P43',domain:D,task:7,approach:'Hybrid',type:'single',
   stem:'The organization wants project teams to share practical knowledge informally across departments. Which approach is simple and effective?',
   options:['Mandatory monthly reports','Regular short “lunch-and-learn” sessions where teams share techniques and lessons','A rule that knowledge stays within each team','Annual conferences only'],answer:[1],
   explanation:'Informal, regular sharing sessions spread practical knowledge with little overhead.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'S4-P44',domain:D,task:7,approach:'Predictive',type:'multi',
   stem:'Which TWO items should be included when transferring a completed system to the support team?',
   options:['Known issues and their workarounds','The project team’s personal opinions about stakeholders','Support procedures and escalation contacts','The original proposal drafts','Unrelated project templates'],answer:[0,2],
   explanation:'Support teams need practical knowledge of known issues, procedures and contacts to support the system.',
   ref:'Focus area: Closing · Performance domain: Resources'},

  // Task 8 — Communication (6)
  {id:'S4-P45',domain:D,task:8,approach:'Predictive',type:'dropdown',
   stem:'A project team grows from 8 to 12 members. How many additional communication channels are created?',
   options:['4','28','38','66'],answer:[2],
   explanation:'Channels = n(n – 1) ÷ 2. For 8 people: 28. For 12 people: 66. The increase is 66 – 28 = 38.',
   ref:'Performance domain: Stakeholders · Focus area: Planning'},
  {id:'S4-P46',domain:D,task:8,approach:'Hybrid',type:'single',
   stem:'A safety hazard has been discovered, and all site workers must know before the next shift starts. Which communication method is most appropriate?',
   options:['An entry in the monthly newsletter','An immediate safety briefing at the start of the shift, supported by posted notices, with confirmation that every crew has been informed','An email to supervisors only','A note in the project wiki'],answer:[1],
   explanation:'Urgent safety information needs direct, timely communication with confirmation of receipt.',
   ref:'Principle: Be an accountable leader · Performance domain: Stakeholders'},
  {id:'S4-P47',domain:D,task:8,approach:'Agile',type:'single',
   stem:'A weekly one-hour status meeting is mostly people reading updates aloud. What would improve it?',
   options:['Making the meeting longer','Sharing updates asynchronously beforehand and using the meeting time for discussion, decisions and removing blockers','Cancelling all communication','Asking only the project manager to speak'],answer:[1],
   explanation:'Meetings are most valuable for interaction and decisions. Status information can be shared asynchronously.',
   ref:'Principle: Focus on value · Focus area: Executing'},
  {id:'S4-P48',domain:D,task:8,approach:'Hybrid',type:'single',
   stem:'An architect gives the steering committee a highly technical explanation of a risk, and members are confused. What should the project manager do?',
   options:['Ask the architect to speak more slowly','Help translate the risk into business terms—its impact on cost, schedule, customers and options—so that the committee can decide','Remove the risk from the agenda','Let the committee figure it out'],answer:[1],
   explanation:'Communication must be tailored to the audience. Executives need business impacts and options.',
   ref:'Performance domain: Stakeholders · Focus area: Monitoring and Controlling'},
  {id:'S4-P49',domain:D,task:8,approach:'Predictive',type:'single',
   stem:'A key stakeholder is deaf and relies on written and visual communication. How should the project manager adapt the communication plan?',
   options:['Continue as usual','Ask the stakeholder about their preferences and provide accessible options—such as captions, sign-language interpretation and written summaries—for meetings and materials','Communicate only through their assistant','Exclude them from meetings'],answer:[1],
   explanation:'Communication should be accessible and tailored to individual needs, starting by asking the person.',
   ref:'Performance domain: Stakeholders · Principle: Integrate sustainability'},
  {id:'S4-P50',domain:D,task:8,approach:'Agile',type:'multi',
   stem:'A new department has joined the project, bringing several new stakeholders. Which TWO actions should the project manager take regarding communication?',
   options:['Update the communication plan with the new stakeholders’ information needs and preferred channels','Send them all past emails','Confirm with them how and how often they want to be updated','Add them to every meeting','Wait until they ask for information'],answer:[0,2],
   explanation:'Communication plans evolve as stakeholders change. Asking about needs ensures the right information reaches them.',
   ref:'Performance domain: Stakeholders · Focus area: Monitoring and Controlling'}
];
