import {ExamQuestion} from '../../exam-types';

const D='Process' as const;

export const PROCESS_QUESTIONS:ExamQuestion[]=[
  // Task 1 — Integrated plan and plan delivery (7)
  {id:'S4-R01',domain:D,task:1,approach:'Predictive',type:'single',
   stem:'Subsidiary plans for schedule and procurement contradict each other: the schedule assumes equipment arrives in March, but the procurement plan shows a June delivery. What does this reveal?',
   options:['Nothing; plans are independent','A gap in integration; the project manager must reconcile the plans so that the project management plan is consistent','The procurement plan should be deleted','The schedule should be hidden from stakeholders'],answer:[1],
   explanation:'Integration management ensures that subsidiary plans are consistent with each other and with the overall objectives.',
   ref:'Principle: Adopt a holistic view · Focus area: Planning'},
  {id:'S4-R02',domain:D,task:1,approach:'Hybrid',type:'single',
   stem:'An organization is new to hybrid delivery. What should the project manager document so that everyone understands how the project will work?',
   options:['Nothing; the team will figure it out','The tailored delivery approach: which parts are predictive or adaptive, how they integrate, the cadence of reviews, and how changes and decisions are handled','Only the Gantt chart','Only the product backlog'],answer:[1],
   explanation:'Documenting the tailored approach creates a shared understanding of how a hybrid project operates.',
   ref:'Performance domain: Governance · Focus area: Planning'},
  {id:'S4-R03',domain:D,task:1,approach:'Agile',type:'single',
   stem:'Which agile event is used to plan the work for the upcoming iteration and agree on its goal?',
   options:['Sprint review','Sprint planning','Sprint retrospective','Backlog refinement'],answer:[1],
   explanation:'In sprint planning, the team decides why the sprint is valuable (sprint goal), what can be done and how it will be done.',
   ref:'Performance domain: Schedule · Focus area: Planning'},
  {id:'S4-R04',domain:D,task:1,approach:'Predictive',type:'single',
   stem:'Halfway through planning, the project manager realizes that the team has not considered how the product will be supported after launch. Which part of planning was missed?',
   options:['Resource leveling','Planning for transition and operations—such as support, training and handover—as part of the project scope and plan','Earned value management','Procurement closure'],answer:[1],
   explanation:'A holistic plan includes the transition to operations so that benefits can be realized after delivery.',
   ref:'Principle: Adopt a holistic view · Focus area: Planning'},
  {id:'S4-R05',domain:D,task:1,approach:'Hybrid',type:'single',
   stem:'The project management plan has been approved. A month later, the team discovers that a key assumption is wrong. What should happen to the plan?',
   options:['Nothing; approved plans cannot change','Assess the impact of the invalid assumption and update the plan through the change control process','Ignore the assumption','Start a new project'],answer:[1],
   explanation:'Plans are updated through change control when assumptions prove wrong. The assumption log should also be updated.',
   ref:'Performance domain: Governance · Focus area: Monitoring and Controlling'},
  {id:'S4-R06',domain:D,task:1,approach:'Agile',type:'single',
   stem:'A start-up wants to launch a new app quickly, with highly uncertain customer needs. Which planning approach suits it best?',
   options:['A detailed two-year plan with fixed scope','A lean, adaptive approach: a product vision, a short roadmap of hypotheses and frequent releases to learn from customers','A predictive approach with phase gates','No planning at all'],answer:[1],
   explanation:'High uncertainty calls for adaptive planning focused on rapid learning.',
   ref:'Principle: Adopt a holistic view · Principle: Focus on value'},
  {id:'S4-R07',domain:D,task:1,approach:'Hybrid',type:'multi',
   stem:'Which TWO actions help ensure that the project management plan remains useful throughout the project?',
   options:['Updating it through change control when significant changes occur','Filing it away after approval','Reviewing it with the team at key points to confirm it still reflects how work is done','Making it as long as possible','Keeping it secret from the team'],answer:[0,2],
   explanation:'A plan stays useful when it is maintained and used as a living guide.',
   ref:'Performance domain: Governance · Focus area: Monitoring and Controlling'},

  // Task 2 — Scope (7)
  {id:'S4-R08',domain:D,task:2,approach:'Predictive',type:'matching',
   stem:'Match each component of the scope baseline to its description.',
   pairs:[{left:'Project scope statement',right:0},{left:'Work breakdown structure (WBS)',right:1},{left:'WBS dictionary',right:2}],
   choices:['Describes the project’s scope, major deliverables, assumptions, constraints and exclusions','Hierarchically decomposes the total scope of work into deliverables and work packages','Provides detailed information about each WBS component'],
   explanation:'Together, the approved scope statement, WBS and WBS dictionary form the scope baseline.',
   ref:'Performance domain: Scope · Focus area: Planning'},
  {id:'S4-R09',domain:D,task:2,approach:'Predictive',type:'single',
   stem:'What is the difference between product scope and project scope?',
   options:['They are the same','Product scope is the features and functions of the result; project scope is the work needed to deliver it','Project scope is always smaller','Product scope includes the project budget'],answer:[1],
   explanation:'Product scope is measured against product requirements; project scope is measured against the project management plan.',
   ref:'Performance domain: Scope · Focus area: Planning'},
  {id:'S4-R10',domain:D,task:2,approach:'Agile',type:'single',
   stem:'A user story is too large to finish in one sprint. What should the team do?',
   options:['Extend the sprint','Split the story into smaller stories that each deliver some value and can be completed within a sprint','Assign it to the most senior developer','Remove it from the backlog'],answer:[1],
   explanation:'Splitting large stories into small, valuable slices keeps flow steady and feedback frequent.',
   ref:'Performance domain: Scope · Focus area: Planning'},
  {id:'S4-R11',domain:D,task:2,approach:'Hybrid',type:'single',
   stem:'Stakeholders from five departments have different requirements for a shared system. Which technique helps them reach agreement efficiently?',
   options:['Individual interviews only','A facilitated workshop—such as a joint application design session—with representatives of all departments','Letting IT decide','A survey with no follow-up'],answer:[1],
   explanation:'Facilitated workshops bring stakeholders together to define and reconcile requirements quickly.',
   ref:'Performance domain: Scope · Focus area: Planning'},
  {id:'S4-R12',domain:D,task:2,approach:'Predictive',type:'single',
   stem:'The customer refuses to accept a deliverable, saying it does not meet expectations, but the team believes it meets the documented requirements. What should the project manager do first?',
   options:['Escalate to legal','Review the deliverable with the customer against the agreed acceptance criteria to identify the specific gaps','Redo the deliverable completely','Close the project'],answer:[1],
   explanation:'The agreed acceptance criteria are the objective basis for validating scope and resolving disputes.',
   ref:'Performance domain: Scope · Focus area: Monitoring and Controlling'},
  {id:'S4-R13',domain:D,task:2,approach:'Agile',type:'single',
   stem:'Who is responsible for writing and maintaining the product backlog in Scrum?',
   options:['The Scrum Master','The product owner, although others may help add items','The sponsor','The project manager alone'],answer:[1],
   explanation:'The product owner is accountable for the product backlog, including its content and order.',
   ref:'Performance domain: Scope · Focus area: Planning'},
  {id:'S4-R14',domain:D,task:2,approach:'Hybrid',type:'multi',
   stem:'Which TWO practices help prevent scope creep?',
   options:['A clear scope baseline or a well-managed, prioritized backlog','Accepting small changes informally','A defined process for evaluating and approving changes','Adding features the team thinks are useful','Avoiding stakeholder reviews'],answer:[0,2],
   explanation:'Clear scope definitions and a disciplined change process keep scope under control.',
   ref:'Performance domain: Scope · Performance domain: Governance'},

  // Task 3 — Value (7)
  {id:'S4-R15',domain:D,task:3,approach:'Predictive',type:'dropdown',
   stem:'A project costs $200,000 today and returns $110,000 at the end of year 1 and $121,000 at the end of year 2. Using a 10% discount rate, what is its net present value (NPV)?',
   options:['–$10,000','$0','$21,000','$31,000'],answer:[1],
   explanation:'PV of year 1 = 110,000 ÷ 1.10 = 100,000. PV of year 2 = 121,000 ÷ 1.21 = 100,000. NPV = 200,000 – 200,000 = $0.',
   ref:'Principle: Focus on value · Performance domain: Finance'},
  {id:'S4-R16',domain:D,task:3,approach:'Agile',type:'single',
   stem:'The product owner wants to know which backlog items customers value most. Which technique asks customers to allocate a fixed budget across features?',
   options:['Planning poker','“Buy a feature” or 100-point prioritization','Burndown analysis','Fishbone diagram'],answer:[1],
   explanation:'Allocation games such as “buy a feature” reveal relative value from the customer’s perspective.',
   ref:'Principle: Focus on value · Performance domain: Scope'},
  {id:'S4-R17',domain:D,task:3,approach:'Hybrid',type:'single',
   stem:'A project was justified by expected savings of $500,000 per year. Six months after launch, savings are $150,000. What should happen?',
   options:['Nothing; the project is closed','The benefits owner analyzes the gap and works with stakeholders on actions to realize the benefits, reporting the results to governance','Ask the project team to return','Change the business case to $150,000'],answer:[1],
   explanation:'Benefits realization continues after closure. The benefits owner tracks results and drives actions to close gaps.',
   ref:'Principle: Focus on value · Focus area: Closing'},
  {id:'S4-R18',domain:D,task:3,approach:'Agile',type:'single',
   stem:'A team releases features continuously, but no one checks whether they are used. What practice should the team adopt?',
   options:['Release less often','Define a success measure for each significant feature and review usage and outcome data after release to guide future work','Stop asking for feedback','Add more features faster'],answer:[1],
   explanation:'Measuring outcomes after release closes the value loop and informs prioritization.',
   ref:'Principle: Focus on value · Focus area: Monitoring and Controlling'},
  {id:'S4-R19',domain:D,task:3,approach:'Predictive',type:'single',
   stem:'Which document describes how and when the benefits of a project will be delivered and measured?',
   options:['Benefits management plan','Configuration management plan','Communication management plan','Quality checklist'],answer:[0],
   explanation:'The benefits management plan describes target benefits, timing, measures, owners and risks to benefits.',
   ref:'Principle: Focus on value · Focus area: Planning'},
  {id:'S4-R20',domain:D,task:3,approach:'Hybrid',type:'single',
   stem:'Two features have the same value. Feature A takes two weeks; Feature B takes six weeks. Using weighted shortest job first (WSJF), which should be done first?',
   options:['Feature B, because it is bigger','Feature A, because the same cost of delay divided by a shorter duration gives a higher priority','Either; WSJF does not consider size','Neither'],answer:[1],
   explanation:'WSJF = cost of delay ÷ job size. With equal value and urgency, the smaller job is done first to deliver value sooner.',
   ref:'Principle: Focus on value · Performance domain: Scope'},
  {id:'S4-R21',domain:D,task:3,approach:'Agile',type:'multi',
   stem:'Which TWO practices help a team deliver value continuously?',
   options:['Releasing small increments frequently','Waiting until all features are finished','Prioritizing the backlog by value with stakeholder input','Measuring success only by budget use','Avoiding customer contact'],answer:[0,2],
   explanation:'Frequent small releases and value-based prioritization keep value flowing to customers.',
   ref:'Principle: Focus on value · Focus area: Executing'},

  // Task 4 — Resources (6)
  {id:'S4-R22',domain:D,task:4,approach:'Predictive',type:'single',
   stem:'Which document describes how team members and physical resources will be estimated, acquired, managed and released?',
   options:['Resource management plan','Risk register','Benefits register','Configuration plan'],answer:[0],
   explanation:'The resource management plan guides how resources are categorized, allocated, managed and released.',
   ref:'Performance domain: Resources · Focus area: Planning'},
  {id:'S4-R23',domain:D,task:4,approach:'Hybrid',type:'single',
   stem:'Two projects need the same scarce specialist in the same month. The portfolio has a clear priority ranking. How should the conflict be resolved?',
   options:['The project manager who asks first gets the specialist','Escalate to portfolio or resource governance, which allocates the specialist based on the agreed priorities','Split the specialist evenly without discussion','Hire a second specialist without approval'],answer:[1],
   explanation:'Cross-project resource conflicts are resolved by the governance that sets priorities across the portfolio.',
   ref:'Performance domain: Governance · Performance domain: Resources'},
  {id:'S4-R24',domain:D,task:4,approach:'Agile',type:'single',
   stem:'A team is consistently overloaded because it commits to more work than it can finish. What should the team do in sprint planning?',
   options:['Commit to even more work','Use its recent velocity and actual capacity to select a realistic amount of work','Ask the product owner to choose for the team','Skip planning'],answer:[1],
   explanation:'Planning based on demonstrated capacity creates realistic commitments and a sustainable pace.',
   ref:'Performance domain: Resources · Focus area: Planning'},
  {id:'S4-R25',domain:D,task:4,approach:'Predictive',type:'single',
   stem:'An activity needs 120 hours of a specialist who can work 6 hours a day on the project. How many working days will the activity take?',
   options:['15 days','20 days','24 days','30 days'],answer:[1],
   explanation:'Duration = effort ÷ available hours per day = 120 ÷ 6 = 20 working days. Effort and duration are different.',
   ref:'Performance domains: Resources, Schedule · Focus area: Planning'},
  {id:'S4-R26',domain:D,task:4,approach:'Hybrid',type:'single',
   stem:'Contractors on the team receive no feedback and feel excluded from team events. What should the project manager do?',
   options:['Treat contractors differently by policy','Include contractors in team rituals and recognition where appropriate, and provide regular feedback on their work','Communicate with contractors only through their agency','Replace them with employees'],answer:[1],
   explanation:'Including all team members builds a cohesive team and better performance, within contractual boundaries.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'S4-R27',domain:D,task:4,approach:'Predictive',type:'multi',
   stem:'Which TWO factors should be considered when estimating activity resources?',
   options:['The skills and availability of team members and equipment','The project manager’s favourite vendor','Historical data from similar activities','The colour of the equipment','Rumours about future budgets'],answer:[0,2],
   explanation:'Resource estimates draw on resource availability and capability as well as historical information.',
   ref:'Performance domain: Resources · Focus area: Planning'},

  // Task 5 — Procurement (6)
  {id:'S4-R28',domain:D,task:5,approach:'Predictive',type:'dropdown',
   stem:'A time-and-materials contract pays $95 per hour. The work is expected to take 120 hours, plus $3,000 in materials. What is the expected contract cost?',
   options:['$11,400','$12,600','$14,400','$15,000'],answer:[2],
   explanation:'Labour = 120 × $95 = $11,400. Total = $11,400 + $3,000 materials = $14,400.',
   ref:'Performance domains: Finance, Resources (procurement)'},
  {id:'S4-R29',domain:D,task:5,approach:'Predictive',type:'single',
   stem:'A five-year contract for steel supply includes a clause that adjusts the price based on a published steel price index. What type of contract is this?',
   options:['Firm fixed price','Fixed price with economic price adjustment','Cost plus fixed fee','Time and materials'],answer:[1],
   explanation:'Economic price adjustment clauses protect both parties from changes in market conditions on long contracts.',
   ref:'Performance domain: Resources (procurement) · Performance domain: Risk'},
  {id:'S4-R30',domain:D,task:5,approach:'Hybrid',type:'single',
   stem:'Before issuing a request for proposal, the project manager wants an independent estimate of what the work should cost. Why?',
   options:['To share it with the bidders','To have a benchmark for evaluating whether proposals are reasonable','To replace the bids','To set the seller’s profit'],answer:[1],
   explanation:'Independent cost estimates help the buyer judge the reasonableness of bids and identify misunderstandings.',
   ref:'Performance domain: Resources (procurement) · Focus area: Planning'},
  {id:'S4-R31',domain:D,task:5,approach:'Predictive',type:'single',
   stem:'Two companies agree to submit a joint proposal, with one as prime contractor and the other as subcontractor. What is this arrangement called?',
   options:['Teaming agreement','Purchase order','Letter of intent from the buyer','Non-disclosure agreement'],answer:[0],
   explanation:'A teaming agreement is a contract between two or more parties to pursue an opportunity together.',
   ref:'Performance domain: Resources (procurement) · Focus area: Planning'},
  {id:'S4-R32',domain:D,task:5,approach:'Agile',type:'single',
   stem:'A buyer wants to try a new agile vendor without a long commitment. Which procurement approach reduces the risk?',
   options:['A five-year exclusive contract','A short initial engagement—such as a few sprints with clear goals—with an option to continue based on results','No contract','Paying the full amount in advance'],answer:[1],
   explanation:'Incremental contracting lets the buyer evaluate performance before committing further.',
   ref:'Performance domains: Resources (procurement), Risk'},
  {id:'S4-R33',domain:D,task:5,approach:'Predictive',type:'multi',
   stem:'Which TWO items are typically used to evaluate seller proposals?',
   options:['Predefined source-selection criteria with weights','The seller’s office decor','An independent cost estimate for comparison','The personal preferences of one team member','The length of the proposal'],answer:[0,2],
   explanation:'Objective criteria and independent estimates support fair and well-reasoned seller selection.',
   ref:'Performance domain: Resources (procurement) · Focus area: Executing'},

  // Task 6 — Finance (7)
  {id:'S4-R34',domain:D,task:6,approach:'Predictive',type:'dropdown',
   stem:'Three identified risks have the following expected costs if they occur: 20% × $50,000, 10% × $100,000 and 30% × $20,000. What contingency reserve does expected monetary value suggest?',
   options:['$16,000','$26,000','$34,000','$170,000'],answer:[1],
   explanation:'EMV = 0.2 × 50,000 + 0.1 × 100,000 + 0.3 × 20,000 = 10,000 + 10,000 + 6,000 = $26,000.',
   ref:'Performance domains: Finance, Risk · Focus area: Planning'},
  {id:'S4-R35',domain:D,task:6,approach:'Predictive',type:'single',
   stem:'EV = $450,000 and AC = $500,000. What is the CPI, and what does it mean?',
   options:['1.11; the project is under budget','0.90; the project gets 90 cents of value for every dollar spent','0.90; the project is ahead of schedule','1.11; the project is behind schedule'],answer:[1],
   explanation:'CPI = EV ÷ AC = 450,000 ÷ 500,000 = 0.90, which means the project is over budget for the work completed.',
   ref:'Performance domain: Finance · Focus area: Monitoring and Controlling'},
  {id:'S4-R36',domain:D,task:6,approach:'Predictive',type:'single',
   stem:'How is the project budget built from the bottom up?',
   options:['By guessing a total','By aggregating activity cost estimates into work packages and control accounts, then adding contingency reserves (cost baseline) and management reserve (total budget)','By copying the last project’s budget','By dividing the sponsor’s target equally across months'],answer:[1],
   explanation:'Cost aggregation rolls estimates up through the WBS, and reserves are added at the appropriate levels.',
   ref:'Performance domain: Finance · Focus area: Planning'},
  {id:'S4-R37',domain:D,task:6,approach:'Hybrid',type:'single',
   stem:'The sponsor asks the project manager to move unused contingency reserve into new scope that a stakeholder requested. What should the project manager do?',
   options:['Move the money immediately','Explain that contingency is for identified risks, and process the new scope as a change request with its own funding decision','Hide the reserve','Spend the reserve on team bonuses'],answer:[1],
   explanation:'Reserves have specific purposes. New scope is a change that needs its own approval and funding.',
   ref:'Performance domains: Finance, Governance'},
  {id:'S4-R38',domain:D,task:6,approach:'Agile',type:'single',
   stem:'How can an agile team give stakeholders confidence about spending when scope is flexible?',
   options:['By hiding costs until the end','By showing cost per sprint, value delivered so far and a forecast of remaining cost for the prioritized backlog','By fixing all scope in advance','By reporting only hours worked'],answer:[1],
   explanation:'Transparent run-rate costs, linked to value delivered and forecasts, give stakeholders financial visibility.',
   ref:'Performance domain: Finance · Principle: Focus on value'},
  {id:'S4-R39',domain:D,task:6,approach:'Predictive',type:'single',
   stem:'A project manager adds a hidden 20% “padding” to every activity estimate. Why is this a poor practice?',
   options:['It is good practice','It hides uncertainty, inflates the budget and schedule, and prevents reserves from being managed transparently; risk-based reserves are better','It reduces the budget','It is required by governance'],answer:[1],
   explanation:'Transparent, risk-based reserves are more honest and easier to manage than hidden padding.',
   ref:'Performance domain: Finance · Principle: Be an accountable leader'},
  {id:'S4-R40',domain:D,task:6,approach:'Hybrid',type:'multi',
   stem:'Which TWO items are typically included in the total project budget but NOT in the cost baseline?',
   options:['Management reserve','Contingency reserve','Funds for unidentified risks (unknown-unknowns)','Work package estimates','Control account budgets'],answer:[0,2],
   explanation:'Management reserve, which covers unknown-unknowns, sits outside the cost baseline. Contingency reserves are included in it.',
   ref:'Performance domain: Finance · Focus area: Planning'},

  // Task 7 — Quality (6)
  {id:'S4-R41',domain:D,task:7,approach:'Agile',type:'single',graphic:'pareto-2',
   stem:'Based on the Pareto chart, which categories together account for about 80% of complaints?',
   options:['Slow response only','Slow response, unclear status and login problems','Payment errors and other','All five categories equally'],answer:[1],
   explanation:'Slow response (38) + unclear status (27) + login problems (15) = 80 of 100 complaints. Focusing on these three gives the largest improvement.',
   ref:'Principle: Embed quality · Focus area: Monitoring and Controlling'},
  {id:'S4-R42',domain:D,task:7,approach:'Predictive',type:'single',graphic:'control-4',
   stem:'The control chart shows daily average pump vibration. All points are within the control limits. What should the project manager conclude?',
   options:['The process is stable; no action is needed','The last seven points rise steadily, a non-random trend that should be investigated before the limit is exceeded','The limits should be widened','The mean should be raised to 55'],answer:[1],
   explanation:'A run of seven consecutive increasing points is a trend that signals a special cause, even within the control limits.',
   ref:'Principle: Embed quality · Focus area: Monitoring and Controlling'},
  {id:'S4-R43',domain:D,task:7,approach:'Predictive',type:'single',
   stem:'What is the main difference between quality assurance and quality control?',
   options:['They are the same','Quality assurance focuses on the processes used to produce deliverables; quality control inspects the deliverables themselves','Quality control is done before work starts','Quality assurance is done only by the customer'],answer:[1],
   explanation:'Assurance builds confidence that processes will produce quality results; control checks the outputs.',
   ref:'Principle: Embed quality · Focus areas: Executing, Monitoring and Controlling'},
  {id:'S4-R44',domain:D,task:7,approach:'Hybrid',type:'single',
   stem:'Peer reviews of design documents catch many defects before construction starts. What category of quality cost are these reviews?',
   options:['External failure cost','Appraisal cost (cost of conformance)','Internal failure cost','Opportunity cost'],answer:[1],
   explanation:'Reviews and inspections are appraisal costs. They are part of the cost of conformance and prevent more expensive failures.',
   ref:'Principle: Embed quality · Performance domain: Finance'},
  {id:'S4-R45',domain:D,task:7,approach:'Agile',type:'single',
   stem:'A team practises test-driven development (TDD). What does this mean?',
   options:['Testing only at the end of the project','Writing an automated test before writing the code that makes it pass, then refactoring','Letting testers write all code','Testing only in production'],answer:[1],
   explanation:'TDD builds quality in from the start and produces a safety net of automated tests.',
   ref:'Principle: Embed quality · Focus area: Executing'},
  {id:'S4-R46',domain:D,task:7,approach:'Hybrid',type:'multi',
   stem:'Which TWO actions improve the quality of deliverables before they reach the customer?',
   options:['Defining clear acceptance criteria and quality standards early','Skipping reviews to save time','Building in reviews, testing and validation at each stage','Relying on customers to find defects','Reducing quality requirements to meet the date without approval'],answer:[0,2],
   explanation:'Early quality definitions and checks at each stage prevent defects from reaching customers.',
   ref:'Principle: Embed quality · Focus area: Planning'},

  // Task 8 — Schedule (6)
  {id:'S4-R47',domain:D,task:8,approach:'Predictive',type:'dropdown',
   stem:'An activity has an optimistic estimate of 8 days and a pessimistic estimate of 20 days. Using the PERT approximation, what is the standard deviation?',
   options:['1 day','2 days','3 days','6 days'],answer:[1],
   explanation:'Standard deviation ≈ (P – O) ÷ 6 = (20 – 8) ÷ 6 = 2 days. A larger value indicates more uncertainty.',
   ref:'Performance domains: Schedule, Risk · Focus area: Planning'},
  {id:'S4-R48',domain:D,task:8,approach:'Predictive',type:'dropdown',
   stem:'An activity has optimistic, most likely and pessimistic estimates of 6, 9 and 15 days. What is the triangular-distribution estimate?',
   options:['9 days','9.5 days','10 days','15 days'],answer:[2],
   explanation:'Triangular estimate = (O + M + P) ÷ 3 = (6 + 9 + 15) ÷ 3 = 10 days. The PERT (beta) estimate would be (6 + 36 + 15) ÷ 6 = 9.5 days.',
   ref:'Performance domain: Schedule · Focus area: Planning'},
  {id:'S4-R49',domain:D,task:8,approach:'Predictive',type:'single',
   stem:'What is the schedule baseline?',
   options:['The latest version of the schedule','The approved version of the schedule model, used as a basis for comparison and changed only through change control','The milestone list','The team’s preferred dates'],answer:[1],
   explanation:'The schedule baseline is the approved reference for measuring schedule performance.',
   ref:'Performance domain: Schedule · Focus area: Planning'},
  {id:'S4-R50',domain:D,task:8,approach:'Agile',type:'single',
   stem:'A Scrum team’s product owner asks for a feature to be delivered by a specific date three sprints away. How should the team respond?',
   options:['Guarantee the date immediately','Use the backlog order and velocity to forecast whether the feature fits within three sprints, and discuss trade-offs if it does not','Refuse to discuss dates','Work overtime from now on'],answer:[1],
   explanation:'Velocity-based forecasting supports realistic date discussions and transparent trade-offs.',
   ref:'Performance domain: Schedule · Focus area: Planning'},
  {id:'S4-R51',domain:D,task:8,approach:'Hybrid',type:'single',
   stem:'Which schedule-compression technique usually increases cost but not risk of rework?',
   options:['Fast tracking','Crashing','Resource smoothing','Rolling-wave planning'],answer:[1],
   explanation:'Crashing adds resources to shorten activities, which increases cost. Fast tracking overlaps activities and increases rework risk.',
   ref:'Performance domain: Schedule · Focus area: Monitoring and Controlling'},
  {id:'S4-R52',domain:D,task:8,approach:'Predictive',type:'multi',
   stem:'Which TWO inputs are most important for developing a realistic schedule?',
   options:['Activity duration estimates and dependencies','The sponsor’s preferred end date alone','Resource availability (calendars)','The colour scheme of the Gantt chart','The number of pages in the charter'],answer:[0,2],
   explanation:'Realistic schedules combine durations, logical dependencies and resource availability.',
   ref:'Performance domain: Schedule · Focus area: Planning'},

  // Task 9 — Evaluate status (5)
  {id:'S4-R53',domain:D,task:9,approach:'Predictive',type:'dropdown',
   stem:'PV = $800,000 and EV = $720,000. What is the SPI?',
   options:['0.80','0.90','1.11','1.20'],answer:[1],
   explanation:'SPI = EV ÷ PV = 720,000 ÷ 800,000 = 0.90. The project has completed 90% of the work planned by this date.',
   ref:'Performance domain: Schedule · Focus area: Monitoring and Controlling'},
  {id:'S4-R54',domain:D,task:9,approach:'Predictive',type:'single',
   stem:'BAC = $2,000,000 and EV = $500,000. What percentage of the work is complete?',
   options:['20%','25%','40%','50%'],answer:[1],
   explanation:'Percent complete = EV ÷ BAC = 500,000 ÷ 2,000,000 = 25%.',
   ref:'Performance domain: Finance · Focus area: Monitoring and Controlling'},
  {id:'S4-R55',domain:D,task:9,approach:'Agile',type:'single',
   stem:'An agile team reports 100% of sprint commitments met for six sprints, but customers see few improvements. What should the project manager examine?',
   options:['Nothing; the team is performing well','Whether the team is delivering valuable, releasable outcomes—or only completing tasks that do not reach customers','The team’s attendance','The length of the daily standup'],answer:[1],
   explanation:'Output metrics can look healthy while value is not delivered. Status should include outcome measures.',
   ref:'Principle: Focus on value · Focus area: Monitoring and Controlling'},
  {id:'S4-R56',domain:D,task:9,approach:'Hybrid',type:'single',
   stem:'What is the main purpose of forecasting in project status reporting?',
   options:['To replace the baseline','To predict future performance and outcomes, such as EAC and completion date, so that decisions can be made early','To report past performance only','To satisfy auditors'],answer:[1],
   explanation:'Forecasts turn past performance into expectations about the future, enabling timely corrective action.',
   ref:'Performance domains: Finance, Schedule · Focus area: Monitoring and Controlling'},
  {id:'S4-R57',domain:D,task:9,approach:'Predictive',type:'multi',
   stem:'Which TWO data sources give the most objective view of project status?',
   options:['Accepted deliverables and measured progress against the baseline','Opinions from the most optimistic team member','Actual cost and earned value data','Hallway conversations','The sponsor’s hopes'],answer:[0,2],
   explanation:'Accepted deliverables and earned value data provide objective evidence of progress.',
   ref:'Principle: Be an accountable leader · Focus area: Monitoring and Controlling'},

  // Task 10 — Closure (5)
  {id:'S4-R58',domain:D,task:10,approach:'Predictive',type:'single',
   stem:'A project is complete, but the sponsor will not sign the acceptance form because of an unrelated dispute with the vendor. What should the project manager do?',
   options:['Close the project without acceptance','Document that the deliverables meet the acceptance criteria, escalate the acceptance issue through governance, and keep the vendor dispute separate','Wait indefinitely','Redo the deliverables'],answer:[1],
   explanation:'Acceptance should be based on the agreed criteria. Separate disputes are handled through their own channels.',
   ref:'Focus area: Closing · Performance domain: Governance'},
  {id:'S4-R59',domain:D,task:10,approach:'Hybrid',type:'single',
   stem:'Why should lessons learned be captured from both successes and failures at closure?',
   options:['Only failures matter','Successes show practices worth repeating, while failures show what to avoid; both improve future projects','Only successes should be shared','Lessons are not needed at closure'],answer:[1],
   explanation:'A balanced review captures good practices as well as problems to avoid.',
   ref:'Principle: Embed quality · Focus area: Closing'},
  {id:'S4-R60',domain:D,task:10,approach:'Agile',type:'single',
   stem:'An agile project ends because the product owner decides that the remaining backlog items have too little value to justify further investment. Is this appropriate?',
   options:['No; all backlog items must be completed','Yes; stopping when remaining value no longer justifies the cost is a valid, value-based decision, followed by an orderly closure','No; the team must work until the budget is spent','Only if the sponsor is absent'],answer:[1],
   explanation:'Agile projects can end when enough value has been delivered. Closure activities still apply.',
   ref:'Principle: Focus on value · Focus area: Closing'},
  {id:'S4-R61',domain:D,task:10,approach:'Predictive',type:'single',
   stem:'Which activity confirms that all contractual obligations have been met before a contract is closed?',
   options:['A procurement audit or contract review against the terms and deliverables','A team-building event','A sprint review','A kickoff meeting'],answer:[0],
   explanation:'Procurement audits and contract reviews verify that obligations were met and capture lessons for future procurements.',
   ref:'Focus area: Closing · Performance domain: Resources (procurement)'},
  {id:'S4-R62',domain:D,task:10,approach:'Hybrid',type:'multi',
   stem:'Which TWO actions help ensure that the project’s results continue to deliver value after closure?',
   options:['Assigning benefit owners and measures in the receiving organization','Deleting the project records','Confirming that the operations team has the knowledge and resources to sustain the product','Disbanding the team before handover','Ending all communication with users'],answer:[0,2],
   explanation:'Sustained value depends on clear benefit ownership and a capable receiving organization.',
   ref:'Principle: Focus on value · Focus area: Closing'}
];
