import {ExamQuestion} from '../../exam-types';

const D='Business Environment' as const;

export const BUSINESS_ENVIRONMENT_QUESTIONS:ExamQuestion[]=[
  // Task 1 — Governance (5)
  {id:'S2-B01',domain:D,task:1,approach:'Predictive',type:'matching',
   stem:'Match each type of PMO to its description.',
   pairs:[{left:'Supportive PMO',right:0},{left:'Controlling PMO',right:1},{left:'Directive PMO',right:2}],
   choices:['Provides templates, training and lessons learned; low control over projects','Requires compliance with frameworks, tools and governance; moderate control','Directly manages projects by assigning project managers; high control'],
   explanation:'PMOs vary in the degree of control they exert, from supportive (consultative) to controlling (compliance) to directive (direct management).',
   ref:'Performance domain: Governance · Focus area: Initiating'},
  {id:'S2-B02',domain:D,task:1,approach:'Predictive',type:'single',
   stem:'In which organizational structure does the project manager usually have the least authority over resources and budget?',
   options:['Projectized','Strong matrix','Functional','Project-oriented PMO'],answer:[2],
   explanation:'In a functional organization, functional managers control resources and budget, and the project manager often acts as a coordinator.',
   ref:'Performance domain: Governance · Focus area: Initiating'},
  {id:'S2-B03',domain:D,task:1,approach:'Hybrid',type:'single',
   stem:'What is the main difference between a program and a portfolio?',
   options:['They are the same','A program is a group of related projects managed together to obtain benefits not available individually; a portfolio is a collection of projects, programs and operations managed to achieve strategic objectives','A portfolio is always smaller than a program','A program has no projects'],answer:[1],
   explanation:'Programs coordinate related work for combined benefits; portfolios select and balance investments to meet strategy.',
   ref:'Performance domain: Governance · Principle: Adopt a holistic view'},
  {id:'S2-B04',domain:D,task:1,approach:'Agile',type:'single',
   stem:'Decisions on an agile program are often revisited because no one remembers why they were made. What governance practice would help?',
   options:['More meetings','A lightweight decision log that records each significant decision, its rationale, the decision-maker and the date','Requiring the sponsor to approve every decision','Avoiding decisions until all information is known'],answer:[1],
   explanation:'A decision log creates transparency and accountability, and prevents rework from revisiting settled decisions.',
   ref:'Performance domain: Governance · Focus area: Executing'},
  {id:'S2-B05',domain:D,task:1,approach:'Hybrid',type:'multi',
   stem:'Which TWO responsibilities usually belong to a project steering committee?',
   options:['Making decisions that exceed the project manager’s authority','Writing user stories','Providing strategic direction and resolving escalated issues','Assigning daily tasks to developers','Running sprint retrospectives'],answer:[0,2],
   explanation:'Steering committees provide direction, approve major changes and resolve escalations; they do not manage day-to-day work.',
   ref:'Performance domain: Governance · Focus area: Monitoring and Controlling'},

  // Task 2 — Compliance (4)
  {id:'S2-B06',domain:D,task:2,approach:'Hybrid',type:'single',
   stem:'A cloud vendor proposes to store Canadian customer data in data centres outside Canada. The organization’s policy requires data to remain in Canada. What should the project manager do?',
   options:['Accept the vendor’s proposal because it is cheaper','Treat data residency as a compliance requirement: require in-country hosting in the contract or choose a compliant option, with input from privacy and legal teams','Ignore the policy because the cloud is secure','Ask the team to decide'],answer:[1],
   explanation:'Organizational policies and legal obligations on data residency are compliance requirements that must be built into procurement and design.',
   ref:'Performance domain: Governance · Focus area: Planning'},
  {id:'S2-B07',domain:D,task:2,approach:'Predictive',type:'single',
   stem:'The sponsor asks the project manager to report a milestone as “complete” to secure the next funding tranche, although testing is unfinished. What should the project manager do?',
   options:['Report it as complete to protect funding','Report the milestone’s true status, explain the remaining work and help the sponsor present an honest recovery plan to the funding body','Ask the team to skip testing','Avoid reporting until testing is done'],answer:[1],
   explanation:'Honesty is a core professional value. Misreporting status is unethical and may breach funding conditions.',
   ref:'Principle: Be an accountable leader · Ethics'},
  {id:'S2-B08',domain:D,task:2,approach:'Predictive',type:'single',
   stem:'A construction subcontractor’s workers are seen without required fall protection. What should the project manager do?',
   options:['Mention it at the next weekly meeting','Ensure the unsafe work stops immediately, notify the subcontractor and the safety officer, and confirm that corrective action is in place before work resumes','Take photos for the final report','Ask the workers to be careful'],answer:[1],
   explanation:'Occupational health and safety rules are legal requirements. Immediate action to stop unsafe work takes priority over schedule.',
   ref:'Principle: Be an accountable leader · Performance domain: Governance'},
  {id:'S2-B09',domain:D,task:2,approach:'Agile',type:'multi',
   stem:'Which TWO practices help an agile team demonstrate compliance to auditors without heavy documentation?',
   options:['Automated tests and pipelines that produce traceable evidence for each release','Skipping documentation because agile values working software','Linking backlog items to the regulatory requirements they satisfy','Keeping compliance knowledge in one person’s head','Holding a single compliance review at the end'],answer:[0,2],
   explanation:'Traceability and automated evidence provide continuous, auditable compliance with minimal overhead.',
   ref:'Principle: Embed quality · Performance domain: Governance'},

  // Task 3 — Manage and control changes (6)
  {id:'S2-B10',domain:D,task:3,approach:'Predictive',type:'single',
   stem:'A production outage requires an immediate configuration change outside the normal change process. What should happen?',
   options:['Make the change and never document it','Follow the emergency change procedure: obtain the authorized approval, implement the change, then document it and submit it for retrospective review','Wait for the next change control board meeting','Ask the vendor to make the change without approval'],answer:[1],
   explanation:'Emergency changes are allowed through a defined fast path, but they must still be approved, documented and reviewed.',
   ref:'Performance domain: Governance · Focus area: Monitoring and Controlling'},
  {id:'S2-B11',domain:D,task:3,approach:'Predictive',type:'single',
   stem:'What is the purpose of a change log?',
   options:['To record all change requests and their status, decisions and dates','To list team members who requested leave','To record defects only','To replace the risk register'],answer:[0],
   explanation:'The change log provides a complete record of change requests and decisions, supporting transparency and audits.',
   ref:'Performance domain: Governance · Focus area: Monitoring and Controlling'},
  {id:'S2-B12',domain:D,task:3,approach:'Predictive',type:'single',
   stem:'What is the correct order of steps in integrated change control?',
   options:['Implement the change, then analyze its impact, then approve it','Document the request, analyze its impact, decide (approve or reject) through the authorized body, then update plans, implement and communicate','Approve the change, then document it','Communicate the change, then decide'],answer:[1],
   explanation:'Changes are documented, analyzed, decided by the right authority and then implemented and communicated.',
   ref:'Performance domain: Governance · Focus area: Monitoring and Controlling'},
  {id:'S2-B13',domain:D,task:3,approach:'Hybrid',type:'single',
   stem:'Many small, uncontrolled changes have increased the project’s scope by 15% without budget or schedule adjustments. What should the project manager do now?',
   options:['Continue absorbing changes','Analyze the cumulative impact, present it to the sponsor and change control board, and reinforce the change control process with the team and stakeholders','Remove the changes without discussion','Blame the stakeholders'],answer:[1],
   explanation:'Cumulative scope creep must be made visible and addressed through governance, and the process must be reinforced to prevent recurrence.',
   ref:'Performance domains: Scope, Governance · Focus area: Monitoring and Controlling'},
  {id:'S2-B14',domain:D,task:3,approach:'Agile',type:'single',
   stem:'In Scrum, who can cancel a sprint, and why?',
   options:['The Scrum Master, when the team is behind','The product owner, when the sprint goal becomes obsolete','Any stakeholder, when priorities change','The developers, when they are tired'],answer:[1],
   explanation:'Only the product owner can cancel a sprint, and only if the sprint goal becomes obsolete—for example, because of a major change in direction.',
   ref:'Performance domain: Scope · Focus area: Executing'},
  {id:'S2-B15',domain:D,task:3,approach:'Hybrid',type:'multi',
   stem:'Which TWO people are typically appropriate members of a change control board?',
   options:['The sponsor or a delegated decision-maker','Every team member','Representatives of key stakeholder groups and technical experts','A randomly selected end user','The vendor’s sales representative'],answer:[0,2],
   explanation:'A CCB includes people with authority and the expertise needed to assess the impacts of changes.',
   ref:'Performance domain: Governance · Focus area: Planning'},

  // Task 4 — Impediments and issues (5)
  {id:'S2-B16',domain:D,task:4,approach:'Agile',type:'single',
   stem:'An agile team is blocked because another team has not delivered an API it depends on. What should the project manager do?',
   options:['Tell the team to wait','Work with the other team’s product owner and project manager to agree on priorities and a delivery date, make the dependency visible on both boards, and escalate if needed','Ask the team to build its own version of the API','Report the other team to management'],answer:[1],
   explanation:'Cross-team dependencies are resolved through collaboration, visibility and, if necessary, escalation through the right channels.',
   ref:'Principle: Adopt a holistic view · Focus area: Executing'},
  {id:'S2-B17',domain:D,task:4,approach:'Predictive',type:'single',
   stem:'The steering committee has postponed a key design decision three times, and the team is idle. What should the project manager do?',
   options:['Make the decision personally','Quantify the cost of the delay, present clear options with a recommendation, and request a decision by a specific date according to governance','Let the team work on something else indefinitely','Stop reporting the issue'],answer:[1],
   explanation:'Showing the impact of indecision and making the decision easy to take helps decision-makers act.',
   ref:'Performance domain: Governance · Principle: Be an accountable leader'},
  {id:'S2-B18',domain:D,task:4,approach:'Agile',type:'single',
   stem:'What is an impediment in agile delivery?',
   options:['Any task in the backlog','Anything that blocks or slows the team’s progress toward its goal and that it cannot easily resolve itself','A defect found during testing','A user story without points'],answer:[1],
   explanation:'Impediments are obstacles to progress. The Scrum Master or project manager helps remove those the team cannot resolve.',
   ref:'Focus area: Executing · Principle: Build an empowered culture'},
  {id:'S2-B19',domain:D,task:4,approach:'Hybrid',type:'single',
   stem:'A key supplier’s factory fire halts delivery of a critical component. This was not identified as a risk. What should the project manager do first?',
   options:['Update the risk register and wait','Treat it as an issue: assess the impact, implement a workaround such as an alternative supplier, inform stakeholders and record lessons for future risk identification','Cancel the project','Blame the risk team'],answer:[1],
   explanation:'Unidentified risks that occur need workarounds. Afterwards, the risk identification process should be improved.',
   ref:'Performance domain: Risk · Focus area: Executing'},
  {id:'S2-B20',domain:D,task:4,approach:'Agile',type:'multi',
   stem:'Which TWO practices make impediments visible so that they can be removed quickly?',
   options:['Raising blockers at the daily standup','Waiting until the sprint review to mention them','An impediment board or blocked markers on the team’s task board','Recording them privately','Reporting them only in the monthly report'],answer:[0,2],
   explanation:'Daily standups and visual signals make blockers visible early so that they can be acted on.',
   ref:'Focus area: Executing · Performance domain: Schedule'},

  // Task 5 — Plan and manage risk (5)
  {id:'S2-B21',domain:D,task:5,approach:'Predictive',type:'dropdown',
   stem:'Option A (build) costs $100,000, with a 40% chance of a $50,000 overrun. Option B (buy) costs $110,000, with a 20% chance of $30,000 in customization. Using expected monetary value, what is the expected cost of the better option?',
   options:['$110,000','$116,000','$120,000','$126,000'],answer:[1],
   explanation:'Option A: 100,000 + 0.4 × 50,000 = $120,000. Option B: 110,000 + 0.2 × 30,000 = $116,000. Option B has the lower expected cost.',
   ref:'Performance domain: Risk · Focus area: Planning'},
  {id:'S2-B22',domain:D,task:5,approach:'Hybrid',type:'matching',
   stem:'Match each opportunity response strategy to its example.',
   pairs:[{left:'Exploit',right:0},{left:'Enhance',right:1},{left:'Share',right:2},{left:'Accept',right:3}],
   choices:['Assign the most talented team members to make sure an early-finish bonus is earned','Add resources to increase the probability of finishing early','Form a joint venture with a partner that can help capture a market opportunity','Take advantage of the opportunity if it arises, without actively pursuing it'],
   explanation:'Exploit ensures the opportunity occurs; enhance increases its probability or impact; share involves a third party; accept takes no proactive action.',
   ref:'Performance domain: Risk · Focus area: Planning'},
  {id:'S2-B23',domain:D,task:5,approach:'Predictive',type:'single',
   stem:'The sponsor wants to know the probability of finishing by a specific date, considering uncertainty in many activities. Which technique is most appropriate?',
   options:['Expert judgment only','Monte Carlo simulation, which runs many iterations of the schedule model to produce a probability distribution of completion dates','Critical path method alone','A RACI chart'],answer:[1],
   explanation:'Monte Carlo simulation combines uncertainty across activities and shows, for example, the date with 80% confidence.',
   ref:'Performance domains: Risk, Schedule · Focus area: Planning'},
  {id:'S2-B24',domain:D,task:5,approach:'Predictive',type:'single',
   stem:'What is the difference between risk appetite and risk threshold?',
   options:['They mean the same thing','Risk appetite is the degree of uncertainty an organization is willing to accept in pursuit of its objectives; a risk threshold is the measurable level of exposure above which action is required','Risk threshold is always higher than appetite','Risk appetite applies only to opportunities'],answer:[1],
   explanation:'Appetite is a general attitude; thresholds turn it into measurable limits that guide responses and escalation.',
   ref:'Performance domain: Risk · Performance domain: Governance'},
  {id:'S2-B25',domain:D,task:5,approach:'Agile',type:'single',
   stem:'An agile team is unsure whether a new payment API can handle the required load. What is the best way to reduce this risk early?',
   options:['Build the whole feature and test at the end','Run a time-boxed technical spike to test the API under load before committing to the design','Accept the risk','Ask the vendor for a guarantee'],answer:[1],
   explanation:'Spikes are short experiments that reduce technical uncertainty early, when changing direction is cheapest.',
   ref:'Performance domain: Risk · Focus area: Planning'},

  // Task 6 — Continuous improvement (5)
  {id:'S2-B26',domain:D,task:6,approach:'Hybrid',type:'single',
   stem:'Which sequence describes the Plan–Do–Check–Act (PDCA) cycle?',
   options:['Plan the change, implement it on a small scale, check the results, and act to standardize or adjust','Plan the project, execute it, close it','Plan, design, code, test','Plan, delegate, control, approve'],answer:[0],
   explanation:'PDCA (the Deming cycle) is an iterative method for continuous improvement based on testing and learning.',
   ref:'Principle: Embed quality · Focus area: Monitoring and Controlling'},
  {id:'S2-B27',domain:D,task:6,approach:'Agile',type:'single',
   stem:'Retrospectives have become repetitive, and the team says “nothing changes.” What should the facilitator do?',
   options:['Cancel retrospectives','Vary the format, use data to focus discussion, and agree on one or two small, owned actions that are reviewed at the next retrospective','Make retrospectives optional','Have the manager decide the improvements'],answer:[1],
   explanation:'Fresh formats, data and follow-through on a few concrete actions keep retrospectives effective.',
   ref:'Principle: Build an empowered culture · Focus area: Monitoring and Controlling'},
  {id:'S2-B28',domain:D,task:6,approach:'Hybrid',type:'single',
   stem:'An organization compares its project practices with those of industry leaders to identify improvements. What is this called?',
   options:['Benchmarking','Brainstorming','Sampling','Fast tracking'],answer:[0],
   explanation:'Benchmarking compares practices or performance with comparable organizations to find ideas and set targets.',
   ref:'Principle: Embed quality · Focus area: Planning'},
  {id:'S2-B29',domain:D,task:6,approach:'Agile',type:'single',
   stem:'Which of the following is an example of waste in lean thinking?',
   options:['Delivering working software to customers','Handoffs, waiting and partially done work','Automated testing','Customer feedback'],answer:[1],
   explanation:'Lean identifies waste such as waiting, handoffs, partially done work, extra features and defects. Removing waste improves flow.',
   ref:'Principle: Focus on value · Principle: Embed quality'},
  {id:'S2-B30',domain:D,task:6,approach:'Hybrid',type:'multi',
   stem:'Which TWO actions turn lessons learned into continuous improvement?',
   options:['Updating organizational templates, checklists or standards based on the lessons','Filing the lessons without review','Assigning owners and dates to implement improvement actions','Discussing lessons only at closure','Keeping lessons confidential'],answer:[0,2],
   explanation:'Lessons lead to improvement when they change organizational assets and have owners who implement them.',
   ref:'Principle: Embed quality · Focus area: Closing'},

  // Task 7 — Support organizational change (5)
  {id:'S2-B31',domain:D,task:7,approach:'Predictive',type:'single',
   stem:'According to the ADKAR change model, what should come before Knowledge (training)?',
   options:['Ability and Reinforcement','Awareness of the need for change and Desire to participate','Reinforcement only','Nothing; training comes first'],answer:[1],
   explanation:'ADKAR stands for Awareness, Desire, Knowledge, Ability and Reinforcement. Training is less effective if people do not understand and want the change.',
   ref:'Performance domain: Stakeholders · Focus area: Executing'},
  {id:'S2-B32',domain:D,task:7,approach:'Hybrid',type:'single',
   stem:'Before rolling out a new case-management system, the project manager wants to know how prepared each department is. What should be used?',
   options:['A change-readiness assessment','A burndown chart','A procurement audit','A RACI chart'],answer:[0],
   explanation:'A readiness assessment identifies gaps in awareness, skills and support so that change activities can be targeted.',
   ref:'Performance domain: Stakeholders · Focus area: Planning'},
  {id:'S2-B33',domain:D,task:7,approach:'Predictive',type:'single',
   stem:'Three months after go-live, many users have returned to their old spreadsheets. What should have been planned to prevent this?',
   options:['More features','Reinforcement activities such as follow-up coaching, usage monitoring, recognition and retiring the old tools','A shorter training course','A larger launch event'],answer:[1],
   explanation:'Sustaining change requires reinforcement after go-live; otherwise, people revert to familiar habits.',
   ref:'Principle: Focus on value · Focus area: Closing'},
  {id:'S2-B34',domain:D,task:7,approach:'Agile',type:'single',
   stem:'An organization adopting agile wants to build momentum for the change. Which action is most effective early on?',
   options:['Mandate agile for all teams at once','Start with a pilot team, make its results visible and use them to build a guiding coalition and short-term wins','Wait until everyone agrees','Hire external coaches to run all teams'],answer:[1],
   explanation:'Short-term wins and a guiding coalition (as in Kotter’s change model) build credibility and momentum for wider change.',
   ref:'Principle: Build an empowered culture · Performance domain: Stakeholders'},
  {id:'S2-B35',domain:D,task:7,approach:'Hybrid',type:'multi',
   stem:'Which TWO actions best reduce resistance to a major process change?',
   options:['Involving affected people in designing the new process','Announcing the change without explanation','Explaining clearly why the change is needed and what it means for each group','Penalizing people who raise concerns','Changing everything on the same day without support'],answer:[0,2],
   explanation:'Involvement and clear communication about the reasons for change build understanding and ownership.',
   ref:'Performance domain: Stakeholders · Principle: Build an empowered culture'},

  // Task 8 — External business environment (4)
  {id:'S2-B36',domain:D,task:8,approach:'Hybrid',type:'single',
   stem:'Which framework helps a project manager systematically scan the external environment for political, economic, social, technological, legal and environmental factors?',
   options:['SWOT','PESTLE','RACI','WBS'],answer:[1],
   explanation:'PESTLE structures the analysis of external factors that may create risks or opportunities for the project.',
   ref:'Principle: Adopt a holistic view · Performance domain: Risk'},
  {id:'S2-B37',domain:D,task:8,approach:'Hybrid',type:'single',
   stem:'The central bank raises interest rates sharply, increasing the cost of the financing that funds the project. What should the project manager do?',
   options:['Ignore it because financing is the finance department’s concern','Work with finance to assess the effect on the business case and funding, and inform the sponsor so that governance can decide whether to adjust scope, phasing or financing','Speed up spending before rates rise further','Stop the project immediately'],answer:[1],
   explanation:'Economic changes can affect project viability. The project manager supports analysis and timely governance decisions.',
   ref:'Principle: Focus on value · Performance domains: Finance, Governance'},
  {id:'S2-B38',domain:D,task:8,approach:'Agile',type:'single',
   stem:'A new law will ban a data-collection practice that the product relies on, effective in six months. What should the product owner and team do?',
   options:['Continue as planned until the law takes effect','Assess the impact with legal experts, reprioritize the backlog to adapt the product before the deadline, and communicate the change to stakeholders','Remove the product from the market immediately','Wait for competitors to react first'],answer:[1],
   explanation:'Adaptive teams respond to external changes by assessing impact and reprioritizing early to stay compliant and valuable.',
   ref:'Performance domains: Governance, Scope · Principle: Focus on value'},
  {id:'S2-B39',domain:D,task:8,approach:'Hybrid',type:'multi',
   stem:'Which TWO practices help a project respond well to changes in the external business environment?',
   options:['Regularly scanning and reviewing external factors with stakeholders','Locking the plan so that it never changes','Keeping risk registers and business cases current as conditions change','Ignoring information from outside the organization','Relying only on last year’s assumptions'],answer:[0,2],
   explanation:'Regular environmental scanning and living risk and business-case documents enable timely adaptation.',
   ref:'Principle: Adopt a holistic view · Performance domain: Risk'}
];
