import {CaseStudy,ExamQuestion} from '../../exam-types';

export const CASE_STUDIES:CaseStudy[]=[
  {id:'D',title:'Case D · Aurora Transit: Tap-to-Pay Fare Modernization (hybrid)',graphic:'network-2',context:[
    'Aurora Transit, a mid-sized Canadian city’s bus operator, is replacing cash fare boxes on 400 buses with tap-to-pay card readers and launching a mobile fare app. Riders will be able to pay with bank cards, phones or a transit card.',
    'Hardware installation follows a predictive plan with installation waves by garage. The supplier provides the readers under a firm-fixed-price contract with liquidated damages for late delivery. A separate agile team builds the mobile app in two-week sprints.',
    'Bus operators are unionized. A riders’ accessibility advisory committee has asked to be involved. The network diagram shows the activities for the first installation wave.'
  ]},
  {id:'E',title:'Case E · Maple Health: Patient Portal (agile, Kanban)',graphic:'cfd-2',context:[
    'Maple Health, a regional health authority, is building a patient portal for booking appointments, viewing test results and messaging clinics. A cross-functional team of nine uses Kanban with continuous delivery to a pilot group of three clinics.',
    'The authority must comply with provincial health-information legislation. Leadership also wants to add an AI chatbot that helps patients choose the right type of appointment.',
    'Clinic managers are used to fixed project dates and ask when features will be “finished.” The cumulative flow diagram shows the team’s work over the last 10 days.'
  ]},
  {id:'F',title:'Case F · Northwind Energy: Wind-Farm Substation Package (predictive)',graphic:'ev-2',context:[
    'Northwind Energy is building the electrical substation and access roads for a 30-turbine wind farm in rural Saskatchewan. This work package has a budget at completion of $2.4 million and a 12-month schedule.',
    'Three contractors share the site: civil works, electrical installation and crane services. Governance requires the project manager to escalate to the steering committee whenever CPI or SPI falls below 0.90.',
    'Weather affects crane lifts, and the site is near a migratory bird route. The chart shows planned value (PV), earned value (EV) and actual cost (AC), in thousands of dollars, at the end of month 8.'
  ]}
];

export const CASE_QUESTIONS:ExamQuestion[]=[
  // ---------- Case D ----------
  {id:'S2-D01',caseId:'D',domain:'Process',task:8,approach:'Hybrid',type:'dropdown',graphic:'network-2',
   stem:'Using the network diagram for the first installation wave, what is the total duration of the wave?',
   options:['13 days','15 days','16 days','24 days'],answer:[2],
   explanation:'Path A-B-E-F-G = 2+5+3+2+3 = 15 days. Path A-C-D-F-G = 2+3+6+2+3 = 16 days. The longest path (critical path) is A-C-D-F-G, so the wave takes 16 days.',
   ref:'Performance domain: Schedule · Focus area: Planning'},
  {id:'S2-D02',caseId:'D',domain:'Process',task:8,approach:'Hybrid',type:'single',graphic:'network-2',
   stem:'Activity B is delayed by 3 days. What is the effect on the duration of the installation wave?',
   options:['No effect, because B is not on the critical path','The wave is extended by 1 day','The wave is extended by 2 days','The wave is extended by 3 days'],answer:[2],
   explanation:'B is on path A-B-E-F-G (15 days), so it has 1 day of total float. A 3-day delay uses the 1 day of float and pushes that path to 18 days, extending the wave by 2 days (16 → 18).',
   ref:'Performance domain: Schedule · Focus area: Monitoring and Controlling'},
  {id:'S2-D03',caseId:'D',domain:'Business Environment',task:2,approach:'Hybrid',type:'single',
   stem:'The app team plans to store riders’ bank card numbers in the app’s database to make repeat payments faster. What should the project manager do?',
   options:['Approve it because it improves the user experience','Engage the payment security and compliance specialists to confirm the card-data requirements that apply, and build the approved approach (such as tokenization) into the backlog and the definition of done','Let the developers decide because it is a technical choice','Postpone the decision until after launch'],answer:[1],
   explanation:'Payment card data is subject to strict industry security standards. Compliance requirements must be confirmed with the accountable specialists and built into the work, not decided informally by the team.',
   ref:'Performance domain: Governance · Principle: Embed quality'},
  {id:'S2-D04',caseId:'D',domain:'People',task:4,approach:'Hybrid',type:'single',
   stem:'The riders’ accessibility advisory committee asks how riders who are blind or have limited hand mobility will use the new readers and the app. What is the best response?',
   options:['Send the committee the vendor’s accessibility brochure','Invite committee members to take part in usability testing of the readers and app increments, and include their feedback in the backlog and installation design','Tell them accessibility will be addressed after launch','Ask the vendor to meet with them instead'],answer:[1],
   explanation:'Engaging affected stakeholders directly, early and through real testing produces a better product and builds trust. Their input should influence decisions.',
   ref:'Performance domain: Stakeholders · Principle: Focus on value'},
  {id:'S2-D05',caseId:'D',domain:'Business Environment',task:3,approach:'Hybrid',type:'single',
   stem:'City council approves a new discounted fare for seniors, to start at launch. It affects both the reader configuration (predictive scope) and the app (agile backlog). How should the change be handled?',
   options:['Add it to the app backlog only','Submit a change request for the reader configuration through change control, and ask the product owner to prioritize the app work in the backlog, coordinating both through the integrated plan','Ask the vendor to add it at no cost','Defer the discount until the next fiscal year'],answer:[1],
   explanation:'In a hybrid project, each part handles change through its own mechanism, but the impacts must be coordinated so that both parts are ready at launch.',
   ref:'Principle: Adopt a holistic view · Performance domain: Governance'},
  {id:'S2-D06',caseId:'D',domain:'Process',task:5,approach:'Hybrid',type:'single',
   stem:'The reader supplier informs you that the second delivery will be four weeks late. The contract includes liquidated damages for late delivery. What should the project manager do first?',
   options:['Deduct the liquidated damages from the next invoice immediately','Review the contract terms with procurement, formally notify the supplier as the contract requires, and request a recovery plan while assessing the schedule impact','Terminate the contract for default','Ignore the delay because the contract protects the buyer'],answer:[1],
   explanation:'Contract administration follows the agreed terms: understand the clauses, give formal notice, and seek recovery while protecting the buyer’s rights. Liquidated damages are applied according to the contract process, not unilaterally.',
   ref:'Performance domains: Resources (procurement), Governance · Focus area: Monitoring and Controlling'},
  {id:'S2-D07',caseId:'D',domain:'People',task:2,approach:'Hybrid',type:'single',
   stem:'The bus operators’ union objects to training sessions scheduled on operators’ days off without overtime pay. Installation is waiting on the training. What should the project manager do?',
   options:['Cancel the training','Meet with union representatives and operations management to understand the concerns and negotiate a training schedule that respects the collective agreement','Make training optional','Ask HR to enforce the original schedule'],answer:[1],
   explanation:'Collaborative negotiation that respects the collective agreement resolves the conflict and keeps the relationship productive.',
   ref:'Performance domains: Resources, Stakeholders · Focus area: Executing'},
  {id:'S2-D08',caseId:'D',domain:'Process',task:1,approach:'Hybrid',type:'single',
   stem:'The app must be ready before the first garage goes live with the new readers. How should the project manager integrate the two delivery approaches?',
   options:['Ask the app team to switch to a predictive schedule','Align app release goals with the installation waves in an integrated roadmap, with shared milestones and regular joint reviews','Let each team plan independently and integrate at launch','Delay the hardware until the app is complete'],answer:[1],
   explanation:'Hybrid integration uses shared milestones and a common roadmap while letting each team keep the approach that suits its work.',
   ref:'Principle: Adopt a holistic view · Focus area: Planning'},
  {id:'S2-D09',caseId:'D',domain:'People',task:8,approach:'Hybrid',type:'multi',
   stem:'Riders need to know how and when fare payment will change. Which TWO communication approaches are most appropriate?',
   options:['Multilingual notices on buses, at stops and online, timed to each garage’s go-live','A single press release on launch day','On-board and community information sessions for riders who may need help, such as seniors','Communication only through the new app','Waiting until complaints arrive to explain the change'],answer:[0,2],
   explanation:'Public-facing change needs communication tailored to diverse audiences and timed to the rollout, with extra support for groups who may struggle with the change.',
   ref:'Performance domain: Stakeholders · Focus area: Executing'},
  {id:'S2-D10',caseId:'D',domain:'Business Environment',task:5,approach:'Hybrid',type:'single',
   stem:'Engineers warn that the readers have not been tested below –30 °C, and winter temperatures in the city reach –40 °C. Which risk response is best?',
   options:['Accept the risk because most days are warmer','Mitigate it by running a cold-weather pilot on a few buses before full rollout and agreeing on performance criteria with the supplier','Transfer the risk by buying insurance','Avoid it by delaying the project until summer'],answer:[1],
   explanation:'Testing under real conditions before full rollout reduces the probability and impact of failure. It also creates evidence to hold the supplier to its specifications.',
   ref:'Performance domain: Risk · Principle: Embed quality'},

  // ---------- Case E ----------
  {id:'S2-E01',caseId:'E',domain:'Process',task:9,approach:'Agile',type:'single',graphic:'cfd-2',
   stem:'Based on the cumulative flow diagram, what is happening to the team’s flow of work?',
   options:['Flow is healthy: all bands are parallel','Work in development keeps growing while completions are flattening, so the team is starting more than it finishes and should limit work in progress','The Ready queue is growing, so the team needs more backlog items','Testing is the bottleneck'],answer:[1],
   explanation:'The “In development” band widens steadily (from 4 to 26 items) while the Done line flattens. More work is being started than finished, which increases cycle time. WIP limits would restore flow.',
   ref:'Performance domain: Schedule · Focus area: Monitoring and Controlling'},
  {id:'S2-E02',caseId:'E',domain:'Process',task:8,approach:'Agile',type:'dropdown',
   stem:'The team has an average of 24 items in progress and completes an average of 2 items per day. Using Little’s Law, what is the average cycle time?',
   options:['6 days','12 days','24 days','48 days'],answer:[1],
   explanation:'Little’s Law: average cycle time = average WIP ÷ average throughput = 24 ÷ 2 = 12 days. Reducing WIP reduces cycle time.',
   ref:'Performance domain: Schedule · Focus area: Monitoring and Controlling'},
  {id:'S2-E03',caseId:'E',domain:'People',task:3,approach:'Agile',type:'single',
   stem:'When a work item is blocked, team members pull a new item instead of helping to unblock it. What should the project manager do?',
   options:['Assign blocked items to specific people','Coach the team on “stop starting, start finishing”: agree on WIP limits and swarm on blocked items','Add more columns to the board','Report the blocked items to the sponsor daily'],answer:[1],
   explanation:'Servant leaders coach teams on flow principles. WIP limits and swarming focus the team on finishing work.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'S2-E04',caseId:'E',domain:'Business Environment',task:2,approach:'Agile',type:'single',
   stem:'A developer copies real patient records into the test environment to reproduce a defect. What should the project manager do?',
   options:['Allow it because the test environment is internal','Stop the practice, involve the privacy officer to assess and remediate any breach, and provide de-identified test data for future testing','Ask the developer to delete the data quietly','Encrypt the test environment and continue'],answer:[1],
   explanation:'Using identifiable health information outside approved purposes may breach health-information legislation. The privacy officer must assess it, and the process must change to prevent recurrence.',
   ref:'Performance domain: Governance · Principle: Be an accountable leader'},
  {id:'S2-E05',caseId:'E',domain:'Business Environment',task:5,approach:'Agile',type:'single',
   stem:'The proposed AI chatbot could direct a patient with urgent symptoms to a routine appointment. How should this risk be addressed?',
   options:['Launch the chatbot and monitor complaints','Limit the chatbot’s scope, have clinical experts review its behaviour, include clear escalation to a human and to emergency guidance, and test it before release','Avoid AI entirely','Add a disclaimer and release it'],answer:[1],
   explanation:'High-impact AI risks need layered mitigation: limited scope, expert validation, human escalation paths and testing before use. A disclaimer alone does not protect patients.',
   ref:'Performance domain: Risk · AI in project management · Principle: Be an accountable leader'},
  {id:'S2-E06',caseId:'E',domain:'People',task:2,approach:'Agile',type:'single',
   stem:'The UX designer wants a short booking form, while the clinical lead insists on ten mandatory questions. They have argued for a week. What is the best approach?',
   options:['Let the clinical lead decide because of patient safety','Facilitate a session to agree on objective criteria—clinical need and completion rate—and test two versions with real patients','Ask the product owner to pick one immediately','Include all ten questions now and review later'],answer:[1],
   explanation:'Using shared criteria and evidence from user testing turns a positional conflict into a collaborative decision.',
   ref:'Principle: Focus on value · Performance domain: Stakeholders'},
  {id:'S2-E07',caseId:'E',domain:'Process',task:7,approach:'Agile',type:'single',
   stem:'An audit finds that several released portal screens cannot be used with screen readers. How should the team prevent this from happening again?',
   options:['Run an accessibility audit once a year','Add accessibility criteria—such as recognized web accessibility guidelines and screen-reader checks—to the definition of done and automate checks where possible','Fix only the screens that patients complain about','Assign one tester to accessibility'],answer:[1],
   explanation:'Adding accessibility to the definition of done builds quality into every increment instead of discovering problems after release.',
   ref:'Principle: Embed quality · Performance domain: Scope'},
  {id:'S2-E08',caseId:'E',domain:'People',task:6,approach:'Agile',type:'single',
   stem:'Clinic managers keep asking for a fixed “finish date” for each feature. The team does not use sprints. What is the best way to manage their expectations?',
   options:['Give them dates based on best-case estimates','Share a service-level expectation based on historical cycle time—for example, 85% of items finish within 10 days—and show progress on the board','Tell them Kanban does not use dates','Switch the team to fixed-date commitments'],answer:[1],
   explanation:'Kanban teams use historical data to set probabilistic expectations. A service-level expectation answers “when?” honestly.',
   ref:'Performance domain: Schedule · Principle: Be an accountable leader'},
  {id:'S2-E09',caseId:'E',domain:'People',task:5,approach:'Agile',type:'single',
   stem:'Two pilot clinics want different features first: one wants online test results, the other wants appointment reminders. What should the project manager recommend?',
   options:['Build both at the same time','Help the product owner facilitate agreement on prioritization criteria—patient impact, call reduction and effort—and apply them transparently','Prioritize the clinic that complained first','Ask the sponsor to decide without discussion'],answer:[1],
   explanation:'Shared, transparent prioritization criteria align expectations and make the decision understandable to both groups.',
   ref:'Principle: Focus on value · Performance domain: Stakeholders'},
  {id:'S2-E10',caseId:'E',domain:'Process',task:3,approach:'Agile',type:'multi',
   stem:'Which TWO measures best show that the patient portal is delivering value?',
   options:['Reduction in phone calls to clinics for booking and results','Number of story points completed','Patient adoption and satisfaction with the portal','Number of screens built','Hours worked by the team'],answer:[0,2],
   explanation:'Value is shown by outcomes for the organization and its users, not by output or effort measures.',
   ref:'Principle: Focus on value · Focus area: Monitoring and Controlling'},

  // ---------- Case F ----------
  {id:'S2-F01',caseId:'F',domain:'Process',task:9,approach:'Predictive',type:'single',graphic:'ev-2',
   stem:'Based on the chart at the end of month 8, how is the substation package performing?',
   options:['Ahead of schedule and under budget','Ahead of schedule and over budget','Behind schedule and over budget','Behind schedule and under budget'],answer:[1],
   explanation:'EV ($1,650k) is above PV ($1,550k), so SV = +$100k and SPI ≈ 1.06 (ahead). EV is below AC ($1,870k), so CV = –$220k and CPI ≈ 0.88 (over budget).',
   ref:'Performance domains: Schedule, Finance · Focus area: Monitoring and Controlling'},
  {id:'S2-F02',caseId:'F',domain:'Process',task:6,approach:'Predictive',type:'dropdown',graphic:'ev-2',
   stem:'If the current cost performance continues, what is the estimate at completion (EAC)? Select the closest value.',
   options:['$2,400,000','$2,620,000','$2,720,000','$2,950,000'],answer:[2],
   explanation:'CPI = 1,650 ÷ 1,870 ≈ 0.882. EAC = BAC ÷ CPI = 2,400 ÷ 0.882 ≈ $2,720,000. $2,620,000 is AC + (BAC – EV), which assumes no further variance.',
   ref:'Performance domain: Finance · Focus area: Monitoring and Controlling'},
  {id:'S2-F03',caseId:'F',domain:'Process',task:6,approach:'Predictive',type:'dropdown',graphic:'ev-2',
   stem:'What to-complete performance index (TCPI) is required to finish within the original budget?',
   options:['0.88','1.07','1.42','1.65'],answer:[2],
   explanation:'TCPI = (BAC – EV) ÷ (BAC – AC) = (2,400 – 1,650) ÷ (2,400 – 1,870) = 750 ÷ 530 ≈ 1.42. That level of efficiency is unrealistic, so a revised budget (EAC-based TCPI) should be discussed.',
   ref:'Performance domain: Finance · Focus area: Monitoring and Controlling'},
  {id:'S2-F04',caseId:'F',domain:'Business Environment',task:8,approach:'Predictive',type:'single',
   stem:'The federal regulator issues new guidance requiring bird-collision monitoring during construction near migratory routes. What should the project manager do first?',
   options:['Continue work because the permit was issued before the guidance','Assess with environmental and legal advisors whether and how the guidance applies, estimate the impact on scope, schedule and cost, and update the risk register and plan through change control','Stop all work until the next permit renewal','Ask the civil contractor to handle it'],answer:[1],
   explanation:'External regulatory changes must be analyzed for applicability and impact before responding, and any changes are processed through governance.',
   ref:'Principle: Integrate sustainability · Performance domains: Governance, Risk'},
  {id:'S2-F05',caseId:'F',domain:'Business Environment',task:4,approach:'Predictive',type:'single',
   stem:'A crane load swings close to workers during a lift. No one is hurt. What should the project manager do first?',
   options:['Record it in the monthly report','Ensure lifting stops until the cause is understood, report the near miss according to safety procedures, and log it as an issue with an owner for investigation and corrective action','Ask the crane contractor to be more careful','Increase the schedule buffer'],answer:[1],
   explanation:'Safety comes first. Near misses must be stopped, reported and investigated so that corrective action prevents a future injury.',
   ref:'Principle: Be an accountable leader · Focus area: Executing'},
  {id:'S2-F06',caseId:'F',domain:'Process',task:10,approach:'Predictive',type:'multi',
   stem:'The substation has been energized and accepted by the grid operator. Which TWO actions should the project manager complete to close the package?',
   options:['Confirm final contractor deliverables and acceptance, settle claims and close the contracts','Start design work for the next wind farm','Hand over as-built drawings, warranties and operating documentation to the operations team, and record lessons learned','Release all contingency to the contractors as a bonus','Rebaseline the cost to match actuals'],answer:[0,2],
   explanation:'Closure covers contract closeout, transition of documentation and knowledge to operations, and capturing lessons learned.',
   ref:'Focus area: Closing · Performance domain: Governance'},
  {id:'S2-F07',caseId:'F',domain:'People',task:1,approach:'Predictive',type:'single',
   stem:'Crews from the three contractors work separately and see their own scope as the only priority, which leads to unsafe site congestion. What should the project manager do?',
   options:['Ask each contractor to manage its own crews','Bring the contractor leads together to agree on a shared site vision—safety, quality and the energization milestone—with common site rules and a joint coordination meeting','Penalize the contractor with the most incidents','Schedule the contractors on different days without discussion'],answer:[1],
   explanation:'A shared vision and common working agreements turn separate crews into one site team focused on the overall outcome.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'S2-F08',caseId:'F',domain:'People',task:7,approach:'Predictive',type:'single',
   stem:'Commissioning revealed several design issues that Northwind has encountered on previous substations. How should the project manager make sure future projects benefit?',
   options:['Mention the issues in the final status report','Capture the lessons with root causes and recommendations, add them to the organization’s lessons-learned repository and share them with design standards owners','Email the design team','Keep the lessons in the project file'],answer:[1],
   explanation:'Lessons have value only if they reach the people and standards that shape future projects.',
   ref:'Principle: Embed quality · Focus area: Closing'},
  {id:'S2-F09',caseId:'F',domain:'Business Environment',task:1,approach:'Predictive',type:'single',graphic:'ev-2',
   stem:'Based on the month-8 performance and the project’s governance rules, what should the project manager do?',
   options:['Nothing, because the project is ahead of schedule','Escalate to the steering committee, because CPI is below the 0.90 threshold, with an analysis of causes, a forecast and recovery options','Wait one more month to confirm the trend','Ask finance to reclassify costs'],answer:[1],
   explanation:'CPI ≈ 0.88 breaches the 0.90 escalation threshold defined by governance. Escalating with analysis and options respects decision rights and enables timely action.',
   ref:'Performance domain: Governance · Principle: Be an accountable leader'},
  {id:'S2-F10',caseId:'F',domain:'Process',task:4,approach:'Predictive',type:'single',
   stem:'High winds keep cancelling crane lifts, and the crane is charged per day whether or not it works. What is the best approach?',
   options:['Demobilize the crane and remobilize when needed, without analysis','Use weather forecasts to plan lift windows, sequence other work around them, and compare standby costs with remobilization costs before deciding','Lift in high winds to stay on schedule','Ask the crane contractor to waive standby charges'],answer:[1],
   explanation:'Resource planning considers resource calendars and constraints such as weather. Decisions about expensive equipment should be based on cost analysis, never on unsafe practices.',
   ref:'Performance domains: Resources, Finance · Focus area: Executing'}
];
