import {ExamQuestion} from '../../exam-types';

const D='People' as const;

export const PEOPLE_QUESTIONS:ExamQuestion[]=[
  // Task 1 — Develop a common vision (7)
  {id:'S2-P01',domain:D,task:1,approach:'Agile',type:'single',
   stem:'An organization uses objectives and key results (OKRs). A new product team’s backlog does not obviously connect to any company objective. What should the project manager do?',
   options:['Ignore the OKRs because the team is agile','Work with the product owner and sponsor to link the product goal and roadmap to the relevant company objectives, and define measurable key results for the product','Ask the team to write their own unrelated OKRs','Delay work until leadership rewrites the OKRs'],answer:[1],
   explanation:'Connecting the product goal to organizational objectives gives the team purpose and helps prioritize work by strategic value.',
   ref:'Principle: Focus on value · Performance domain: Governance'},
  {id:'S2-P02',domain:D,task:1,approach:'Hybrid',type:'single',
   stem:'Two departments are merging their project teams into one. Each team has its own way of working and its own idea of what the project is for. What should the project manager do first?',
   options:['Adopt the larger team’s practices','Facilitate a team chartering session in which both groups agree on the purpose, values, working agreements and decision-making approach','Keep the teams separate','Ask HR to resolve the cultural differences'],answer:[1],
   explanation:'A team charter created together establishes a shared vision and ground rules, which is essential when combining teams with different cultures.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'S2-P03',domain:D,task:1,approach:'Predictive',type:'single',
   stem:'Team members on a long infrastructure project have lost sight of why it matters, and engagement is falling in year two. What is the most effective action?',
   options:['Increase the frequency of status meetings','Reconnect the team with the project’s purpose—for example by sharing the community benefits, hearing from future users and celebrating milestones achieved','Offer overtime pay','Replace disengaged team members'],answer:[1],
   explanation:'Reconnecting people with the purpose and impact of their work is a powerful driver of engagement on long projects.',
   ref:'Principle: Build an empowered culture · Focus area: Executing'},
  {id:'S2-P04',domain:D,task:1,approach:'Agile',type:'single',
   stem:'Which statement best describes a good product vision?',
   options:['A detailed list of features with delivery dates','A brief, inspiring statement of who the product is for, the problem it solves and why it matters, which guides decisions without prescribing solutions','The project budget and schedule','The team’s technical architecture'],answer:[1],
   explanation:'A good vision is short, outcome-focused and stable enough to guide many decisions, while leaving room for the team to discover solutions.',
   ref:'Performance domain: Scope · Principle: Focus on value'},
  {id:'S2-P05',domain:D,task:1,approach:'Hybrid',type:'multi',
   stem:'A sponsor asks how to make sure everyone on a new hybrid program shares the same vision. Which TWO actions should the project manager recommend?',
   options:['Co-create the vision and success measures with key stakeholders and team representatives','Publish the vision only in the charter archive','Make the vision visible—for example on team boards and in planning sessions—and refer to it in decisions','Let each workstream define success independently','Limit the vision to the executive team'],answer:[0,2],
   explanation:'Co-creation builds ownership, and visibility keeps the vision active in daily decisions.',
   ref:'Principle: Adopt a holistic view · Performance domain: Stakeholders'},
  {id:'S2-P06',domain:D,task:1,approach:'Agile',type:'single',
   stem:'During refinement, developers frequently debate whether a feature “fits the product.” The debates are long and inconclusive. What would help most?',
   options:['Let the most senior developer decide','Ask the product owner to make the product goal and target users explicit so that the team can test ideas against them','Ban debates during refinement','Defer all disputed features'],answer:[1],
   explanation:'A clear product goal provides a shared yardstick for decisions and shortens unproductive debates.',
   ref:'Performance domain: Scope · Focus area: Planning'},
  {id:'S2-P07',domain:D,task:1,approach:'Predictive',type:'single',
   stem:'A project charter has been approved, but the team was not involved in creating it. Several members question the project’s objectives. What should the project manager do?',
   options:['Tell the team that the charter is final','Review the charter with the team, explain the business need and objectives, listen to concerns, and raise any significant gaps with the sponsor','Rewrite the charter with the team without involving the sponsor','Ignore the concerns'],answer:[1],
   explanation:'The project manager builds shared understanding of the approved direction and channels valid concerns to the sponsor, rather than changing authorized documents unilaterally.',
   ref:'Focus area: Initiating · Performance domain: Governance'},

  // Task 2 — Manage conflicts (5)
  {id:'S2-P08',domain:D,task:2,approach:'Hybrid',type:'single',
   stem:'A disagreement between two team members has escalated into a long, heated email chain copied to the whole team. What should the project manager do?',
   options:['Reply-all asking everyone to stop','Contact both team members directly, move the discussion to a private conversation and help them work through the issue','Forward the emails to HR','Wait for the conflict to burn out'],answer:[1],
   explanation:'Conflicts should be handled privately and directly. Email often escalates conflict, so a conversation is more effective.',
   ref:'Performance domain: Resources · Principle: Be an accountable leader'},
  {id:'S2-P09',domain:D,task:2,approach:'Predictive',type:'single',
   stem:'On most projects, which three sources cause the majority of conflicts?',
   options:['Personalities, office space and parking','Schedules, priorities and resources','Budgets, weather and vendors','Templates, tools and meetings'],answer:[1],
   explanation:'Schedules, priorities and scarce resources are commonly cited as the leading sources of project conflict. Personality conflicts are less frequent than often assumed.',
   ref:'Performance domain: Resources · Focus area: Executing'},
  {id:'S2-P10',domain:D,task:2,approach:'Agile',type:'single',
   stem:'Developers in two countries disagree about code-review practices. One group sees direct criticism as normal, while the other sees it as disrespectful. What is the best approach?',
   options:['Tell everyone to stop giving feedback','Facilitate a discussion of cultural differences in communication and help the team agree on a shared code-review etiquette','Separate the teams','Adopt the style of the larger group'],answer:[1],
   explanation:'Making cultural differences visible and agreeing on shared norms resolves the conflict and builds understanding.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'S2-P11',domain:D,task:2,approach:'Hybrid',type:'single',
   stem:'A project manager settles a disagreement by emphasizing the areas where two parties agree and playing down the differences. Which conflict-resolution approach is this, and when is it appropriate?',
   options:['Forcing; it is appropriate in emergencies','Smoothing/accommodating; it can maintain harmony when the relationship matters more than the issue, but it may not resolve the root cause','Collaborating; it is always the best option','Withdrawing; it is appropriate for urgent issues'],answer:[1],
   explanation:'Smoothing preserves relationships temporarily, but the underlying issue may return. It is useful when harmony is the priority.',
   ref:'Performance domain: Resources · Focus area: Executing'},
  {id:'S2-P12',domain:D,task:2,approach:'Agile',type:'multi',
   stem:'Which TWO practices help an agile team prevent destructive conflict?',
   options:['Clear working agreements that the team creates and revisits','Avoiding all disagreement in meetings','Regular retrospectives that create a safe space to raise concerns','Having the Scrum Master make all decisions','Assigning blame for missed goals'],answer:[0,2],
   explanation:'Agreements and safe forums for feedback let teams handle disagreement constructively before it becomes destructive.',
   ref:'Principle: Build an empowered culture · Focus area: Executing'},

  // Task 3 — Lead the project team (7)
  {id:'S2-P13',domain:D,task:3,approach:'Hybrid',type:'matching',
   stem:'Match each team-member situation to the most appropriate situational-leadership style.',
   pairs:[{left:'A new graduate with high enthusiasm but little experience',right:0},{left:'A member who has some skills but is discouraged after early setbacks',right:1},{left:'A capable member who lacks confidence in a new area',right:2},{left:'A highly skilled, motivated expert',right:3}],
   choices:['Directing','Coaching','Supporting','Delegating'],
   explanation:'Situational leadership adapts to each person’s competence and commitment: directing for enthusiastic beginners, coaching for disillusioned learners, supporting for capable but cautious contributors, and delegating to self-reliant experts.',
   ref:'Principle: Be an accountable leader · Performance domain: Resources'},
  {id:'S2-P14',domain:D,task:3,approach:'Predictive',type:'single',
   stem:'According to Herzberg’s two-factor theory, which of the following is a motivator rather than a hygiene factor?',
   options:['Salary','Working conditions','Recognition for achievement','Company policies'],answer:[2],
   explanation:'Hygiene factors (salary, conditions, policies) prevent dissatisfaction, but motivators such as achievement, recognition and growth create satisfaction.',
   ref:'Performance domain: Resources · Principle: Build an empowered culture'},
  {id:'S2-P15',domain:D,task:3,approach:'Agile',type:'single',
   stem:'The team has worked overtime for four sprints to meet a marketing date. Errors are increasing, and two members mention burnout. What should the project manager do?',
   options:['Continue until the date is met','Raise the issue with the product owner and stakeholders, restore a sustainable pace and renegotiate scope or date based on real capacity','Offer pizza at late meetings','Replace the tired team members'],answer:[1],
   explanation:'Sustainable pace is an agile principle. Overwork reduces quality and morale, so scope or date must be renegotiated transparently.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'S2-P16',domain:D,task:3,approach:'Hybrid',type:'matching',
   stem:'Match each source of power to the example that best illustrates it.',
   pairs:[{left:'Team members follow the project manager because she is a respected expert in cloud architecture',right:0},{left:'Team members follow the project manager because of her formal position',right:1},{left:'Team members admire the project manager and want to work with her',right:2},{left:'The project manager can approve training and recognition for team members',right:3}],
   choices:['Expert power','Legitimate (formal) power','Referent power','Reward power'],
   explanation:'Expert power comes from knowledge, legitimate from position, referent from respect and admiration, and reward from the ability to give benefits. Expert and referent power are usually the most effective.',
   ref:'Principle: Be an accountable leader · Performance domain: Resources'},
  {id:'S2-P17',domain:D,task:3,approach:'Agile',type:'single',
   stem:'A team member admits in a retrospective that they deployed a defect that caused a short outage. What should the project manager do?',
   options:['Note the mistake in the person’s performance file','Thank them for being open, and help the team analyze the systemic causes and improve its safeguards, without blame','Remove their deployment access','Ask the team to vote on consequences'],answer:[1],
   explanation:'Blameless learning encourages transparency. Focusing on systems rather than individuals prevents recurrence and protects psychological safety.',
   ref:'Principle: Build an empowered culture · Principle: Embed quality'},
  {id:'S2-P18',domain:D,task:3,approach:'Predictive',type:'single',
   stem:'The project manager wants to give team members feedback that includes input from peers, stakeholders and the manager. Which approach is this?',
   options:['Management by objectives','360-degree feedback','Forced ranking','Earned value review'],answer:[1],
   explanation:'360-degree feedback gathers input from multiple directions, giving a balanced view of a team member’s performance.',
   ref:'Performance domain: Resources · Focus area: Monitoring and Controlling'},
  {id:'S2-P19',domain:D,task:3,approach:'Hybrid',type:'single',
   stem:'A capable team member often waits for permission before making decisions that are within their role. What should the project manager do?',
   options:['Continue approving each decision','Clarify the decisions they are empowered to make, express confidence in their judgment and support them when they take initiative','Assign their decisions to someone else','Ask them to escalate every decision to the sponsor'],answer:[1],
   explanation:'Clear decision boundaries and visible trust build autonomy and speed up delivery.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},

  // Task 4 — Engage stakeholders (7)
  {id:'S2-P20',domain:D,task:4,approach:'Hybrid',type:'hotspot',graphic:'grid-2',
   stem:'The grid shows four stakeholder groups for a hospital scheduling system. Click the stakeholder group that should be engaged with a “keep informed” strategy.',
   options:['Chief financial officer','Regulator liaison','Front-line nurses','IT help desk'],answer:[2],
   explanation:'Front-line nurses have high interest but lower formal power, so they should be kept informed and involved appropriately. The CFO (high/high) is managed closely, the regulator liaison (high power, low interest) is kept satisfied, and the IT help desk (low/low) is monitored.',
   ref:'Performance domain: Stakeholders · Focus area: Planning'},
  {id:'S2-P21',domain:D,task:4,approach:'Predictive',type:'single',
   stem:'The salience model classifies stakeholders using which three attributes?',
   options:['Power, interest and influence','Power, legitimacy and urgency','Interest, impact and attitude','Influence, budget and authority'],answer:[1],
   explanation:'The salience model considers power (ability to impose will), legitimacy (appropriateness of involvement) and urgency (need for immediate attention).',
   ref:'Performance domain: Stakeholders · Focus area: Initiating'},
  {id:'S2-P22',domain:D,task:4,approach:'Agile',type:'single',
   stem:'Customers of a subscription service are spread across Canada and rarely attend online sprint reviews. How can the team gather their feedback?',
   options:['Rely on internal opinions','Use lightweight methods such as in-product feedback, short usability sessions with a few customers and analytics, and share the findings at sprint reviews','Wait until the annual customer survey','Ask the sales team to guess'],answer:[1],
   explanation:'Engagement methods should fit stakeholders’ circumstances. Several lightweight channels bring the customer’s voice into each iteration.',
   ref:'Performance domain: Stakeholders · Principle: Focus on value'},
  {id:'S2-P23',domain:D,task:4,approach:'Predictive',type:'matching',
   stem:'Match each stakeholder engagement level to its description.',
   pairs:[{left:'Not aware of the project or its potential impacts',right:0},{left:'Aware of the project and its impacts, and opposed to the change',right:1},{left:'Aware of the project but neither supportive nor opposed',right:2},{left:'Aware of the project and actively engaged in ensuring its success',right:3}],
   choices:['Unaware','Resistant','Neutral','Leading'],
   explanation:'The engagement assessment matrix uses unaware, resistant, neutral, supportive and leading to compare current and desired engagement.',
   ref:'Performance domain: Stakeholders · Focus area: Planning'},
  {id:'S2-P24',domain:D,task:4,approach:'Hybrid',type:'single',
   stem:'A key regulator will approve the project’s environmental plan but is rarely available. What is the best engagement approach?',
   options:['Submit everything at the end for approval','Agree early with the regulator on review points, information needs and timelines, and engage them at those points','Ignore the regulator until approval is needed','Ask the sponsor to call the regulator weekly'],answer:[1],
   explanation:'Engagement with high-power stakeholders should be planned around their needs and decision points to avoid late surprises.',
   ref:'Performance domains: Stakeholders, Governance · Focus area: Planning'},
  {id:'S2-P25',domain:D,task:4,approach:'Agile',type:'single',
   stem:'A department head who was supportive has stopped responding to the team after a reorganization. What should the project manager do first?',
   options:['Remove the department head from the stakeholder register','Reassess the stakeholder’s interests and influence after the reorganization, and meet with them to understand their new priorities','Escalate to the sponsor','Assume they still support the project'],answer:[1],
   explanation:'Stakeholder attitudes and influence change. Reassessment and direct conversation reveal how to re-engage them.',
   ref:'Performance domain: Stakeholders · Focus area: Monitoring and Controlling'},
  {id:'S2-P26',domain:D,task:4,approach:'Hybrid',type:'single',
   stem:'Which document records stakeholders’ names, roles, interests, influence and classification?',
   options:['Stakeholder register','Communications management plan','Issue log','RACI chart'],answer:[0],
   explanation:'The stakeholder register holds identification and assessment information. The engagement and communication plans build on it.',
   ref:'Performance domain: Stakeholders · Focus area: Initiating'},

  // Task 5 — Align stakeholder expectations (6)
  {id:'S2-P27',domain:D,task:5,approach:'Hybrid',type:'single',
   stem:'At the kickoff, stakeholders disagree on whether cost, schedule or features is the top priority. What tool helps align expectations?',
   options:['A Gantt chart','A trade-off (project priority) matrix that shows which constraints are fixed, flexible or negotiable','The issue log','A cost baseline'],answer:[1],
   explanation:'A trade-off matrix makes priorities explicit and guides decisions when constraints conflict.',
   ref:'Performance domain: Governance · Focus area: Initiating'},
  {id:'S2-P28',domain:D,task:5,approach:'Agile',type:'single',
   stem:'The customer expects the minimum viable product to look as polished as the final product. What should the project manager do?',
   options:['Delay the MVP until it is polished','Explain the purpose of the MVP—learning with minimum effort—and agree on its scope and quality criteria with the customer before release','Release without explanation','Rename the MVP a “beta”'],answer:[1],
   explanation:'Expectation alignment means agreeing on what the MVP is for and what it will include before it is released.',
   ref:'Principle: Focus on value · Performance domain: Scope'},
  {id:'S2-P29',domain:D,task:5,approach:'Predictive',type:'single',
   stem:'Two vendors and the internal team have different understandings of what “system integration testing complete” means. What should be done?',
   options:['Let each party use its own definition','Agree on shared entry and exit criteria for integration testing and record them in the test plan and contracts','Ask the sponsor to decide when testing is complete','Skip integration testing'],answer:[1],
   explanation:'Shared, documented criteria prevent disputes between parties about when work is complete.',
   ref:'Principle: Embed quality · Performance domain: Scope'},
  {id:'S2-P30',domain:D,task:5,approach:'Agile',type:'single',
   stem:'A sponsor new to agile expects a detailed plan for every feature for the next year. How should the project manager align expectations?',
   options:['Produce the detailed plan','Explain progressive planning, show the product roadmap and release forecast, and agree on how the sponsor will see progress and influence priorities','Refuse to plan','Switch to predictive delivery'],answer:[1],
   explanation:'Aligning expectations means helping the sponsor understand how adaptive planning gives visibility and control in a different form.',
   ref:'Performance domain: Schedule · Principle: Be an accountable leader'},
  {id:'S2-P31',domain:D,task:5,approach:'Hybrid',type:'single',
   stem:'Operations managers assume the new system will cut staffing needs by 30%, but the business case does not mention staffing reductions. What should the project manager do?',
   options:['Let the assumption stand','Clarify the documented benefits with the sponsor and operations managers, and correct the misunderstanding before it shapes their plans','Add staffing reductions to the scope','Inform HR of the expected reduction'],answer:[1],
   explanation:'Unrealistic expectations about benefits must be corrected early with reference to the approved business case.',
   ref:'Principle: Focus on value · Performance domain: Stakeholders'},
  {id:'S2-P32',domain:D,task:5,approach:'Agile',type:'multi',
   stem:'Which TWO actions best align a client’s expectations at the start of an agile engagement?',
   options:['Agree on the definition of done and how acceptance will work','Promise a fixed list of features','Explain the cadence of reviews and how the client can change priorities','Avoid discussing uncertainty','Commit to a fixed price and fixed scope'],answer:[0,2],
   explanation:'Shared definitions and a clear collaboration rhythm set realistic expectations for adaptive delivery.',
   ref:'Performance domain: Stakeholders · Focus area: Initiating'},

  // Task 6 — Manage stakeholder expectations (6)
  {id:'S2-P33',domain:D,task:6,approach:'Hybrid',type:'single',
   stem:'An unhappy stakeholder bypasses the project manager and complains directly to the CEO about the project’s progress. What should the project manager do?',
   options:['Ask the CEO to ignore the complaint','Meet with the stakeholder to understand the concerns, address them with facts and options, and brief the sponsor so that the CEO receives a consistent response','Exclude the stakeholder from future meetings','Complain to the stakeholder’s manager'],answer:[1],
   explanation:'Understanding and addressing the stakeholder’s concerns directly resolves the root cause. Keeping the sponsor informed maintains alignment at the top.',
   ref:'Performance domain: Stakeholders · Principle: Be an accountable leader'},
  {id:'S2-P34',domain:D,task:6,approach:'Agile',type:'single',
   stem:'A sprint review shows that a highly anticipated feature will not be ready for the planned release. What should the project manager do?',
   options:['Hide the information until the release','Discuss it transparently at the review, explain the reasons and options, and work with the product owner to update the release forecast','Ask the team to skip testing','Promise the feature in a hot-fix'],answer:[1],
   explanation:'Reviews exist for transparency. Sharing bad news early with options keeps stakeholders’ expectations realistic.',
   ref:'Performance domain: Stakeholders · Focus area: Monitoring and Controlling'},
  {id:'S2-P35',domain:D,task:6,approach:'Predictive',type:'single',
   stem:'After go-live, the customer says the system “does not do what we expected,” although all signed-off requirements were met. What should the project manager do first?',
   options:['Point out that the requirements were signed','Meet with the customer to understand the gaps between their expectations and the delivered scope, and identify options such as change requests or a later phase','Reopen the project and fix everything for free','Close the project'],answer:[1],
   explanation:'Understanding the gap is the first step. The response is then handled through the appropriate change or follow-on mechanism.',
   ref:'Performance domain: Stakeholders · Focus area: Closing'},
  {id:'S2-P36',domain:D,task:6,approach:'Hybrid',type:'single',
   stem:'Executives expect a new AI forecasting tool to be 100% accurate. What should the project manager do?',
   options:['Agree, to maintain their support','Explain how the tool’s accuracy is measured, share realistic accuracy ranges from testing and agree on how forecasts will be used in decisions','Disable the tool','Avoid discussing accuracy'],answer:[1],
   explanation:'Managing expectations about AI means being transparent about its limits and agreeing on appropriate use.',
   ref:'AI in project management · Principle: Be an accountable leader'},
  {id:'S2-P37',domain:D,task:6,approach:'Agile',type:'single',
   stem:'Several managers ask the team for custom weekly reports in different formats, which takes a day of effort each week. What is the best approach?',
   options:['Continue producing all reports','Agree with the managers on a shared dashboard or information radiator that meets their core needs, and stop duplicating effort','Stop all reporting','Assign a junior developer to reporting'],answer:[1],
   explanation:'Transparent, shared progress information meets stakeholders’ needs while reducing waste.',
   ref:'Performance domain: Stakeholders · Focus area: Monitoring and Controlling'},
  {id:'S2-P38',domain:D,task:6,approach:'Predictive',type:'multi',
   stem:'A major milestone will be missed. Which TWO actions best manage the sponsor’s expectations?',
   options:['Inform the sponsor promptly with the cause, the impact and the recovery options','Report the milestone as complete and catch up later','Recommend a course of action and agree on next steps with the sponsor','Wait until the next monthly report','Blame the vendor publicly'],answer:[0,2],
   explanation:'Prompt, honest communication with a recommendation supports good decisions and maintains trust.',
   ref:'Principle: Be an accountable leader · Performance domain: Stakeholders'},

  // Task 7 — Help ensure knowledge transfer (6)
  {id:'S2-P39',domain:D,task:7,approach:'Hybrid',type:'single',
   stem:'An organization has several agile teams that keep solving the same testing problems independently. What should the project manager suggest?',
   options:['A monthly report on testing problems','A community of practice where testers share techniques, tools and lessons across teams','Hiring a testing consultant for each team','A rule that teams may not change testing practices'],answer:[1],
   explanation:'Communities of practice spread knowledge across teams and reduce duplicated effort.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'S2-P40',domain:D,task:7,approach:'Hybrid',type:'single',
   stem:'What is the difference between explicit and tacit knowledge?',
   options:['They are the same','Explicit knowledge is easily written down and shared, such as procedures; tacit knowledge is personal and hard to express, such as experience and judgment','Tacit knowledge is always documented','Explicit knowledge cannot be shared'],answer:[1],
   explanation:'Tacit knowledge is best transferred through interaction—mentoring, shadowing and storytelling—while explicit knowledge can be documented.',
   ref:'Performance domain: Resources · Focus area: Executing'},
  {id:'S2-P41',domain:D,task:7,approach:'Agile',type:'single',
   stem:'New team members take two months to become productive. How can the team shorten onboarding?',
   options:['Ask new members to read all past documentation','Create an onboarding playbook, assign a buddy, and pair new members on real work from the first week','Give new members only low-priority work for two months','Hire only experienced people'],answer:[1],
   explanation:'Structured onboarding combined with hands-on pairing transfers both explicit and tacit knowledge quickly.',
   ref:'Performance domain: Resources · Principle: Build an empowered culture'},
  {id:'S2-P42',domain:D,task:7,approach:'Hybrid',type:'single',
   stem:'A senior planner is retiring in three months. The planner knows the history behind many of the organization’s scheduling assumptions. What should the project manager do?',
   options:['Ask the planner to write a summary on their last day','Arrange for a successor to shadow the planner, record key decisions and assumptions, and capture stories through structured interviews','Hire a consultant after the planner leaves','Accept the loss of knowledge'],answer:[1],
   explanation:'Tacit knowledge needs time and interaction to transfer. Starting early with shadowing and interviews preserves it.',
   ref:'Performance domain: Resources · Focus area: Executing'},
  {id:'S2-P43',domain:D,task:7,approach:'Agile',type:'multi',
   stem:'Which TWO practices help an agile team retain knowledge as members change?',
   options:['Rotating pairs and sharing work across team members','Keeping each component with one specialist','Maintaining lightweight, living documentation such as decision records and a team wiki','Relying on memory','Restricting access to the code repository'],answer:[0,2],
   explanation:'Shared work spreads knowledge, and living documentation preserves it for current and future members.',
   ref:'Performance domain: Resources · Principle: Embed quality'},
  {id:'S2-P44',domain:D,task:7,approach:'Predictive',type:'single',
   stem:'Lessons learned from previous projects are stored in a repository that no one reads. What would most improve their use?',
   options:['Making the repository larger','Reviewing relevant lessons during planning, tagging them by topic and assigning owners to update standards based on them','Emailing all lessons to everyone','Deleting old lessons'],answer:[1],
   explanation:'Lessons create value only when they are found and acted on. Integrating them into planning and standards closes the loop.',
   ref:'Principle: Embed quality · Focus area: Planning'},

  // Task 8 — Plan and manage communication (6)
  {id:'S2-P45',domain:D,task:8,approach:'Predictive',type:'matching',
   stem:'Match each communication method to the most appropriate example.',
   pairs:[{left:'Interactive communication',right:0},{left:'Push communication',right:1},{left:'Pull communication',right:2}],
   choices:['A workshop to resolve a requirements dispute','A weekly status email sent to the distribution list','A project knowledge base that stakeholders visit when they need information'],
   explanation:'Interactive methods allow real-time exchange; push methods send information to recipients; pull methods let large audiences access information when needed.',
   ref:'Performance domain: Stakeholders · Focus area: Planning'},
  {id:'S2-P46',domain:D,task:8,approach:'Hybrid',type:'single',
   stem:'In the sender–receiver communication model, what is the receiver’s responsibility?',
   options:['To encode the message','To make sure the message is received in its entirety, understood correctly and acknowledged','To choose the communication medium','To send the message again'],answer:[1],
   explanation:'The receiver decodes the message, confirms understanding and gives feedback. The sender ensures that the message is clear and complete.',
   ref:'Performance domain: Stakeholders · Focus area: Executing'},
  {id:'S2-P47',domain:D,task:8,approach:'Agile',type:'single',
   stem:'Team members complain that they spend too much time in meetings, leaving little time for delivery. What should the project manager do?',
   options:['Cancel all meetings','Review meetings with the team, remove or shorten those without clear value, and keep the essential agile events time-boxed','Add a meeting to discuss the problem every day','Ask members to multitask during meetings'],answer:[1],
   explanation:'Communication should be efficient. Reviewing the value of each meeting reduces waste while keeping essential collaboration.',
   ref:'Principle: Focus on value · Focus area: Executing'},
  {id:'S2-P48',domain:D,task:8,approach:'Predictive',type:'single',
   stem:'Which information belongs in a communications management plan?',
   options:['Individual salaries','Stakeholder information needs, message content, format, frequency, responsible person and escalation process','Detailed technical specifications','The project’s risk responses'],answer:[1],
   explanation:'The communications plan defines who needs what information, when, how, from whom and how issues are escalated.',
   ref:'Performance domain: Stakeholders · Focus area: Planning'},
  {id:'S2-P49',domain:D,task:8,approach:'Hybrid',type:'single',
   stem:'An executive asks for “just one page” on a complex program. What should the project manager provide?',
   options:['A one-page summary with overall status, key metrics, top risks and the decisions needed, with links to detail','The full status report reduced to a small font','A list of all completed tasks','Only the financial forecast'],answer:[0],
   explanation:'Executive communication should be concise and decision-oriented, with detail available on request.',
   ref:'Performance domain: Stakeholders · Focus area: Monitoring and Controlling'},
  {id:'S2-P50',domain:D,task:8,approach:'Agile',type:'single',
   stem:'A project team spans Regina, Montréal and Manila. Important decisions made in chat are being missed by members in other time zones. What should the team do?',
   options:['Make all decisions in live meetings at midnight for some members','Agree on a working agreement to record decisions in a shared decision log and summarize key chat threads, with clear response times','Stop using chat','Let each location make its own decisions'],answer:[1],
   explanation:'Asynchronous teams need explicit agreements and a single source of truth for decisions so that no one is left out.',
   ref:'Principle: Build an empowered culture · Performance domain: Stakeholders'}
];
