import {ExamQuestion} from '../../exam-types';

const D='Process' as const;

export const PROCESS_QUESTIONS:ExamQuestion[]=[
  // Task 1 — Integrated plan and plan delivery (7)
  {id:'S2-R01',domain:D,task:1,approach:'Hybrid',type:'matching',
   stem:'Match each project life cycle to its description.',
   pairs:[{left:'Predictive',right:0},{left:'Iterative',right:1},{left:'Incremental',right:2},{left:'Adaptive (agile)',right:3}],
   choices:['Scope, time and cost are determined early; changes are carefully managed','The product is refined through repeated cycles that add understanding','Usable portions of the product are delivered in successive pieces','Short iterations deliver and refine increments, with continuous customer feedback'],
   explanation:'Predictive fixes scope early; iterative refines through cycles; incremental delivers usable pieces; adaptive combines iteration and incremental delivery with rapid feedback.',
   ref:'Principle: Adopt a holistic view · Focus area: Planning'},
  {id:'S2-R02',domain:D,task:1,approach:'Predictive',type:'single',
   stem:'Which baselines are usually part of the project management plan on a predictive project?',
   options:['Scope, schedule and cost baselines','Risk, quality and communication baselines','Resource, procurement and stakeholder baselines','Only the schedule baseline'],answer:[0],
   explanation:'The scope, schedule and cost baselines are integrated (performance measurement baseline) and used to measure performance.',
   ref:'Performance domains: Scope, Schedule, Finance · Focus area: Planning'},
  {id:'S2-R03',domain:D,task:1,approach:'Predictive',type:'single',
   stem:'The near-term work is well understood, but later phases depend on decisions not yet made. Which planning technique is most appropriate?',
   options:['Plan everything in detail now','Rolling-wave planning: plan near-term work in detail and later work at a higher level, refining it as information becomes available','Do not plan later phases at all','Use only top-down estimates'],answer:[1],
   explanation:'Rolling-wave planning is a form of progressive elaboration suited to uncertainty in later work.',
   ref:'Performance domain: Schedule · Focus area: Planning'},
  {id:'S2-R04',domain:D,task:1,approach:'Hybrid',type:'single',
   stem:'A medical-device software project must meet strict regulatory documentation requirements but also wants frequent user feedback. What approach is most appropriate?',
   options:['Pure agile with minimal documentation','A hybrid approach that uses iterative development with documentation and validation activities built into each increment and its definition of done','Pure predictive with no user feedback until the end','Skip the regulatory documentation'],answer:[1],
   explanation:'Tailoring lets regulated projects gain the benefits of iterative delivery while meeting compliance by embedding documentation in the workflow.',
   ref:'Principle: Adopt a holistic view · Performance domain: Governance'},
  {id:'S2-R05',domain:D,task:1,approach:'Predictive',type:'single',
   stem:'Which plan defines how versions of project documents and product components are identified, controlled and tracked?',
   options:['Configuration management plan','Communication management plan','Resource management plan','Benefits management plan'],answer:[0],
   explanation:'Configuration management controls versions and changes to product and document items, supporting change control.',
   ref:'Performance domain: Governance · Focus area: Planning'},
  {id:'S2-R06',domain:D,task:1,approach:'Agile',type:'single',
   stem:'Five agile teams are working on one large product. Which practice helps them plan together and manage dependencies?',
   options:['Each team plans independently','A joint, cadence-based planning event (such as big-room or program-increment planning) in which teams align objectives and identify dependencies','A single detailed Gantt chart for all teams','Assigning one product owner to plan for all teams privately'],answer:[1],
   explanation:'Scaled agile approaches use joint planning events to align teams, surface dependencies and agree on shared objectives.',
   ref:'Principle: Adopt a holistic view · Performance domain: Schedule'},
  {id:'S2-R07',domain:D,task:1,approach:'Hybrid',type:'multi',
   stem:'Which TWO activities should take place at a project kickoff meeting?',
   options:['Communicating objectives, roles and the delivery approach','Approving the final deliverables','Agreeing on how the team will work together and communicate','Closing the procurement contracts','Rebaselining the schedule'],answer:[0,2],
   explanation:'A kickoff aligns everyone on objectives, roles, approach and ways of working.',
   ref:'Focus area: Planning · Performance domain: Stakeholders'},

  // Task 2 — Develop and manage scope (8)
  {id:'S2-R08',domain:D,task:2,approach:'Predictive',type:'single',
   stem:'Which tool links requirements to their business objectives and to the deliverables and tests that satisfy them?',
   options:['Requirements traceability matrix','Issue log','Resource histogram','Stakeholder register'],answer:[0],
   explanation:'The traceability matrix ensures that each requirement adds value and is delivered and tested.',
   ref:'Performance domain: Scope · Focus area: Planning'},
  {id:'S2-R09',domain:D,task:2,approach:'Agile',type:'matching',
   stem:'Match each MoSCoW category to its meaning.',
   pairs:[{left:'Must have',right:0},{left:'Should have',right:1},{left:'Could have',right:2},{left:'Won’t have (this time)',right:3}],
   choices:['Critical; the release fails without it','Important, but the release is still viable without it','Desirable if time and resources allow','Agreed to be out of scope for this release'],
   explanation:'MoSCoW makes scope priorities explicit so that trade-offs can be made within a fixed time-box.',
   ref:'Performance domain: Scope · Principle: Focus on value'},
  {id:'S2-R10',domain:D,task:2,approach:'Agile',type:'single',
   stem:'In the Kano model, what is a “delighter” (attractive) feature?',
   options:['A basic feature customers expect; its absence causes dissatisfaction','A feature that increases satisfaction in proportion to how well it is delivered','An unexpected feature that greatly increases satisfaction when present but does not cause dissatisfaction when absent','A feature customers dislike'],answer:[2],
   explanation:'Kano classifies features as basic (must-be), performance (one-dimensional) and delighters (attractive), helping teams prioritize.',
   ref:'Principle: Focus on value · Performance domain: Scope'},
  {id:'S2-R11',domain:D,task:2,approach:'Agile',type:'single',
   stem:'The team struggles to see how individual user stories fit into the overall user experience. Which technique helps?',
   options:['A WBS dictionary','User story mapping, which arranges stories along the user’s journey and slices them into releases','A RACI chart','A control chart'],answer:[1],
   explanation:'Story mapping visualizes the end-to-end journey, helping the team plan releases that deliver coherent value.',
   ref:'Performance domain: Scope · Focus area: Planning'},
  {id:'S2-R12',domain:D,task:2,approach:'Predictive',type:'single',
   stem:'What does the “100% rule” mean in a work breakdown structure?',
   options:['Every work package must be 100% complete before the next starts','The WBS includes all of the work defined by the scope—and only that work—with each level fully representing its parent','Each work package should take 100 hours','The budget must be 100% allocated to work packages'],answer:[1],
   explanation:'The 100% rule ensures that nothing is missing and nothing extra is included at any level of the WBS.',
   ref:'Performance domain: Scope · Focus area: Planning'},
  {id:'S2-R13',domain:D,task:2,approach:'Agile',type:'single',
   stem:'Stories frequently enter sprints without enough information and get stuck. What should the team introduce?',
   options:['A longer sprint','A “definition of ready” that describes what a story needs before it can be pulled into a sprint','A detailed requirements document for every story','A rule that only the product owner can start stories'],answer:[1],
   explanation:'A definition of ready improves flow by making sure stories are understood, sized and testable before work starts.',
   ref:'Performance domain: Scope · Principle: Embed quality'},
  {id:'S2-R14',domain:D,task:2,approach:'Predictive',type:'single',
   stem:'Users struggle to describe what they want from a new reporting tool. Which requirements-elicitation technique is most effective?',
   options:['A questionnaire to 1,000 users','Prototyping, so that users can react to a model and refine their requirements','Reading the old system’s manual','Asking the vendor for its standard requirements'],answer:[1],
   explanation:'Prototypes give users something concrete to react to, which uncovers needs they cannot easily articulate.',
   ref:'Performance domain: Scope · Focus area: Planning'},
  {id:'S2-R15',domain:D,task:2,approach:'Predictive',type:'multi',
   stem:'Which TWO items are typically found in a WBS dictionary entry?',
   options:['Description of the work package and its acceptance criteria','The sponsor’s personal objectives','Responsible organization, schedule milestones and cost estimate','The lessons-learned register','The team’s vacation calendar'],answer:[0,2],
   explanation:'The WBS dictionary provides detail for each WBS component, including description, responsibility, milestones, estimates and acceptance criteria.',
   ref:'Performance domain: Scope · Focus area: Planning'},

  // Task 3 — Value-based delivery (7)
  {id:'S2-R16',domain:D,task:3,approach:'Predictive',type:'dropdown',
   stem:'A project costs $240,000 and is expected to generate $60,000 in net cash inflows each year. What is the simple payback period?',
   options:['2 years','3 years','4 years','6 years'],answer:[2],
   explanation:'Payback period = investment ÷ annual inflow = 240,000 ÷ 60,000 = 4 years. It ignores the time value of money.',
   ref:'Principle: Focus on value · Performance domain: Finance'},
  {id:'S2-R17',domain:D,task:3,approach:'Predictive',type:'single',
   stem:'Four candidate projects have the following net present values. Based on NPV alone, which should be selected?',
   options:['Project A: NPV $120,000 over 3 years','Project B: NPV $95,000 over 1 year','Project C: NPV $150,000 over 5 years','Project D: NPV –$20,000 over 2 years'],answer:[2],
   explanation:'NPV already accounts for the time value of money, so the project with the highest NPV (C) is preferred, regardless of duration.',
   ref:'Principle: Focus on value · Performance domain: Governance'},
  {id:'S2-R18',domain:D,task:3,approach:'Predictive',type:'dropdown',
   stem:'A project has expected benefits of $1,500,000 and costs of $1,200,000. What is the benefit–cost ratio?',
   options:['0.80','1.25','1.50','3.00'],answer:[1],
   explanation:'BCR = benefits ÷ costs = 1,500,000 ÷ 1,200,000 = 1.25. A ratio above 1.0 means benefits exceed costs.',
   ref:'Principle: Focus on value · Performance domain: Finance'},
  {id:'S2-R19',domain:D,task:3,approach:'Agile',type:'single',
   stem:'A team uses value stream mapping on its release process and finds that work waits 9 days for approvals out of a 12-day lead time. What should it focus on?',
   options:['Speeding up coding','Reducing the waiting (non-value-added) time in the approval steps','Adding more developers','Increasing the sprint length'],answer:[1],
   explanation:'Value stream mapping highlights waste. Here, most of the lead time is waiting, so improving approvals gives the biggest gain.',
   ref:'Principle: Focus on value · Principle: Embed quality'},
  {id:'S2-R20',domain:D,task:3,approach:'Agile',type:'single',
   stem:'What is a minimum marketable feature (MMF)?',
   options:['The smallest piece of functionality that delivers real value to users and can be released on its own','A prototype used only for internal testing','The least expensive feature in the backlog','A feature required by regulation'],answer:[0],
   explanation:'An MMF is the smallest unit of functionality that has standalone value to the market, enabling early value delivery.',
   ref:'Principle: Focus on value · Performance domain: Scope'},
  {id:'S2-R21',domain:D,task:3,approach:'Hybrid',type:'single',
   stem:'A business case was approved two years ago. Market changes now suggest that the main benefit may not materialize. When should the business case be reviewed?',
   options:['Only at project closure','At planned governance points and whenever significant changes affect the expected value','Never, once approved','Only if the budget is exceeded'],answer:[1],
   explanation:'The business case is a living document that should be revisited to confirm that the project still justifies investment.',
   ref:'Principle: Focus on value · Performance domain: Governance'},
  {id:'S2-R22',domain:D,task:3,approach:'Agile',type:'multi',
   stem:'Which TWO concepts help a product owner decide what to build next to maximize value?',
   options:['Cost of delay','The number of developers on the team','Customer feedback from the latest increment','The age of the backlog item','The length of the item’s description'],answer:[0,2],
   explanation:'Cost of delay quantifies urgency, and customer feedback validates what users actually value.',
   ref:'Principle: Focus on value · Performance domain: Scope'},

  // Task 4 — Plan and manage resources (6)
  {id:'S2-R23',domain:D,task:4,approach:'Predictive',type:'single',
   stem:'A team member was promised to the project in the contract with the client before the project started. What is this called?',
   options:['Negotiation','Pre-assignment','Acquisition','Virtual team'],answer:[1],
   explanation:'Pre-assignment happens when team members are selected in advance—for example, because they were named in a proposal or contract.',
   ref:'Performance domain: Resources · Focus area: Planning'},
  {id:'S2-R24',domain:D,task:4,approach:'Predictive',type:'single',
   stem:'Which document shows when each team member is available to work on the project, including holidays and other commitments?',
   options:['Resource calendar','Project charter','Risk register','Change log'],answer:[0],
   explanation:'Resource calendars identify working days, shifts and availability, which are essential for scheduling and leveling.',
   ref:'Performance domains: Resources, Schedule · Focus area: Planning'},
  {id:'S2-R25',domain:D,task:4,approach:'Hybrid',type:'single',
   stem:'The project manager must choose between three candidates for a business analyst role. Which approach is most objective?',
   options:['Choose the candidate the sponsor likes best','Use multicriteria decision analysis with weighted criteria such as experience, availability, cost and domain knowledge','Choose the cheapest candidate','Choose the candidate who applied first'],answer:[1],
   explanation:'Weighted criteria make resource selection transparent and aligned with project needs.',
   ref:'Performance domain: Resources · Focus area: Planning'},
  {id:'S2-R26',domain:D,task:4,approach:'Agile',type:'single',
   stem:'An agile team depends on a database specialist who is shared with three other teams, causing frequent waits. What is the best long-term solution?',
   options:['Ask the specialist to work overtime','Have the specialist coach team members to build database skills within the team, reducing the dependency','Wait for the specialist each time','Remove database work from the backlog'],answer:[1],
   explanation:'Growing cross-functional skills (T-shaped team members) removes bottlenecks and improves flow.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'S2-R27',domain:D,task:4,approach:'Predictive',type:'single',
   stem:'Why should a project manager track physical resources such as equipment and materials, not just people?',
   options:['It is only required for audits','Shortages, late deliveries or misuse of physical resources can delay the schedule and increase cost','Physical resources do not affect projects','To reduce the number of team members'],answer:[1],
   explanation:'Physical resource management covers availability, logistics and usage of equipment and materials, which directly affect delivery.',
   ref:'Performance domain: Resources · Focus area: Executing'},
  {id:'S2-R28',domain:D,task:4,approach:'Hybrid',type:'multi',
   stem:'A team is fully remote for the first time. Which TWO resource-management actions are most important?',
   options:['Provide the collaboration tools and access people need to work effectively','Require cameras on at all times','Agree on availability, core hours and expectations in the team’s working agreements','Measure productivity by keyboard activity','Reduce one-to-one meetings'],answer:[0,2],
   explanation:'Remote teams need the right tools and clear, agreed expectations. Surveillance damages trust.',
   ref:'Performance domain: Resources · Principle: Build an empowered culture'},

  // Task 5 — Plan and manage procurement (6)
  {id:'S2-R29',domain:D,task:5,approach:'Predictive',type:'matching',
   stem:'Match each procurement document to its purpose.',
   pairs:[{left:'Request for information (RFI)',right:0},{left:'Request for quotation (RFQ)',right:1},{left:'Request for proposal (RFP)',right:2}],
   choices:['Gathers information about sellers’ capabilities before deciding how to procure','Asks for prices when the requirement is clearly defined and price is the main factor','Asks for proposed solutions when the requirement is complex and several factors will be evaluated'],
   explanation:'RFIs explore the market, RFQs compare prices for well-defined needs, and RFPs evaluate solutions for complex needs.',
   ref:'Performance domain: Resources (procurement) · Focus area: Planning'},
  {id:'S2-R30',domain:D,task:5,approach:'Predictive',type:'dropdown',
   stem:'A team can license software for $18,000 per month, or build its own for $240,000 plus $6,000 per month in maintenance. After how many months does building become cheaper?',
   options:['10 months','13 months','20 months','40 months'],answer:[2],
   explanation:'Break-even: 240,000 + 6,000m = 18,000m → 240,000 = 12,000m → m = 20 months. If the tool is needed for more than 20 months, building is cheaper.',
   ref:'Performance domains: Finance, Resources (procurement) · Focus area: Planning'},
  {id:'S2-R31',domain:D,task:5,approach:'Predictive',type:'single',
   stem:'A vendor bidding on your project sends you expensive concert tickets. What should you do?',
   options:['Accept them because they do not affect your decision','Decline the gift, follow the organization’s policy and inform the procurement or ethics function as required','Accept them and give them to the team','Share them with the other bidders'],answer:[1],
   explanation:'Accepting gifts from bidders creates a conflict of interest. The ethical response is to decline and follow policy.',
   ref:'Principle: Be an accountable leader · Ethics'},
  {id:'S2-R32',domain:D,task:5,approach:'Predictive',type:'single',
   stem:'A seller submits a claim saying the buyer’s late approvals caused extra costs. The buyer disagrees. What is the preferred way to resolve it?',
   options:['Go directly to court','Negotiate in good faith using the contract terms and records, and use alternative dispute resolution if negotiation fails','Ignore the claim','Terminate the contract'],answer:[1],
   explanation:'Claims administration prefers negotiation, then alternative dispute resolution such as mediation, before litigation.',
   ref:'Performance domains: Resources (procurement), Governance · Focus area: Monitoring and Controlling'},
  {id:'S2-R33',domain:D,task:5,approach:'Agile',type:'single',
   stem:'An agile vendor’s contract has a fixed total budget. Halfway through, the client wants to add new features. How can this be handled within the contract?',
   options:['Refuse all new features','Use the contract’s change mechanism to swap new features for lower-priority backlog items of similar size, keeping the total budget fixed','Charge for every change without discussion','Extend the contract automatically'],answer:[1],
   explanation:'“Money for nothing, change for free” style clauses let clients swap scope within a fixed budget, aligning contracts with agile delivery.',
   ref:'Performance domains: Resources (procurement), Scope'},
  {id:'S2-R34',domain:D,task:5,approach:'Hybrid',type:'multi',
   stem:'Which TWO practices help the buyer manage seller performance during a contract?',
   options:['Regular performance reviews against agreed measures and deliverables','Paying all invoices without checking','Inspections or audits of the seller’s work, as allowed by the contract','Avoiding contact with the seller','Changing the contract terms informally'],answer:[0,2],
   explanation:'Controlling procurements includes performance reviews and inspections to confirm that the seller meets its obligations.',
   ref:'Performance domain: Resources (procurement) · Focus area: Monitoring and Controlling'},

  // Task 6 — Plan and manage finance (6)
  {id:'S2-R35',domain:D,task:6,approach:'Predictive',type:'dropdown',
   stem:'PV = $400,000, EV = $360,000 and AC = $420,000. What is the cost variance (CV)?',
   options:['–$40,000','–$60,000','+$20,000','–$20,000'],answer:[1],
   explanation:'CV = EV – AC = 360,000 – 420,000 = –$60,000 (over budget). SV = EV – PV = –$40,000.',
   ref:'Performance domain: Finance · Focus area: Monitoring and Controlling'},
  {id:'S2-R36',domain:D,task:6,approach:'Predictive',type:'dropdown',
   stem:'A rough order of magnitude (ROM) estimate for a project is $500,000. Using a typical ROM accuracy range of –25% to +75%, what is the estimate range?',
   options:['$450,000 to $550,000','$375,000 to $875,000','$475,000 to $550,000','$250,000 to $750,000'],answer:[1],
   explanation:'–25% of $500,000 is $375,000, and +75% is $875,000. ROM estimates are used early, when information is limited.',
   ref:'Performance domain: Finance · Focus area: Initiating'},
  {id:'S2-R37',domain:D,task:6,approach:'Predictive',type:'single',
   stem:'Historical data shows that installing fibre costs $45 per metre. The project needs 12,000 metres. Which estimating technique is this?',
   options:['Analogous estimating','Parametric estimating','Bottom-up estimating','Three-point estimating'],answer:[1],
   explanation:'Parametric estimating uses a statistical relationship between variables (cost per metre × metres) to calculate the estimate: $540,000.',
   ref:'Performance domain: Finance · Focus area: Planning'},
  {id:'S2-R38',domain:D,task:6,approach:'Predictive',type:'dropdown',
   stem:'BAC = $1,000,000, EV = $360,000 and AC = $420,000. The cost overrun was caused by a one-time event that will not recur. What is the EAC?',
   options:['$1,000,000','$1,060,000','$1,167,000','$1,420,000'],answer:[1],
   explanation:'For atypical variance, EAC = AC + (BAC – EV) = 420,000 + 640,000 = $1,060,000. The remaining work is expected to be done at the budgeted rate.',
   ref:'Performance domain: Finance · Focus area: Monitoring and Controlling'},
  {id:'S2-R39',domain:D,task:6,approach:'Hybrid',type:'single',
   stem:'The approved budget exceeds the organization’s funding available in the first quarter. What should the project manager do?',
   options:['Spend as planned and request more funding later','Perform funding limit reconciliation—reschedule work or spending to fit the funding constraints, possibly adjusting the schedule','Cancel the project','Move costs to another project'],answer:[1],
   explanation:'Funding limit reconciliation aligns planned spending with funding availability, which may require schedule changes.',
   ref:'Performance domain: Finance · Focus area: Planning'},
  {id:'S2-R40',domain:D,task:6,approach:'Agile',type:'single',
   stem:'How do many organizations fund long-lived agile product teams?',
   options:['With a fixed budget per feature, approved one at a time','Through persistent funding of value streams or product teams, with regular reviews of the value delivered to adjust investment','By paying only after the product is complete','Through the operations budget only'],answer:[1],
   explanation:'Lean or product-based funding provides stable team funding and adjusts investment based on outcomes, rather than funding individual projects.',
   ref:'Performance domain: Finance · Principle: Focus on value'},

  // Task 7 — Plan and optimize quality (6)
  {id:'S2-R41',domain:D,task:7,approach:'Predictive',type:'single',graphic:'pareto',
   stem:'Based on the Pareto chart of UAT defects, where should the team focus improvement efforts first?',
   options:['Documentation and performance defects','Data entry and integration defects, which together account for about 74% of all defects','UI layout defects','All categories equally'],answer:[1],
   explanation:'The two largest categories (46 + 28 = 74 of 100 defects) are the “vital few.” Addressing their root causes gives the biggest improvement.',
   ref:'Principle: Embed quality · Focus area: Monitoring and Controlling'},
  {id:'S2-R42',domain:D,task:7,approach:'Predictive',type:'single',graphic:'control-2',
   stem:'The control chart shows claim processing cycle times. What should the project manager conclude?',
   options:['The process is stable; no action is needed','Sample 9 is above the upper control limit, indicating a special cause that should be investigated','The control limits are too wide','The mean should be changed to 27.5 hours'],answer:[1],
   explanation:'A point outside the control limits signals a special (assignable) cause of variation that should be investigated and addressed.',
   ref:'Principle: Embed quality · Focus area: Monitoring and Controlling'},
  {id:'S2-R43',domain:D,task:7,approach:'Predictive',type:'single',
   stem:'An independent team reviews whether the project is following the organization’s quality policies and processes. What is this called?',
   options:['Quality audit','Inspection','Benchmarking','Statistical sampling'],answer:[0],
   explanation:'A quality audit is a structured, independent review of whether project activities comply with policies and processes. It helps identify improvements.',
   ref:'Principle: Embed quality · Focus area: Executing'},
  {id:'S2-R44',domain:D,task:7,approach:'Predictive',type:'single',
   stem:'Testing every unit of 50,000 manufactured parts would be too expensive. What should the team use?',
   options:['No testing','Statistical sampling: inspect a representative sample to draw conclusions about the whole population','Customer testing only','Testing only the first 100 parts'],answer:[1],
   explanation:'Statistical sampling reduces the cost of quality control while providing reliable conclusions when samples are chosen correctly.',
   ref:'Principle: Embed quality · Focus area: Monitoring and Controlling'},
  {id:'S2-R45',domain:D,task:7,approach:'Agile',type:'single',
   stem:'An agile team wants to catch integration defects as early as possible. Which practice helps most?',
   options:['Integrating code once per release','Continuous integration with automated tests run on every change','Manual testing at the end of each quarter','Asking customers to report defects'],answer:[1],
   explanation:'Continuous integration detects defects within minutes of a change, when they are cheapest to fix.',
   ref:'Principle: Embed quality · Focus area: Executing'},
  {id:'S2-R46',domain:D,task:7,approach:'Hybrid',type:'multi',
   stem:'Which TWO costs are examples of the cost of non-conformance (failure costs)?',
   options:['Rework and scrap','Training for the team','Warranty claims and lost customers','Process documentation','Equipment calibration'],answer:[0,2],
   explanation:'Internal failure (rework, scrap) and external failure (warranty, lost business) are costs of non-conformance. Training, documentation and calibration are costs of conformance.',
   ref:'Principle: Embed quality · Performance domain: Finance'},

  // Task 8 — Plan and manage schedule (5)
  {id:'S2-R47',domain:D,task:8,approach:'Predictive',type:'matching',
   stem:'Match each dependency type to its example.',
   pairs:[{left:'Mandatory (hard logic)',right:0},{left:'Discretionary (preferred logic)',right:1},{left:'External',right:2}],
   choices:['A foundation must be poured before walls can be built','The team prefers to finish the design review before starting coding, based on best practice','Construction cannot start until the city issues a building permit'],
   explanation:'Mandatory dependencies are inherent in the work; discretionary dependencies are chosen by the team; external dependencies involve parties outside the project.',
   ref:'Performance domain: Schedule · Focus area: Planning'},
  {id:'S2-R48',domain:D,task:8,approach:'Predictive',type:'dropdown',
   stem:'An activity has an early start of day 5, early finish of day 9, late start of day 8 and late finish of day 12. What is its total float?',
   options:['0 days','3 days','4 days','7 days'],answer:[1],
   explanation:'Total float = LS – ES = 8 – 5 = 3 days (or LF – EF = 12 – 9 = 3 days).',
   ref:'Performance domain: Schedule · Focus area: Planning'},
  {id:'S2-R49',domain:D,task:8,approach:'Predictive',type:'single',
   stem:'Paint must cure for 2 days before carpet can be installed. How is this represented in the schedule?',
   options:['A lead of 2 days','A lag of 2 days on the finish-to-start relationship','A start-to-start relationship','Float of 2 days'],answer:[1],
   explanation:'A lag is a required delay between activities. A lead allows a successor to start before the predecessor finishes.',
   ref:'Performance domain: Schedule · Focus area: Planning'},
  {id:'S2-R50',domain:D,task:8,approach:'Predictive',type:'single',
   stem:'The project manager decides to start testing before development is fully complete to recover schedule time. What is the main risk of this technique?',
   options:['Higher cost from added resources','Increased risk of rework because activities that were sequential now overlap','No risk','Reduced scope'],answer:[1],
   explanation:'Fast tracking overlaps activities, which can save time but increases the risk of rework. Crashing adds cost.',
   ref:'Performance domains: Schedule, Risk · Focus area: Monitoring and Controlling'},
  {id:'S2-R51',domain:D,task:8,approach:'Hybrid',type:'single',
   stem:'Which relationship type means the successor cannot finish until the predecessor finishes—for example, “editing cannot finish until writing finishes”?',
   options:['Finish-to-start','Start-to-start','Finish-to-finish','Start-to-finish'],answer:[2],
   explanation:'Finish-to-finish links the completion of two activities. Finish-to-start is the most common relationship type.',
   ref:'Performance domain: Schedule · Focus area: Planning'},

  // Task 9 — Evaluate project status (5)
  {id:'S2-R52',domain:D,task:9,approach:'Agile',type:'dropdown',graphic:'burnup-2',
   stem:'Based on the burnup chart, if the team maintains its current velocity, at the end of which sprint will the release be complete?',
   options:['Sprint 8','Sprint 9','Sprint 10','Sprint 11'],answer:[1],
   explanation:'After sprint 6, 180 of 270 points are done (scope was reduced from 300 to 270). Velocity is 30 points per sprint, so the remaining 90 points take 3 sprints: the release finishes at the end of sprint 9.',
   ref:'Performance domain: Schedule · Focus area: Monitoring and Controlling'},
  {id:'S2-R53',domain:D,task:9,approach:'Predictive',type:'single',
   stem:'Governance has set a variance threshold of ±10% for cost. The project’s cost variance is –6%. What should the project manager do?',
   options:['Escalate immediately to the steering committee','Continue monitoring and take corrective action within the project manager’s authority, because the variance is within the agreed threshold','Ignore the variance','Rebaseline the budget'],answer:[1],
   explanation:'Variance thresholds define when escalation is needed. Within the threshold, the project manager manages the variance and monitors the trend.',
   ref:'Performance domain: Governance · Focus area: Monitoring and Controlling'},
  {id:'S2-R54',domain:D,task:9,approach:'Hybrid',type:'single',
   stem:'Over the past four months, the CPI has been 0.98, 0.95, 0.93 and 0.91. What does trend analysis suggest?',
   options:['Performance is stable','Cost performance is steadily deteriorating; the project manager should investigate causes before the variance exceeds thresholds','The project will finish under budget','No action is required until CPI falls below 0.80'],answer:[1],
   explanation:'Trend analysis looks at the direction of performance over time, enabling early intervention.',
   ref:'Performance domain: Finance · Focus area: Monitoring and Controlling'},
  {id:'S2-R55',domain:D,task:9,approach:'Agile',type:'single',
   stem:'A team’s velocity jumped from 30 to 45 points after management started comparing teams’ velocities. What is the most likely explanation?',
   options:['The team became 50% more productive','Estimates may have been inflated in response to the comparison, so velocity is being misused as a performance measure','The sprint length changed','The product owner added more stories'],answer:[1],
   explanation:'Velocity is a team-specific planning tool. Using it to compare teams encourages point inflation and makes it meaningless.',
   ref:'Principle: Build an empowered culture · Focus area: Monitoring and Controlling'},
  {id:'S2-R56',domain:D,task:9,approach:'Predictive',type:'multi',
   stem:'Which TWO items are typically included in a work performance report for stakeholders?',
   options:['Status against baselines and forecasts','Every email exchanged that month','Key risks, issues and decisions needed','Team members’ personal notes','Raw timesheet entries'],answer:[0,2],
   explanation:'Performance reports summarize progress, forecasts, risks, issues and decisions—not raw data.',
   ref:'Performance domain: Stakeholders · Focus area: Monitoring and Controlling'},

  // Task 10 — Manage project closure (5)
  {id:'S2-R57',domain:D,task:10,approach:'Predictive',type:'single',
   stem:'What is the purpose of the final project report?',
   options:['To record team members’ performance ratings','To summarize the project’s performance against objectives, including scope, quality, cost, schedule, benefits and lessons learned','To request additional funding','To list all project emails'],answer:[1],
   explanation:'The final report summarizes outcomes and performance and provides information for organizational learning.',
   ref:'Focus area: Closing · Performance domain: Governance'},
  {id:'S2-R58',domain:D,task:10,approach:'Agile',type:'single',
   stem:'An agile team is moving to a new product, and the current product will be supported by an operations team. What should happen before the team moves?',
   options:['The team leaves immediately','The team transitions knowledge, documentation, monitoring and support processes to the operations team, and confirms the handover with the product owner','The backlog is deleted','The operations team learns from the code alone'],answer:[1],
   explanation:'Closure in agile includes a deliberate transition so that the receiving team can operate and support the product.',
   ref:'Focus area: Closing · Performance domain: Resources'},
  {id:'S2-R59',domain:D,task:10,approach:'Predictive',type:'single',
   stem:'Several years after closure, an auditor asks for evidence that the project’s deliverables were accepted. Where should this be found?',
   options:['In team members’ personal email','In the archived project records, as defined by the organization’s retention policies','Nowhere; projects do not keep records','In the vendor’s files only'],answer:[1],
   explanation:'Archiving records according to policy supports audits, legal needs and future projects.',
   ref:'Focus area: Closing · Performance domain: Governance'},
  {id:'S2-R60',domain:D,task:10,approach:'Hybrid',type:'single',
   stem:'A phase of a multi-phase project is complete. What should happen at the phase end?',
   options:['The next phase starts automatically','A phase-gate review confirms the phase deliverables and decides whether to continue, change or stop the project','The team is released permanently','The business case is archived'],answer:[1],
   explanation:'Phase-end reviews are governance decision points that confirm results and the continued viability of the project.',
   ref:'Performance domain: Governance · Focus area: Closing'},
  {id:'S2-R61',domain:D,task:10,approach:'Predictive',type:'multi',
   stem:'Which TWO conditions should be met before a project is formally closed?',
   options:['All deliverables are accepted, or the project has been formally terminated','The team has started a new project','Contracts are closed and resources are released','The sponsor has left the organization','The budget is fully spent'],answer:[0,2],
   explanation:'Formal closure requires acceptance (or termination), closed contracts and released resources, along with archived records.',
   ref:'Focus area: Closing · Performance domain: Governance'}
];
