import {ExamQuestion} from '../../exam-types';

const D='Business Environment' as const;

export const BUSINESS_ENVIRONMENT_QUESTIONS:ExamQuestion[]=[
  // Task 1 — Governance (5)
  {id:'S5-B01',domain:D,task:1,approach:'Hybrid',type:'single',
   stem:'A newly appointed project manager finds that three different executives each believe they can approve scope changes on a hybrid logistics project. What should the project manager do first?',
   options:['Accept changes from whichever executive asks first','Ask the sponsor to confirm the decision rights and escalation path, and record them in the governance section of the plan','Freeze all scope until the project ends','Let the team decide which executive to follow'],answer:[1],
   explanation:'Unclear decision rights cause conflict and rework. The sponsor confirms who decides what, and the agreement is documented so everyone follows it.',
   ref:'Performance domain: Governance · Focus area: Planning'},
  {id:'S5-B02',domain:D,task:1,approach:'Predictive',type:'single',
   stem:'A steering committee wants the project manager to bring every purchase above $500 to its monthly meeting. Approvals are now delaying critical-path work. What is the best approach?',
   options:['Keep waiting for monthly approvals','Propose tiered approval thresholds that keep oversight of significant spend while delegating small purchases to the project manager','Make purchases without approval','Split purchases into amounts under $500'],answer:[1],
   explanation:'Governance should be proportionate. Tiered thresholds keep control where it matters and remove delays where risk is low. Splitting purchases to avoid approval is unethical.',
   ref:'Principle: Tailor the approach · Performance domain: Governance'},
  {id:'S5-B03',domain:D,task:1,approach:'Agile',type:'single',
   stem:'Several agile teams in a portfolio build features that depend on one another, and conflicting priorities keep blocking delivery. Which governance practice helps most?',
   options:['A shared, regular cross-team planning and prioritization event with the product owners and key stakeholders','Each team setting its priorities independently','A yearly portfolio review only','Assigning all dependencies to one team'],answer:[0],
   explanation:'Regular cross-team planning (for example, big-room or increment planning) aligns priorities and makes dependencies visible across teams.',
   ref:'Performance domain: Governance · Principle: Adopt a holistic view'},
  {id:'S5-B04',domain:D,task:1,approach:'Hybrid',type:'multi',
   stem:'Which TWO items belong in a project governance framework?',
   options:['Decision-making authority and escalation thresholds','The team’s preferred lunch schedule','Stage-gate or review points and the criteria used at each','Each developer’s personal coding style','The colour scheme of status reports'],answer:[0,2],
   explanation:'A governance framework defines who decides, when decisions are escalated, and when and how the project is reviewed.',
   ref:'Performance domain: Governance · Focus area: Initiating'},
  {id:'S5-B05',domain:D,task:1,approach:'Predictive',type:'single',
   stem:'A project is being set up in a weak matrix organization. What should the project manager expect about their authority?',
   options:['Full authority over resources and budget','Limited authority, with functional managers controlling most resources and budget','No need to coordinate with functional managers','Authority equal to the CEO'],answer:[1],
   explanation:'In a weak matrix, functional managers keep most control. The project manager must coordinate and negotiate for resources.',
   ref:'Performance domain: Governance · Focus area: Initiating'},

  // Task 2 — Compliance (4)
  {id:'S5-B06',domain:D,task:2,approach:'Agile',type:'single',
   stem:'An agile team is building a payments feature that must meet card-industry security standards. How should compliance be handled?',
   options:['Check compliance only once, just before launch','Build the security requirements into the Definition of Done and acceptance criteria, and include a compliance specialist in reviews','Leave compliance to the payment provider','Ignore the standards because agile teams are self-organizing'],answer:[1],
   explanation:'Building compliance into the Definition of Done means each increment is checked as it is built, avoiding late, costly surprises.',
   ref:'Performance domain: Governance · Focus area: Monitoring and controlling'},
  {id:'S5-B07',domain:D,task:2,approach:'Predictive',type:'single',
   stem:'During construction, an inspector reports that a newly revised fire code applies to the project. The design was approved under the old code. What should the project manager do first?',
   options:['Continue building to the old design','Assess the impact of the new code on scope, schedule and cost with the designers, and submit a change request','Ask the inspector to ignore the revision','Stop the project permanently'],answer:[1],
   explanation:'Regulatory requirements are mandatory. The project manager analyses the impact and uses the change process to adapt the design.',
   ref:'Performance domain: Governance · Focus area: Monitoring and controlling'},
  {id:'S5-B08',domain:D,task:2,approach:'Hybrid',type:'single',
   stem:'A hybrid project collects personal data from users in two countries with different privacy laws. What should the project manager do during planning?',
   options:['Follow whichever law is easier','Identify the applicable requirements with legal experts, record them in a compliance register, and assign owners and checks','Assume the vendor handles privacy','Collect the data first and check the law later'],answer:[1],
   explanation:'Compliance planning identifies all applicable requirements, how they will be met and verified, and who owns each one.',
   ref:'Performance domain: Governance · Focus area: Planning'},
  {id:'S5-B09',domain:D,task:2,approach:'Agile',type:'single',
   stem:'An internal audit asks an agile team for evidence that its releases followed the approved testing process. The team has none written down. What should the project manager do going forward?',
   options:['Recreate records after the fact','Agree with the audit team on lightweight, automated evidence (such as pipeline test logs and review records) captured as part of normal work','Stop releasing software','Tell the auditors agile does not need evidence'],answer:[1],
   explanation:'Automated, lightweight evidence satisfies audit needs without slowing delivery. Backdating records would be dishonest.',
   ref:'Principle: Be a diligent, respectful and caring steward · Performance domain: Governance'},

  // Task 3 — Changes (6)
  {id:'S5-B10',domain:D,task:3,approach:'Predictive',type:'single',
   stem:'A client asks a site engineer directly to move a doorway. The engineer agrees, and the change is built before anyone tells the project manager. What should the project manager do?',
   options:['Ignore it because the client asked','Document the change, assess its impact, take it through the change control process for formal approval, and remind the team of the process','Reverse the work immediately at the team’s cost','Discipline the engineer publicly'],answer:[1],
   explanation:'Unapproved changes must still be recorded and assessed. The project manager also reinforces the process to prevent recurrence.',
   ref:'Performance domain: Governance · Focus area: Monitoring and controlling'},
  {id:'S5-B11',domain:D,task:3,approach:'Agile',type:'single',
   stem:'Halfway through a sprint, a stakeholder asks for an urgent new report. The sprint goal would not be at risk if it waited. What should happen?',
   options:['Add it to the sprint immediately','The product owner adds it to the product backlog and orders it for a future sprint','The developers decide to drop another sprint item','Cancel the sprint'],answer:[1],
   explanation:'New requests go to the product backlog. The product owner orders them, and the sprint goal stays protected.',
   ref:'Performance domain: Governance · Focus area: Executing'},
  {id:'S5-B12',domain:D,task:3,approach:'Hybrid',type:'single',
   stem:'An approved change adds a new interface to a hybrid project. Which action should the project manager take after approval?',
   options:['Update the affected baselines, plans and backlog, and tell the affected stakeholders','Start work without updating any documents','Ask for approval again','Archive the change request unread'],answer:[0],
   explanation:'Once a change is approved, the project manager updates the baselines and plans and tells everyone affected, so work and reporting reflect it.',
   ref:'Performance domain: Governance · Focus area: Monitoring and controlling'},
  {id:'S5-B13',domain:D,task:3,approach:'Predictive',type:'single',
   stem:'The change control board rejects a change request that the client strongly wanted. What should the project manager do next?',
   options:['Implement it anyway','Record the decision in the change log and tell the client the outcome and the reasons','Submit the same request every week','Hide the decision from the client'],answer:[1],
   explanation:'Decisions on changes, including rejections, are logged and communicated so stakeholders understand the outcome.',
   ref:'Performance domain: Governance · Focus area: Monitoring and controlling'},
  {id:'S5-B14',domain:D,task:3,approach:'Agile',type:'single',
   stem:'A product manager worries that frequent backlog changes will cause scope creep on an agile project. What is the best response?',
   options:['Ban all backlog changes','Explain that the time box and budget stay fixed while the product owner adjusts scope by value, and show the effect on forecasts transparently','Add more sprints whenever scope grows','Let any stakeholder edit the backlog'],answer:[1],
   explanation:'In agile delivery, time and cost are usually fixed and scope flexes. Ordering by value and showing forecasts openly keeps change under control.',
   ref:'Principle: Focus on value · Performance domain: Scope'},
  {id:'S5-B15',domain:D,task:3,approach:'Hybrid',type:'matching',
   stem:'Match each change to how it should normally be handled on a hybrid project.',
   pairs:[{left:'A new user story for the software component',right:0},{left:'A change to the contracted hardware delivery date',right:1},{left:'A correction to a typo in a meeting agenda',right:2},{left:'A request that would raise the approved budget by 15%',right:1}],
   choices:['Product owner adds and orders it in the backlog','Formal change request through the change control board','Handled directly by the owner, with no change control needed'],
   explanation:'Backlog items flex through the product owner. Changes to contracted or baselined items go through change control. Trivial edits to non-controlled documents need no formal process.',
   ref:'Principle: Tailor the approach · Performance domain: Governance'},

  // Task 4 — Impediments and issues (5)
  {id:'S5-B16',domain:D,task:4,approach:'Agile',type:'single',
   stem:'For three days in a row, a developer reports in the daily scrum that she is waiting for database access from another department. What should the team facilitator do?',
   options:['Wait for her to resolve it','Take ownership of the impediment, escalate it with the other department and track it visibly until it is removed','Reassign her to testing permanently','Raise it again at the retrospective'],answer:[1],
   explanation:'Removing impediments the team cannot solve itself is a core role of the servant leader. Waiting for the retrospective delays the fix.',
   ref:'Principle: Be a diligent, respectful and caring steward · Performance domain: Team'},
  {id:'S5-B17',domain:D,task:4,approach:'Predictive',type:'single',
   stem:'A risk the team identified has occurred: the supplier’s factory flooded. What should the project manager do first?',
   options:['Add a new risk to the register','Carry out the planned risk response and log the event in the issue log','Wait for the supplier to recover','Close the project'],answer:[1],
   explanation:'Once a risk occurs, it becomes an issue. The planned response is carried out and the issue is tracked in the issue log.',
   ref:'Performance domain: Uncertainty · Focus area: Executing'},
  {id:'S5-B18',domain:D,task:4,approach:'Hybrid',type:'single',
   stem:'The issue log has 40 open items, and stakeholders complain that nothing gets resolved. What should the project manager do?',
   options:['Close all the old issues','Prioritize issues by impact and urgency, assign an owner and a due date to each, and review progress regularly','Stop recording new issues','Send the whole log to the sponsor'],answer:[1],
   explanation:'Issues need owners, dates and priorities to be resolved. A regular review keeps them moving.',
   ref:'Performance domain: Governance · Focus area: Monitoring and controlling'},
  {id:'S5-B19',domain:D,task:4,approach:'Agile',type:'single',
   stem:'An agile team’s cycle time has doubled because every change needs a manual sign-off from a security officer, who reviews them once a week. What should the project manager do?',
   options:['Skip the security review','Work with the security officer to agree on automated checks and clear criteria, so most changes pass without waiting for a weekly review','Ask the team to work overtime','Batch more changes into each review'],answer:[1],
   explanation:'Removing a systemic bottleneck while keeping the control is the best fix. Skipping the control is not acceptable.',
   ref:'Principle: Optimize flow · Performance domain: Delivery'},
  {id:'S5-B20',domain:D,task:4,approach:'Hybrid',type:'single',
   stem:'Two departments disagree over who must fix a recurring data-quality issue that is delaying user acceptance testing. Neither department reports to the project manager. What should the project manager do?',
   options:['Bring the facts, the impact on the milestone and options to the sponsor or governance forum named in the escalation path, and ask for a decision on ownership','Fix the data personally every week','Let testing slip until the departments agree','Pick one department and assign the work to it'],answer:[0],
   explanation:'When an issue crosses lines of authority the project manager does not hold, it is escalated through the agreed path with facts and options so that someone with authority can decide.',
   ref:'Performance domain: Governance · Principle: Be an accountable leader'},

  // Task 5 — Risk (5)
  {id:'S5-B21',domain:D,task:5,approach:'Predictive',type:'single',
   stem:'A risk has a 30% probability and a $200,000 impact. A mitigation costs $40,000 and would lower the probability to 5%. Is the mitigation worth it?',
   options:['No, because $40,000 is more than the remaining exposure','Yes. The expected exposure drops from $60,000 to $10,000, a $50,000 reduction for a $40,000 cost','No, because the risk might not happen','Yes, because all risks must be mitigated'],answer:[1],
   explanation:'Expected value before = 0.30 × 200,000 = 60,000. After = 0.05 × 200,000 = 10,000. The $50,000 reduction is greater than the $40,000 cost.',
   ref:'Performance domain: Uncertainty · Focus area: Planning'},
  {id:'S5-B22',domain:D,task:5,approach:'Agile',type:'single',
   stem:'An agile team is unsure whether a new third-party mapping service can handle its expected load. What is the best way to reduce this risk early?',
   options:['Wait until the final release to test it','Run a time-boxed spike or load test in an early sprint and use the results to decide','Add a large contingency reserve only','Transfer the risk to the users'],answer:[1],
   explanation:'Agile teams reduce technical uncertainty early by experimenting (spikes and tests) and deciding from the evidence.',
   ref:'Performance domain: Uncertainty · Principle: Navigate complexity'},
  {id:'S5-B23',domain:D,task:5,approach:'Hybrid',type:'matching',
   stem:'For a hospital equipment rollout, match each planned action to the threat-response strategy it represents.',
   pairs:[{left:'Requiring the installer to post a performance bond',right:0},{left:'Dropping an unproven custom module from the scope',right:1},{left:'Running a pilot on one ward before the full rollout',right:2},{left:'Setting aside a contingency reserve for a minor delivery delay',right:3}],
   choices:['Transfer','Avoid','Mitigate','Accept'],
   explanation:'A performance bond shifts the financial impact to a third party (transfer). Removing the module eliminates the threat (avoid). A pilot lowers the probability and impact of a failed rollout (mitigate). A contingency reserve is active acceptance.',
   ref:'Performance domain: Uncertainty · Focus area: Planning'},
  {id:'S5-B24',domain:D,task:5,approach:'Predictive',type:'single',
   stem:'After a response is carried out, a smaller risk remains. What is this called, and what should be done with it?',
   options:['A secondary risk; ignore it','A residual risk; record it, and plan contingency or acceptance as appropriate','An issue; close it','A trigger; escalate it to the sponsor'],answer:[1],
   explanation:'Residual risk is what remains after a response. It is recorded and managed, usually through contingency or acceptance.',
   ref:'Performance domain: Uncertainty · Focus area: Monitoring and controlling'},
  {id:'S5-B25',domain:D,task:5,approach:'Hybrid',type:'single',
   stem:'A new exchange-rate policy could cut the cost of imported equipment by 12%. How should the project manager treat this?',
   options:['Ignore it because it is not a threat','Record it as an opportunity and plan a response such as exploit or enhance, for example by timing the purchase','Treat it as an issue','Transfer it to the vendor'],answer:[1],
   explanation:'Risks include opportunities. Positive risks are recorded and responded to with strategies such as exploit, enhance, share or accept.',
   ref:'Performance domain: Uncertainty · Principle: Optimize risk responses'},

  // Task 6 — Continuous improvement (5)
  {id:'S5-B26',domain:D,task:6,approach:'Agile',type:'single',
   stem:'An agile team’s retrospectives produce long lists of ideas, but nothing changes. What should the facilitator suggest?',
   options:['Stop holding retrospectives','Pick one or two improvement actions, add them to the next sprint backlog with owners, and review the results at the next retrospective','Have the manager choose the improvements','Write the ideas in a report for the PMO'],answer:[1],
   explanation:'Small, owned, visible improvement actions that are reviewed later turn retrospectives into real improvement.',
   ref:'Performance domain: Team · Focus area: Executing'},
  {id:'S5-B27',domain:D,task:6,approach:'Predictive',type:'single',
   stem:'A construction project keeps finding the same defects in formwork inspections. Which tool would best help identify the root cause?',
   options:['A cause-and-effect (fishbone) diagram used with the crew','A responsibility matrix','A milestone chart','A stakeholder register'],answer:[0],
   explanation:'Cause-and-effect diagrams help a team explore possible causes of a recurring problem so it can be fixed at the source.',
   ref:'Performance domain: Delivery · Focus area: Monitoring and controlling'},
  {id:'S5-B28',domain:D,task:6,approach:'Hybrid',type:'single',
   stem:'When is the best time to capture and share lessons learned on a 2-year hybrid project?',
   options:['Only at final closure','Throughout the project (for example, at retrospectives and phase ends), applying them right away and adding them to the organization’s knowledge base','Only when something goes wrong','Never, because each project is unique'],answer:[1],
   explanation:'Capturing lessons throughout the project lets the current project benefit, not just future ones.',
   ref:'Performance domain: Governance · Focus area: Executing'},
  {id:'S5-B29',domain:D,task:6,approach:'Agile',type:'single',
   stem:'A Kanban team wants to improve its flow. Which measure would best show whether a process change helped?',
   options:['Number of meetings held','Cycle time and throughput before and after the change','Number of emails sent','Hours worked per person'],answer:[1],
   explanation:'Flow metrics such as cycle time and throughput show whether a change actually improved delivery.',
   ref:'Principle: Optimize flow · Performance domain: Measurement'},
  {id:'S5-B30',domain:D,task:6,approach:'Hybrid',type:'single',
   stem:'The PMO finds that projects across the organization repeat the same procurement mistakes. What is the most effective improvement?',
   options:['Blame the procurement team','Analyse lessons from several projects, update the procurement templates and guidance, and share them through the community of practice','Ask each project manager to be careful','Stop all procurement'],answer:[1],
   explanation:'Improving organizational process assets from lessons across many projects makes improvement systemic.',
   ref:'Performance domain: Governance · Principle: Build quality into processes and deliverables'},

  // Task 7 — Organizational change (4)
  {id:'S5-B31',domain:D,task:7,approach:'Hybrid',type:'single',
   stem:'A new scheduling system will change how 400 clinic staff book appointments. Many staff are anxious. What should the project manager do first?',
   options:['Launch the system and handle complaints afterwards','Work with clinic leaders to understand staff concerns, explain why the change is needed, and plan training and support with champions from each clinic','Make the system optional forever','Tell staff the decision cannot be discussed'],answer:[1],
   explanation:'People adopt change when they understand why it is needed, feel heard and get support. Local champions help adoption.',
   ref:'Principle: Enable change to achieve the envisioned future state · Performance domain: Stakeholders'},
  {id:'S5-B32',domain:D,task:7,approach:'Agile',type:'single',
   stem:'An organization is moving its teams to agile ways of working. Middle managers fear losing their role. How should the change be supported?',
   options:['Remove all middle managers','Help managers define their new role, such as removing impediments, developing people and coaching, and involve them in shaping the transition','Ignore their concerns','Delay the transition indefinitely'],answer:[1],
   explanation:'Agile transformations succeed when managers see a valued new role and help shape the change.',
   ref:'Principle: Enable change to achieve the envisioned future state · Performance domain: Team'},
  {id:'S5-B33',domain:D,task:7,approach:'Predictive',type:'single',
   stem:'A project delivers a new warehouse system on time, but three months later most staff still use the old spreadsheets. What was most likely missing?',
   options:['A better user interface','Organizational change activities such as readiness assessment, training, reinforcement and retiring the old process','More testing','A larger budget'],answer:[1],
   explanation:'Delivering an output is not enough. Benefits come from adoption, which needs planned change management and the retirement of old ways.',
   ref:'Principle: Focus on value · Performance domain: Stakeholders'},
  {id:'S5-B34',domain:D,task:7,approach:'Hybrid',type:'multi',
   stem:'Which TWO actions help make an organizational change last after the project closes?',
   options:['Aligning performance measures and incentives with the new way of working','Removing all user support on go-live day','Assigning business owners who are accountable for sustaining the change and its benefits','Keeping the old system available indefinitely','Ending all communication at handover'],answer:[0,2],
   explanation:'Aligned measures and accountable business owners reinforce the change after the project team leaves.',
   ref:'Principle: Enable change to achieve the envisioned future state · Focus area: Closing'},

  // Task 8 — External environment (4)
  {id:'S5-B35',domain:D,task:8,approach:'Agile',type:'single',
   stem:'A competitor releases a feature that customers are asking for. The agile team is mid-release. What should the product owner do?',
   options:['Ignore the competitor','Assess the market impact with stakeholders and reorder the backlog if the new feature now has higher value','Copy the competitor’s design exactly','Stop the current release'],answer:[1],
   explanation:'Changes in the market can change value. The product owner reassesses and reorders the backlog in response.',
   ref:'Principle: Focus on value · Performance domain: Stakeholders'},
  {id:'S5-B36',domain:D,task:8,approach:'Predictive',type:'single',
   stem:'A government announces a new tariff on imported steel that takes effect in four months. The project will buy most of its steel in six months. What should the project manager do?',
   options:['Wait and see what happens','Analyse the cost impact, update the risk register, and discuss options with the sponsor such as buying early or using other sources','Increase the budget without telling anyone','Cancel the steel order'],answer:[1],
   explanation:'External changes are assessed for impact and handled through risk responses and governance decisions.',
   ref:'Performance domain: Uncertainty · Focus area: Monitoring and controlling'},
  {id:'S5-B37',domain:D,task:8,approach:'Hybrid',type:'single',
   stem:'A project manager wants to scan the external environment systematically for factors that could affect a 3-year project. Which technique fits best?',
   options:['PESTLE analysis (political, economic, social, technological, legal and environmental factors)','Burndown chart','Daily standup','Earned value analysis'],answer:[0],
   explanation:'PESTLE gives a structured way to identify external factors that could affect the project.',
   ref:'Performance domain: Uncertainty · Focus area: Planning'},
  {id:'S5-B38',domain:D,task:8,approach:'Agile',type:'single',
   stem:'A new accessibility law will apply to all public websites in nine months. An agile team is building a public portal. What should the team do?',
   options:['Wait until the law takes effect','Work with the product owner to add the accessibility requirements to the backlog and the Definition of Done now, ordered to meet the deadline','Leave accessibility to a later project','Ask users to request accessible pages'],answer:[1],
   explanation:'Upcoming legal requirements are built into the backlog and Definition of Done early, so the product is compliant when the law takes effect.',
   ref:'Performance domain: Governance · Principle: Navigate complexity'},
];
