import {CaseStudy,ExamQuestion} from '../../exam-types';

export const CASE_STUDIES:CaseStudy[]=[
  {id:'M',title:'Case M · Prairie University: Student Information System Replacement (hybrid)',graphic:'risk-5',context:[
    'Prairie University is replacing its 30-year-old student information system with a cloud software-as-a-service (SaaS) product. The vendor configures the product in predictive phases, while an internal agile team builds integrations with the learning platform, finance and residence systems.',
    'The registrar’s office, faculties, IT and student representatives all have strong views about the project. The system must go live outside the busy registration periods in the academic calendar.',
    'The project risk team has plotted six risks (R1–R6) on a probability-and-impact matrix, shown in the chart.'
  ]},
  {id:'N',title:'Case N · GreenRoute Logistics: Route-Optimization Platform (agile, Kanban)',graphic:'cfd-5',context:[
    'GreenRoute Logistics runs 600 delivery vehicles across Western Canada and is converting part of its fleet to electric vehicles. An internal team of seven uses Kanban to build and continuously improve a route-optimization platform for dispatchers and drivers.',
    'Requests arrive from dispatch, fleet maintenance, sustainability reporting and customer service. The platform depends on a third-party telematics provider for live vehicle data.',
    'The cumulative flow diagram shows the team’s work over the last 10 days.'
  ]},
  {id:'O',title:'Case O · St. Bridget’s Hospital: Emergency Department Renovation (predictive)',graphic:'ev-5',context:[
    'St. Bridget’s Hospital is renovating its emergency department (ED) in four phases while the ED stays open 24 hours a day. The project has a budget at completion of $5 million over 12 months.',
    'Infection prevention and control rules apply to all construction work near patient areas. Clinical staff must be trained on new equipment and layouts before each phase opens.',
    'The chart shows planned value (PV), earned value (EV) and actual cost (AC), in thousands of dollars, at the end of month 9.'
  ]}
];

export const CASE_QUESTIONS:ExamQuestion[]=[
  // ---------- Case M ----------
  {id:'S5-M01',caseId:'M',domain:'Business Environment',task:5,approach:'Hybrid',type:'hotspot',graphic:'risk-5',
   stem:'In the SIS risk matrix, click the risk that should be first in line for a response because it has the highest probability × impact score.',
   options:['R1','R2','R3','R4','R5','R6'],answer:[1],
   explanation:'R2 has probability 4 and impact 4, a score of 16. R3 scores 15 (5 × 3), R1 scores 12, R4 scores 10, R5 scores 4 and R6 scores 2.',
   ref:'Performance domain: Risk · Focus area: Planning'},
  {id:'S5-M02',caseId:'M',domain:'Process',task:1,approach:'Hybrid',type:'single',
   stem:'The SaaS vendor configures the product in fixed phases, while the internal team builds integrations in sprints. What is the most important element of the integrated plan?',
   options:['Separate plans with no links','Shared integration milestones and interface agreements, with joint testing points aligned to the vendor’s configuration phases','Asking the vendor to work in sprints','Delaying integrations until configuration is finished'],answer:[1],
   explanation:'Integrated milestones and interface agreements connect the predictive and adaptive streams so that they converge on time.',
   ref:'Principle: Adopt a holistic view · Focus area: Planning'},
  {id:'S5-M03',caseId:'M',domain:'People',task:4,approach:'Hybrid',type:'single',
   stem:'Student representatives say they learned about the new system from rumours, and they want a say in the student-facing features. What should the project manager do?',
   options:['Tell them decisions have already been made','Involve student representatives in design reviews and usability testing of student-facing features, and add them to the communication plan','Communicate only through the student newspaper','Wait until go-live'],answer:[1],
   explanation:'Students are key users. Engaging them early improves the product and builds support.',
   ref:'Performance domain: Stakeholders · Principle: Focus on value'},
  {id:'S5-M04',caseId:'M',domain:'Business Environment',task:2,approach:'Hybrid',type:'single',
   stem:'Academic records must be retained and reproducible for decades under university policy and legislation. What must be ensured during data migration?',
   options:['Only current students’ records are migrated','A records-retention plan confirms that all required historical records are migrated or archived in a compliant, retrievable form, and this is verified before the old system is retired','The old system is shut down immediately after go-live','Records older than five years are deleted'],answer:[1],
   explanation:'Records-retention obligations continue through system changes and must be verified before the legacy system is decommissioned.',
   ref:'Performance domain: Governance · Focus area: Closing'},
  {id:'S5-M05',caseId:'M',domain:'Process',task:5,approach:'Hybrid',type:'single',
   stem:'The SaaS contract is being negotiated. Which clause is most important for protecting the university if it changes providers in the future?',
   options:['A clause about the vendor’s logo','A data-portability and exit clause that guarantees the university can export its data in a usable format and receive transition support','A clause that removes all service levels','A discount for the first month'],answer:[1],
   explanation:'Exit and data-portability terms reduce lock-in risk with cloud services.',
   ref:'Performance domains: Resources (procurement), Risk'},
  {id:'S5-M06',caseId:'M',domain:'Business Environment',task:3,approach:'Hybrid',type:'single',
   stem:'The registrar wants extensive customizations to match current processes. Customizations could make future SaaS upgrades difficult. What should happen?',
   options:['Approve all customizations','Assess each request through change control—considering adopting the standard process, cost and upgrade impacts—and approve only those with clear justification','Reject all requests without discussion','Let the vendor decide'],answer:[1],
   explanation:'Change control should weigh the long-term costs of customization against its benefits.',
   ref:'Performance domain: Governance · Principle: Focus on value'},
  {id:'S5-M07',caseId:'M',domain:'People',task:2,approach:'Hybrid',type:'single',
   stem:'IT wants to go live in early August for technical reasons, but the registrar says August is too close to fall registration. They are no longer speaking to each other. What should the project manager do?',
   options:['Choose IT’s date because it controls the systems','Bring both leaders together to examine the risks of each date against the academic calendar and agree on a go-live window that protects registration','Choose the registrar’s date without discussion','Ask the vendor to decide'],answer:[1],
   explanation:'Collaborative problem solving using shared information about risk and timing resolves the conflict.',
   ref:'Performance domain: Stakeholders · Focus area: Executing'},
  {id:'S5-M08',caseId:'M',domain:'Process',task:8,approach:'Hybrid',type:'single',
   stem:'Go-live is not allowed during registration periods. How should this constraint be handled in the schedule?',
   options:['Ignore it until near go-live','Treat the blackout periods as fixed constraints, plan go-live and cutover rehearsals around them, and include schedule reserve before the planned window','Plan go-live during registration and hope for the best','Remove the constraint'],answer:[1],
   explanation:'Known calendar constraints must be built into the schedule, with reserves to protect the go-live window.',
   ref:'Performance domain: Schedule · Focus area: Planning'},
  {id:'S5-M09',caseId:'M',domain:'Business Environment',task:7,approach:'Hybrid',type:'single',
   stem:'Faculty members must enter grades in a new way. Many are sceptical and say they lack time to learn it. What should the project manager do?',
   options:['Mandate the new process without support','Work with deans to explain the benefits for faculty, offer short just-in-time training and help at grading time, and gather feedback from early adopters','Let faculty keep using paper','Train only administrative staff'],answer:[1],
   explanation:'Adoption improves when benefits are clear, support is timely and leaders champion the change.',
   ref:'Performance domain: Stakeholders · Principle: Build an empowered culture'},
  {id:'S5-M10',caseId:'M',domain:'Process',task:2,approach:'Hybrid',type:'single',
   stem:'Before configuration starts, the team wants to understand where the SaaS product’s standard processes do not meet the university’s needs. What should it do?',
   options:['Start configuration immediately','Conduct a fit-gap analysis comparing the product’s standard features with documented requirements, and decide how to handle each gap','Write all requirements from scratch','Ask the vendor to customize everything'],answer:[1],
   explanation:'Fit-gap analysis defines scope for configuration, process change or customization.',
   ref:'Performance domain: Scope · Focus area: Planning'},

  // ---------- Case N ----------
  {id:'S5-N01',caseId:'N',domain:'Process',task:9,approach:'Agile',type:'single',graphic:'cfd-5',
   stem:'Based on the cumulative flow diagram, what is happening?',
   options:['The team has a bottleneck in testing','Work in progress is stable and the team completes work steadily, but new requests arrive faster than the team can finish them, so the backlog keeps growing','The team stopped working','Cycle time is increasing sharply'],answer:[1],
   explanation:'The In progress and Testing bands keep a constant width (stable WIP and cycle time), and Done grows steadily. The Backlog band widens because demand exceeds throughput.',
   ref:'Performance domain: Schedule · Focus area: Monitoring and Controlling'},
  {id:'S5-N02',caseId:'N',domain:'Process',task:8,approach:'Agile',type:'dropdown',graphic:'cfd-5',
   stem:'The team has 9 items in progress (6 in progress plus 3 in testing) and finishes about 4 items per day. Using Little’s Law, what is the average cycle time?',
   options:['1.5 days','2.25 days','4 days','9 days'],answer:[1],
   explanation:'Cycle time = WIP ÷ throughput = 9 ÷ 4 = 2.25 days.',
   ref:'Performance domain: Schedule · Focus area: Monitoring and Controlling'},
  {id:'S5-N03',caseId:'N',domain:'People',task:5,approach:'Agile',type:'single',
   stem:'Every department expects its requests to be handled immediately. How can the team align expectations about response times?',
   options:['Promise immediate delivery to everyone','Agree with stakeholders on classes of service—for example, an expedite class for urgent operational issues and standard handling for other requests—with typical delivery times based on data','Handle requests in random order','Stop accepting requests'],answer:[1],
   explanation:'Classes of service make prioritization rules and expected delivery times explicit.',
   ref:'Performance domain: Stakeholders · Principle: Focus on value'},
  {id:'S5-N04',caseId:'N',domain:'People',task:3,approach:'Agile',type:'single',
   stem:'Two senior developers disagree about a branching strategy and ask the project manager to decide. What should the project manager do?',
   options:['Make the decision','Coach the team to decide, for example by agreeing on criteria and trying one approach as a time-boxed experiment','Ask the most senior developer to decide','Let each developer use their own strategy'],answer:[1],
   explanation:'Servant leaders help teams make their own technical decisions rather than deciding for them.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'S5-N05',caseId:'N',domain:'Business Environment',task:4,approach:'Agile',type:'single',
   stem:'The telematics provider’s rate limits are blocking real-time route updates during peak hours. What should the project manager do?',
   options:['Ignore the problem','Work with the provider to understand options—such as a higher service tier or a different data approach—assess costs and impacts, and escalate through the contract owner if needed','Ask developers to bypass the limits','Remove real-time features'],answer:[1],
   explanation:'External dependencies that block work are resolved by working with the provider and the right internal owners.',
   ref:'Performance domains: Resources (procurement), Risk'},
  {id:'S5-N06',caseId:'N',domain:'Business Environment',task:8,approach:'Agile',type:'single',
   stem:'The federal government announces higher carbon pricing and new incentives for electric fleets. How should the team respond?',
   options:['Continue with the current priorities','Assess the effects with the business—such as greater value from electric-vehicle routing and charging features—and reprioritize the backlog accordingly','Stop all development','Wait for competitors to react'],answer:[1],
   explanation:'External policy changes can shift value. Adaptive teams reprioritize based on updated analysis.',
   ref:'Principle: Integrate sustainability · Principle: Focus on value'},
  {id:'S5-N07',caseId:'N',domain:'Process',task:3,approach:'Agile',type:'single',
   stem:'A request would save the company $8,000 per week once delivered; another would save $2,000 per week. Both take about the same effort. How should they be ordered?',
   options:['By the order received','The first request first, because its cost of delay is four times higher','The second request first, because it is cheaper','Both at the same time'],answer:[1],
   explanation:'Cost of delay helps prioritize. With equal effort, the item with the higher cost of delay should go first.',
   ref:'Principle: Focus on value · Performance domain: Scope'},
  {id:'S5-N08',caseId:'N',domain:'People',task:8,approach:'Agile',type:'single',
   stem:'Drivers are on the road all day and rarely read email. How should the team communicate changes to the driver app and collect feedback?',
   options:['Send long emails','Use short in-app notifications and release notes, brief messages through dispatch, and a simple in-app feedback option','Hold meetings during delivery hours','Rely on drivers to discover changes'],answer:[1],
   explanation:'Communication channels should match how the audience works.',
   ref:'Performance domain: Stakeholders · Focus area: Executing'},
  {id:'S5-N09',caseId:'N',domain:'Process',task:7,approach:'Agile',type:'single',
   stem:'Several recent releases caused production problems for dispatchers. How can the team release continuously while protecting quality?',
   options:['Release once a quarter','Strengthen automated testing, use feature flags to release gradually, and monitor production so that problems are detected and rolled back quickly','Stop testing to release faster','Ask dispatchers to test in production'],answer:[1],
   explanation:'Automated tests, gradual rollout and monitoring allow frequent releases with controlled risk.',
   ref:'Principle: Embed quality · Focus area: Executing'},
  {id:'S5-N10',caseId:'N',domain:'Business Environment',task:1,approach:'Agile',type:'single',
   stem:'The company’s weekly change approval board delays every release, even small, low-risk ones. What governance improvement should the project manager propose?',
   options:['Bypass the board','Propose defining low-risk changes as pre-approved “standard changes” with automated controls and evidence, while keeping board review for high-risk changes','Release only once a month','Remove all controls'],answer:[1],
   explanation:'Governance can be tailored by risk, using automated controls to keep oversight while enabling flow.',
   ref:'Performance domain: Governance · Principle: Adopt a holistic view'},

  // ---------- Case O ----------
  {id:'S5-O01',caseId:'O',domain:'Process',task:9,approach:'Predictive',type:'single',graphic:'ev-5',
   stem:'Based on the chart at the end of month 9, how is the ED renovation performing?',
   options:['Ahead of schedule and under budget','Behind schedule and over budget','Behind schedule but under budget','On schedule and on budget'],answer:[1],
   explanation:'EV ($3,000k) is below PV ($3,600k): SPI ≈ 0.83, behind schedule. EV is below AC ($3,300k): CPI ≈ 0.91, over budget.',
   ref:'Performance domains: Schedule, Finance · Focus area: Monitoring and Controlling'},
  {id:'S5-O02',caseId:'O',domain:'Process',task:6,approach:'Predictive',type:'dropdown',graphic:'ev-5',
   stem:'Both cost and schedule performance are expected to influence the remaining work. What is the estimate at completion (EAC)? Select the closest value.',
   options:['$5,300,000','$5,500,000','$5,940,000','$6,600,000'],answer:[2],
   explanation:'CPI = 3,000 ÷ 3,300 ≈ 0.909 and SPI = 3,000 ÷ 3,600 ≈ 0.833. EAC = AC + (BAC – EV) ÷ (CPI × SPI) = 3,300 + 2,000 ÷ 0.758 ≈ $5,940,000. $5,500,000 is BAC ÷ CPI; $5,300,000 is AC + (BAC – EV).',
   ref:'Performance domain: Finance · Focus area: Monitoring and Controlling'},
  {id:'S5-O03',caseId:'O',domain:'Process',task:6,approach:'Predictive',type:'dropdown',graphic:'ev-5',
   stem:'What to-complete performance index (TCPI) is needed to finish within the original budget?',
   options:['0.91','1.05','1.18','1.40'],answer:[2],
   explanation:'TCPI = (BAC – EV) ÷ (BAC – AC) = (5,000 – 3,000) ÷ (5,000 – 3,300) = 2,000 ÷ 1,700 ≈ 1.18.',
   ref:'Performance domain: Finance · Focus area: Monitoring and Controlling'},
  {id:'S5-O04',caseId:'O',domain:'Process',task:4,approach:'Predictive',type:'dropdown',graphic:'resource-2',
   stem:'The resource histogram shows the nurses needed for transition shifts as each phase opens. Eight nurses are available. What is the largest weekly shortfall?',
   options:['1 nurse','2 nurses','3 nurses','11 nurses'],answer:[2],
   explanation:'Demand peaks at 11 nurses in week 5. With 8 available, the largest shortfall is 3 nurses. Weeks 4 (10) and 6 (9) are also over capacity.',
   ref:'Performance domain: Resources · Focus area: Planning'},
  {id:'S5-O05',caseId:'O',domain:'People',task:4,approach:'Predictive',type:'single',
   stem:'ED physicians and nurses say they were not consulted on the new layout, which they believe will slow patient flow. What should the project manager do?',
   options:['Proceed because the design is approved','Engage clinical leaders promptly to review the layout—for example through a walkthrough or mock-up—and assess any changes through change control','Ask them to adapt after opening','Refer them to the architect'],answer:[1],
   explanation:'Clinical users are key stakeholders. Their concerns must be heard, and any changes managed through governance.',
   ref:'Performance domain: Stakeholders · Principle: Focus on value'},
  {id:'S5-O06',caseId:'O',domain:'Business Environment',task:2,approach:'Predictive',type:'single',
   stem:'An infection-control officer finds that a dust barrier next to a patient area has been opened by workers to move materials. What should the project manager do?',
   options:['Note it for the weekly meeting','Ensure the work stops and the barrier is restored immediately, investigate with the contractor and infection control, and reinforce the required procedures','Ask the officer to ignore it this once','Move patients without discussion'],answer:[1],
   explanation:'Infection prevention rules protect vulnerable patients. Breaches require immediate correction and prevention of recurrence.',
   ref:'Performance domain: Governance · Principle: Be an accountable leader'},
  {id:'S5-O07',caseId:'O',domain:'People',task:6,approach:'Predictive',type:'single',
   stem:'The hospital CEO has publicly promised that phase 3 will open before winter, but the schedule now shows a six-week delay. What should the project manager do?',
   options:['Say nothing and try to recover','Inform the CEO promptly with the cause, the revised forecast and options—such as phasing or added resources—so that the CEO can update the public message','Report the date as unchanged','Blame the contractor publicly'],answer:[1],
   explanation:'Leaders need early, honest information to manage public expectations.',
   ref:'Principle: Be an accountable leader · Performance domain: Stakeholders'},
  {id:'S5-O08',caseId:'O',domain:'People',task:2,approach:'Predictive',type:'single',
   stem:'The contractor wants to run noisy work during the day to save money, but the infection-control and clinical teams want it done at night. They cannot agree. What should the project manager do?',
   options:['Let the contractor decide','Facilitate a discussion of patient safety, clinical needs and cost, using the contract and hospital policies as the basis, and agree on a schedule—escalating to the sponsor if necessary','Side with the clinical team without discussion','Stop the noisy work permanently'],answer:[1],
   explanation:'Conflicts are resolved using objective criteria and policies, with escalation if the parties cannot agree.',
   ref:'Performance domains: Resources, Stakeholders · Focus area: Executing'},
  {id:'S5-O09',caseId:'O',domain:'People',task:7,approach:'Predictive',type:'single',
   stem:'Hospital facilities staff will maintain the new medical gas and ventilation systems. What is the best way to transfer knowledge?',
   options:['Email them the manuals','Involve facilities staff in commissioning and testing, provide hands-on training from the installers, and hand over maintenance procedures and records','Ask the contractor to maintain the systems forever','Train them after the warranty ends'],answer:[1],
   explanation:'Hands-on involvement during commissioning, plus documentation, prepares staff to maintain critical systems.',
   ref:'Performance domain: Resources · Focus area: Closing'},
  {id:'S5-O10',caseId:'O',domain:'Business Environment',task:5,approach:'Predictive',type:'single',
   stem:'Switching services to a renovated area could temporarily disrupt emergency care. Which risk response is most appropriate?',
   options:['Accept the risk','Plan detailed transition procedures with clinical leaders, rehearse the switchover, schedule it for low-demand periods and prepare contingency plans such as temporary diversion','Avoid renovating the ED','Transfer the risk to the contractor'],answer:[1],
   explanation:'Critical-service risks require layered mitigation and contingency planning with the people who run the service.',
   ref:'Performance domain: Risk · Principle: Be an accountable leader'}
];
