import {ExamQuestion} from '../../exam-types';

const D='People' as const;

export const PEOPLE_QUESTIONS:ExamQuestion[]=[
  // Task 1 — Develop a common vision (8)
  {id:'S5-P01',domain:D,task:1,approach:'Hybrid',type:'single',
   stem:'A public–private partnership brings a city and a private company together on a transit project. Each organization has different goals. What should the project manager do first?',
   options:['Follow the goals of the organization that pays the most','Facilitate agreement on shared project outcomes and success measures that both partners commit to, documented in the governance agreement','Let each partner pursue its own goals','Avoid discussing goals'],answer:[1],
   explanation:'Partnerships need explicit shared outcomes so that both parties work toward the same definition of success.',
   ref:'Performance domain: Governance · Principle: Adopt a holistic view'},
  {id:'S5-P02',domain:D,task:1,approach:'Agile',type:'single',
   stem:'An internal platform team builds tools for other development teams. Its members do not see the other teams as “customers.” What should the project manager do?',
   options:['Ignore it','Help the platform team define a vision centred on the developer teams it serves, and involve those teams in setting priorities','Ask the platform team to work only on technical upgrades','Merge all teams'],answer:[1],
   explanation:'Treating internal users as customers gives platform teams a clear, value-focused vision.',
   ref:'Principle: Focus on value · Performance domain: Stakeholders'},
  {id:'S5-P03',domain:D,task:1,approach:'Predictive',type:'single',
   stem:'Budget cuts have reduced the project’s scope, and the team feels the project has lost its purpose. What should the project manager do?',
   options:['Tell the team to accept it','Work with the sponsor to restate the project’s purpose and achievable outcomes within the new scope, and share it with the team','Keep the old vision unchanged','Ask the team to choose new goals alone'],answer:[1],
   explanation:'When scope changes, the vision and outcomes should be restated so that the team understands what success now means.',
   ref:'Principle: Focus on value · Performance domain: Stakeholders'},
  {id:'S5-P04',domain:D,task:1,approach:'Agile',type:'single',
   stem:'A new product owner joins mid-project and starts reprioritizing the backlog in a different direction from the agreed vision. What should the project manager do?',
   options:['Accept every change','Meet with the new product owner to review the product vision, the reasons behind current priorities and stakeholder commitments, and agree on how any change in direction will be decided and communicated','Ask the team to ignore the product owner','Escalate immediately to the CEO'],answer:[1],
   explanation:'Changes of direction should be deliberate and transparent, and anchored in a shared understanding of the vision.',
   ref:'Performance domain: Scope · Principle: Be an accountable leader'},
  {id:'S5-P05',domain:D,task:1,approach:'Hybrid',type:'single',
   stem:'An organization has many projects competing for attention. How can leadership help each team connect its work to company priorities?',
   options:['By keeping strategy confidential','By sharing a portfolio roadmap that shows strategic themes and how each project contributes to them','By ranking teams publicly','By funding projects equally'],answer:[1],
   explanation:'A visible portfolio roadmap links individual projects to strategy and helps teams see their contribution.',
   ref:'Principle: Adopt a holistic view · Performance domain: Governance'},
  {id:'S5-P06',domain:D,task:1,approach:'Predictive',type:'single',
   stem:'A maintenance team works on an ageing system that users take for granted. Morale is low because the work feels invisible. What should the project manager do?',
   options:['Increase the workload','Show the team the value of their work—such as outages avoided and services kept running—and share recognition from users and leaders','Move them to a new project','Stop reporting on maintenance'],answer:[1],
   explanation:'Making the impact of “invisible” work visible connects the team to its purpose.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'S5-P07',domain:D,task:1,approach:'Agile',type:'single',
   stem:'Teams in a large program keep losing sight of the overall objective. What practice helps keep the vision visible every day?',
   options:['A yearly vision email','Displaying the vision and key outcome measures on team boards and starting planning sessions by revisiting them','Hiding the vision until the end','Changing the vision each sprint'],answer:[1],
   explanation:'Keeping the vision visible and referring to it routinely keeps teams aligned.',
   ref:'Principle: Adopt a holistic view · Focus area: Executing'},
  {id:'S5-P08',domain:D,task:1,approach:'Hybrid',type:'multi',
   stem:'Which TWO qualities make a project vision statement effective?',
   options:['It is short, clear and easy to remember','It lists every feature in detail','It describes the desired outcome and who benefits','It changes every week','It uses complex technical jargon'],answer:[0,2],
   explanation:'Effective visions are concise and outcome-focused, so that everyone can remember and use them.',
   ref:'Principle: Focus on value · Focus area: Initiating'},

  // Task 2 — Manage conflicts (5)
  {id:'S5-P09',domain:D,task:2,approach:'Agile',type:'single',
   stem:'Three teams share one test environment and keep overwriting each other’s data, causing frequent arguments. What should the project manager do?',
   options:['Let the loudest team decide','Bring the teams together to agree on a shared booking schedule and rules, and explore whether additional environments are justified','Assign the environment to one team','Ignore the conflict'],answer:[1],
   explanation:'Conflicts over shared resources are resolved by agreeing on fair rules and addressing the capacity constraint.',
   ref:'Performance domain: Resources · Principle: Adopt a holistic view'},
  {id:'S5-P10',domain:D,task:2,approach:'Hybrid',type:'single',
   stem:'Team members from different cultures disagree about deadlines: some see dates as firm commitments, others as flexible targets. Tension is growing. What should the project manager do?',
   options:['Tell everyone to work harder','Discuss the different expectations openly and agree as a team on what a committed date means and how risks to dates will be raised early','Assign deadlines only to some members','Avoid setting dates'],answer:[1],
   explanation:'Making cultural assumptions explicit and agreeing on shared norms prevents recurring conflict.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'S5-P11',domain:D,task:2,approach:'Agile',type:'single',
   stem:'The sales director pressures developers directly to add features for a big client, which conflicts with the product owner’s priorities. What should the project manager do?',
   options:['Let developers decide','Bring the sales director and product owner together to discuss the client’s needs and value, and agree on prioritization through the backlog','Tell the sales director to stop','Add the features secretly'],answer:[1],
   explanation:'Conflicts between business stakeholders and the product owner are resolved by discussing value openly through the agreed process.',
   ref:'Performance domain: Scope · Performance domain: Stakeholders'},
  {id:'S5-P12',domain:D,task:2,approach:'Predictive',type:'single',
   stem:'An internal team and a vendor disagree about whether delivered work meets quality standards. Both have evidence. What is the best approach?',
   options:['Accept the vendor’s view','Review the work jointly against the contract’s quality criteria and test results, agree on the gaps and corrective actions, and escalate through the contract if needed','Reject all vendor work','Ignore the disagreement'],answer:[1],
   explanation:'Objective criteria in the contract provide the basis for resolving quality disputes.',
   ref:'Principle: Embed quality · Performance domain: Resources (procurement)'},
  {id:'S5-P13',domain:D,task:2,approach:'Hybrid',type:'multi',
   stem:'Which TWO outcomes show that a conflict has been resolved through collaboration?',
   options:['Both parties understand each other’s concerns and support the solution','One party gives in to avoid further argument','The solution addresses the underlying problem, not just the symptoms','The issue is postponed indefinitely','The manager imposes a decision without discussion'],answer:[0,2],
   explanation:'Collaboration produces shared commitment and addresses root causes.',
   ref:'Performance domain: Resources · Focus area: Executing'},

  // Task 3 — Lead the project team (7)
  {id:'S5-P14',domain:D,task:3,approach:'Hybrid',type:'single',
   stem:'What is the difference between coaching and mentoring?',
   options:['They are the same','Coaching usually focuses on improving specific skills or performance through questions and feedback; mentoring is a longer-term relationship in which an experienced person guides someone’s career development','Mentoring is always formal and paid','Coaching is only for executives'],answer:[1],
   explanation:'Both support development, but they differ in focus and duration.',
   ref:'Performance domain: Resources · Principle: Be an accountable leader'},
  {id:'S5-P15',domain:D,task:3,approach:'Agile',type:'single',
   stem:'According to research on motivation for knowledge work, which three factors are most important for intrinsic motivation?',
   options:['Pay, bonuses and titles','Autonomy, mastery and purpose','Strict rules, supervision and penalties','Office location, equipment and parking'],answer:[1],
   explanation:'Intrinsic motivation grows when people have autonomy, opportunities to master skills and a meaningful purpose.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'S5-P16',domain:D,task:3,approach:'Predictive',type:'single',
   stem:'The project manager delegates a vendor evaluation to a team member, but the result does not meet expectations. What was most likely missing?',
   options:['Nothing; the team member failed','Clear expectations about the outcome, criteria, deadline, authority and check-in points when the work was delegated','A bigger budget','More team members'],answer:[1],
   explanation:'Effective delegation defines what success looks like and how progress will be checked.',
   ref:'Principle: Be an accountable leader · Performance domain: Resources'},
  {id:'S5-P17',domain:D,task:3,approach:'Hybrid',type:'single',
   stem:'In a heated steering meeting, a stakeholder criticizes the project manager unfairly. The project manager feels angry. What is the best response?',
   options:['Respond angrily to defend the team','Stay calm, acknowledge the concern, respond with facts, and follow up privately to resolve the issue','Leave the meeting','Ignore the stakeholder from now on'],answer:[1],
   explanation:'Self-regulation—managing one’s own emotions—is a key part of emotional intelligence and maintains professional credibility.',
   ref:'Principle: Be an accountable leader · Performance domain: Stakeholders'},
  {id:'S5-P18',domain:D,task:3,approach:'Agile',type:'single',
   stem:'A project manager takes over a team with low morale after a failed release. What should they do first?',
   options:['Announce stricter controls','Listen to team members individually and as a group to understand what happened and what they need, and then agree on a few visible improvements','Replace the team','Start the next release immediately'],answer:[1],
   explanation:'Rebuilding morale starts with listening and quick, visible actions that show the team’s concerns matter.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},
  {id:'S5-P19',domain:D,task:3,approach:'Hybrid',type:'single',
   stem:'A team member’s performance remains below expectations after coaching and training. What should the project manager do next?',
   options:['Ignore it to avoid conflict','Document the performance gaps and support provided, discuss them with the team member and their functional manager, and follow the organization’s performance-management process','Remove the team member immediately without process','Give their work to others silently'],answer:[1],
   explanation:'When coaching has not worked, the organization’s formal process ensures fairness and clarity.',
   ref:'Principle: Be an accountable leader · Performance domain: Resources'},
  {id:'S5-P20',domain:D,task:3,approach:'Agile',type:'multi',
   stem:'Which TWO practices help build trust in a fully remote team?',
   options:['Keeping commitments and being transparent about progress and problems','Monitoring screens to check activity','Regular informal check-ins and opportunities for social connection','Communicating only by formal email','Withholding information to avoid worry'],answer:[0,2],
   explanation:'Reliability, transparency and social connection build trust in remote teams. Surveillance erodes it.',
   ref:'Principle: Build an empowered culture · Performance domain: Resources'},

  // Task 4 — Engage stakeholders (6)
  {id:'S5-P21',domain:D,task:4,approach:'Predictive',type:'hotspot',graphic:'grid-5',
   stem:'The grid shows four stakeholder groups for a university project. Click the group that requires only monitoring.',
   options:['Board of governors','Dean of Engineering','Students','Alumni office'],answer:[3],
   explanation:'The alumni office has low power and low interest in this project, so monitoring is enough. The board (high power, low interest) is kept satisfied, the dean (high/high) is managed closely, and students (low power, high interest) are kept informed.',
   ref:'Performance domain: Stakeholders · Focus area: Planning'},
  {id:'S5-P22',domain:D,task:4,approach:'Hybrid',type:'single',
   stem:'A project will change shift patterns for unionized workers. When should the union be engaged?',
   options:['After the new shifts are announced','Early, before decisions are final, so that concerns and collective-agreement requirements can be considered','Only if workers complain','Never; HR handles unions'],answer:[1],
   explanation:'Early engagement with unions respects agreements, reduces conflict and leads to better solutions.',
   ref:'Performance domain: Stakeholders · Focus area: Planning'},
  {id:'S5-P23',domain:D,task:4,approach:'Predictive',type:'single',
   stem:'Internal audit has asked to review the project’s controls. The project manager sees this as a distraction. What is the best approach?',
   options:['Delay the audit as long as possible','Engage internal audit as a stakeholder: agree on scope and timing, provide the information requested and use the findings to improve controls','Provide minimal information','Ask the sponsor to cancel the audit'],answer:[1],
   explanation:'Auditors are stakeholders whose input can strengthen the project. Cooperative engagement builds trust.',
   ref:'Performance domain: Governance · Performance domain: Stakeholders'},
  {id:'S5-P24',domain:D,task:4,approach:'Agile',type:'single',
   stem:'The project has 40 stakeholder groups, and the team is unsure where to focus engagement effort. What should the project manager do?',
   options:['Engage all groups equally','Analyze stakeholders by their influence, interest and impact, and prioritize engagement effort accordingly','Engage only the sponsor','Wait for stakeholders to contact the team'],answer:[1],
   explanation:'Stakeholder analysis focuses limited effort where it matters most, while still monitoring others.',
   ref:'Performance domain: Stakeholders · Focus area: Planning'},
  {id:'S5-P25',domain:D,task:4,approach:'Hybrid',type:'single',
   stem:'A partner organization’s staff are critical to the project’s success but report to their own managers. How can the project manager engage them effectively?',
   options:['Give them orders directly','Build relationships with the partner’s managers and staff, agree on shared goals and working arrangements, and recognize their contributions','Exclude them from planning','Complain to their managers when problems arise'],answer:[1],
   explanation:'Influence without authority relies on relationships, shared goals and recognition.',
   ref:'Performance domain: Stakeholders · Principle: Be an accountable leader'},
  {id:'S5-P26',domain:D,task:4,approach:'Agile',type:'multi',
   stem:'Which TWO practices help keep end users engaged throughout an agile project?',
   options:['Inviting them to regular demos of working software','Showing them the product only at the end','Acting visibly on their feedback in later increments','Ignoring feedback that conflicts with the plan','Limiting contact to formal surveys once a year'],answer:[0,2],
   explanation:'Users stay engaged when they see the product regularly and see their feedback make a difference.',
   ref:'Performance domain: Stakeholders · Principle: Focus on value'},

  // Task 5 — Align stakeholder expectations (6)
  {id:'S5-P27',domain:D,task:5,approach:'Predictive',type:'single',
   stem:'Stakeholders disagree about what conditions must be met before the new system can go live. What should the project manager facilitate?',
   options:['A decision by the vendor','Agreement on explicit go/no-go criteria—such as test results, data reconciliation, training completion and support readiness—before the go-live decision','A vote on the day of go-live','Going live without criteria'],answer:[1],
   explanation:'Agreed go/no-go criteria align expectations and make the go-live decision objective.',
   ref:'Performance domain: Governance · Focus area: Executing'},
  {id:'S5-P28',domain:D,task:5,approach:'Hybrid',type:'single',
   stem:'Business users believe the SaaS vendor is responsible for everything, including user access management and data quality. What should the project manager do?',
   options:['Let them find out later','Clarify the shared-responsibility model—what the vendor manages and what the organization must manage—and agree on internal owners','Ask the vendor to take on everything at no cost','Ignore the confusion'],answer:[1],
   explanation:'Cloud services involve shared responsibilities. Clarifying them early prevents gaps.',
   ref:'Performance domain: Governance · Performance domain: Stakeholders'},
  {id:'S5-P29',domain:D,task:5,approach:'Agile',type:'single',
   stem:'Two partner organizations want to report the project’s progress using different measures. What should the project manager do?',
   options:['Use both without explanation','Agree with both partners on a common set of progress and outcome measures, with clear definitions and data sources','Let each partner report separately','Avoid reporting'],answer:[1],
   explanation:'Common, well-defined measures align expectations and avoid conflicting reports.',
   ref:'Performance domain: Stakeholders · Focus area: Planning'},
  {id:'S5-P30',domain:D,task:5,approach:'Hybrid',type:'single',
   stem:'Operations managers assume the project team will provide support for a year after go-live. The plan includes four weeks of hypercare. What should the project manager do?',
   options:['Say nothing','Clarify the hypercare period and the long-term support model with operations early, and agree on how support will transition','Agree to a year of support without approval','Cancel hypercare'],answer:[1],
   explanation:'Expectations about post-launch support must be aligned well before go-live.',
   ref:'Focus area: Closing · Performance domain: Stakeholders'},
  {id:'S5-P31',domain:D,task:5,approach:'Predictive',type:'single',
   stem:'A client expects all features in the first release, but the approved plan delivers in two phases. What should the project manager do?',
   options:['Deliver everything in phase 1','Review the phased plan with the client, explain the reasons and the benefits of phasing, and confirm agreement on phase 1 scope','Delay the project until everything is ready','Ignore the client’s expectation'],answer:[1],
   explanation:'Revisiting agreed plans with stakeholders keeps expectations aligned with what will be delivered.',
   ref:'Performance domain: Scope · Performance domain: Stakeholders'},
  {id:'S5-P32',domain:D,task:5,approach:'Agile',type:'multi',
   stem:'Which TWO actions help align expectations when a project depends on many teams?',
   options:['Sharing a common roadmap showing dependencies and target dates as ranges','Letting each team promise dates independently','Holding regular cross-team reviews of progress and risks with stakeholders','Hiding dependencies to simplify communication','Promising fixed dates for uncertain work'],answer:[0,2],
   explanation:'Shared roadmaps and regular joint reviews create a single, realistic picture for stakeholders.',
   ref:'Principle: Adopt a holistic view · Performance domain: Stakeholders'},

  // Task 6 — Manage stakeholder expectations (6)
  {id:'S5-P33',domain:D,task:6,approach:'Predictive',type:'single',
   stem:'A department head is surprised by a large internal charge for the project’s work and complains. What should the project manager do?',
   options:['Tell them to talk to finance','Explain how costs were allocated, show the basis in the approved budget, and improve financial communication so that cost expectations are clear in future','Waive the charge','Ignore the complaint'],answer:[1],
   explanation:'Clear explanation and better communication prevent financial surprises.',
   ref:'Performance domain: Finance · Performance domain: Stakeholders'},
  {id:'S5-P34',domain:D,task:6,approach:'Hybrid',type:'single',
   stem:'A supportive executive stakeholder retires, and the successor seems sceptical of the project. What should the project manager do?',
   options:['Assume the successor will support the project','Meet the successor early to understand their priorities and concerns, share the project’s value and status, and update the stakeholder engagement plan','Avoid the successor','Ask the former executive to continue'],answer:[1],
   explanation:'Stakeholder changes require re-engagement and updated plans.',
   ref:'Performance domain: Stakeholders · Focus area: Monitoring and Controlling'},
  {id:'S5-P35',domain:D,task:6,approach:'Agile',type:'single',
   stem:'An executive expects that adopting AI tools will let the team cut its size in half next quarter. What should the project manager do?',
   options:['Agree to keep the executive happy','Share evidence from the team’s actual use of AI tools, explain realistic productivity effects and risks, and agree on how impacts will be measured before making staffing decisions','Refuse to discuss AI','Cut the team immediately'],answer:[1],
   explanation:'Expectations about AI benefits should be grounded in evidence and measured, not assumed.',
   ref:'AI in project management · Principle: Be an accountable leader'},
  {id:'S5-P36',domain:D,task:6,approach:'Hybrid',type:'single',
   stem:'Stakeholders expect the project’s benefits immediately after go-live, but the business case shows benefits building over 18 months. What should the project manager do?',
   options:['Say nothing','Communicate the benefit timeline clearly before go-live, along with early indicators that show progress toward the benefits','Promise immediate benefits','Delay go-live'],answer:[1],
   explanation:'Explaining when benefits will appear—and how progress will be shown—prevents disappointment.',
   ref:'Principle: Focus on value · Performance domain: Stakeholders'},
  {id:'S5-P37',domain:D,task:6,approach:'Agile',type:'single',
   stem:'A user group is unhappy after a release removed a feature it relied on. What should the project manager do first?',
   options:['Defend the decision','Listen to the group’s concerns, understand the impact, and work with the product owner on a response—such as a workaround or reconsidering the change','Restore the feature immediately without analysis','Ignore the complaints'],answer:[1],
   explanation:'Understanding the impact before responding leads to the right solution and rebuilds trust.',
   ref:'Performance domain: Stakeholders · Principle: Focus on value'},
  {id:'S5-P38',domain:D,task:6,approach:'Predictive',type:'multi',
   stem:'Which TWO practices help prevent stakeholders from being surprised by project problems?',
   options:['Regular, honest status reporting with risks and forecasts','Reporting only after problems are solved','Agreeing on escalation thresholds and notifying stakeholders when they are reached','Sharing information only with the sponsor','Using optimistic forecasts'],answer:[0,2],
   explanation:'Transparent reporting and agreed escalation rules give stakeholders early warning.',
   ref:'Principle: Be an accountable leader · Performance domain: Governance'},

  // Task 7 — Knowledge transfer (6)
  {id:'S5-P39',domain:D,task:7,approach:'Hybrid',type:'single',
   stem:'The organization is switching vendors mid-project. The outgoing vendor holds key knowledge about the system. What should the project manager do?',
   options:['End the outgoing contract immediately','Plan a transition period in which the outgoing and incoming vendors overlap, with documented handover deliverables and joint working sessions','Ask the new vendor to figure it out','Rely on old documentation only'],answer:[1],
   explanation:'A planned overlap with defined handover deliverables protects critical knowledge during vendor transitions.',
   ref:'Performance domains: Resources (procurement), Risk'},
  {id:'S5-P40',domain:D,task:7,approach:'Agile',type:'single',
   stem:'Sprint review demonstrations are valuable, but people who miss them lose context. What simple practice helps?',
   options:['Making attendance mandatory','Recording short demo videos with brief notes and storing them in a shared, searchable location','Repeating every demo in person','Sending the code to stakeholders'],answer:[1],
   explanation:'Recorded demos make knowledge available to people who could not attend.',
   ref:'Performance domain: Stakeholders · Principle: Build an empowered culture'},
  {id:'S5-P41',domain:D,task:7,approach:'Predictive',type:'single',
   stem:'An organization wants junior project managers to learn from experienced ones in a structured way. What should it set up?',
   options:['A rule that juniors work alone','A mentoring program that pairs junior and senior project managers with regular sessions and goals','Annual lectures only','A library of old project plans only'],answer:[1],
   explanation:'Structured mentoring transfers tacit knowledge and accelerates development.',
   ref:'Performance domain: Resources · Principle: Build an empowered culture'},
  {id:'S5-P42',domain:D,task:7,approach:'Agile',type:'single',
   stem:'An agile team wonders how much documentation it needs. What is the best guidance?',
   options:['None; agile means no documentation','“Just enough” documentation that serves a clear purpose—such as supporting operations, compliance or future maintainers—kept current with the product','Document everything in detail','Only document after the project ends'],answer:[1],
   explanation:'Agile values working software, but purposeful documentation remains necessary and should be kept current.',
   ref:'Principle: Embed quality · Principle: Focus on value'},
  {id:'S5-P43',domain:D,task:7,approach:'Hybrid',type:'single',
   stem:'A new project is about to start that is very similar to one completed last year. What should the project manager do first?',
   options:['Start planning from scratch','Review the previous project’s lessons learned, records and estimates, and talk to people who worked on it','Copy the old plan without review','Ignore the previous project'],answer:[1],
   explanation:'Using organizational knowledge from similar projects improves planning and avoids repeated mistakes.',
   ref:'Principle: Embed quality · Focus area: Initiating'},
  {id:'S5-P44',domain:D,task:7,approach:'Predictive',type:'multi',
   stem:'Which TWO actions help make sure lessons learned are actually used?',
   options:['Including a review of relevant lessons in project start-up','Storing lessons where no one can find them','Turning key lessons into updated checklists or standards','Writing lessons only for the final report','Limiting lessons to one person’s notes'],answer:[0,2],
   explanation:'Lessons are used when they are reviewed at start-up and built into standards.',
   ref:'Principle: Embed quality · Focus area: Planning'},

  // Task 8 — Communication (6)
  {id:'S5-P45',domain:D,task:8,approach:'Predictive',type:'matching',
   stem:'Match each type of communication to its example.',
   pairs:[{left:'Formal written',right:0},{left:'Formal verbal',right:1},{left:'Informal written',right:2},{left:'Informal verbal',right:3}],
   choices:['A signed contract amendment','A presentation to the steering committee','A quick chat message to a colleague','A hallway conversation'],
   explanation:'Choosing the right formality and medium depends on the purpose and the need for a record.',
   ref:'Performance domain: Stakeholders · Focus area: Planning'},
  {id:'S5-P46',domain:D,task:8,approach:'Agile',type:'single',
   stem:'Virtual meetings are unproductive: people are distracted, and a few voices dominate. What should the project manager do?',
   options:['Hold more meetings','Agree on virtual meeting norms—such as a clear agenda, cameras on when possible, using chat and hand-raise features, and inviting input from everyone—and model them','Ban virtual meetings','Record meetings and skip them'],answer:[1],
   explanation:'Explicit norms and facilitation make virtual meetings more inclusive and effective.',
   ref:'Principle: Build an empowered culture · Focus area: Executing'},
  {id:'S5-P47',domain:D,task:8,approach:'Hybrid',type:'single',
   stem:'Important messages are not reaching field staff because their supervisors do not pass them on. What should the project manager do?',
   options:['Send more emails to supervisors','Identify the barrier, agree with supervisors on their role in cascading messages, and add a direct channel to field staff with a way to confirm receipt','Stop communicating with field staff','Blame the supervisors'],answer:[1],
   explanation:'Communication plans should identify and remove barriers and confirm that messages reach their audience.',
   ref:'Performance domain: Stakeholders · Focus area: Monitoring and Controlling'},
  {id:'S5-P48',domain:D,task:8,approach:'Predictive',type:'single',
   stem:'How should the frequency of communication with a stakeholder be decided?',
   options:['The same for everyone','Based on the stakeholder’s needs, influence and the project’s situation, as agreed in the communication plan and adjusted when needs change','As rarely as possible','As often as possible'],answer:[1],
   explanation:'Communication frequency should be tailored and kept under review.',
   ref:'Performance domain: Stakeholders · Focus area: Planning'},
  {id:'S5-P49',domain:D,task:8,approach:'Agile',type:'single',
   stem:'A project manager sends regular updates but never knows whether stakeholders find them useful. What should be added?',
   options:['Longer updates','A feedback loop—such as a quick pulse question or periodic check-in—to learn what stakeholders find useful and adjust','More frequent updates','Fewer recipients'],answer:[1],
   explanation:'Feedback turns one-way communication into an improving, two-way process.',
   ref:'Performance domain: Stakeholders · Focus area: Monitoring and Controlling'},
  {id:'S5-P50',domain:D,task:8,approach:'Hybrid',type:'multi',
   stem:'Which TWO practices improve communication on projects with many technical specialists and business stakeholders?',
   options:['A shared glossary of key terms','Using as much jargon as possible','Tailoring messages to each audience’s level of expertise','Sending the same detailed technical report to everyone','Avoiding questions in meetings'],answer:[0,2],
   explanation:'Shared terminology and audience-tailored messages reduce misunderstanding.',
   ref:'Performance domain: Stakeholders · Focus area: Executing'}
];
