import {ExamQuestion} from '../../exam-types';

const D='Process' as const;

export const PROCESS_QUESTIONS:ExamQuestion[]=[
  // Task 1 — Integrated plan and plan delivery (7)
  {id:'S5-R01',domain:D,task:1,approach:'Predictive',type:'single',
   stem:'Which process or activity coordinates all aspects of the project so that the parts work together as a whole?',
   options:['Quality control','Integration management','Procurement closure','Team building'],answer:[1],
   explanation:'Integration management combines and coordinates the project’s plans, processes and decisions into a unified whole.',
   ref:'Principle: Adopt a holistic view · Performance domain: Governance'},
  {id:'S5-R02',domain:D,task:1,approach:'Hybrid',type:'single',
   stem:'An organization’s standard methodology is fully predictive, but a new project has high uncertainty in its user-facing features. What should the project manager do?',
   options:['Use the standard methodology unchanged','Propose a tailored hybrid approach to governance, explaining which parts will be adaptive and how oversight will be maintained','Use agile without telling anyone','Delay the project until requirements are certain'],answer:[1],
   explanation:'Tailoring with transparent governance matches the approach to the project’s characteristics.',
   ref:'Principle: Adopt a holistic view · Performance domain: Governance'},
  {id:'S5-R03',domain:D,task:1,approach:'Agile',type:'single',
   stem:'An agile team works without any long-term planning, and stakeholders cannot see where the product is heading. What is missing?',
   options:['A detailed Gantt chart','A product roadmap that shows the planned direction and major outcomes over the coming months','More daily standups','A longer sprint'],answer:[1],
   explanation:'Agile teams still need a roadmap to communicate direction and support longer-term decisions.',
   ref:'Performance domain: Scope · Focus area: Planning'},
  {id:'S5-R04',domain:D,task:1,approach:'Predictive',type:'single',
   stem:'Which document describes how the project will be executed, monitored, controlled and closed, and integrates all the subsidiary plans and baselines?',
   options:['Project charter','Project management plan','Business case','Issue log'],answer:[1],
   explanation:'The project management plan is the integrated document that guides project delivery.',
   ref:'Performance domain: Governance · Focus area: Planning'},
  {id:'S5-R05',domain:D,task:1,approach:'Hybrid',type:'single',
   stem:'A project will use AI tools to summarize meetings and draft documents. What should be addressed in the project’s plans?',
   options:['Nothing','Which tools are approved, what information may be shared with them, how outputs will be reviewed, and who is accountable for final content','Only the licence cost','A ban on all documents'],answer:[1],
   explanation:'Using AI responsibly requires explicit guidance on approved tools, data, review and accountability.',
   ref:'AI in project management · Performance domain: Governance'},
  {id:'S5-R06',domain:D,task:1,approach:'Agile',type:'single',
   stem:'A team adopts Kanban for a support-heavy product. Which planning practice fits this approach?',
   options:['Fixed two-week sprint commitments','Regular replenishment meetings to select and order the next work items, with WIP limits and service-level expectations','Annual planning only','No planning at all'],answer:[1],
   explanation:'Kanban uses replenishment and flow policies rather than fixed sprint commitments.',
   ref:'Performance domain: Schedule · Focus area: Planning'},
  {id:'S5-R07',domain:D,task:1,approach:'Hybrid',type:'multi',
   stem:'Which TWO factors should influence how much planning detail a project needs up front?',
   options:['The level of uncertainty and the cost of changing course later','The project manager’s preference for long documents','Regulatory and contractual requirements','The colour of the templates','The number of meeting rooms available'],answer:[0,2],
   explanation:'Planning depth should reflect uncertainty, the cost of change and external requirements.',
   ref:'Principle: Adopt a holistic view · Focus area: Planning'},

  // Task 2 — Scope (7)
  {id:'S5-R08',domain:D,task:2,approach:'Predictive',type:'single',
   stem:'Which technique decomposes deliverables into smaller, more manageable components?',
   options:['Decomposition','Crashing','Benchmarking','Resource leveling'],answer:[0],
   explanation:'Decomposition breaks project deliverables into work packages that can be estimated and managed.',
   ref:'Performance domain: Scope · Focus area: Planning'},
  {id:'S5-R09',domain:D,task:2,approach:'Agile',type:'single',
   stem:'The product owner adds many items to the backlog that may never be built. The backlog has 900 items, and it is hard to find what matters. What should happen?',
   options:['Keep adding items','Regularly refine the backlog: remove or archive items unlikely to be done, keep near-term items detailed and later items coarse','Freeze the backlog','Sort items alphabetically'],answer:[1],
   explanation:'A healthy backlog is actively curated so that it stays focused on valuable work.',
   ref:'Performance domain: Scope · Focus area: Planning'},
  {id:'S5-R10',domain:D,task:2,approach:'Predictive',type:'single',
   stem:'A requirement says “The system must be fast.” What is the problem, and how should it be fixed?',
   options:['No problem','It is not measurable; rewrite it with testable criteria, such as “95% of searches return results within two seconds”','Remove it','Make it longer'],answer:[1],
   explanation:'Requirements must be clear and testable so that they can be verified.',
   ref:'Principle: Embed quality · Performance domain: Scope'},
  {id:'S5-R11',domain:D,task:2,approach:'Hybrid',type:'single',
   stem:'Stakeholders observe that users do things differently from what the procedures describe. Which elicitation technique reveals how work is really done?',
   options:['Reviewing the procedure manual','Observation (job shadowing) in the users’ real work environment','A survey only','Asking managers'],answer:[1],
   explanation:'Observation reveals actual practices, workarounds and hidden requirements.',
   ref:'Performance domain: Scope · Focus area: Planning'},
  {id:'S5-R12',domain:D,task:2,approach:'Agile',type:'single',
   stem:'What does “acceptance criteria” mean for a user story?',
   options:['The developer’s technical notes','Specific conditions that the story must satisfy to be accepted by the product owner','The story’s size in points','The sprint length'],answer:[1],
   explanation:'Acceptance criteria define when a story meets the user’s needs.',
   ref:'Performance domain: Scope · Principle: Embed quality'},
  {id:'S5-R13',domain:D,task:2,approach:'Predictive',type:'single',
   stem:'Who is responsible for formally accepting the completed project deliverables?',
   options:['The project team','The customer or sponsor, as defined in the acceptance process','The vendor','The PMO'],answer:[1],
   explanation:'Formal acceptance is given by the authorized customer or sponsor.',
   ref:'Performance domain: Scope · Focus area: Closing'},
  {id:'S5-R14',domain:D,task:2,approach:'Hybrid',type:'multi',
   stem:'Which TWO practices help confirm that requirements are complete and correct before major build work starts?',
   options:['Reviewing requirements with stakeholders and walking through key scenarios','Skipping reviews to save time','Building a prototype or model for feedback','Letting developers assume missing details','Waiting for testing to find gaps'],answer:[0,2],
   explanation:'Reviews and prototypes find gaps and misunderstandings early.',
   ref:'Performance domain: Scope · Principle: Embed quality'},

  // Task 3 — Value (7)
  {id:'S5-R15',domain:D,task:3,approach:'Hybrid',type:'single',graphic:'tornado-2',
   stem:'Based on the tornado diagram, which variable has the greatest effect on the project’s NPV?',
   options:['Licence cost','Staff productivity gain','Enrolment growth','Hosting cost'],answer:[2],
   explanation:'Enrolment growth has the widest bar (–500 to +450), so its uncertainty affects NPV the most. It deserves the most attention in validation and risk planning.',
   ref:'Performance domains: Risk, Finance · Principle: Focus on value'},
  {id:'S5-R16',domain:D,task:3,approach:'Hybrid',type:'dropdown',graphic:'tornado-2',
   stem:'If enrolment growth turns out at its low estimate and other variables stay at base values, what will the NPV be?',
   options:['–$500,000','$700,000','$1,200,000','$1,650,000'],answer:[1],
   explanation:'Base NPV $1,200,000 + (–$500,000) = $700,000. The project remains worthwhile, but with less margin.',
   ref:'Performance domain: Finance · Principle: Focus on value'},
  {id:'S5-R17',domain:D,task:3,approach:'Predictive',type:'single',
   stem:'A project has already spent $2 million. Completing it will cost $1 million more and deliver benefits worth $800,000. What should guide the decision to continue?',
   options:['The $2 million already spent','Only future costs and benefits: spending $1 million more to gain $800,000 is not justified on financial grounds alone','The sponsor’s reputation','The team’s preference'],answer:[1],
   explanation:'Money already spent is a sunk cost and should not drive decisions. Compare future costs with future benefits.',
   ref:'Principle: Focus on value · Performance domain: Governance'},
  {id:'S5-R18',domain:D,task:3,approach:'Agile',type:'single',
   stem:'A team has a long list of possible features. Which approach helps it learn quickly what customers really value before building much?',
   options:['Building every feature fully','Running small experiments—such as prototypes, landing-page tests or concierge versions—to test demand','Asking only internal staff','Copying competitors'],answer:[1],
   explanation:'Cheap experiments validate value before significant investment.',
   ref:'Principle: Focus on value · Performance domain: Risk'},
  {id:'S5-R19',domain:D,task:3,approach:'Hybrid',type:'single',
   stem:'Who should be accountable for realizing the benefits of a new HR system after it goes live?',
   options:['The vendor','A business owner in HR named as the benefits owner','The project team, permanently','No one'],answer:[1],
   explanation:'Benefits are realized in the business, so a business owner should be accountable.',
   ref:'Principle: Focus on value · Focus area: Closing'},
  {id:'S5-R20',domain:D,task:3,approach:'Agile',type:'single',
   stem:'Which statement best describes an “outcome” compared with an “output”?',
   options:['They are the same','An output is something produced, such as a feature; an outcome is the change it creates, such as fewer support calls','An outcome is always a document','An output is always intangible'],answer:[1],
   explanation:'Focusing on outcomes keeps teams aimed at the change that creates value.',
   ref:'Principle: Focus on value · Performance domain: Scope'},
  {id:'S5-R21',domain:D,task:3,approach:'Hybrid',type:'multi',
   stem:'Which TWO practices help ensure that a project keeps delivering value as conditions change?',
   options:['Reviewing the business case and priorities at regular intervals','Locking all priorities at the start','Measuring outcomes and adjusting plans based on the results','Ignoring stakeholder feedback','Finishing all planned features regardless of value'],answer:[0,2],
   explanation:'Regular review and outcome-based adjustment keep the project focused on value.',
   ref:'Principle: Focus on value · Focus area: Monitoring and Controlling'},

  // Task 4 — Resources (6)
  {id:'S5-R22',domain:D,task:4,approach:'Predictive',type:'single',
   stem:'Which chart shows the amount of a resource needed in each time period, compared with its availability?',
   options:['Resource histogram','Fishbone diagram','Burnup chart','Tornado diagram'],answer:[0],
   explanation:'Resource histograms highlight over-allocation and help with leveling decisions.',
   ref:'Performance domain: Resources · Focus area: Planning'},
  {id:'S5-R23',domain:D,task:4,approach:'Hybrid',type:'single',
   stem:'A key team member is suddenly on extended leave. What should the project manager do first?',
   options:['Wait for their return','Assess the effect on the schedule and deliverables, and identify options such as redistributing work, bringing in a replacement or adjusting the plan','Ask the team to absorb the work without discussion','Stop the project'],answer:[1],
   explanation:'Resource disruptions require impact analysis and a deliberate response.',
   ref:'Performance domain: Resources · Focus area: Executing'},
  {id:'S5-R24',domain:D,task:4,approach:'Agile',type:'single',
   stem:'An agile team is asked to support three products at the same time, and context switching is hurting its output. What should the project manager do?',
   options:['Ask the team to work faster','Make the cost of context switching visible and work with stakeholders to limit the team’s concurrent work or prioritize between products','Assign each member to a different product','Ignore it'],answer:[1],
   explanation:'Limiting concurrent work reduces the waste of context switching and improves flow.',
   ref:'Performance domain: Resources · Principle: Focus on value'},
  {id:'S5-R25',domain:D,task:4,approach:'Predictive',type:'single',
   stem:'The project needs a specialized laboratory for testing. It is booked by other departments for most of the year. What should the project manager do during planning?',
   options:['Assume it will be available','Confirm availability early, reserve the needed dates and include the dependency in the schedule','Plan testing anywhere','Skip testing'],answer:[1],
   explanation:'Physical resources with limited availability must be planned and reserved early.',
   ref:'Performance domains: Resources, Schedule · Focus area: Planning'},
  {id:'S5-R26',domain:D,task:4,approach:'Hybrid',type:'single',
   stem:'How should the project manager decide whether to use internal staff or contractors for a short-term specialized task?',
   options:['Always use contractors','Compare cost, availability, expertise, knowledge retention and risk for each option','Always use internal staff','Choose randomly'],answer:[1],
   explanation:'A structured comparison supports a sound resourcing decision.',
   ref:'Performance domain: Resources · Focus area: Planning'},
  {id:'S5-R27',domain:D,task:4,approach:'Agile',type:'multi',
   stem:'Which TWO practices help an agile team manage its capacity well?',
   options:['Planning based on recent velocity or throughput','Committing to as much work as stakeholders request','Accounting for holidays, support duties and other commitments','Ignoring team members’ availability','Adding people to late work to speed it up'],answer:[0,2],
   explanation:'Realistic capacity planning uses historical data and actual availability.',
   ref:'Performance domain: Resources · Focus area: Planning'},

  // Task 5 — Procurement (6)
  {id:'S5-R28',domain:D,task:5,approach:'Predictive',type:'dropdown',
   stem:'A vendor agreement is a fixed-price-incentive-fee contract with a target cost of $100,000, a target profit of $10,000, a ceiling price of $120,000 and a 70/30 buyer/seller share ratio. What is the point of total assumption (PTA)? Select the closest value.',
   options:['$110,000','$114,286','$120,000','$128,571'],answer:[1],
   explanation:'PTA = (ceiling price – target price) ÷ buyer’s share + target cost = (120,000 – 110,000) ÷ 0.70 + 100,000 ≈ $114,286. Above this cost, the seller bears all additional costs.',
   ref:'Performance domains: Finance, Resources (procurement)'},
  {id:'S5-R29',domain:D,task:5,approach:'Predictive',type:'single',
   stem:'The buyer’s needs are clear and well defined, and the market has several qualified sellers. Which contract type gives the buyer the most cost certainty?',
   options:['Time and materials','Firm fixed price','Cost plus percentage of cost','Cost plus award fee'],answer:[1],
   explanation:'A firm fixed price works well for well-defined scope and gives the buyer the most cost certainty.',
   ref:'Performance domain: Resources (procurement) · Focus area: Planning'},
  {id:'S5-R30',domain:D,task:5,approach:'Hybrid',type:'single',
   stem:'Why is a cost-plus-percentage-of-cost contract generally discouraged?',
   options:['It is too simple','It rewards the seller for increasing costs, because the fee grows with the cost','It gives the buyer too much control','It is illegal everywhere'],answer:[1],
   explanation:'Cost-plus-percentage-of-cost contracts give the seller no incentive to control costs.',
   ref:'Performance domains: Resources (procurement), Finance'},
  {id:'S5-R31',domain:D,task:5,approach:'Predictive',type:'single',
   stem:'A buyer receives three bids. One is far lower than the independent estimate and the other bids. What should the buyer do?',
   options:['Accept the lowest bid immediately','Clarify with the bidder whether it has understood the scope correctly before deciding, because a very low bid may indicate a misunderstanding or risk','Reject it automatically','Share it with the other bidders'],answer:[1],
   explanation:'Unusually low bids may signal a misunderstanding or an unrealistic price that creates delivery risk.',
   ref:'Performance domain: Resources (procurement) · Performance domain: Risk'},
  {id:'S5-R32',domain:D,task:5,approach:'Agile',type:'single',
   stem:'A buyer contracts an agile vendor and wants to protect itself if the vendor underperforms. Which contract feature helps most?',
   options:['A single payment at the end','Payment per accepted increment, with the right to end the engagement after any increment','A five-year lock-in','No acceptance criteria'],answer:[1],
   explanation:'Paying for accepted increments with exit points limits the buyer’s exposure.',
   ref:'Performance domains: Resources (procurement), Risk'},
  {id:'S5-R33',domain:D,task:5,approach:'Predictive',type:'multi',
   stem:'Which TWO activities are part of controlling procurements?',
   options:['Reviewing seller performance against the contract','Writing the business case','Managing contract changes and claims','Hiring the project team','Creating the project charter'],answer:[0,2],
   explanation:'Controlling procurements includes performance monitoring, change management and claims administration.',
   ref:'Performance domain: Resources (procurement) · Focus area: Monitoring and Controlling'},

  // Task 6 — Finance (6)
  {id:'S5-R34',domain:D,task:6,approach:'Predictive',type:'dropdown',
   stem:'A project’s estimate at completion (EAC) is $1,250,000, and actual costs to date are $700,000. What is the estimate to complete (ETC)?',
   options:['$450,000','$550,000','$700,000','$1,950,000'],answer:[1],
   explanation:'ETC = EAC – AC = 1,250,000 – 700,000 = $550,000.',
   ref:'Performance domain: Finance · Focus area: Monitoring and Controlling'},
  {id:'S5-R35',domain:D,task:6,approach:'Predictive',type:'dropdown',
   stem:'EV = $400,000 and AC = $440,000. What is the cost variance percentage (CV%)?',
   options:['–9.1%','–10%','+10%','–40%'],answer:[1],
   explanation:'CV = EV – AC = –$40,000. CV% = CV ÷ EV = –40,000 ÷ 400,000 = –10%.',
   ref:'Performance domain: Finance · Focus area: Monitoring and Controlling'},
  {id:'S5-R36',domain:D,task:6,approach:'Predictive',type:'single',
   stem:'A project estimates its cost by comparing it with a similar project completed last year and adjusting for size. Which technique is this?',
   options:['Analogous estimating','Bottom-up estimating','Parametric estimating','Reserve analysis'],answer:[0],
   explanation:'Analogous estimating uses a similar past project as the basis. It is quick but less accurate.',
   ref:'Performance domain: Finance · Focus area: Planning'},
  {id:'S5-R37',domain:D,task:6,approach:'Hybrid',type:'single',
   stem:'Finance asks why the project’s monthly spending forecast keeps changing. What should the project manager provide?',
   options:['No explanation','A reconciliation of forecast changes to their causes—such as approved changes, risks realized and timing shifts—with the updated forecast','A fixed forecast that never changes','Only the total budget'],answer:[1],
   explanation:'Explaining variances and forecast changes builds financial credibility.',
   ref:'Performance domain: Finance · Focus area: Monitoring and Controlling'},
  {id:'S5-R38',domain:D,task:6,approach:'Agile',type:'single',
   stem:'An agile program must report spending against its approved funding each quarter. Which approach works best?',
   options:['Estimating every story in dollars','Tracking team run-rate costs against the funded capacity and showing the outcomes delivered for that investment','Reporting only at the end','Converting the program to a fixed-scope contract'],answer:[1],
   explanation:'Capacity-based funding is tracked through run rates, linked to the value delivered.',
   ref:'Performance domain: Finance · Principle: Focus on value'},
  {id:'S5-R39',domain:D,task:6,approach:'Predictive',type:'multi',
   stem:'Which TWO actions should the project manager take when actual costs are trending above the budget?',
   options:['Analyze the causes of the variance','Hide the variance until it disappears','Forecast the impact and propose corrective actions or a re-baseline through governance','Use management reserve without approval','Stop recording costs'],answer:[0,2],
   explanation:'Cost control requires analysis, forecasting and governed corrective action.',
   ref:'Performance domain: Finance · Focus area: Monitoring and Controlling'},

  // Task 7 — Quality (6)
  {id:'S5-R40',domain:D,task:7,approach:'Predictive',type:'single',
   stem:'A team wants to know whether two variables—such as hours of training and defect rate—are related. Which tool should it use?',
   options:['Scatter diagram','Gantt chart','RACI chart','Network diagram'],answer:[0],
   explanation:'A scatter diagram shows whether, and how strongly, two variables are correlated.',
   ref:'Principle: Embed quality · Focus area: Monitoring and Controlling'},
  {id:'S5-R41',domain:D,task:7,approach:'Predictive',type:'single',
   stem:'Which tool helps make sure that each inspection step is performed consistently?',
   options:['Checklist','Tornado diagram','Burndown chart','Org chart'],answer:[0],
   explanation:'Checklists standardize repetitive quality activities and reduce the chance of missed steps.',
   ref:'Principle: Embed quality · Focus area: Monitoring and Controlling'},
  {id:'S5-R42',domain:D,task:7,approach:'Agile',type:'single',
   stem:'The team’s definition of done does not include performance testing, and slow pages are discovered after release. What should the team do?',
   options:['Accept slow pages','Add appropriate performance checks to the definition of done and automate them where practical','Test performance once a year','Ask users to report slow pages'],answer:[1],
   explanation:'Strengthening the definition of done builds quality attributes into every increment.',
   ref:'Principle: Embed quality · Performance domain: Scope'},
  {id:'S5-R43',domain:D,task:7,approach:'Hybrid',type:'single',
   stem:'Who is ultimately responsible for the quality of the project’s deliverables?',
   options:['Only the quality department','The project manager is accountable for project quality, while everyone on the team is responsible for the quality of their own work','The customer','The vendor alone'],answer:[1],
   explanation:'Quality is everyone’s responsibility, with the project manager accountable overall.',
   ref:'Principle: Embed quality · Principle: Be an accountable leader'},
  {id:'S5-R44',domain:D,task:7,approach:'Predictive',type:'single',
   stem:'A team runs controlled tests that change several factors at once to find the combination that produces the strongest concrete mix. What technique is this?',
   options:['Design of experiments','Benchmarking','Brainstorming','Sampling'],answer:[0],
   explanation:'Design of experiments identifies which factors, and which combinations, influence a result.',
   ref:'Principle: Embed quality · Focus area: Planning'},
  {id:'S5-R45',domain:D,task:7,approach:'Hybrid',type:'multi',
   stem:'Which TWO practices reduce the cost of quality over the life of a project?',
   options:['Investing in prevention, such as training and clear standards','Relying on customers to find defects','Detecting defects early through reviews and testing','Skipping inspections','Accepting rework as normal'],answer:[0,2],
   explanation:'Prevention and early detection are cheaper than late failures and rework.',
   ref:'Principle: Embed quality · Performance domain: Finance'},

  // Task 8 — Schedule (6)
  {id:'S5-R46',domain:D,task:8,approach:'Predictive',type:'dropdown',graphic:'network-5',
   stem:'Refer to the network diagram. How many days will the project take from start to finish?',
   options:['12 days','14 days','15 days','21 days'],answer:[1],
   explanation:'Paths: A-B-D-F = 2+4+5+3 = 14; A-C-E-F = 2+3+4+3 = 12. The critical path is A-B-D-F, so the duration is 14 days.',
   ref:'Performance domain: Schedule · Focus area: Planning'},
  {id:'S5-R47',domain:D,task:8,approach:'Predictive',type:'single',graphic:'network-5',
   stem:'Activity E is delayed by 3 days. What happens to the project duration?',
   options:['No change','It increases by 1 day','It increases by 2 days','It increases by 3 days'],answer:[1],
   explanation:'Path A-C-E-F is 12 days, so E has 2 days of float. A 3-day delay makes that path 15 days—1 day longer than the current 14.',
   ref:'Performance domain: Schedule · Focus area: Monitoring and Controlling'},
  {id:'S5-R48',domain:D,task:8,approach:'Agile',type:'dropdown',
   stem:'The remaining release backlog is 300 points. The team’s velocity has ranged from 25 to 35 points per sprint. What is a reasonable forecast range for the number of sprints?',
   options:['8 to 10 sprints','9 to 12 sprints','10 to 14 sprints','12 to 15 sprints'],answer:[1],
   explanation:'300 ÷ 35 ≈ 8.6, rounded up to 9 sprints; 300 ÷ 25 = 12 sprints. A range of 9 to 12 sprints reflects real variability.',
   ref:'Performance domain: Schedule · Focus area: Planning'},
  {id:'S5-R49',domain:D,task:8,approach:'Predictive',type:'single',
   stem:'What is free float?',
   options:['The total time a project can be delayed','The amount of time an activity can be delayed without delaying the early start of any immediate successor','The time between project start and finish','Time added by the sponsor'],answer:[1],
   explanation:'Free float protects successors’ early starts; total float protects the project end date.',
   ref:'Performance domain: Schedule · Focus area: Planning'},
  {id:'S5-R50',domain:D,task:8,approach:'Hybrid',type:'single',
   stem:'A path in the schedule has only 2 days of float on a 12-month project. Why should the project manager watch it closely?',
   options:['It is not important','It is a near-critical path; small delays could make it critical and threaten the end date','It has too much float','It can be ignored until it becomes critical'],answer:[1],
   explanation:'Near-critical paths can easily become critical and should be monitored alongside the critical path.',
   ref:'Performance domains: Schedule, Risk · Focus area: Monitoring and Controlling'},
  {id:'S5-R51',domain:D,task:8,approach:'Predictive',type:'multi',
   stem:'Which TWO actions help protect a fixed project end date?',
   options:['Monitoring the critical and near-critical paths closely','Ignoring float consumption','Including schedule reserve based on risk analysis','Adding untracked work','Removing all dependencies from the schedule'],answer:[0,2],
   explanation:'Close monitoring and risk-based schedule reserve help protect fixed deadlines.',
   ref:'Performance domain: Schedule · Performance domain: Risk'},

  // Task 9 — Evaluate status (5)
  {id:'S5-R52',domain:D,task:9,approach:'Agile',type:'single',graphic:'burndown-5',
   stem:'What does the sprint burndown suggest about how the team is working?',
   options:['Work is completed steadily throughout the sprint','Little work was completed until day 5, then large amounts finished at once—suggesting large items or late testing, which hides progress and increases risk','The team is ahead of schedule from day 1','The team added scope'],answer:[1],
   explanation:'A flat line followed by a steep drop often means work is batched or tested late. Smaller items and continuous testing give steadier flow.',
   ref:'Performance domain: Schedule · Focus area: Monitoring and Controlling'},
  {id:'S5-R53',domain:D,task:9,approach:'Predictive',type:'single',
   stem:'A project finishes three months late, but its SPI at completion is 1.0. Why?',
   options:['The project was on time','Because SPI is based on value earned, it always reaches 1.0 when all work is complete, even if the project is late—so SPI is less useful near the end','SPI was calculated wrongly','The schedule was rebaselined'],answer:[1],
   explanation:'At completion, EV equals PV (both equal BAC), so SPI = 1.0 regardless of lateness. Time-based measures complement SPI late in a project.',
   ref:'Performance domain: Schedule · Focus area: Monitoring and Controlling'},
  {id:'S5-R54',domain:D,task:9,approach:'Hybrid',type:'single',
   stem:'Which information is most useful in a status report for a sponsor who needs to make decisions?',
   options:['A list of every task completed','Progress against objectives, forecasts, key risks and issues, and the decisions needed','Team members’ working hours','The full project schedule'],answer:[1],
   explanation:'Decision-oriented status reports focus on what the sponsor needs to know and decide.',
   ref:'Performance domain: Stakeholders · Focus area: Monitoring and Controlling'},
  {id:'S5-R55',domain:D,task:9,approach:'Predictive',type:'single',
   stem:'What is the difference between the period CPI and the cumulative CPI?',
   options:['They are the same','Period CPI shows cost efficiency for one reporting period; cumulative CPI shows efficiency since the project started, which is more stable for forecasting','Period CPI is always higher','Cumulative CPI ignores actual costs'],answer:[1],
   explanation:'Cumulative CPI smooths out short-term swings and is commonly used for forecasting the EAC.',
   ref:'Performance domain: Finance · Focus area: Monitoring and Controlling'},
  {id:'S5-R56',domain:D,task:9,approach:'Agile',type:'multi',
   stem:'Which TWO measures give stakeholders a balanced view of an agile team’s progress?',
   options:['A release burnup showing completed work against total scope','The number of hours worked','Outcome measures, such as usage or customer satisfaction','The number of emails sent','The length of meetings'],answer:[0,2],
   explanation:'Combining delivery progress with outcome measures shows both how much is done and whether it matters.',
   ref:'Principle: Focus on value · Focus area: Monitoring and Controlling'},

  // Task 10 — Closure (6)
  {id:'S5-R57',domain:D,task:10,approach:'Predictive',type:'single',
   stem:'The project is complete, and the team is eager to move on. Which activity is most often skipped but valuable?',
   options:['Celebrating','Capturing lessons learned and updating organizational process assets','Releasing the team','Closing contracts'],answer:[1],
   explanation:'Lessons learned are frequently rushed or skipped, but they are a key benefit for future projects.',
   ref:'Principle: Embed quality · Focus area: Closing'},
  {id:'S5-R58',domain:D,task:10,approach:'Hybrid',type:'single',
   stem:'After go-live, the project provides a short period of intensive support before handing over to operations. What is this period called?',
   options:['Hypercare','Fast tracking','Rolling-wave planning','Crashing'],answer:[0],
   explanation:'Hypercare stabilizes a new solution after go-live before a full handover to business-as-usual support.',
   ref:'Focus area: Closing · Performance domain: Resources'},
  {id:'S5-R59',domain:D,task:10,approach:'Predictive',type:'single',
   stem:'A project is cancelled because its business case is no longer valid. What is the value of completing closure activities?',
   options:['None','It ensures that contracts are closed properly, completed work and knowledge are preserved, resources are released and lessons are captured','It restarts the project','It increases the budget'],answer:[1],
   explanation:'Even cancelled projects need closure to protect the organization and capture value.',
   ref:'Focus area: Closing · Performance domain: Governance'},
  {id:'S5-R60',domain:D,task:10,approach:'Agile',type:'single',
   stem:'An agile team is disbanded after the product moves to maintenance mode. What should happen to the product backlog?',
   options:['Delete it','Review it with the product owner and the receiving team, keep items that remain relevant, and hand it over with context','Keep it secret','Print it for the archive only'],answer:[1],
   explanation:'The backlog contains valuable knowledge about future needs and should be transferred deliberately.',
   ref:'Focus area: Closing · Performance domain: Scope'},
  {id:'S5-R61',domain:D,task:10,approach:'Predictive',type:'single',
   stem:'When should the project manager release resources such as equipment and facilities that are no longer needed?',
   options:['Only at the very end of the project','As soon as they are no longer needed, following the resource management plan, to avoid unnecessary cost','Never','When the sponsor asks'],answer:[1],
   explanation:'Releasing resources promptly reduces cost and makes them available to others.',
   ref:'Performance domains: Resources, Finance · Focus area: Closing'},
  {id:'S5-R62',domain:D,task:10,approach:'Hybrid',type:'multi',
   stem:'Which TWO items should the final project report include?',
   options:['A comparison of results with the project’s objectives and success criteria','Personal criticism of team members','A summary of key lessons learned and recommendations','Confidential salary information','Unverified rumours'],answer:[0,2],
   explanation:'The final report summarizes performance against objectives and shares lessons for the future.',
   ref:'Focus area: Closing · Performance domain: Governance'}
];
