import {Component,ElementRef,ViewChild,HostListener} from '@angular/core';import {FormsModule} from '@angular/forms';import {RouterLink} from '@angular/router';import {downloadBlob,exportSvg} from '../../core/export-utils';
interface Node{id:string;kind:string;x:number;y:number;w:number;h:number;label:string;color:string}
interface Edge{id:string;from:string;to:string;label:string;color:string}
interface Drawing{name:string;nodes:Node[];edges:Edge[]}
@Component({standalone:true,imports:[FormsModule,RouterLink],templateUrl:'./diagram.component.html',styleUrl:'./diagram.component.css'})
export class DiagramComponent{
 @ViewChild('canvas') canvas?:ElementRef<SVGSVGElement>;
 name='My Diagram';nodes:Node[]=[];edges:Edge[]=[];selected='';edgeSelected='';kind='process';template='blank';zoom=1;fitZoom=.65;grid=true;message='';from='';to='';edgeLabel='';history:string[]=[];future:string[]=[];dirty=false;
 drag?:{id:string;x:number;y:number;px:number;py:number};
 kinds=[{id:'process',label:'Process / Activity'},{id:'entity',label:'External Entity'},{id:'system',label:'System'},{id:'store',label:'Data Store'},{id:'decision',label:'Decision'},{id:'start',label:'Start / End'},{id:'text',label:'Text'},{id:'lane',label:'Swimlane'}];
 templates=[{id:'blank',label:'Blank canvas'},{id:'context',label:'Context diagram'},{id:'dfd',label:'DFD Level 0 (overview)'},{id:'dfd1',label:'DFD Level 1 (decomposition)'},{id:'process',label:'Process diagram'},{id:'swimlane',label:'Swimlane process'},{id:'wbs',label:'Work breakdown structure'},{id:'org',label:'Organization chart'},{id:'stakeholders',label:'Stakeholder map'}];
 get node(){return this.nodes.find(n=>n.id===this.selected)} get edge(){return this.edges.find(e=>e.id===this.edgeSelected)}
 fit(){this.fitZoom=Math.max(.25,Math.min(1,((this.canvas?.nativeElement.parentElement?.clientWidth||800)-16)/1200));this.zoom=this.fitZoom}
 state(){return JSON.stringify({name:this.name,nodes:this.nodes,edges:this.edges})}
 record(){this.history.push(this.state());if(this.history.length>60)this.history.shift();this.future=[];this.dirty=true}
 undo(){if(!this.history.length)return;this.future.push(this.state());this.restore(this.history.pop()!);this.dirty=true}
 redo(){if(!this.future.length)return;this.history.push(this.state());this.restore(this.future.pop()!);this.dirty=true}
 restore(s:string){const d=JSON.parse(s) as Drawing;this.name=d.name;this.nodes=d.nodes;this.edges=d.edges;this.selected='';this.edgeSelected=''}
 newNode(kind:string,label:string,x:number,y:number,w=170,h=70):Node{return {id:crypto.randomUUID(),kind,label,x,y,w,h,color:kind==='entity'?'#e1ecff':kind==='decision'?'#fff0c2':kind==='lane'?'#f3f6fa':'#d8f4f1'}}
 add(){this.record();const n=this.newNode(this.kind,this.kinds.find(x=>x.id===this.kind)!.label,100+(this.nodes.length%5)*30,100+(this.nodes.length%5)*60,this.kind==='lane'?1000:170,this.kind==='lane'?180:70);this.nodes.push(n);this.select(n.id)}
 select(id:string){this.selected=id;this.edgeSelected=''}
 selectEdge(id:string){this.edgeSelected=id;this.selected=''}
 updateNode(field:keyof Node,value:any){const n=this.node;if(!n)return;this.record();(n as any)[field]=field==='w'?Math.max(70,Math.min(1100,Number(value)||170)):field==='h'?Math.max(35,Math.min(700,Number(value)||70)):value;n.x=Math.max(0,Math.min(Number(n.x)||0,1200-n.w));n.y=Math.max(0,Math.min(Number(n.y)||0,800-n.h))}
 updateEdge(field:keyof Edge,value:string){if(!this.edge)return;this.record();(this.edge as any)[field]=value}
 duplicate(){if(!this.node)return;this.record();const n={...this.node,id:crypto.randomUUID(),x:Math.min(1200-this.node.w,this.node.x+30),y:Math.min(800-this.node.h,this.node.y+30)};this.nodes.push(n);this.select(n.id)}
 remove(){if(!this.selected&&!this.edgeSelected)return;this.record();this.nodes=this.nodes.filter(n=>n.id!==this.selected);this.edges=this.edges.filter(e=>e.id!==this.edgeSelected&&e.from!==this.selected&&e.to!==this.selected);this.selected='';this.edgeSelected=''}
 connect(){if(!this.from||!this.to||this.from===this.to||!this.nodes.some(n=>n.id===this.from)||!this.nodes.some(n=>n.id===this.to)){this.message='Choose two different shapes.';return}this.record();this.edges.push({id:crypto.randomUUID(),from:this.from,to:this.to,label:this.edgeLabel,color:'#183c5a'});this.edgeLabel='';this.message='Connector added. Select its line to edit or delete it.'}
 point(e:PointerEvent){const svg=this.canvas!.nativeElement;const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform(svg.getScreenCTM()!.inverse())}
 startDrag(e:PointerEvent,n:Node){e.stopPropagation();this.select(n.id);if(e.button!==0)return;this.record();const p=this.point(e);this.drag={id:n.id,x:n.x,y:n.y,px:p.x,py:p.y};this.canvas!.nativeElement.setPointerCapture(e.pointerId)}
 move(e:PointerEvent){if(!this.drag)return;const n=this.nodes.find(n=>n.id===this.drag!.id)!;const p=this.point(e);const snap=(v:number)=>this.grid?Math.round(v/20)*20:v;n.x=Math.max(0,Math.min(1200-n.w,snap(this.drag.x+p.x-this.drag.px)));n.y=Math.max(0,Math.min(800-n.h,snap(this.drag.y+p.y-this.drag.py)))}
 end(){this.drag=undefined}
 endpoint(e:Edge,end:boolean){const n=this.nodes.find(n=>n.id===(end?e.to:e.from))!;const other=this.nodes.find(n=>n.id===(end?e.from:e.to))!;const cx=n.x+n.w/2,cy=n.y+n.h/2,dx=other.x+other.w/2-cx,dy=other.y+other.h/2-cy;const k=n.kind==='decision'?1/(Math.abs(dx)/(n.w/2)+Math.abs(dy)/(n.h/2)||1):Math.min(n.w/2/(Math.abs(dx)||.001),n.h/2/(Math.abs(dy)||.001));return {x:cx+dx*k,y:cy+dy*k}}
 control(e:Edge){const a=this.endpoint(e,false),b=this.endpoint(e,true);const dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy)||1;const bend=this.edges.some(o=>o.from===e.to&&o.to===e.from)?40:0;return {x:(a.x+b.x)/2-dy/len*bend,y:(a.y+b.y)/2+dx/len*bend}}
 path(e:Edge){const a=this.endpoint(e,false),b=this.endpoint(e,true),c=this.control(e);return `M ${a.x} ${a.y} Q ${c.x} ${c.y} ${b.x} ${b.y}`}
 midpoint(e:Edge){const a=this.endpoint(e,false),b=this.endpoint(e,true),c=this.control(e);return {x:(a.x+b.x+2*c.x)/4,y:(a.y+b.y+2*c.y)/4-8}}
 diamond(n:Node){return `${n.w/2},0 ${n.w},${n.h/2} ${n.w/2},${n.h} 0,${n.h/2}`}
 lines(n:Node){const max=Math.max(8,Math.floor(n.w/9));const words=n.label.split(/\s+/);const lines:string[]=[''];for(const w of words){let i=lines.length-1;if((lines[i]+' '+w).length>max&&lines[i]){lines.push(w)}else{lines[i]+=(lines[i]?' ':'')+w}}return lines.slice(0,Math.max(1,Math.floor(n.h/18)))}
 loadTemplate(){if(this.dirty&&!confirm('Replace the current drawing? Save or download it first to keep a copy.'))return;this.record();this.nodes=[];this.edges=[];this.selected='';this.edgeSelected='';this.from='';this.to='';this.name=this.templates.find(t=>t.id===this.template)!.label;
 const add=(kind:string,label:string,x:number,y:number,w=170,h=70)=>{const n=this.newNode(kind,label,x,y,w,h);this.nodes.push(n);return n};const link=(a:Node,b:Node,label='')=>this.edges.push({id:crypto.randomUUID(),from:a.id,to:b.id,label,color:'#183c5a'});
 if(this.template==='context'){const a=add('entity','Applicant',80,240),b=add('system','Application System',460,240,210,90),c=add('entity','Staff',900,240);link(a,b,'Application');link(b,c,'Review request');link(c,b,'Decision');link(b,a,'Status')}
 if(this.template==='dfd'||this.template==='dfd1'){const a=add('entity','Applicant',50,160),b=add('process',this.template==='dfd'?'1.0 Receive application':'1.1 Validate submission',350,160,210),c=add('process',this.template==='dfd'?'2.0 Review application':'1.2 Register application',720,160,210),d=add('store','D1 Applications',540,420,220),e=add('entity','Staff',960,420);link(a,b,'Application');link(b,c,'Validated details');link(c,d,'Application record');link(d,c,'Stored details');link(c,e,'Review information')}
 if(this.template==='process'||this.template==='swimlane'){if(this.template==='swimlane'){add('lane','Applicant',20,20,1160,260);add('lane','Service Team',20,300,1160,280)}const a=add('start','Start',60,110,120,60),b=add('process','Submit application',270,110),c=add('decision','Complete?',540,this.template==='swimlane'?370:90,170,100),d=add('process','Review application',820,this.template==='swimlane'?380:110),e=add('start','End',1010,this.template==='swimlane'?390:110,120,60);link(a,b);link(b,c);link(c,d,'Yes');link(c,b,'No: revise');link(d,e)}
 if(['wbs','org','stakeholders'].includes(this.template)){const root=add('system',this.template==='wbs'?'1.0 Project':this.template==='org'?'Project Sponsor':'Project Team',510,80);const names=this.template==='wbs'?['1.1 Planning','1.2 Delivery','1.3 Transition']:this.template==='org'?['Project Manager','Business Lead','Technical Lead']:['Sponsor','Users','Supplier'];names.forEach((label,i)=>{const n=add('process',label,150+i*350,330);link(root,n)})}
 this.message='Template loaded. Labels and shapes are editable.'}
 save(){try{localStorage.setItem('pmport-diagram',this.state());this.dirty=false;this.message='Saved on this device.'}catch{this.message='Browser storage is unavailable. Download an editable file instead.'}}
 open(){try{const s=localStorage.getItem('pmport-diagram');if(!s){this.message='No saved drawing on this device.';return}if(this.dirty&&!confirm('Open the saved drawing and replace current changes?'))return;this.record();this.restore(s);this.dirty=false;this.message='Saved drawing opened.'}catch{this.message='Could not read saved drawing.'}}
 download(){downloadBlob(new Blob([this.state()],{type:'application/json'}),'pmport-diagram.json');this.message='Editable JSON downloaded.'}
 async importFile(e:Event){const f=(e.target as HTMLInputElement).files?.[0];if(!f)return;try{if(f.size>2e6)throw Error();const d=JSON.parse(await f.text());if(typeof d.name!=='string'||!Array.isArray(d.nodes)||!Array.isArray(d.edges)||d.nodes.length>150||d.edges.length>300)throw Error();const ids=new Set<string>();for(const n of d.nodes){if(typeof n.id!=='string'||ids.has(n.id)||!this.kinds.some(k=>k.id===n.kind)||typeof n.label!=='string'||!/^#[0-9a-f]{6}$/i.test(n.color)||!['x','y','w','h'].every(k=>Number.isFinite(n[k]))||n.x<0||n.y<0||n.w<35||n.h<30||n.x+n.w>1200||n.y+n.h>800)throw Error();ids.add(n.id)}for(const edge of d.edges){if(!ids.has(edge.from)||!ids.has(edge.to)||typeof edge.label!=='string'||typeof edge.id!=='string'||!/^#[0-9a-f]{6}$/i.test(edge.color))throw Error()}if(this.dirty&&!confirm('Replace current changes with this drawing?'))return;this.record();this.restore(JSON.stringify(d));this.message='Editable drawing imported.'}catch{this.message='Choose a valid PMPORT diagram JSON file.'}finally{(e.target as HTMLInputElement).value=''}}
 async export(format:'png'|'jpg'|'pdf'){try{await exportSvg(this.canvas!.nativeElement,this.name.replace(/[^a-z0-9]+/gi,'-')||'diagram',format);this.message=format.toUpperCase()+' exported.'}catch{this.message='Export failed. Try again.'}}
 @HostListener('window:beforeunload',['$event']) unload(e:BeforeUnloadEvent){if(this.dirty)e.preventDefault()}
 @HostListener('document:keydown',['$event']) key(e:KeyboardEvent){if((e.target as HTMLElement).matches('input,textarea,select'))return;if(e.key==='Delete'){e.preventDefault();this.remove()}if((e.ctrlKey||e.metaKey)&&e.key==='z'){e.preventDefault();e.shiftKey?this.redo():this.undo()}}
}
