import {Component,OnInit,OnDestroy,inject} from '@angular/core';
import {RouterLink} from '@angular/router';import {AsyncPipe} from '@angular/common';import {map} from 'rxjs';import {ContentService} from '../../core/services/content.service';import {MediaVideo,EventItem} from '../../core/models/portfolio.models';
interface Slide{id:string;label:string;title:string;description:string;image:string;alt:string;path:string;action:string;published:boolean}
@Component({standalone:true,selector:'app-home',imports:[RouterLink,AsyncPipe],template:`
<section class="landing page"><div class="intro"><p class="eyebrow">PMPORT · Project Management, Learning & Practice</p><span class="edition">Explore / Learn / Practise</span></div>
<section class="banner" aria-label="Featured PMPORT content" aria-roledescription="carousel" (mouseenter)="hover=true" (mouseleave)="hover=false" (focusin)="focus=true" (focusout)="focus=false" (touchstart)="touchX=$event.touches[0].clientX" (touchend)="swipe($event)">
@if(slides.length){@let s=slides[index];<img class="banner-image" [src]="s.image" [alt]="s.alt" [class.still]="reduced" [attr.data-slide]="s.id"><div class="banner-shade"></div><div class="banner-copy" [attr.aria-live]="paused?'polite':'off'"><p class="eyebrow">{{s.label}}</p><h1>{{s.title}}</h1><p>{{s.description}}</p><a class="button primary" [routerLink]="s.path">{{s.action}}</a></div><div class="banner-controls"><button (click)="step(-1)" aria-label="Previous slide">‹</button><div class="dots">@for(slide of slides;track slide.id;let i=$index){<button [class.selected]="i===index" (click)="index=i" [attr.aria-label]="'Show '+slide.label" [attr.aria-current]="i===index?'true':null"></button>}</div><button (click)="step(1)" aria-label="Next slide">›</button><button (click)="paused=!paused" [attr.aria-label]="paused?'Play slideshow':'Pause slideshow'">{{paused?'▶':'Ⅱ'}}</button></div>}
</section>
<div class="section-heading"><div><p class="eyebrow">Your next step</p><h2>Explore PMPORT</h2></div><p class="muted">From an idea to a useful outcome.</p></div>
<div class="explore-grid">@for(item of destinations;track item.path){<a class="explore-card" [routerLink]="item.path"><span class="card-number">{{item.number}}</span><h3>{{item.title}}</h3><p>{{item.description}}</p><span class="card-link">Explore {{item.title}}</span></a>}</div>
<section class="section-block"><div class="section-heading"><div><p class="eyebrow">PM Knowledge Lake</p><h2>Featured reading</h2></div><a routerLink="/resources">All resources</a></div><a class="article-card" routerLink="/resources/future-project-management-canada"><img src="future-project-management-canada.png" alt="Maple leaf with connected streams of project work, collaboration and data"><div><span class="eyebrow">Canada · Project management · Data</span><h3>The Future of Project Management in Canada</h3><p class="muted">What Canadian evidence tells us about AI, modernization, business analysis and better project outcomes.</p><span class="card-link">Read article</span></div></a></section>
<section class="section-block"><div class="section-heading"><div><p class="eyebrow">PM Media</p><h2>Learn one concept at a time.</h2></div><a routerLink="/media">Watch PMPortLive</a></div>@if(videos$|async;as videos){<div class="grid two">@for(v of videos.slice(0,2);track v.id){<a class="media-card card" [href]="'https://www.youtube.com/watch?v='+v.youtubeVideoId" target="_blank" rel="noreferrer"><div class="video-thumb"><img [src]="'https://i.ytimg.com/vi/'+v.youtubeVideoId+'/hqdefault.jpg'" [alt]="v.title" loading="lazy" [hidden]="thumbnailUnavailable.has(v.id)" (error)="thumbnailUnavailable.add(v.id)">@if(thumbnailUnavailable.has(v.id)){<span class="video-fallback">▶<small>Watch on PMPortLive</small></span>}</div><h3>{{v.title}}</h3><p class="muted">{{v.description}}</p><span class="card-link">Watch on YouTube</span></a>}</div>}</section>
<section class="section-block"><div class="section-heading"><div><p class="eyebrow">PM Events & Gallery</p><h2>Connect and share.</h2></div><a routerLink="/events">Explore events</a></div>@if(events$|async;as events){<div class="grid two">@for(e of events.slice(0,2);track e.title){<article class="card"><p class="eyebrow">{{e.date}}</p><h3>{{e.title}}</h3><p class="muted">{{e.description}}</p><a routerLink="/events" class="card-link">View events & gallery</a></article>}@empty{<article class="card"><h3>Community moments</h3><p class="muted">Explore the gallery and visit again for published event updates.</p><a routerLink="/events" class="card-link">Explore events & gallery</a></article>}</div>}</section>
<section class="meet section-block"><img src="my_profile_pic.png" alt="Md Alamgir Hossain" loading="lazy"><div><p class="eyebrow">Meet the person behind PMPORT</p><h2>Md Alamgir Hossain</h2><p class="lead">Project leadership, business systems and continuous learning in Regina, Saskatchewan.</p><a class="button secondary" routerLink="/about">Explore my portfolio</a></div></section>
</section>`,styleUrl:'./home.component.css'})
export class HomeComponent implements OnInit,OnDestroy{
 private content=inject(ContentService);thumbnailUnavailable=new Set<string>();slides:Slide[]=[];index=0;paused=false;hover=false;focus=false;reduced=false;touchX=0;timer?:ReturnType<typeof setInterval>;
 readonly destinations=[{number:'01',title:'PM Tools',description:'Create artifacts, draw diagrams and calculate critical paths.',path:'/pm-tools'},{number:'02',title:'PMFaciliter',description:'Explore guided learning and practical project exercises.',path:'/pm-faciliter'},{number:'03',title:'PM Media',description:'Understand concepts through PMPortLive videos.',path:'/media'},{number:'04',title:'Events & Gallery',description:'Community moments and professional connections.',path:'/events'},{number:'05',title:'Knowledge Lake',description:'Articles, reading notes and useful resources.',path:'/resources'},{number:'06',title:'Portfolio',description:'Professional work, coursework and verified credentials.',path:'/portfolio'}];
 videos$=this.content.load<MediaVideo[]>('media.json').pipe(map(x=>x.filter(v=>v.published&&v.youtubeVideoId).sort((a,b)=>a.priority-b.priority)));
 events$=this.content.load<EventItem[]>('events.json').pipe(map(x=>x.filter(e=>e.title&&!/^Recent event (one|two|three|four)$/i.test(e.title)).sort((a,b)=>a.priority-b.priority)));
 ngOnInit(){this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;this.paused=this.reduced;this.content.load<Slide[]>('home-slides.json').subscribe(x=>this.slides=x.filter(s=>s.published));this.timer=setInterval(()=>{if(!this.paused&&!this.hover&&!this.focus&&!document.hidden)this.step(1)},7000)}
 step(n:number){if(this.slides.length)this.index=(this.index+n+this.slides.length)%this.slides.length}
 swipe(e:TouchEvent){const delta=e.changedTouches[0].clientX-this.touchX;if(Math.abs(delta)>60)this.step(delta>0?-1:1)}
 ngOnDestroy(){clearInterval(this.timer)}
}
