export type PracticeQuestionType='Multiple choice'|'Scenario'|'Dropdown';
export interface PracticeQuestion{id:number;type:PracticeQuestionType;category:string;question:string;options:string[];answer:number;explanation:string}

type Seed=[PracticeQuestionType,string,string,string[],number,string];

/**
 * Builds 100 self-contained practice questions: 40 concept/scenario questions
 * plus 60 calculation scenarios with varied values. Keeping this in a separate
 * file makes the bank easy to extend without changing the learning-page layout.
 */
export function buildQuestionBank():PracticeQuestion[]{
  const seeds:Seed[]=[
    ['Multiple choice','Integration','Which document formally authorizes a project?',['Business case','Project charter','Benefits register','Risk report'],1,'The project charter formally authorizes the project and the project manager’s authority.'],
    ['Scenario','Stakeholders','A powerful stakeholder has low day-to-day interest. What is the best engagement approach?',['Monitor only','Keep satisfied','Manage closely','Keep informed'],1,'High-power, low-interest stakeholders are generally kept satisfied.'],
    ['Dropdown','Agile','Who is accountable for ordering the Product Backlog?',['Sponsor','Scrum Master','Product Owner','Developers'],2,'The Product Owner orders the Product Backlog to maximize value.'],
    ['Multiple choice','Risk','What is a positive uncertainty called?',['Defect','Issue','Opportunity','Constraint'],2,'A positive risk is an opportunity.'],
    ['Scenario','Change','A customer requests an additional feature in a predictive project. What should the project manager do first?',['Start the work','Reject it','Assess impact and follow change control','Ask the team to work overtime'],2,'Requested changes should be analyzed before approval or implementation.'],
    ['Dropdown','Scope','Which tool decomposes deliverables into manageable work packages?',['Product roadmap','Work breakdown structure','Risk register','Kanban board'],1,'The WBS hierarchically decomposes project scope.'],
    ['Multiple choice','Schedule','Which schedule compression technique adds resources and may increase cost?',['Fast tracking','Crashing','Resource smoothing','Rolling-wave planning'],1,'Crashing shortens duration by adding resources at additional cost.'],
    ['Scenario','Schedule','Two activities normally performed sequentially are overlapped. Which technique is being used?',['Crashing','Fast tracking','Resource levelling','Monte Carlo analysis'],1,'Fast tracking overlaps activities and may increase risk.'],
    ['Dropdown','Quality','Which principle focuses on preventing defects instead of inspecting them out later?',['Gold plating','Prevention over inspection','Scope validation','Reserve analysis'],1,'Building quality into the process is preferable to relying only on inspection.'],
    ['Multiple choice','Communications','Communication requirements should primarily be based on what?',['Project manager preference','Stakeholder information needs','Cheapest available tool','Team size only'],1,'Communication is planned around stakeholder needs and project context.'],
    ['Scenario','Team','Two team members disagree about a technical approach. What should the project manager encourage first?',['Avoidance','Collaboration and problem solving','Management escalation','Immediate reassignment'],1,'Collaborative problem solving seeks a durable win-win outcome.'],
    ['Dropdown','Procurement','Which document asks sellers to propose how they would meet a solution need?',['RFP','Invoice','Issue log','Project charter'],0,'A request for proposal solicits solution approaches and commercial proposals.'],
    ['Multiple choice','Agile','What is the purpose of a Sprint Retrospective?',['Approve scope','Improve team process','Demonstrate the increment','Estimate the entire project'],1,'The retrospective identifies improvements to quality and effectiveness.'],
    ['Scenario','Agile','A team repeatedly carries unfinished work into the next sprint. What is the best first action?',['Extend every sprint','Inspect causes with the team and adjust planning','Remove the Product Owner','Count partial work as done'],1,'The team should inspect the pattern and adapt its planning or workflow.'],
    ['Dropdown','Business Analysis','Which artifact links requirements to their origin and downstream deliverables?',['Stakeholder cube','Requirements traceability matrix','Burnup chart','Control chart'],1,'The RTM supports traceability from source through delivery and validation.'],
    ['Multiple choice','Business Analysis','What does acceptance criteria define?',['Team salaries','Conditions a solution must satisfy','Vendor ownership','Project funding'],1,'Acceptance criteria make expected behavior and completion testable.'],
    ['Scenario','Leadership','A capable team needs ownership and little direction. Which style is most appropriate?',['Directing','Delegating','Commanding','Micromanaging'],1,'Delegating supports autonomy when capability and commitment are high.'],
    ['Dropdown','Risk','Which response transfers ownership of a threat to a third party?',['Exploit','Transfer','Accept','Enhance'],1,'Insurance, warranties and contracts can transfer threat ownership or impact.'],
    ['Multiple choice','Risk','A risk has occurred and is now affecting delivery. Where should it be tracked?',['Issue log','Assumption log only','Backlog only','Lessons register only'],0,'An occurred risk is an issue and needs active resolution.'],
    ['Scenario','Stakeholders','A stakeholder resists a new system because the impact is unclear. What should happen first?',['Exclude the stakeholder','Understand concerns and clarify impacts','Escalate immediately','Delay all communication'],1,'Listening and impact-focused communication help address resistance constructively.'],
    ['Dropdown','Cost','What is management reserve intended for?',['Known work package costs','Unknown-unknowns within project scope','Gold plating','Approved invoices only'],1,'Management reserve covers unforeseen work within the project scope.'],
    ['Multiple choice','Scope','What is scope creep?',['Approved change','Uncontrolled expansion without approved change','Progressive elaboration','Scope validation'],1,'Scope creep is unauthorized or uncontrolled expansion of scope.'],
    ['Scenario','Quality','A team adds unrequested features believing the customer will like them. What is this?',['Value engineering','Gold plating','Scope validation','Kaizen'],1,'Gold plating adds extras that were not approved and can introduce risk.'],
    ['Dropdown','Governance','What log records significant project choices and their rationale?',['Decision log','Resource calendar','Quality metric','Team charter'],0,'A decision log preserves what was decided, by whom and why.'],
    ['Multiple choice','Agile','What does Definition of Done provide?',['A shared quality/completion standard','A list of stakeholders','A funding limit','A release date'],0,'The Definition of Done creates transparency about completed work.'],
    ['Scenario','Agile','A Product Owner wants urgent work added mid-sprint. What should the team do?',['Automatically add it','Discuss impact and protect the Sprint Goal','Hide capacity','Cancel Scrum'],1,'The Sprint Goal provides focus; changes require collaboration and impact consideration.'],
    ['Dropdown','Schedule','What identifies the longest-duration path through a network?',['Resource histogram','Critical path method','Affinity diagram','Burndown chart'],1,'The critical path determines the earliest possible project completion.'],
    ['Multiple choice','Estimation','Which estimate uses optimistic, most likely and pessimistic values?',['Bottom-up only','Three-point estimate','Analogous only','Parametric only'],1,'Three-point estimating accounts for uncertainty using three values.'],
    ['Scenario','Procurement','A seller misses a contractual milestone. What should be reviewed first?',['Team charter','Contract terms and agreed remedies','Product vision','Benefits register'],1,'The contract defines obligations, remedies and escalation mechanisms.'],
    ['Dropdown','Benefits','Who normally owns realization of business benefits after project transition?',['Benefits owner or operational sponsor','Scheduler','Scrum Master only','Vendor'],0,'Benefit accountability normally continues in the business after delivery.'],
    ['Multiple choice','Ethics','A project manager discovers an unfavorable error in a status report. What is the best action?',['Hide it','Correct it and communicate transparently','Wait until closeout','Blame the team'],1,'Professional responsibility requires honesty and timely correction.'],
    ['Scenario','Team','A virtual team is experiencing misunderstandings. What is the best next step?',['Increase written reports only','Agree communication norms and channels','Stop meetings','Replace remote members'],1,'A team working agreement clarifies channels, timing and expected behavior.'],
    ['Dropdown','Change','Which group may approve or reject significant change requests?',['Change control board','Daily Scrum','Procurement audit','Quality circle'],0,'A CCB evaluates changes within its defined authority.'],
    ['Multiple choice','Monitoring','What is a leading indicator?',['A measure predicting future performance','A final historical result only','A closed issue','An approved invoice'],0,'Leading indicators provide early signals before final outcomes occur.'],
    ['Scenario','Business Analysis','Two stakeholders give conflicting requirements. What should the BA do first?',['Select the senior person’s option','Facilitate clarification using goals and evidence','Implement both immediately','Remove both requirements'],1,'Facilitated analysis connects requirements to objectives and constraints.'],
    ['Dropdown','Closing','What should occur before formally closing a project?',['Obtain acceptance and transition deliverables','Delete records','Release products without approval','Start unrelated scope'],0,'Formal acceptance and transition are key prerequisites to closure.'],
    ['Multiple choice','Lessons Learned','When should lessons learned be captured?',['Only at the end','Throughout the project and at closure','Only after failure','Only by the sponsor'],1,'Continuous learning allows improvements during delivery as well as later.'],
    ['Scenario','Risk','A low-probability threat would be catastrophic. What should the team do?',['Ignore it','Plan an appropriate response and contingency','Delete it from the register','Convert it to an assumption'],1,'Severity and risk appetite matter; rare but extreme threats require deliberate planning.'],
    ['Dropdown','Portfolio','A program is best described as what?',['Unrelated operational tasks','Related projects managed together for added benefits','A single work package','A department budget'],1,'Programs coordinate related work to realize benefits unavailable from separate management.'],
    ['Multiple choice','Value','What should guide prioritization when capacity is limited?',['Who asks loudest','Expected value, risk and strategic alignment','Alphabetical order','Longest task first'],1,'Transparent value-based criteria support defensible prioritization.']
  ];

  const questions:PracticeQuestion[]=seeds.map((seed,index)=>({id:index+1,type:seed[0],category:seed[1],question:seed[2],options:seed[3],answer:seed[4],explanation:seed[5]}));
  let id=questions.length+1;
  const variants=[1,2,3,4,5,6,7,8,9,10,11,12];
  for(const n of variants){const ev=70+n*5,ac=80+n*5,cpi=ev/ac;questions.push({id:id++,type:'Scenario',category:'EVM',question:`A project has EV ${ev} and AC ${ac}. Which CPI is closest?`,options:[(cpi-.1).toFixed(2),cpi.toFixed(2),(cpi+.1).toFixed(2),'1.50'],answer:1,explanation:'CPI = EV ÷ AC. A value below 1.00 means the project is over budget.'});}
  for(const n of variants){const ev=75+n*4,pv=85+n*4,spi=ev/pv;questions.push({id:id++,type:'Multiple choice',category:'EVM',question:`EV is ${ev} and PV is ${pv}. What is the approximate SPI?`,options:['0.50',spi.toFixed(2),'1.00','1.25'],answer:1,explanation:'SPI = EV ÷ PV. Below 1.00 indicates less work was earned than planned.'});}
  for(const n of variants){const o=2+n,m=5+n,p=11+n,pert=(o+4*m+p)/6;questions.push({id:id++,type:'Dropdown',category:'Estimation',question:`For O=${o}, M=${m}, and P=${p}, what is the PERT estimate?`,options:[String(m),pert.toFixed(1),String(p),((o+m+p)/3).toFixed(1)],answer:1,explanation:'PERT expected duration = (O + 4M + P) ÷ 6.'});}
  for(const n of variants){const people=n+4,channels=people*(people-1)/2;questions.push({id:id++,type:'Multiple choice',category:'Communications',question:`How many potential communication channels exist among ${people} people?`,options:[String(people*2),String(channels),String(people-1),String(people*people)],answer:1,explanation:'Communication channels = n(n−1) ÷ 2.'});}
  for(const n of variants){const probability=(n+2)/20,impact=10000+n*1000,emv=probability*impact;questions.push({id:id++,type:'Scenario',category:'Risk',question:`A threat has probability ${(probability*100).toFixed(0)}% and impact $${impact.toLocaleString()}. What is its EMV?`,options:[`$${impact.toLocaleString()}`,`$${emv.toLocaleString()}`,`$${(impact-emv).toLocaleString()}`,'$0'],answer:1,explanation:'Expected monetary value = probability × monetary impact.'});}
  return questions;
}
