export function downloadBlob(blob:Blob,name:string){const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
export async function exportWorkbook(title:string,headers:string[],rows:(string|number)[][],name:string){const XLSX=await import('xlsx');const ws=XLSX.utils.aoa_to_sheet([[title],[],headers,...rows]);ws['!cols']=headers.map(()=>({wch:28}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Project');XLSX.writeFile(wb,name+'.xlsx')}
export async function exportTablePdf(title:string,headers:string[],rows:(string|number)[][],name:string){const {jsPDF}=await import('jspdf');const doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a3',compress:true});const width=doc.internal.pageSize.getWidth(),height=doc.internal.pageSize.getHeight();const margin=12,col=(width-2*margin)/Math.max(headers.length,1);let y=30;doc.setFontSize(15);doc.text(doc.splitTextToSize(title,width-24),margin,16);doc.setFontSize(8);
 const row=(cells:(string|number)[],header=false)=>{const lines=cells.map(c=>doc.splitTextToSize(String(c??''),col-5) as string[]);const h=Math.max(10,...lines.map(l=>l.length*4+5));if(y+h>height-12){doc.addPage();y=15;if(!header)row(headers,true)}doc.setFont('helvetica',header?'bold':'normal');cells.forEach((_,i)=>{doc.setDrawColor(170,185,195);doc.rect(margin+i*col,y,col,h);doc.text(lines[i],margin+i*col+2,y+5)});y+=h};
 row(headers,true);rows.forEach(r=>row(r));doc.save(name+'.pdf')}
export async function exportSvg(svg:SVGSVGElement,name:string,format:'png'|'jpg'|'pdf'){
 const clone=svg.cloneNode(true) as SVGSVGElement;clone.querySelectorAll('[data-editor-only]').forEach(n=>n.remove());clone.setAttribute('xmlns','http://www.w3.org/2000/svg');const box=svg.viewBox.baseVal;const w=box.width||1200,h=box.height||800;clone.setAttribute('width',String(w));clone.setAttribute('height',String(h));const source=new XMLSerializer().serializeToString(clone);const url=URL.createObjectURL(new Blob([source],{type:'image/svg+xml'}));
 try{const img=new Image();await new Promise<void>((resolve,reject)=>{img.onload=()=>resolve();img.onerror=()=>reject(new Error('Image conversion failed'));img.src=url});const canvas=document.createElement('canvas');canvas.width=w*2;canvas.height=h*2;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#ffffff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);
 if(format==='pdf'){const {jsPDF}=await import('jspdf');const pdf=new jsPDF({orientation:w>=h?'landscape':'portrait',unit:'px',format:[w,h],hotfixes:['px_scaling'],compress:true});pdf.addImage(canvas.toDataURL('image/png'),'PNG',0,0,w,h);pdf.save(name+'.pdf')}else{const blob=await new Promise<Blob>((res,rej)=>canvas.toBlob(b=>b?res(b):rej(new Error('Export failed')),format==='jpg'?'image/jpeg':'image/png',.94));downloadBlob(blob,name+'.'+format)}
 }finally{URL.revokeObjectURL(url)}
}
